### PR TITLE
Make overriding cnf-handler work

### PR DESCRIPTION
**Pull request by faho**
Do this by renaming the __fish_command_not_found_handler used during
startup to __fish_startup_command_not_found_handler. That allows us to
check if __fish_command_not_found_handler has been defined and skip the
setup of the normal one.

Now disabling cnf-handling can be done via defining an empty
__fish_command_not_found_handler in config.fish.

It's quite possible that I haven't understood the full complexity of the situation so I've decided to open a PR instead of just pushing. Of course solving #845 could make all of this moot.

### CODE REVIEW

**Comment by zanchey** [comment]
Looks good to me.

**Comment by faho** [comment]
I re-simplified it a bit (not sure why I didn't do it that way right away).

I intend to merge this tomorrow unless anyone objects.

**Comment by faho** [comment]
There's a point here that's probably not as intuitive as it should be - if you define `__fish_command_not_found_handler` without "--on-event fish_command_not_found", it will disable the cnf-logic without being executed itself. (I also don't quite like users fiddling with the dunderscore "namespace", but I guess renaming it would constitute an API break which I also don't like)

There's no great solution I can see for it - one would be to have a way to check if an event handler is registered for a particular event, a way to register already defined functions as event handlers might work as well (if it can't get double-defined). The former is kinda nice, the latter is kinda un-orthogonal (since this specially named function would magically become an event handler no matter how it's defined).

Regardless, this solves a problem and doesn't _hurt_ or prevent doing something better, so I'll merge this anyway now.

**Comment by faho** [comment]
Squashed merge as 2f3123e1757f495afc799f0c734283d4513db0f8.

**Pull request closed without merging**
