### PR TITLE
Guess an emoji width of 2 for glibc >= 2.26

### PR DESCRIPTION
**Pull request by faho**
## Description

That was when Glibc introduced Unicode 9 support, so everything since
then should use the new width.

I have no idea how to detect it for other operating systems or libcs.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by zanchey** [comment]
Sorry @faho, this didn't get merged for 3.0b1, and I'm not convinced we should take it for 3.0.0.

**Comment by floam** [comment]
I wouldn't have issue with trying to get it in the next beta - if we're pretty confident that this version of glibc has that behavior, the change doesn't seem particularly risky. We also do some heuristics to determine the emoji width on particular macOS versions.

Emojis being treated as a different width than they are rendered, mucking up the command line interactively causes so many people to have a bad time and report issues here... assuaging it for a big group of people in our next release seems pretty desirable.

**Comment by floam** [comment]
... and a problem with that is we don't plan to have a second beta, unless it turned out 3.0b1 was a serious dumpster fire, which it is not.

**Comment by faho** [comment]
Having thought more about this, this isn't the correct solution.

We should instead do a compile-time test of one or more characters - https://cmake.org/cmake/help/latest/command/try_run.html#command:try_run.

**Pull request closed without merging**
