### PR TITLE
Add cargo and rustc completion.

### PR DESCRIPTION
**Pull request by bheesham**
I've added completion for [Rust](https://github.com/rust-lang/rust) and [Cargo](https://github.com/rust-lang/cargo).

### CODE REVIEW

**Comment by bheesham** [comment]
Derp. The last commit is a lie. I thought the new line was added but it wasn't.

**Comment by faho** [comment]
For the rustc completion: You can add descriptions to any completion option by separating the option and it's description with a tab character and the next option with a newline.

I.e. something like this should give properly described options:

```fish
printf "%s\t%s\n" box-pointers "some text that describes box-pointers" fat-ptr-transmutes "some description for fat-ptr-transmutes"
```

**Comment by bheesham** [comment]
Descriptions for flags have now been added. I ended up writing a Python script to help me out.

**Comment by faho** [comment]
Did you mean to commit and push that?

>I ended up writing a Python script

Can't say I'm a massive fan. Push it and I'll take a look.

**Comment by bheesham** [comment]
It's over here: https://github.com/bheesham/rust.fish

**Comment by faho** [comment]
>No I didn't since this was only for completions.

Ah okay, it's for _generating completion scripts_. I thought you had written a helper that is called at runtime. This is kinda neat, but I'd still like it more if we could generate the completions on the user's machine since they then perfectly match the rust version (since that's apparently possible).

What you basically do here is call `rust -C help` and `rust -W help` and bang the output into the shape we want with some regex-magic, right? If so, we usually use `sed` for that (and I don't like the idea of asking for other utilities unrelated to the command to be installed, even something as ubiquitous as python), but we now also have, hot off the presses, our new cool `string` tool, with its subcommand `string match` (basically `grep`) and `string replace` (basically `sed`'s "s/PATTERN/REPLACEMENT/").

I could also take a look, but I'll have to download rust first and my current internet connection won't allow for that, so I'll try to get to it over the weekend.

**Comment by bheesham** [comment]
Yep, that's exactly what the script does.

Ah yeah. I saw the pull request for `string`. I'll refactor some of the code to start using it when I get a chance to.

**Comment by faho** [comment]
@bheesham: Any progress?

**Comment by bheesham** [comment]
Ah crap, nope. This completely escaped my mind for a bit.

I'll pick this issue back up around Thursday.

**Comment by bheesham** [comment]
@faho , I'm now using the string commands. All I'm using the Python script for now is to not have to write `complete -c rustc` and `complete -c cargo`.

I've been able to bring the filesize of `rustc.fish` down from 28.3kb to 2.66kb!

**Comment by faho** [comment]
How well does this perform? It does quite a lot of `math` calls.

**Comment by bheesham** [comment]
Not too well I think.

The current version (run the `rustc -{Z,W,C} help` command, parse output, iterate) `source`s in around 390ms on my laptop. The previous version which used Python to generate the completions `source`s in about 9ms.

I guess my next challenge is to find a way to generate completions without heavily relying on `math`.

**Comment by bheesham** [comment]
Cool. The time it takes to source is now significantly less than what it was before.

It's around 88ms for me. Still not as fast as file Python generates, but hey, it's a major improvement.

**Comment by bheesham** [comment]
I did run into a strange problem though.

`rustc -W help | string replace -r -i '(\s+)(.+)(\s+)(allow|warn|deny|forbid)(\s+){2}([^\n]+)' '$2 $6'` outputs the wrong thing. It keeps in the footer of the help message, which is weird.

Output: paste.fedoraproject.org/283277/14456988

Any ideas?

**Comment by faho** [comment]
> outputs the wrong thing. It keeps in the header and footer of the help message, which is weird.

Well, it looks like it just doesn't match on them, so it replaces nothing - the lines appear unchanged.

**Comment by faho** [comment]
>It's around 88ms for me. Still not as fast as file Python generates, but hey, it's a major improvement.

That probably warrants the technical term "good enough" - unless you're running a monster rig.

**Comment by faho** [comment]
Okay, I tested it a bit and played a bit around, and while there's still plenty of micro-optimizations possible (e.g. the recurring `| egrep -v '^$' | egrep -v ':$'` can be replaced by `| string match -r '^.*[^:]$'` - which saves a total of 6 grep calls when setting up the completion), but for me it's basically instantaneous anyway.

The semantics of `egrep` and `string` (i.e. pcre2) seem to be different enough that  the `egrep | string replace` in the `rust -W help` part can't be replaced with `string match -r` directly, which is unfortunate, but in the end it doesn't really matter (we've tried so hard, and got so far).

So unless you think there's anything missing, this seems about ready to merge. Okay?

**Comment by bheesham** [comment]
Sounds like a plan. :-)

Thanks for all the pointers!

**Comment by faho** [comment]
Merged, thanks!

**Pull request merged**
