### PR TITLE
git prompt: Interpret values as true for bools instead of relying on defined-or-not

### PR DESCRIPTION
**Pull request by faho**
This allows explicitly turning these settings off by setting the variable to e.g. 0.

See #7120

This is technically a change in behavior iff you set these variables to anything *but* "1". I don't think I've ever seen that, and it's easy enough to fix.

Note: This lacks the "hide" stuff (`__fish_git_prompt_hide_stagedstate` and friends), it's not documented, nigh-useless now that we properly look at the status order. I want to remove it.

## TODOs:

- [X] Changes to fish usage are reflected in user documentation/manpages.
- [X] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by mqudsi** [comment]
I'm not sure how I feel about this. I agree that it should be possible to set them to some value to indicate that they are disabled, but to assume that in a loosely typed scripting language everyone will by default understand or muscle memory default to a numeric `1` for truthiness is not sitting well with me.

You've gone from accepting any value as "true" but not having a way to express "false" to understanding every variable to be "false" except for the one and only value reserved as "true".

In writing GUI frontends for CLIs, I have found the greatest success in considering any of `on`, `true`, `1`, or `yes` (all case-insensitive, of course) to be equivalent to `true`. I'm not suggesting we document that (by all means, go ahead and keep the documentation the same and insist that users use `1`) but we should be more liberal in parsing even if that means we need a helper function like `is_true <var_name>`.

**Comment by faho** [comment]
>I agree that it should be possible to set them to some value to indicate that they are disabled, but to assume that in a loosely typed scripting language everyone will by default understand or muscle memory default to a numeric 1 for truthiness is not sitting well with me.

It's quite simply how people use this:

https://github.com/search?q=__fish_git_prompt_show_informative_status&type=code

By a country mile, "1" is used to signify true.

It's also how *we* do it, it's how *we* set $fish_private_mode, $fish_term24bit, $fish_use_posix_spawn, $fish_handle_reflow and other [random](https://github.com/fish-shell/fish-shell/blob/acb77ad1a37aee15969ed80b840cf55642cbe650/share/functions/__fish_npm_helper.fish#L18) [helper](https://github.com/fish-shell/fish-shell/blob/acb77ad1a37aee15969ed80b840cf55642cbe650/share/functions/__fish_shared_key_bindings.fish#L216) variables.

Statistically, 1 has won. "true" is a distant second.

And I'm not sold that having multiple true values is helpful - like yes, we have a cheesy "[bool_from_string](https://github.com/fish-shell/fish-shell/blob/14d2a6d8ff18434a9672887d60009eef92ea21cc/src/wcstringutil.h#L165-L177)" helper that is technically used for some of these, but people don't use that capability, and having one true value makes the check easier.

This is the absolute, 100% correct check to test if $fish_handle_reflow is a true value:

```fish
test "$fish_handle_reflow" = 1
```

This is easy to get right (well, ignoring `test`s issues). On the other hand, this is the check to see if $fish_term24bit is set to true:

```fish
string match -ri '^[yt1]' -- $fish_term24bit
```

So these values are true: "yakshaving", "Tarpit", "1WRONG" and these are not: "ja", "waar", "oui".

**Comment by mqudsi** [comment]
GitHub's default code search includes too many duplicates. [Using cs.github.com](https://cs.github.com/?q=__fish_git_prompt_show_informative_status&p=1&pt=bbebc12f2607dc8300fcafb29693e0bc4fb7bd916c7015ec941cfab9b4d8c4c020f84c21d3623947a562d369a4867d7c10deb0af415f7b5b51ca0aaf87460bdcc9fe667f466b4051c175de74b5f64bf70a46957d3a93060d0117894fef4165ed9b022f39f99fe5a6e66472841b5210c9b18a14b0dd151e4948dd15ac7ee06c664ca32c6e245d37ca1bd26e2f7387bb3c8670a62afb094658830caf57e3b0a6fa175718d5128a3f97d81b047a75e4bc5d5e05105882f599e46df462191f09ce6dd9e52927a89dd7baf83f9448d2c56a619786be021b9bb19d16b4e4a46222a867cf16a3ca7d1efcd5bc3ffcb5bb3afcb62a85bfec93025fd388ae0dca63aae721ce7fe5aca28cb68d860803179d74110602e6e53130876fff0873e34526cd3385f82bc61476aa1a476d8f9250a4e9351e0559dd4fcb2793fb992093329bba302fd3820bc6dd6d7971e872be8179f372985557659c468f94b0a8bf7d0fdd5dc5be0bc5b6994fb2f16cf8d01fafb21b023d9bbc66f59ba5faaa663338a970e05225c1448aec50f519b468b8125ec4caae0f) shows much more variety, including "yes" and "true" - and I didn't even use a regex to ignore the `1` cases.

**Comment by faho** [comment]
>Using cs.github.com shows much more variety

Yeah, they want me to sign up for the waitlist, I'll just take your word for it that there are other cases.

In our code non-1 cases are a rarity.

Anyway: I still don't believe that making this more complicated helps. You tell people that "1" is true, and they'll use "1". Tell people that "true is one of true, yes, on, 1", they'll have to think about which one of them they want to use, and case-insensitive means you can get "yEs", which I see absolutely no reason for (we're not case-insensitive in our keywords or variable names or really a lot of other places) and which I would always want to correct, everywhere.

**Comment by mqudsi** [comment]
I'm (also) saying people already have these set from a time before we told them what to set it to. Their configs will break.

The results show a bunch of themes that people clone/copy/download internally set "yes" or "true" for the prompt status variable. Anyone using these is going to have braeakage.

[The oh-my-fish theming guide](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md) use `yes`, `true`, and `1` all over the place in their theming guide and tutorials.

The results show a whole bunch of these.

**Comment by mqudsi** [comment]
It's nice that this clears up the earlier confusing statement about boolean variables vs git variables.

**Pull request merged**
