### PR TITLE
Remove overrides of default CMake flags

### PR DESCRIPTION
**Pull request by robinlinden**
CMake sets these flags to sane defaults depending on which compiler
you're using, so overriding them isn't very nice.

For example:

with g++, I get
```
-- Debug: -g
-- RelWithDebInfo: -O2 -g -DNDEBUG
-- MinSizeRel: -O2 -g -DNDEBUG
-- Release: -O3 -DNDEBUG
```

and with MSVC you get something like
```
-- Debug: /MDd /Zi /Ob0 /Od /RTC1
-- RelWithDebInfo: /MD /Zi /O2 /Ob1 /DNDEBUG
-- MinSizeRel: /MD /Zi /O2 /Ob1 /DNDEBUG
-- Release: /MD /O2 /Ob2 /DNDEBUG
```

### CODE REVIEW

**Comment by zanchey** [comment]
I thought this was put in deliberately to avoid the `-DNDEBUG` definition, but our implementation of `assert` ignores that so I think this is reasonable. I will ask @mqudsi to comment as he added this initially.

**Comment by krobelus** [comment]
We could also remove from the travis configuration the `-g` and `-O2` flags in CXXFLAGS (and CFLAGS).

**Comment by ridiculousfish** [comment]
I agree let's try to find a way to avoid defining NDEBUG. I believe the asserts are valuable.

**Comment by ridiculousfish** [comment]
I merged this as 34e06c44408947e0942098d7c69e58fff1b37c04 but then splice out the NDEBUG bits in 2c81229ee61f7aa67a0198e92dfc460957e3ea4e . Thanks!

**Comment by faho** [comment]
>I agree let's try to find a way to avoid defining NDEBUG. I believe the asserts are valuable.

@ridiculousfish I think you might have misunderstood. Our custom `assert()` doesn't obey NDEBUG, so we can leave it in without disabling asserts.

**Comment by mqudsi** [comment]
At the time this was added, I was unaware CMake automatically injected these flags. Mea culpa.

**Comment by ridiculousfish** [comment]
> Our custom `assert()` doesn't obey NDEBUG, so we can leave it in without disabling asserts.

There's lots of plain old `assert()` calls, I don't think we're overriding those though I could be wrong.

**Comment by faho** [comment]
I'd imagine https://github.com/fish-shell/fish-shell/blob/master/src/common.h#L218-L224 should cover just about everything?

**Comment by ridiculousfish** [comment]
Well TIL!

**Comment by zanchey** [comment]
It's just as well, because Homebrew forces `-DNDEBUG`, though I don't know why.

**Comment by ridiculousfish** [comment]
It turns out that our #undef that faho showed isn't quite sufficient - if any header after `common.h` pulls in `assert.h` then it will redefine our assert back. So many casualties in the assertion war.

Probably this can be fixed via a clang-format rule that enforces a certain header file ordering. But for now I'm going to leave the CMake bits in place.

**Comment by krobelus** [comment]
This triggered another discussion in https://github.com/fish-shell/fish-shell/commit/0b3d3de9bf91241c333f5b581e52eef579f53434#commitcomment-57218424:

> The way we undefined assert is often no worky, depending on the order of #includes.

I think we should fix that by including `<assert.h>` in `src/common.h`. This way we always get our assertion.

**Pull request closed without merging**
