### PR TITLE
Select fonts actually used on terminals for the web config.

### LINKED ISSUE #2924: fish_config prompt rendering is wrong
Consider the preview for the Terlar theme:

screenshot 2016-04-09 at 10 14 11 pm

On my terminal it actually renders like this:

screenshot 2016-04-09 at 10 11 04 pm

There are issues:
 1. For certain glyphs like that lightning bolt, the webapp isn't picking the glyphs we'd like see at the terminal. 
 2. There is some bug with the colors likely not changing/ending the way they actually do in a terminal (color of the second line).
 3. All of the git-aware commands only have an indication and preview of their true nature if you happen to execute them in a git repo.

A PR for 1 is incoming. 2 is caused because that color changes depending on exit status... and for some reason that's always not 0 in the demonstrations I guess.

After looking over how these are rendered, I wonder if fish wouldn't be better off using a Javascript module that is capable of more accurately and fully rendering a string full of ANSI/vt100 escape sequences the  same way a terminal would. It would be neat to show color schemes and the prompt together, by feeding something like [tty.js](https://github.com/chjj/tty.js/) actual fish output.

### PR DESCRIPTION
**Pull request by floam**
Fixes #2924

Instead of just using Courier New across the board<sup>1</sup>, give the browser several good options for a fixed width font to use.

This is the new list of fonts to have it use. Browser will use the first one in the list they have. `monospace` is a special reserved name for a fallback, which has the browser use whatever it has hardcoded in or configured to be used for fixed width text if all else fails. This is Courier or Courier New on the majority of browsers.

1. `"Source Code Pro"` (can has Powerline)
2. `Menlo`      (OS X default)
3. `Consolas` (Windows default)
4. `"Bitstream Vera Sans Mono"`(On many Linux machines)
5. `monospace`

The ordering was made under the consideration that Source Code Pro is a nice font which is "out there" and has official Powerline support in case someone ever tries to render a powerline glyph here. We also can legally embed this font if we ever wish. Otherwise I hope to get something reasonable that is more likely than not going to be what someone's terminal would be configured with out of the box. Someone with Menlo (belongs to Apple, is the default Terminal.app font) is likely to be on OS X and want to use that before Consolas (belongs to Microsoft which is the default Win10 cmd.exe font, but also comes with Office for Mac) even if they have both. Bitstream Vera Sans Mono is going to be on a lot of Linux machines but also many OS X and Windows machines because it's been around a long while and is open source, so it goes to the end before the browser is left to its own devices. 

[1]: it's actually Courier New with a fallback of `monospace`. `monospace` is often Courier New but not everywhere.

### CODE REVIEW

**Comment by floam** [comment]
Before: 
screenshot 2016-04-09 at 10 14 11 pm

After:
screenshot 2016-04-09 at 10 11 16 pm

Terminal:
screenshot 2016-04-09 at 10 11 04 pm

**Comment by pickfire** [comment]
@floam Why not `DejaVu Sans Mono` on Linux? I use that on my terminal.

**Comment by floam** [comment]
I picked it because thought it was most likely to exist and be an OS default -I haven't been a desktop Linux user in several years now- how common is DejaVu Sans in relation to Bitstream Vera Sans?

**Comment by pickfire** [comment]
@floam, `DejaVu Sans` and `Bitstream Vera` is 2 different thing. **You can't just compare apples to oranges**.

And `Bitstream Vera Sans Mono` isn't installed in my system by default.

**Comment by faho** [comment]
The [archlinux package statistics](https://www.archlinux.de/?page=PackageStatistics) show ttf-dejavu is installed on 81% of systems (that upload statistics), while ttf-bitstream-vera is on 51%.

Debian statistics can be found at the [popcon site](http://popcon.debian.org/), but I don't know the package names offhand.

**Comment by faho** [comment]
@floam: Okay, on debian it's 28% for [ttf-dejavu](https://qa.debian.org/popcon.php?package=ttf-dejavu) vs 9% for [ttf-bitstream-vera](https://qa.debian.org/popcon.php?package=ttf-bitstream-vera). Of course the proportion of non-X installations is probably higher for debian so there'll be a lot of systems without any ttf packages installed - and those won't be running `fish_config`.

**Comment by MarkGriffiths** [comment]
fwiw, I went through this in some detail when I was working out the font priority for the documentation and  wrote it up in the [doc formatting guide](https://github.com/fish-shell/fish-shell/blob/master/doc_src/FORMATTING.md#fonts). While I totally appreciate that it's two different use cases, but there's probably some alignment in respective conclusions. DejaVu Sans Mono came out top in my research.

**Comment by floam** [comment]
Settled!
On Tue, Apr 12, 2016 at 9:51 AM Mark Griffiths <notifications@github.com>
wrote:

> fwiw, I went through this in some detail when I was working out the font
> priority for the documentation and wrote it up in the doc formatting guide
> <https://github.com/fish-shell/fish-shell/blob/master/doc_src/FORMATTING.md#fonts>.
> While I totally appreciate that it's two different use cases, but there's
> probably some alignment in respective conclusions. DejaVu Sans Mono came
> out top in my research.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fish-shell/fish-shell/pull/2925#issuecomment-209003548>
>
-- 
Aaron

**Comment by floam** [comment]
> floam, DejaVu Sans and Bitstream Vera is 2 different thing. You can't just compare apples to oranges.

I thought DejaVu Sans was a not-as-common derivative of Bitstream Vera. It turns out that it's a common derivative of Bitstream Vera Sans.

> I hope you don't assume a specific font is installed in a linux computer by default.

It's true, I did guess that it was likely you could have that font when I made the change - but of course since you don't have it what would have happened is it would use your browser's `monospace` font - which might be DejaVu? In any case I have updated this to prefer DejaVu. I decided not to place DejaVu in front of Bitstream Vera but instead just do it instead. I think most linux machines will have a good `monospace` fallback that isn't strange to see on a terminal.

**Comment by floam** [comment]
By the way, if there is any font as common that Source Code Pro that has officially supported Powerline glyphs baked in: let me know, it should go on the front half of the list.

**Comment by floam** [comment]
I might ask you @pickfire, since I know a lot of us don't have very diverse locales, are there any changes  (CJK-specific, or otherwise) you can suggest regarding fonts or how fish_config displays the prompt for you?

**Comment by floam** [comment]
Wow, some careful consideration there @MarkGriffiths in your guide. I will probably more or less adopt what you do there - I can't see how this is so different. I think it could benefit from use of different fonts for different kinds of information too, instead of plastering the choice onto `body {`.

**Comment by pickfire** [comment]
@floam, I personally use `WenQuanYi Zen Hei` to display chinese characters, there is also `WenQuanYi Micro Hei` IIRC and it is for phone. `DejaVu Sans Mono` can't display CJK fonts.

I think the browser might have a fallback mechanism to display CJK fonts which is to use other fonts.

**Comment by terlar** [comment]
If you want a font that includes most things you could go for `Noto Sans` which includes most glyphs if you only want to stick to one font, you also have the joint effort by Google and Adobe `Source Han Sans` which is what the Noto CJK characters are based upon.

You can get Source Han Sans here: https://github.com/adobe-fonts/source-han-sans/

**Comment by floam** [comment]
My question is: /should/ I add CJK font to the list in this kind of a case- even though my girlfriend is a Chinese national with better english than me she cannot seem to understand what I''m asking her when I ask if here's such a thing as monospaced Chinese characters "you know like in like in programming"."they do that in english"....

Are there monospaced CJK characters that are used at terminal, specifically? Or does everyone just pick a monospaced font like is in the list and rely on the OS finding the correct glyphs?

**Comment by jakwings** [comment]
> should I add CJK font to the list in this kind of a case.

You don't have to put various characters to show what a theme look like, right? Just show the code in ASCII charset and people will understand, even without a CJK font installed (so you won't see weird things on the screen).

> and do replacements happen?

For most popular terminal emulators, only the ambiguous-width characters matters (table drawing characters `┌┬┐├┼┤└┴┘`, ellipsis `…`, em dash `—`, etc.), but it doesn't really matter to the theme.

> Or does everyone just pick a monospaced font like is in the list above and rely on the OS to find the correct glyphs?

Yes, if there is no suitable font for my taste. Most terminals don't allow users to set custom fallback fonts.

**Comment by floam** [comment]
> @floam, I personally use WenQuanYi Zen Hei to display chinese characters, there is also WenQuanYi Micro Hei IIRC and it is for phone. DejaVu Sans Mono can't display CJK fonts.

Thanks. I think both those fonts are not monospaced (WenQuanYi Zen Hei and  WenQuanYi ) since DejaVu sans has no CJK fonts where do the missing glyphs come from?

**Comment by floam** [comment]
<em>You don't have to put various characters to show what a theme looks like, right?</em>

The web config actually shows your real prompt from whatever directory you are in. So there could be any kind of characters there.

**Comment by jakwings** [comment]
Ah, sorry, I forgot to view the "Prompt" section on the webpage. :P I thought the example is static.

For Chinese there are: WenQuanYi Zen Hei Mono, WenQuanYi Micro Hei Mono, WenQuanYi Unibit

For CJK: Source Han Sans ?? HW (?? is TC SC JP KR?, I don't remember…)

Ambiguous-width characters is a reason that Source Han Sans HW is out for me, because it uses double-width for tables and ellipses.

**Comment by floam** [comment]
｀

**Comment by floam** [comment]
I

**Comment by pickfire** [comment]
> Would somebody in Korea, Malaysia, China have their terminal set up with a CJK font?

@floam I used chinese font in terminal in order to search for meanings:
```fish
ydcv "看到了吗?"
```

Need to ask some active members about using CJK characters in terminal. CC @bucaran, @xiaq, @jethrokuan

**Comment by bucaran** [comment]
I use `Source Code Pro` too.

screen shot 2016-04-15 at 7 58 45 pm

**Comment by jethrokuan** [comment]
I've now switched to `Source Code Pro`, but have never needed to type non-english characters in my terminal. I run arch-linux.

**Comment by krader1961** [comment]
This is starting to get moldy. Should this be merged or does it need more work?

P.S., I don't understand why we're even forcing a preference for a particular font in the portion of fish HTML that attempts to render what the user might see in their terminal. We can't know what font the user's terminal is using. So how likely is it that this heuristic will produce a better experience than just specifying "monospace"? Too, if someone is using the Powerline or a CJK monospace font it seems to me it is their responsibility to configure their web browser to use that as their default monospace font.

**Comment by floam** [comment]
Oh, I forgot about this. I think I'll update this with what we do in the dock (Thanks @MarkGriffiths)

The reason I started this was because we were specially using Courier New, which I think we can all agree isn't awesome.

Most browsers these days do not make it easy to pick a monospace font. It's a webapp, nothing wrong with picking fonts we like.

**Comment by terlar** [comment]
I don't know about your system but on linux with fontconfig it is quite easy to set the `monospace` font. I have set that one to my preferred monospace font and that is used in different applications and web browsers. So in my case `monospace` would always be the preferred font, however I understand that that might be a bad experience for other users. I could alternatively not have the new fonts installed or blacklist them to achieve the same effect.

**Comment by krader1961** [comment]
> Most browsers these days do not make it easy to pick a monospace font.

Really? In Chrome and Safari it's trivial to specify the monospace font I want the browser to use by default. And as @terlar points out web browsers probably honor the system wide setting if they haven't been told to use something else. All an app has to do is specify `font-family: monospace` in the relevant CSS code to use my preferred font. I guess what I'm asking is why is fish specifying anything other than `monospace`? Can't this be "fixed" by simply replacing

```
font-family: Courier, "Courier New", monospace;
```

with

```
font-family: monospace;
```

?

**Comment by floam** [comment]
> In Chrome and Safari it's trivial to specify the monospace font I want the browser to use by default.

Can you show me a screenshot of where you are easily setting that option in Safari 9? I don't think you're going to get this done without fiddling with undocumented keys through `defaults write com.Apple.Safari ...` or authoring a user stylesheet. Why should a user have to workaround artifacts in fish's configuration interface by such means?

> font-family: Courier, "Courier New", monospace;
and 
> font-family: monospace;

Are equivalent, is the point. Safari/WebKit use Courier for `monospace`.

**Comment by krader1961** [comment]
> Can you show me a screenshot of where ...

I can't  because apparently I was relying on my faulty memory. As much as I prefer OS X over MS Windows this is one aspect where OS X sucks. I didn't think to confirm my assertion because I haven't used the Safari browser in a very long time. Do we really need to override user preferences in more sane browsers just to accommodate Safari users? Perhaps we do but I haven't seen a good argument for doing so. Certainly the code you're modifying doesn't make that case since it simply forces the Safari behavior on non-Safari browsers.

P.S., Gitter reports that you modified your comment at least eleven times since you first wrote it and as I was typing this response. Do you really expect people to keep rereading a comment you made as they're responding to it?

**Comment by krader1961** [comment]
> ... because these are (almost always) equivalent, is the point.

I admit I'm a neophyte with respect to HTML and CSS but I don't see how those are equivalent. We're explicitly telling the browser to use a font if it is available. Even if that isn't the one selected by the user as their preferred default monospace font.

It may be the case that we have to force the use of a specific font given the de facto behavior of the browsers we're targeting, not to mention the relevant standards. But that should be explicit (e.g., via comments in the code) rather than implicit.

**Comment by floam** [comment]
> Do you really expect people to keep rereading a comment you made as they're responding to it? 

I didn't - the edits were inconsequential, or at least seemed that way. I mostly was restyling your quote there and making small fixups for the sake of brevity. I only had the two points to make and they didn't change - if you read it once at any time your takeaway would be unchanged.

However - potentially causing uncertainty or confusion is certainly not helpful towards goal ("agh, improve that!") - I did forget that edits of all sizes will show up the same on Gitter's radar - I'll try to keep in mind that formatting/brevity improvements may not be quite as clear-cut good-for-everyone as they seem at first, in the future.

**Comment by floam** [comment]
> Even if that isn't the one selected by the user as their preferred default monospace font.

This is basically not how it works - this hypothetical user is relying on unpredictable, basiclaly undefined behavior that is rarely bothered with, and is not very effective towards his goals. `monospace` is the *fallback* font, not a "user's favorite"  override. it is not intended by the W3C to be anything other than an implementation-defined fallback which has the property of "it's some monospaced font the system has" - that's it AFAIK.

It's been a long time since changing these defaults would have much effect on the rendering of typically-encountered WWW content. Most browsers do not expose this rarely-effective, hard-to-understand option for tweaking by end-users anymore. It will only come into play if and when all the **actual fonts preferred by the author** are unavailable. As one commenter up above described, for Chrome, he's going to be setting his preferred font by modifying things down at the level of font-config - and even changing what `monospace` resolves to won't help him - next he needs to start nuking all the other fonts an web author might ask for. Should he do this successfully, this is still no guarantee that Chromium will actually use that preference of his all of the time for "monospace" - there are a number of exceptions hard-coded in for various situations..

**Comment by floam** [comment]
> forces Safari behavior on non-Safari browsers.

This is hardly Safari-specific, FWIW.

**Comment by jakwings** [comment]
@terlar 

> I don't know about your system but on linux with fontconfig it is quite easy to set the monospace font. I have set that one to my preferred monospace font and that is used in different applications and web browsers.

Esay? I don't think so. You may need to keep logout and login until you find the best font(s). This solution is already included in my previous thought: *(There might be ways to do this outside the terminal, but that's difficult.)* That's even harder on Mac and Windows, or other distributions of \*nix.

@krader1961 

> It may be the case that we have to force the use of a specific font given the de facto behavior of the browsers we're targeting, not to mention the relevant standards. But that should be explicit (e.g., via comments in the code) rather than implicit.

No need to be so serious. All popular web-browsers (Safari, Firefox, Chrome, IE?) only let you specify **one** font for monospace, then the missing glyphs come from the fallback fonts which include proportional fonts. Also, most terminals only let you set one font. And more importantly, we cannot (easily) detect which fonts are used by the terminal. It is impossible to make it perfect.

So the points made by @floam are just this simple: to make the preview prettier and fashionable. We are not dealing with bugs.

**Comment by terlar** [comment]
@jakwings 
This is a one time thing and usually something you do once to setup your preferred fonts. It is totally possible to do without restart though. Just configure things in `~/.config/fontconfig/fonts.conf` and run `fc-cache -fr`.

Personally it was one of the best things I did for the look of my system and general feeling across applications and webbrowsers. To properly configure the fonts nicely really gives the general feel on the web and in apps. You'd be surprised that there are quite a few pages out there that relies on these "default" fonts, especially when it comes to wikis and documentation pages.

However your point about other systems probably stands and I don't think we should do what is most convenient for one system or browser. Whatever suits people, I don't mind. Just giving some input on the default fallback fonts and how people might be using them.

**Comment by terlar** [comment]
Something like this is not uncommon from what I've seen:

```css
pre, code, tt {
  font-family: monospace;
}
```

**Comment by floam** [comment]
To accomplish what exactly, outside the context of a reset/normalization stylesheet?

**Comment by floam** [comment]
If you're talking about setting your preferred fonts, a user stylesheet configured in the browser with:

```
pre, code, tt {
  font-family: "My favorite font";
}
```

... would likely be a more correct and successful method to go about doing that than trying to fool around with an actual font definition for `monospace`.

**Comment by terlar** [comment]
I meant that many pages are using that and thus setting up your defaults will result in a better experience. The same goes for `sans-serif` and `serif` too. For example wikipedia has `sans-serif` as default font for the text body. And if you check the code blocks on wikipedia it is `font-family: monospace, Courier`. Making sure that if you have a preferred monospace configured it will use that, otherwise fallback to `Courier`.

The point of configuring your monospace font is that instead of in every configuration, every application etc having to set that specific font you just configure it in one place. So I configure which font should be my monospace font and then in all other places, the terminal, the browser, my text editor I use monospace as font. If I ever would like to change my monospace font I just reconfigure what `monospace` is resolved to.

**Comment by floam** [comment]
I don’t believe setting those particular elements styles with `font-family: monospace;` should do anything on its own — that should be the implicit behavior until a different styling is set or inherited. It’s kind of like saying `b { font-weight: bold; }`. Likely any instance you see of this is either to overrule something else they did in the stylesheet, or it’s being done for clarity and/or to pave over any potential implementation differences, sometimes as a CSS reset (ie. https://necolas.github.io/normalize.css/4.1.1/normalize.css).

**Comment by floam** [comment]
> font-family: monospace, Courier 

This is not done why you think it is. It’s to counter a Firefox bug to where it does not size monospace fonts set with em units correctly. Doing this causes it to go down a different cod path so that the `font-size` is calculated the normal way and inline monospaced text sized with em’s will be the same size as proportional text, instead of using an annoying hard-coded font-size behavior for `monospace` (default for these elements) unique to Firefox. Courier will be ignored but it affects the end result. It doesn’t affect the font used.

Aaron

**Comment by MarkGriffiths** [comment]
At the end of the day, in a html/css context, font selection is like cake. Everyone likes cake, everyone wants some cake, some need or would prefer a certain kind of cake and people, on the whole will moan if they don't get any cake at all. The longer you spend talking about what the cake should be, the prospect of anyone getting cake becomes ever more distant.

However, if you turn up with a lovely, appetising cake that happens to be gluten, lactose and nut free (my partner excels at this), chances are that everyone will be happy that they've had cake without ever considering the decision tree that led to that cake being baked.

And no doubt there's a few of you thinking 'I don't like cake, can I have a biscuit?'...

More scientifically, good browser font selection is probably the result of more overlapping bell curves and polarised user opinion than any other aspect of user facing design. It is, after all, the foundation of achieving good communication with the user. Hitting the sweet spot between individual user specificity, platform generalisation and implementation exceptions takes time, research, experience and some iteration. So a few clichés/points...

#### Content is king.

This isn't about your choice of terminal font, this is about rendering `fish_config` in a way that more closely resembles what a user will actually experience (which is rarely Courier these days). The fonts used should be able to accurately render the content as presented.

If you use 'exotic' characters in your prompt, there's a much better chance that DejaVu or Source Code Sans, if installed, will provide a fair preview, before falling back to Unicode substitution or system-specific defaults such as Menlo (a slightly recut subset of DejaVu) or Consolas and ultimately `monospace`

#### `monospace` is a bad first alternative.

Personally I can't stand Courier as a monospaced font and here OSX is diametrically opposed to Linux. Safari (and iOS) removed any ability to set default fonts ages ago, so when trying to accommodate a general audience it should only be used as a final catch-all, not to 'just support' Safari, but because Safari's implementation changes the generalisation.

Done right, this will often be the font picked up by Linux clients, playing to the configurable ethos inherent in the platform, unless the user has any of the higher priority alternative fonts installed, which should still feel 'correct' for that user.

I have browser CSS overrides locally defined that target code, pre, tt tags/classes etc to prevent me seeing Courier on Wikipedia and even override Github's defaults, but that's just me applying my opinion through user specific options. The usual User > Application > System > Global priority should apply.

#### 'Configurability is the root of all evil'

The fish design doc says it all right there. While the temptation is present to provide any user the ability to configure things exactly the way they want, this should be done in a way external to what fish provides, which should be a good, wide default.

Looking at the html source of `fish_config` it might be an idea to add consistent class declarations to any `<div>` tag containing terminal-like content to allow an external user stylesheet to override the provided defaults. Might be a good solution for powerline font users who want to see the previews rendered exactly as they want. Chances are that a user who has set up a powerline based prompt isn't going to be going into `fish_config` to change it.

#### 'Do it right and no one will know you've done anything at all'.

Can't over emphasise how important this one is. Get the defaults right and most of the users will be entirely happy in their ignorance and acceptance, and those who aren't are exactly the ones who will know what they can do about it. I actually prefer the aphorism 'Simplicity is the ultimate sophistication', and there's nothing quite as sophisticated as getting web fonts right.

**Comment by floam** [comment]
> it might be an idea to add consistent class declarations to any <div>

A lot of these `div`'s could also be not-divs, there are more semantically-correct elements that should be be used in most of these cases `<tt>` then inline or `<code>` for blocks. I intend to go ahead and try to improve this, and use a class elsewhere, to avoid having us set these fonts at the `body {` level, which strikes me as Wrong.  (I also want to use proportional fonts in places where that makes sense.) Indeed, this will make it easier to override for anyone who cares.

But this PR, I feel is done, unless you or anyone else can point out something I missed, I think it should be merged.

**Comment by jakwings** [comment]
It is weird that the line-height is still 1.8em instead of 1.0.

**Comment by krader1961** [comment]
This pull request is now more than a month old.

@MarkGriffiths: Do you see any reason not to merge this? You seem to be the only fish contributor with expertise on such matters. It looks okay to me in as much as the new set of preferred fonts is no worse, and probably better, than the old set. But then I don't understand why fish is even overriding what should be the users preferred monospace font. If a fish user who is using something like "Source Code Pro" can't be bothered to configure their browser to use that font why is fish forcing it to be used (assuming it is installed)?

Regardless, I'm going to merge this approximately 48 hours from now if no one objects. We need to either merge or reject pull requests in a timely manner.

**Comment by MarkGriffiths** [comment]
@krader1961: The key point is that not everyone can override the default fonts, and worse, cannot override the default on a standard, os-provided browser, so providing a nicely collapsing alternative becomes more important (disregarding any use of embedded fonts, which I think would be totally out of scope here).

Since @floam's last commit on this, the fonts look in a sensible, usable order that should just about encapsulate everyone and I think it'll be a great improvement.

**Comment by krader1961** [comment]
Merged as 00e32a0909e5d0d303936eec8cb697cb67069861

**Pull request closed without merging**
