### PR TITLE
Use a custom Lynx style sheet (LSS file) to work around Lynx bug

### LINKED ISSUE #4170: lynx bug causes `help` output to render as black on blue background
fish 2.5.0
Linux alarm 3.8.11-4-ARCH #1 SMP Sat Oct 22 11:59:55 MDT 2016 armv7l GNU/Linux
xterm

I am pretty sure this might be a lynx bug, but I will report it here as well since it might have a possible workaround on the fish side as well...

Steps to reproduce:
- install fish on a system that uses lynx as the browser (for exemple, a raspberry pi running raspbian)
- enter fish
- type help
- scroll to the introduction paragraph (on lynx)

Expected behavior:
The text should be pretty readable, for example, white over black.

Actual behavior:
The paragraph is black over blue, which is pretty ugly, see the picture

us3gyqe

-----

Here is a simplified html that causes this issue, the problem seems to be the "contents" class name...

```html
<html>
<body>

<div class="contents"> <p>foo</p> </div>

</body>
</html>
```

### PR DESCRIPTION
**Pull request by mqudsi**
Lynx uses a very naïve method of applying styles to HTML elements by
hashing the element type and the class name to generate a map of
hash:style. After the hash is calculated, Lynx does not go back and
check whether or not the actual string values match the LSS properties.

See the following links on the Links mailing list:
  * http://lists.gnu.org/archive/html/lynx-dev/2015-12/msg00037.html
  * http://lists.gnu.org/archive/html/lynx-dev/2015-12/msg00039.html

This patch copies the default Lynx stylesheet but removes highlighting
and other styles that would result in unreadable text (due to not enough
contrast with the background color), and if the `help` builtin detects
that the best web browser to use is Lynx, it instructs it to use this
modified stylesheet.

Fixes #4170

### CODE REVIEW

**Comment by mqudsi** [comment]
@zanchey can you please help me configure the build script to copy `./doc_src/lynx.lss` (from this commit) to `$__fish_help_dir` on install?

**Comment by floam** [comment]
In `Makefile.in`, just look for all the $(INSTALL) lines and add a new one for lynx.lss where you see it installing the documentation.

**Comment by mqudsi** [comment]
Thanks @floam!

**Comment by floam** [comment]
I'll take a look at the Xcode project later today, it'll need adjustment too.

**Comment by mqudsi** [comment]
Thanks, @floam, I see you already made the changes.

**Pull request merged**
