### PR TITLE
Add 'bigword' vi key bindings

### PR DESCRIPTION
**Pull request by msteed**
Please consider the following changes to the vi mode key bindings, which implement operations on whitespace-delimited words. The term 'bigword' comes from GNU readline.

Not having contributed to fish before, I'm happy to make changes for a better fit with the project. If this approach is not sufficiently fishy, I'd like to help implement this functionality in a fishier way.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Merged as cdfb425ac4bd64c2b043755eab6a748984b2e8e8. Thanks!!!

**Comment by msteed** [comment]
@ridiculousfish - looks like you snagged the doc changes but not the code

**Comment by ridiculousfish** [comment]
No, I think I got it all! See the parent of that commit.

**Comment by msteed** [comment]
Quite right, my mistake. Thanks!

**Comment by ridiculousfish** [comment]
Thank you for double-checking me :)

**Pull request closed without merging**
