### PR TITLE
Normalize tokenization of non-standard `[` usages

### LINKED ISSUE #2485: Fish does not split arguments in brackets
```
> fish --version
fish, version 2.1.1
> function showargs
    echo \($argv\)
end
> showargs one two three four
(one) (two) (three) (four)
> showargs one [two three] four
(one) ([two) (three]) (four)
> showargs one t[wo three] four
(one) (t[wo three) (four)
```

Arguments are being joined together when a `[` is embedded in an argument, but not when an argument starts with it.

### PR DESCRIPTION
**Pull request by mqudsi**
This enables the tokenizer to handle weird cases like those demonstrated
in this comment [0] on #2485. We basically expand support for `[` as
plain text to cover more cases than just the `[` alias for `test`, and don't tokenize content between `[` and `]` instances if the opening `[` is not standing on its own.

Honestly, `[` and `]` should generally be quoted as they have very
special meaning to the shell, but if someone wants to do something
creative with them (@cben, still interested?) this will at least
standardize their behavior and remove ambiguous parsing cases.

[0]: https://github.com/fish-shell/fish-shell/issues/2485#issuecomment-167235194

(I haven't tested this enough, I'm honestly surprised it passed all the unit tests.)

Closes #2485.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Can you explain more on what the behavior change is? I can't tell from the description what "handle weird cases" means. How will square brackets work after this change?

Also yes please write a bunch of tests :)

**Comment by cben** [comment]
Some notes on this here: https://github.com/fish-shell/fish-shell/issues/2485#issuecomment-427373424

**Comment by ridiculousfish** [comment]
From #2485 do I understand correctly that square brackets are normal characters except in indexing situations (i.e. immediately following `$` and `()`)? That's my preference:

    echo foo[ bar]      # two args
    echo (cmd)[ bar] # indexing operation
    echo $stuff[more stuff] # indexing operation

Let's add some tests to this to illustrate the behavior.

**Comment by mqudsi** [comment]
@ridiculousfish the current commits in this PR are going to be trashed, not happy with the new behavior. But the question is how to tokenize this:

```fish
set vars one [two three] four
printf \"%s\"\  $vars
set vars one t[wo thre]e four
printf \"%s\"\  $vars
```

**Comment by ridiculousfish** [comment]
I think it's acceptable to treat square brackets as an extension of variable expansion. So `[two` and `three]` would be distinct arguments as are all of the tokens in your example.

**Comment by mqudsi** [comment]
@ridiculousfish I'm not sure how to fix this. The relevant code [is here](https://github.com/fish-shell/fish-shell/blob/dfe6bc531e7388759ad703459dfe96a91c0c4bee/src/tokenizer.cpp#L207), but the problem is with the architecture.

The tokenizer is completely independent from the parser, and there's no support for conditional tokenization based off of the preceding token's classification (or for re-tokenizing an already tokenized portion of the buffer based on a determination made by the parser).

`[` needs to be magic if it immediately follows a subshell or variable (I can't think of any other cases where indexing is legal), in order to allow indexing the results of `$foo` or `(printf 'hello\nworld')` (allowing separation by whitespace?). 

The subshell case is easily treatable: 

```diff
diff --git a/src/tokenizer.cpp b/src/tokenizer.cpp
index 68b1d38e..cc24f108 100644
--- a/src/tokenizer.cpp
+++ b/src/tokenizer.cpp
@@ -141,6 +141,10 @@ tok_t tokenizer_t::read_string() {
     const wchar_t *const buff_start = this->buff;
     bool is_first = true;
 
+    // Determines whether a literal `[` will be given any special treatement.
+    // Set to true only in case a variable or a subshell is first parsed.
+    bool may_index = false;
+
     while (true) {
         wchar_t c = *this->buff;
 #if false
@@ -168,6 +172,7 @@ tok_t tokenizer_t::read_string() {
         } else if (c == L'(') {
             paran_offsets.push_back(this->buff - this->start);
             expecting.push_back(L')');
+            may_index = true;
             mode |= tok_modes::subshell;
         } else if (c == L'{') {
             brace_offsets.push_back(this->buff - this->start);
@@ -204,7 +209,7 @@ tok_t tokenizer_t::read_string() {
             }
             expecting.pop_back();
         } else if (c == L'[') {
-            if (this->buff != buff_start) {
+            if (may_index && this->buff != buff_start) {
                 if ((mode & tok_modes::array_brackets) == tok_modes::array_brackets) {
                     // Nested brackets should not overwrite the existing slice_offset
                     // mqudsi: TOK_ILLEGAL_SLICE is the right error here, but the shell
```

but the problem is with variables. When a `$` is encountered, tokenization is ended, meaning the tokenizer isn't aware that we're handling a token immediately after a variable name, and so there's no way to indicate to it that it should special-case the bracket handling. 

(Curiously, with the above patch alone basic indexing functionality remains intact for both subshells and variables.)

I've never fully grokked the tokenizer/parser duo, (in fact, a huge chunk of the problem comes from the fact that `expand.cpp` and `highlight.cpp` do their own tokenization). There are a lot of ways to fix this, but the ones that I see all involve centralizing all the lexing/parsing into one location, something I really don't want to give a go right now. Do you have any ideas on an easy fix for this?

**Comment by ridiculousfish** [comment]
yes an essential unsolved problem is that the tokenization required unbounded recursion: an index expression `$foo[...]` can contain command substitutions which themselves may require index expressions. It's gross.

I don't really know how to solve this yet, but I suspect that tokenization as a separate step won't survive.

**Comment by faho** [comment]
I'm closing this since it's not good to be merged, and we already have an open issue to track discussion - #2485.

**Pull request closed without merging**
