### PR TITLE
feat(completion): Add kops.fish completion

### PR DESCRIPTION
**Pull request by dzvon**
[kOps] is a set of tools for installing, operating, and deleting Kubernetes clusters.

[kOps]: https://github.com/kubernetes/kops/

### CODE REVIEW

**Review by Dominik50111 — COMMENTED** [review]
Ahoj

**Review by Dominik50111 — COMMENTED** [review]
Ok

**Review by Dominik50111 — COMMENTED** [review]
N

**Comment by zanchey** [comment]
Thanks!

**Pull request merged**
