### PR TITLE
Add missing color definitions to __fish_init_1_50_0 reset.

### PR DESCRIPTION
**Pull request by bucaran**
The values where determined by inspecting the values of:

* `fish_color_end`
* `fish_color_user`
* `fish_color_host`

after resetting the color theme via fish_config.

### CODE REVIEW

**Comment by faho** [comment]
user and host would also need to be documented (in doc_src/index.hdr.in).

And then there's a question: Do we want to remove the code to set them from the prompts (terlar and classic_vcs - the former sets user to bold green, the latter to bold cyan)? Do we want to add them to the themes? Do we want to set root's user color to red (or brred)?

**Comment by bucaran** [comment]
Those are good questions, and I don't have any particular preferences. But now I see where that green came from :)

If those colors are not adequate, then just set them to normal. This plus some sloppy code on my part was causing a bug in https://github.com/fisherman/fisherman/issues/246.

I fixed it on my end already, but I thought it would be nice and consistent to set the colors here to some values.

I don't mind adding the corresponding documentation, just let me know if you want to proceed with this :)

**Comment by faho** [comment]
>I don't mind adding the corresponding documentation, just let me know if you want to proceed with this :)

Yes, please do. The rest we can do later.

**Comment by bucaran** [comment]
@faho Done, what's the next challenge?

**Comment by faho** [comment]
Well, merging seems to have been easy, so the next is determining the answers to those questions.

My preliminary answers are:

- We don't want to remove the setting just yet - users who jump from a release that doesn't have this to one that doesn't set them in the prompt anymore would be left out

- Yes, we do want to add them to the themes.

- I'm not sure about root's color

**Comment by zanchey** [comment]
Taking this for 2.3.0.

**Pull request merged**
