### PR TITLE
Add completions for pass

### PR DESCRIPTION
**Pull request by legovini**
These are the completion definitions for the 'pass' tool, "the standard unix password manager", see http://www.passwordstore.org/ .

I preserved the copyright note of the original author, the license is GPLv2+. I just split the original code into two files, as I see it's usually done in fish.

### CODE REVIEW

**Comment by faho** [comment]
>I just split the original code into two files, as I see it's usually done in fish.

We've actually been trying to reduce that, and I'd much prefer a single-file solution, unless a function is usable elsewhere (for example in other completions).

>I preserved the copyright note of the original author, the license is GPLv2+.

Where did you get this from? Upstream? If so, they can ship their completion - that's what we made vendor_completions.d for. See "Where to put completions" in [the documentation](http://fishshell.com/docs/current/index.html#completion). 

Because of that I'm closing this.
In case upstream doesn't want to ship them anymore, please say so and we'll revisit this.

**Comment by zanchey** [comment]
Yes, this is a duplicate of #1843 and #2089.

**Comment by legovini** [comment]
Indeed the completion file was already part of the upstream package, but it was not distributed with the Debian package. I filed a bug there a new package with the fish completions installed in vendor_completions.d is already available in the official repository!

**Comment by faho** [comment]
That's good news. I always like it when upstreams support fish.

**Pull request closed without merging**
