### PR TITLE
Introduce path variables

### PR DESCRIPTION
**Pull request by ridiculousfish**
This PR is another go at #436, more ambitious than #5188.

This introduces a notion of "path variables." Path variables provide special support for colon-delimited variables including PATH, PYTHONPATH, GOPATH, etc. 

Path variables act as normal variables except:

1. They are joined by `:` instead of space inside quotes. `echo "$PATH"` will have colons.
2. They are *implicitly split* by colons. That is, `set PATH "/tmp/bin:$PATH"` will no longer result in a bogus PATH. Path variables cannot contain colons themselves.

Variables that end in "PATH" are automatically path variables. Variables can be queried for their path status (though somewhat awkwardly) via `set -q`.

Users can mark a variable as path via `set --path MYVAR SOMEVALUE`, or `set --unpath` to mark it as not a path. This property is tied to a variable (not its name) similar to `--export` and `--unexport`.

I played around with a notion of having each variable track a settable delimiter but found it to be too complex; I think having specific support for path-style variable is just right and not overly constraining for the future.

Unanswered questions:

1. Should non-path variables be exported separated by spaces or colons? (Spaces I suppose?)
2. Do we still want splitenv with this version? (I think not).
3. Universal variables will need to support these, which means we'll need to modify the universal variable file format. This is a good release to do so, since the file moved so there's no backwards compatibility concern.  That will probably be a separate PR.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
If you want to set a variable to a fixed value without inferring its path status, you can do it:

     set --unpath SOMEPATH /foo/:/blah

To "recongeal" a path variable to a single string with colons:

    set --unpath SOMEPATH "$SOMEPATH"

This is a little sneaky:

1. First $SOMEPATH is expanded. It's still a path variable so it gets colons.
2. `set` receives `--unpath` so it doesn't split on those colons.

**Comment by faho** [comment]
>This property is tied to a variable (not its name) similar to --export and --unexport.

I'm not entirely sure what that means. Do you mean it needs to be specified every time, otherwise we fall back to the default?

I.e.

```fish
set --path foo bar:baz # results in two elements
set foo bingo:bongo # results in one element because it reverts to not a path

set --unpath FOOPATH bingo:bongo # one element
set FOOPATH bar:baz # two elements because it reverts to a path
```

That seems like it would make non-default variables a tad annoying. What's the rationale here?

**Comment by faho** [comment]
>Should non-path variables be exported separated by spaces or colons? (Spaces I suppose?)

Spaces is the most generally useful. I suppose that means we've given up on inheriting lists?

>Do we still want splitenv with this version? (I think not).

Doesn't seem all that useful, no.

**Comment by ridiculousfish** [comment]
> I'm not entirely sure what that means. Do you mean it needs to be specified every time, otherwise we fall back to the default?

No, if you don't specify `path` or `unpath`, it uses the existing status (if any), or inherits from a parent (if any), or lastly falls back to the default name-based heuristic.

More precisely, the behavior is:

1. New variables inherit the path status of variables in parent scopes. So if you set a path variable in the global scope, and override in it in local scopes, the local gets the path status of the global.

2. If you modify an existing variable, and don't specify `--path` or `--unpath`, it retains its old path status.

3. If you do explicitly specify `--path` or `--unpath`, that's scoped the same as the variable. So for example you can have a local path variable shadow a global non-path variable.

This matches the behavior of `--export` and `--unexport`.

**Comment by faho** [comment]
>No, if you don't specify path or unpath, it uses the existing status (if any), or inherits from a parent (if any), or lastly falls back to the default name-based heuristic.

That'll work!

**Pull request closed without merging**
