### PR TITLE
Update pcre2 to 10.21 release and track as a git submodule instead of hosting a copy in version control

### PR DESCRIPTION
**Pull request by floam**
It'd be nice if fish could include pcre2 10.21 when when 2.3.0 comes out. This PR updates pcre2 and further tracks it as a git submodule (GitHub mirror of svn). See https://gist.github.com/gitaarik/8735255 on how to work with these.

This will make maintenance easier in the future and permit easy bisecting should a  future release break something in fish, while keeping the actual files and their histories out of the the fish tree. Only the metadata regarding the commit and repo we we want is stored. On clone you get the pcre2 tree inside your working directory like before and it won't try to update itself to their HEAD. It's pointing at exactly the the commit corresponding to the 10.21 release right now.

### CODE REVIEW

**Comment by floam** [comment]
Yes, it's broken and I need to fix it.

**Comment by floam** [comment]
What. That was ugly but I don't know why it didn't run autogen.

**Comment by floam** [comment]
OK, I think travis has his own install script.

**Comment by krader1961** [comment]
My two cents: Updating the pcre2 lib we bundle with this project is fine but I'm not convinced we should use the git-submodule capability to do so. In particular because the github version of the pcre2 project is mirrored from SVN which means we can't sync to a specific tag (i.e., release label). We'll always be syncing to whatever the latest commit was or having to figure out what the desired commit ID should be.

Also, the only reason we do this is because at the time fish started using the pcre2 library a lot of distros didn't include it. I'm willing to bet that's no longer true. Which, if true, greatly reduces the need for us to be always tracking the pcre2 project. We really should be using whatever pcre2 lib is in the distro and only falling back to the one we bundle with the fish source if the lib isn't found. If we do that then it's not clear we need to track the latest changes to the pcre2 source.

It looks like @msteed did the original integration and @ridiculousfish and @zanchey have made all the subsequent changes so I'd like to see at least two of them weigh in on whether this is a good idea.

**Comment by msteed** [comment]
See the discussion beginning at https://github.com/fish-shell/fish-shell/issues/156#issuecomment-124966284 that led to including the pcre2 sources in fish. Maybe some of those considerations have changed; I'll defer to fish project owners on that. I do agree with @krader1961's concerns about using git submodules.

If we move to requiring pcre2-10.21 or later, we can take advantage of some improved behavior in `pcre2_substitute()`.

**Comment by ridiculousfish** [comment]
We definitely don't want to track pcre2 HEAD. We should update to new PCRE2 versions only when they do releases, and after our testing.

Regarding using distro-supplied PCRE2s, naively it seems like this would make us vulnerable to differences across library versions and increase our testing matrix. If there was a known buggy or incompatible version, for example, we would have to blacklist it. What are the benefits for doing this?

**Comment by floam** [comment]
> . We'll always be syncing to whatever the latest commit was or having to figure out what the desired commit ID should be.

Not sure why it would be necessary to bump it from being locked to an SVN commit corresponding to a releasee more than a couple times a year as needed.

**Comment by jrobeson** [comment]
distros like Debian and Fedora are gonna use the non-bundled pcre versions where possible anyways. So it's either test more at the source, or deal with the potential bug reports later.

**Comment by krader1961** [comment]
> Regarding using distro-supplied PCRE2s, naively it seems like this would make us vulnerable to differences across library versions and increase our testing matrix.

Sure but why is pcre2 any different than ncurses or glibc in that regard? It looks to me like the oldest release of pcre2 on sourceforge is dated 2015-01-05 and there have been three releases since then. So a modest amount of churn. And, of course, a lot of the code is from the older pcre library which is quite mature and stable.

> this PR is stuck at 10.21

Yep, I see that now. It took me a few minutes to figure out that you're committing a dependency on a specific github commit ID that this [page](https://github.com/svn2github/pcre2/commits/master) shows is the "Final file updates for 10.21 release" committed on Jan 12.

As long as you can make Travis work reliably with this change and a couple of us pull it into our own local repos and don't have any problems I'm okay with merging this.

**Comment by ridiculousfish** [comment]
> Sure but why is pcre2 any different than ncurses or glibc in that regard?

It's not in that regard - we are vulnerable to differences in any of our dependencies. See for example #626 or #2199 for places where we got bit by libc differences.

However it's not practical to ship our own versions of these because 1. they're quite big, and 2. they differ across systems. (obviously, running glibc on OS X won't work). But PCRE2 is small and ought to have no platform differences, so we can ship our own version.

My question was an honest one - What are the benefits for using a system supplied PCRE2?

**Comment by zanchey** [comment]
See [Debian's upstream guide](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code) for their reasoning on why they prefer projects to avoid shipping copies of code, or at least allow the use of system libraries.

**Comment by krader1961** [comment]
> What are the benefits for using a system supplied PCRE2?

The users of a system can expect fish'es behavior regarding pcre's to behave similarly to other programs in that distro; i.e., be bug for bug compatible. This is obviously unlikely to be noticed in practice in this specific instance. We should always be using the distro supplied support libraries whenever it isn't known to break us.

**Comment by zanchey** [comment]
My concern is that this pulls in a dependency on automake, further complicating the build process and development. I think the Xcode build and the tarball generation scripts will also need updating.

**Comment by floam** [comment]
> My question was an honest one - What are the benefits for using a system supplied PCRE2?

If there's a security vulnerability, I can expect a faster reaction, and it will fix all my apps. Same goes for some other bug between my OS and that library.

**Comment by jrobeson** [comment]
@krader1961 : Fedora packages had to get an exception from FESCO (committee) to bundle any libraries until very recently. And it's still very frowned upon to bundle any libraries

**Comment by jrobeson** [comment]
on that note @amluto : how come you bundle pcre in the fedora packages?

**Comment by jrobeson** [comment]
@zanchey  I don't really have a problem with fish including pcre, as long as automake still works and we can still build against the system pcre

**Comment by ridiculousfish** [comment]
Ok, I'm convinced, if someone wants to put in the work to enable building with a system-installed PCRE2 that sounds good

**Comment by floam** [comment]
It already will build (and works fine) with a system PCRE2 if you configure with `--without-included-pcre2`. Shall it it prefer a system pcre2 and use the included one a a fallback?

**Comment by amluto** [comment]
@jrobeson Do I?  I don't think Fedora's fish is new enough to use pcre at all.

Which reminds me: I don't suppose anyone wants to make a new release of fish.

/me waits anxiously for Fedora 22 to be EOLed.  I get crash reports all the time on Fedora 22, I think it's some glibc bug that's fixed in newer Fedora versions, and I have no desire to try to track it down.

**Comment by jrobeson** [comment]
oh @amluto I didn't realize it was that new of a dependency.

@floam : I think it should use the system pcre2 if it exists, and then fall back (with notice/warning)

**Comment by zanchey** [comment]
I added the ability to use system pcre2 (and turned it on by default) way back in 3ffbf9a7ea569 - the question here is whether we should use a git submodule rather than storing the contents of the release tarball. My preference is for the latter to avoid taking an automake dependency and complicating the build further.

**Comment by ridiculousfish** [comment]
Wow @ zanchey, way ahead of all of us :+1:  I agree with storing the tarball rather than submodule.

**Comment by floam** [comment]
Could we store the actual tarball instead of a directory structure? I suppose I dislike that static analyzers are about as happy to show tell me about the dead code in the pcre2 codebase as it is the fish database, and all of the files have no meaningful git history.

Something that we'd get for free with the git submodule if we want it is the behavior where until you do a git init in ./pcre2/ it need not be grabbed. I was going to have it do one automatically the first ./configure

**Comment by floam** [comment]
Probably the most "first class" way to include pcre2 in the fish tree would be to pare it down to exactly what fish needed and throw out the rest - including it's building system - [and just let fish build it](http://www.pcre.org/current/doc/html/NON-AUTOTOOLS-BUILD.txt).. but this project forking pcre2 would not be great. 

I suppose I don't understand the original motivation or current reservations in this topic - I read the thread linked to by @msteed searching for the discussion about the pros and cons of including a package or doing a git module vs. other ways of bundling the pcre2 project into fish and found it that there just wasn't actually much said and little in the way of people explaining where they are coming from.

**Comment by zanchey** [comment]
The advantage of having the tarball, expanded, in the source tree, is that it's easy to understand and replace.

Merging only an edited copy of the source or using a non-autotools build creates problems for maintainers and downstream packagers

Storing the compressed tarball adds further (possibly manual) steps to the build process and makes it harder to get new developers and packagers up to speed.

Using the git version, as discussed, complicates the build process, adds an Automake dependency, and makes the Xcode build tricky as well.

If static analysis is the problem, it is probably easier to avoid analysing artefacts from that directory than anything else.

I'm going to close this for now as it appears @ridiculousfish and I agree at present, although I'm happy to hear other's opinions.

**Comment by krader1961** [comment]
Turning this into a git submodule has limited benefit for us given how often pcre2 changes and we make a new fish release. And it doesn't solve the issue of lint tools reporting on the pcre2 code. Like the configure tests and compatibility shim for getopt_long() that I recently removed I suspect that in a year or two we'll be able to remove the pcre2 code and simply make that package a hard dependency for any distro that wants to include fish. And that includes anyone installing it on OS X  (using homebrew to install pcre2 isn't a huge burden).

**Comment by floam** [comment]
>  And it doesn't solve the issue of lint tools reporting on the pcre2 code

Oh, it would have for me, as if one didn't ever choose to run `git init` in the submodule folder and the configure scripts didn't do it for me when they found no system prcre2, it would just stay empty. 

Of course if I want that I am free to set up a git hook to delete it or somehow configure it to track the directory locally as empty. :)

After peering inside the build system and having autotools flashbacks -- especially as I assumed the xcode project was either shelling out to the Makefile or generated along with it from a CMake definition or something (that's why there's no automake right??)... it's a nice break that I got let off hook and this one got summarily closed. After putting together a shortlist of things I'd want to address to get this accepted with nobody able to notice anything changed... a valid point exists that it perhaps not would have been worth, on balance, the work necessary to secure my foresighted, benevolent, pure, and necessary vision for the future...

**Comment by floam** [comment]
> Like the configure tests and compatibility shim for getopt_long() 

I was just thinking, wouldn't these be better spun off into sister repos under the fish-shell organization, linked in as...

**Pull request closed without merging**
