### PR TITLE
completions(ollama): ollama need no files as i know

### PR DESCRIPTION
**Pull request by NextAlone**
## Description

Fix completions for ollama

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by mqudsi** [comment]
Can you please remove the changelog changes? We wouldn't include something like this there (the pull request template should probably be updated).

**Comment by zanchey** [comment]
The PR template does have a note (as a comment): "Don't document changes for completions inside CHANGELOG.rst, there are lot of such edits"

**Comment by NextAlone** [comment]
Should i create a new pr, only with completion file?

**Comment by mqudsi** [comment]
You're good. It was easier for me to just do it locally. Thanks for the PR!

**Pull request closed without merging**
