### PR TITLE
fst and lst functions for first and last members of list respectively.

### PR DESCRIPTION
**Pull request by Nirma**
While writing fish scripts in my personal and work life I have found this shorthand useful.

### CODE REVIEW

**Comment by faho** [comment]
Can you point out a script where you've used it, or even better a place in fish where it'd be useful?

Also I'm not sold on the names, I'd like "first" or "last", though "last" is an actual command on linux at least. How about "__first" and "__last"? We have a couple standard functions that we prefix with "__fish_" (like "__fish_seen_subcommand_from") but that's quite a mouthful and "__" should be reasonably unique on its own.

I like the idea of a "fishlib", a standard library of functions that one can expect to be there on a fish installation.

**Comment by Nirma** [comment]
@faho I used as a simple way to grab extremes in sorted lists. 
For example `fst (ls -S)` will give you the largest file and `lst (ls -S)` will give you the smallest but the cool thing about doing it this way in my opinion is that it works with both fish lists and the output of commands.

**Comment by Nirma** [comment]
@faho @ridiculousfish I agree the naming is odd but if these functions were to be included I don't want to   cause conflicts with the `last` command or inconsistencies like having one function named first and the other lst. Haskell uses fst and snd for grabbing the first and the second members of a tuple so I don't believe the naming is too foreign to developers.

**Comment by ridiculousfish** [comment]
This can be written directly as `(ls -S)[1]` and `(ls -S)[-1]` though that may look a little weird.

**Comment by Nirma** [comment]
@ridiculousfish I really like that approach too but one issue with directly indexing the output like that is it will error out when there isn't any output.
If you run `echo (ls)[1]` in an empty directory it will fail with `fish: Could not expand string '(ls)[1]'
echo (ls)[1]`

**Comment by pickfire** [comment]
I got the following errors in an empty directory by `echo (ls)[1]`:
```
Array index out of bounds
fish: echo (ls ^/dev/null)[0] ^/dev/null
```

**Comment by faho** [comment]
>fish: echo (ls ^/dev/null)[0] ^/dev/null

That error is to be expected, fish lists start at 1.

    echo $PATH[1] # works
    echo $PATH[0] # Array index out of bounds
    echo (ls)[1] # works
    echo (ls)[0] # Array index out of bounds

**Comment by Nirma** [comment]
@faho "I got the following errors in an empty directory by echo (ls)[1]" he is indexing by one in the first part. 
That is an issue in empty directories / when there is no output.
Its expected because you are indexing the first element of nothing, but wouldn't it be better to just safely either pull the first value or do nothing?

**Comment by Nirma** [comment]
@ridiculousfish I really think what @faho suggested with having a standard fish function library would help a lot.
What do you think of friendly fish convenience functions?

**Comment by ridiculousfish** [comment]
I appreciate that these are convenient, but I dislike grabbing names, especially short names, since they override any installed commands (now or in the future) with the same name. This would be more appropriate as a [wahoo package](https://github.com/fish-shell/wahoo) (or, of course, you can define them locally).

**Comment by faho** [comment]
I've thought about this some more, and I believe that these functions do the same thing slices do (i.e. "[1]" and "[-1]" in particular), so because of [the law of orthogonality](http://fishshell.com/docs/current/design.html), they should be removed or not added in the first place, and any issues slices have should be fixed instead.

As for the question of a "fishlib" of convenience functions shipped along with the shell, I personally like the idea, but the specifics (particularly of names) need to be sorted out before any progress can be made. My suggestion would be to start all fishlib functions with an uncommon prefix, e.g. "fish_" or just "_".

I am therefore closing this for now, if anybody disagrees, please speak up.

**Comment by Nirma** [comment]
@faho @ridiculousfish Thanks guys for the feedback, I really appreciate it!
Im still trying to get a feel for the fish shell philosophy!

**Pull request closed without merging**
