### PR TITLE
Allow POSIX-style loops with do/done and if statements with then/fi

### PR DESCRIPTION
**Pull request by krobelus**
I sometimes want to compose a for-loop in fish (so I have completion
and can test it right away) and paste the final command line into
a /bin/sh script, or send it to someone who doesn't have fish yet.
Support this by accepting the POSIX syntax for if/for/while statements.

Our motto "Don't be evil like them POSIX shells" has allowed us to
keep the fish syntax clean and easy to learn. To appeal to a broader
audience -- mostly users who are already corrupted by other shells --
why not allow certain evil constructs? Specifically, they are:

        for var in values; do command; done
        while condition; do command; done
        if condition; then command; fi

But don't document them, since that would make "if --help" more
confusing to new users. Maybe mention them somewhere else?

Also, accidentally allow

        begin; done
        function my-function; done

though those could be disabled if we care.

This introduces some breaking changes to the language: the new keywords
"do", "done", "then", "fi", plus the next commit's "elif" can no
longer be used in command position (whether as script or function).
This will probably not cause many problems because POSIX shells
already disallow these keywords as commands.

### CODE REVIEW

**Comment by floam** [comment]
I would like to revisit much of our dogma related to POSIX. This isn't the first thing that comes to mind but I should try to be kind and see that it's progress in the right direction and does not break anything.

**Comment by floam** [comment]
My immediate reaction, however, is "CORRUPTION!!"

**Comment by krobelus** [comment]
Yeah, I was a bit conflicted. Every single one of these is objectively worse than our existing syntax, so this feels really dirty.
But it does help a use case, and maybe it is what the people want..

**Comment by IlanCosman** [comment]
My first reaction is also "please don't". I will find out that one of these evil syntaxes, like `elif`. is .01% faster than the alternative and then be _**obligated**_ to use it 😂

**Comment by ridiculousfish** [comment]
I am in favor of adding bash-isms where users encounter friction, especially to support pasted one-liners. But also we shouldn't add bash syntax wherever we can, because fish cannot realistically get to the point of running more than a fraction of bash scripts (what with `set`, parens, etc). I think loop-syntax is in this second category. It's not used very often outside of scripts, and this feature alone will probably not enable any new scripts. So for that reason I think we should not add this.

Note #522 tracks the idea of a bash-compatibility layer. There's no design there at all, should someone want to pick it up.

**Comment by krobelus** [comment]
Makes sense.
I often use for-loops interactively, especially when a task is too complicated for `xargs`.
Though I can see that the scenario where this helps is a bit obscure and doesn't justify the cost / potential confusion.

**Pull request closed without merging**
