### PR TITLE
List killring entries

### PR DESCRIPTION
**Pull request by Caroleq**
## Description
This is proposal for a new variable containing entries from killring.   

I added a test for that, but tbh I'm not sure if this is needed - there is little that may get broken.  

Fixes issue #7445

## TODOs:

- [x] Changes to fish usage are reflected in user documentation/manpages.
- [X] Tests have been added for regressions fixed
- [X] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by krobelus** [comment]
Seems reasonable. You should rebase on latest master, then the merge commit will go away.

**Comment by Caroleq** [comment]
> Seems reasonable. You should rebase on latest master, then the merge commit will go away.

Done.  


Now I think we may want to add this variable to the documentation. I'll update PR today or tomorrow.

**Comment by zanchey** [comment]
I suggest adding this to the list in "Special variables" in `doc_src/interactive.rst` too.

**Comment by krobelus** [comment]
One interesting question is if/how the killring can be changed by the user. I think currently none of the electric variables are modifiable. Either way, I'm sure that's possible to add later.

**Comment by Caroleq** [comment]
> I suggest adding this to the list in "Special variables" in `doc_src/interactive.rst` too.

This section was in language.rst - I added it there.  



> One interesting question is if/how the killring can be changed by the user. I think currently none of the electric variables are modifiable. Either way, I'm sure that's possible to add later.

Hmm, my understanding of kill ring is that it can be modified only by adding new entries.

**Comment by zanchey** [comment]
I apologise for the bikeshedding, but I'm just wondering if it would be better to call this `fish_killring`. Electric variables become reserved variable names, and have the potential to break existing uses (though I can't see any in https://github.com/search?l=fish&p=1&q=killring&type=Code).

**Comment by krobelus** [comment]
> Hmm, my understanding of kill ring is that it can be modified only by adding new entries.

Yeah but maybe there's a good reason to modifying it on-the-fly, even if we can't imagine one yet.

(New subcommands to the builtin `status` are often a viable alternative to new special variables, but a variable seems OK here)

**Comment by ridiculousfish** [comment]
Looks good, merged as 9d66ddc8408b98362d5377cc498af02ff60eb991. Thank you!

**Pull request closed without merging**
