### PR TITLE
Possible fix for #2392

### PR DESCRIPTION
**Pull request by amluto**
I can't reproduce the bug in the first place, and this only affects weird error paths, so it's untested.

### CODE REVIEW

**Comment by faho** [comment]
@amluto: Can you get the original reporter to test this? It seems nobody can reproduce this (I certainly can't), so getting them to check would at least lend some credibility to this patch.

**Comment by faho** [comment]
For the benefit of keeping info here: This patch was pushed in Fedora on 2015-09-24, when the original reporter reported no longer seeing the bug.

It's then been pushed to Fedora's stable repositories on 2015-10-17, and as far as I can see nobody reported the bug again.

I'm now assigning @ridiculousfish because of https://github.com/fish-shell/fish-shell/issues/2392#issuecomment-143053688.

**Comment by zanchey** [comment]
@ridiculousfish, any objections to taking this?

**Comment by ridiculousfish** [comment]
After finally reviewing this I think it's a very good fix. We do swallow SIGPIPE in the fish shell so it makes sense we would get EPIPE. Really top-notch analysis from @amluto - kudos!

**Comment by ridiculousfish** [comment]
Merged with rebase as fea798011b25dea69c9ea7cc75c13170b99b0e9a. Sorry for the long delay and thanks for the nice fix!

**Pull request closed without merging**
