### PR TITLE
Add `nvme` completions

### PR DESCRIPTION
**Pull request by moverest**
This MR adds completions for the `nvme` Linux utility. It completes the sub-commands and some of their options.

### CODE REVIEW

**Comment by mqudsi** [comment]
Looks good. I like the jq-based default and the regular fallback.

Does `nvme` ever require sudo to provide the results?

**Comment by moverest** [comment]
> Does nvme ever require sudo to provide the results?

Yes, it does need root permissions on my machine (Arch Linux). I'm not sure why though because `nvme list` does seem to find them (when looking at the file accesses it makes to `/sys` with `strace`). It just does not print them for some reason. :thinking:

**Comment by mqudsi** [comment]
Ok, so does that mean the completions won't work because they execute `nvme` without sudo?

**Comment by moverest** [comment]
There's a fallback with `string match -vr -- 'p[0-9]+$' /dev/nvme*`.

**Comment by mqudsi** [comment]
Gotcha. Thanks for explaining.

**Pull request merged**
