### PR TITLE
fix: completion `git mv` with files

### PR DESCRIPTION
**Pull request by NextAlone**
## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
I'm not sure this is correct. This would enable the normal file completions for `git mv`, but that completes more than what `git mv` operates on.

E.g. go to a git repository and run this:

```fish
touch foo
git mv foo bar
```

You'll get an error:

> fatal: not under version control, source=foo, destination=bar

And the same if "bar" is tracked.

So at the very least, the source needs to be tracked by git already.

So this would need `__fish_git_files`, presumably with the list of all files that aren't untracked - `__fish_git_files all-staged copied deleted modified renamed`?

The destination can't be an existing file at all or you get "target already exists", unless `--force` was given. So technically we could complete *all files* if `--force` was given. I think that's okay to leave.

**Comment by NextAlone** [comment]
> I'm not sure this is correct. This would enable the normal file completions for `git mv`, but that completes more than what `git mv` operates on.
> 
> E.g. go to a git repository and run this:
> 
> ```fish
> touch foo
> git mv foo bar
> ```
> 
> You'll get an error:
> 
> > fatal: not under version control, source=foo, destination=bar
> 
> And the same if "bar" is tracked.
> 
> So at the very least, the source needs to be tracked by git already.
> 
> So this would need `__fish_git_files`, presumably with the list of all files that aren't untracked - `__fish_git_files all-staged copied deleted modified renamed`?
> 
> The destination can't be an existing file at all or you get "target already exists", unless `--force` was given. So technically we could complete _all files_ if `--force` was given. I think that's okay to leave.

I can't get all git files with `__fish_git_files`, with command mentioned above.

**Comment by faho** [comment]
> I can't get all git files with __fish_git_files, with command mentioned above.

What's missing?

What does `git status --porcelain=2` print, in the first two columns, for the missing files?

**Comment by NextAlone** [comment]
> > I can't get all git files with __fish_git_files, with command mentioned above.
> 
> What's missing?
> 
> What does `git status --porcelain=2` print, in the first two columns, for the missing files?

It only gets changed files, while files no changes won't show.

**Comment by faho** [comment]
Aaah, okay, yeah, that's right.

Okay, ls-files is probably the right thing to use, then.

**Comment by faho** [comment]
Okay, merged. Thanks!

**Comment by NextAlone** [comment]
> Okay, merged. Thanks!

Thank you too

**Pull request merged**
