### PR TITLE
Better manpage completions

### PR DESCRIPTION
**Pull request by alehed**
On my system quite a few commands didn't get command completed, including my own ones.
This didn't happen for obvious reasons since running the create_manpage_completions script with
--stdout showed that the content was parsed just fine.
This was because there were other files with the same base name (usually directories, pdfs or builtin 
links) which were parsed, not understood and then caused command.fish to be deleted again. 
Placing a PDF next to the manpage is standard procedure in my LaTeX Distribution's manpages.
With these changes the amount of generated manpage completion files quadrupled.

### CODE REVIEW

**Comment by alehed** [comment]
It also might fix #136. But I didn't check.

**Comment by alehed** [comment]
If you want I can also put the return into the else case.
Is there any special squishing, rebasing I have to do?

**Comment by alehed** [comment]
Ready for review

**Comment by ridiculousfish** [comment]
Merged as 32d54e37f79447cab508e5ae21ae6c9b805408bd. Thanks!!

**Pull request closed without merging**
