### PR TITLE
Force completions to call npm command, not aliases

### LINKED ISSUE #3158: Fish completions, function with same name
I'm having a hard time with completions and a function I have created. 

```
function npm -d "node package manager"
  __nvm_run "npm" $argv
end
```

So this function basically calls `__nvm_run` checks if nvm has already sourced node, if not sources it and then runs npm, if node is already sourced then it just runs npm.

That function creates this issue https://github.com/fish-shell/fish-shell/issues/3152

If I change the function to this:

```
function npm -d "node package manager" -c npm -w npm
   echo "This won't run"
  __nvm_run "npm" $argv
end
```

The completions works fine, but the function it's not called anymore.

any help?

### PR DESCRIPTION
**Pull request by FabioAntunes**
Fixes #3158 and #3152

### CODE REVIEW

**Comment by faho** [comment]
Nice catch, I think I completely looked past that occurence at least twice.

I don't think the `type -q` call is right here, especially if you're calling `command npm` afterwards.

So instead I committed just the one-line change.

**Comment by FabioAntunes** [comment]
The reason why I did that, is if we have any npm alias, npm will be a valid command even if it's not available or installed if you press tab for completions you will get a message from the system.

screenshot from 2016-06-21 11 56 36

**Comment by faho** [comment]
@FabioAntunes: `type -q` doesn't help with that, at all. It checks commands, builtins _and functions_.

If you have a function that is called `npm`, `type -q npm` will be true even if you don't have a command.

What would work is `command -s npm >/dev/null`, with the obvious issue that it would simply complete nothing instead of printing an error. Though I don't quite get why you do this weird autoloading thing - are you manipulating $PATH in the `npm` wrapper? Why?

(The reason the function doesn't work for our completions is because of variable scoping, btw - the local variables aren't inherited by the function even though they're exported - I think there's an issue open about that).

**Comment by FabioAntunes** [comment]
Well it's a long history, but nvm is a bash tool that allows you to switch node versions on the fly, but if you want to use in on fish you have to source nvm on your `config.fish`, which increases the loading time by 1/2 seconds. This tool that I have created what it does it checks if there's any node already sourced, if so then call the commands if not it sources the nvm, then calls the command (node, npm or nvm).

On my pull request I'm not doing `type -q` I'm doing `type -P` which I believe it checks for commands and not alias?

Now a funny thing about these completions is that half of them are coming from npm and the other half are added manually when npm exists, when npm is not available all of the completions come from npm.fish. So using my pull request this is what I get, as you can see, in the next screenshot, I don't have npm available, after running `which npm`. Then I try to run the completions and although I don't have npm since I have the `type -P` it doesn't call the `command npm` to get npm completions,so there's no system error, and it uses completions available in the npm.fish

screenshot from 2016-06-21 13 27 48

Now if I just run npm it will source nvm and it will make node and npm avalaible (you can see by this line: `Now using node v4.4.0 (npm v3.9.5)`). If I try to run completions again you can check that half of them, more or less, are coming from npm directly they are the ones without description and the other half are the ones from the npm.fish

screenshot from 2016-06-21 13 28 17

**Comment by faho** [comment]
>On my pull request I'm not doing type -q I'm doing type -P which I believe it checks for commands and not alias?

Oh yeah. Sorry, missed that. That'll work.

>If I try to run completions again you can check that half of them, more or less, are coming from npm directly they are the ones without description and the other half are the ones from the npm.fish

Yes. The idea was that npm would know more than we can, so by using its tool the completions would improve even though there's no descriptions for the things it offers. That the descriptions are cleared is something in need of improvement in fish itself. More than that, it's not particularly understandable _which_ descriptions are cleared and which aren't. (See e.g. `info` in your screenshots - why does that still have a description while "install" loses it?)

Of course it might be possible to improve our own completions to the point that npm's don't help anymore, then we could drop them. That weird wrapper thing was part experiment to see how this kind of thing would be done.

Are there any particular cases where the `npm complete` thing still helps, or have we reached parity already?

>nvm is a bash tool that allows you to switch node versions on the fly

Ah, so nvm does that weird stuff. I'd have designed it quite differently, TBH.

**Comment by FabioAntunes** [comment]
First of all I'm taking my first steps in fish scripting so I can't make 100% accurate opinions, with that being said, forgive me if I say something that doesn't make sense.

> Are there any particular cases where the npm complete thing still helps, or have we reached parity already?
I don't know if `npm.fish` already has all the completions, but one reason to keep `npm complete` would be that any API changes would be reflected automatically


> Yes. The idea was that npm would know more than we can, so by using its tool the completions would improve even though there's no descriptions for the things it offers. That the descriptions are cleared is something in need of improvement in fish itself. More than that, it's not particularly understandable which descriptions are cleared and which aren't. (See e.g. info in your screenshots - why does that still have a description while "install" loses it?)
I don't mind having a look at this, and find why the descriptions are cleared

> Of course it might be possible to improve our own completions to the point that npm's don't help anymore, then we could drop them. That weird wrapper thing was part experiment to see how this kind of thing would be done
To be honest I think it was a great idea, it allows to keep completions more up to date.

> Ah, so nvm does that weird stuff. I'd have designed it quite differently, TBH.
There are some plugins that are version managers purely on fish https://github.com/fisherman/fnm https://github.com/fisherman/verman

**Comment by faho** [comment]
>I don't mind having a look at this, and find why the descriptions are cleared

It seems like this would be in src/complete.cpp and src/wildcard.cpp.

One more question:

I've had another look at the completions, and there's one more time we call `command npm`:

```fish
# list available npm scripts and their parial content
function __fish_npm_run
  command npm run | string match -r -v '^[^ ]|^$' | string trim | while read -l name
    set -l trim 20
    read -l value
    echo "$value" | cut -c1-$trim | read -l value
    printf "%s\t%s\n" $name $value
  end
end
```

We have two options here:

- Remove the `command` and just call `npm`, whatever that may be.

- Check `command -s` and don't run the function if we don't have a command.

The latter would of course mean you don't get these completions if you haven't run nvm yet. The former _should_ work here, even with your wrapper function (since we don't have the variable scoping issue we have above). Am I missing anything?

Also thank you for your patience with my decidedly non-webscale brain (I'm the ultimate javascript hipster - I've written thousands of lines of it, but never in a web-context).

**Comment by FabioAntunes** [comment]
> I've had another look at the completions, and there's one more time we call command npm:
```
# list available npm scripts and their parial content
function __fish_npm_run
  command npm run | string match -r -v '^[^ ]|^$' | string trim | while read -l name
    set -l trim 20
    read -l value
    echo "$value" | cut -c1-$trim | read -l value
    printf "%s\t%s\n" $name $value
  end
end
```

Nice catch this one would be even more harder to spot, it only shows when we try to run completions on `npm run` because it tries to use npm to read a local `package.json` file for the scripts that are inside. So if I try to run completions on `npm run` I will get this:
```
The program 'npm' is currently not installed. You can install it by typing:
sudo apt-get install npm
/usr/share/fish/completions/npm.fish (line 2): command npm run | string match -r -v '^[^ ]|^$' | string trim | while read -l name
                                                       ^
in function “__fish_npm_run”
	called on standard input

in command substitution
	called on standard input

```


> We have two options here:
> 
>  - Remove the `command` and just call `npm`, whatever that may be.
> 
>  - Check `command -s` and don't run the function if we don't have a command.

I would go for the second one, that would fix the error message without breaking existing logic and any new plugin/function that creates a npm alias would work. 

> Also thank you for your patience with my decidedly non-webscale brain (I'm the ultimate javascript hipster - I've written thousands of lines of it, but never in a web-context).

It's me that have to thank you for wasting some of your time, trying to solve something that isn't that much important

**Pull request closed without merging**
