### PR TITLE
Emerge completions

### PR DESCRIPTION
**Pull request by JelteF**
Add some more advanced completions for the `emerge` command.

### CODE REVIEW

**Comment by zanchey** [comment]
Merged with rebase as 789a542..f920be5.

I must admit those completions look very slow; lots of forking with long pipelines. I don't use Gentoo so I can't comment but they might be a good target for optimisation.

**Comment by JelteF** [comment]
They weren't much slower than before, but they are quite slow in comparison to others. You can really feel it thinking when pressing tab. I think it takes close to a second. What takes longest I think is gathering all possible packages, but I'm not sure. I might look into optimizing it a bit in the future.

**Comment by zanchey** [comment]
The other option would be copying the behaviour of `__fish_print_packages` and using a cache.

**Comment by JelteF** [comment]
Hmm, there's an application that sort of does that already to make searching through the packages faster. It might be possible to use it for this. It is called `eix` and as far as I know most Gentoo guys have it installed. It might be good to use that when available and use the current as a fallback.

**Pull request closed without merging**
