### PR TITLE
don't print internal token in error message

### LINKED ISSUE #3187: exec "$foo": prints fish internal unicode private use character U+FDD3
### Reproduction Steps:

Where `test` can be any name that is not a set variable:
1. Type `> exec "$test"` ( or just `> "$test"`) 
2. (or just type a double quoted dollar sign and hit enter: `> "$"`)
3. Hit enter and observe the error message.
### Observed behavior:

image
Also, same thing happens to `$argv` on the command not found handler. Github isn't rendering the character below but it is between the quotes:

```
> "$"
fish: Unknown command ''
```
### Additional information:

Doesn't happen if one uses single quotes. Bug is in `master`, 2.3.0, 2.2.0.

### PR DESCRIPTION
**Pull request by krader1961**
Attempting to execute something like `exec "$test"` results in a fish internal
token (a Unicode private use char) being printed in the resulting error
message. That's obviously not desirable.

Fixes #3187

### CODE REVIEW

**Comment by llwu** [comment]
I also find the rather unfortunate property that
> "$"
doesn't go into that if branch for me at all (because of the && cmd[1] != L'\0'). It just expands to a single VARIABLE_EXPAND_SINGLE. I'm not sure why that conditional is there, so I don't know what to do about it.

**Comment by krader1961** [comment]
@llwu, Good point. It's not clear to me, either, why that condition is present. If I remove it nothing bad happens. It does cause the following behavior:

```
$ "$"
Variables may not be used as commands. In fish, please define a function or use 'eval "$"'.
```

Obviously the recommendation doesn't make any sense but acting on it simply produces a more meaningful error:

```
$ eval "$"
Expected a variable name after this $.
fish: eval "$"
            ^
```

I should probably just make additional modifications to the block I've already changed in order to report the "Expected a variable name after this $" message for that case.

**Comment by floam** [comment]
This PR isn't affecting the bug for me.

**Comment by krader1961** [comment]
There are other cases this PR doesn't fix which occurred to me earlier today. For example, `"abc$def$"`. I'm working on generalizing the code to handle all of these cases.

**Comment by krader1961** [comment]
@floam, Please take another look.

**Comment by floam** [comment]
It seems to be working rather nicely compared to before. I'm playing with it to see if I can find anything worse than `exec "$__f"ish_'bin'_"dir"/fish`

**Comment by krader1961** [comment]
Closed with merge of commit 512506f0f986cadfa18cefa6dbc10ccab4fd0541.

**Pull request closed without merging**
