### PR TITLE
fix handling of line continuation in keywords

### LINKED ISSUE #2897: Line continuation not working properly?
I'm designing a shell scripting language, so this is nitpicking. I just compare the behavior of fish to bash's.

fish, version 2.2.0-722-g411d573

Before every test, run `set -geu PATH` and `set -geu fish_user_paths` in order to use built-in functions only. (**Update: oh, when PATH is empty, it defaults to "/usr/bin:/bin"**)

Please save every test into separate files and manually source them.

*   Test 1:

    ```fish
    rand\
    om
    ```

    prints a random number

*   Test 2:

    ```fish
    buil\
    tin random
    ```

    prints nothing

*   Test 3:

    ```fish
    true
    a\
    nd echo ok
    ```

    prints nothing

*   Test 4:

    ```fish
    if true; e\
    nd
    ```

    Error: `Missing end to balance this if statement`

*   Test 5:

    ```fish
    i\
    f true; echo ok; end
    ```

    Error: `'end' outside of a block`

*   Test 6:

    ```fish
    if\
     true; end
    ```

    Error: `'end' outside of a block`

*   Test 7:

    ```fish
    if true; end\
    ;
    ```

    Error: `Missing end to balance this if statement`

Some other keywords are also tested, and it seems that only `begin/if/while/switch/function/end` (well, maybe all buitins) do not support line continuation.

### PR DESCRIPTION
**Pull request by jakwings**
The current behavior is more consistent with line continuation outside
keywords.

Fixes #2897

### CODE REVIEW

**Comment by jakwings** [comment]
Ouch, there is still a bug:

```fish
'i\
f` true; echo ok; end
```

This should fails because there is no line continuation is single quoted strings.

**Comment by jakwings** [comment]
I don't think anyone want to use a quoted string as a keyword. For example: `"if"` `'if'` `i"f"`.

**Comment by jakwings** [comment]
Another bug not solved: when the token does not pass the keyword check, it fails silently.

**Comment by jakwings** [comment]
My expectation that quoted strings are never keywords or names of builtins, is rejected by #1398.  However, I don't know why `i"if"` is accepted, but `i\f` not?

**Comment by faho** [comment]
I think it's fair to say that this is too late to make it into the next release (which might be as early as ʇɥbıuoʇ).

**Comment by jakwings** [comment]
@ridiculousfish 

> Nice work. I implemented quoted keywords in response to #1398 and I think it's the right thing to do. Quoting should not be a "back door" for running an external command.

Ok, I've pushed another patch to allow escape sequence in keyword names, although I still miss the tradition[1] from bash.

[1]: escaping or quoting can invalidate special chars

**Comment by krader1961** [comment]
Ugh! This is going to require more changes to `fish_indent` for it to produce canonical output. But since this change addresses the problems documented in issue #2897 and is consistent with the earlier change made by @ridiculousfish in issue #1398 I'm going to merge it. I'm not entirely comfortable with the `is_keyword_char()` name since backslashes aren't really valid keyword chars but I can't think of a cleaner way to express what your change is doing within the context of the existing code.

Also, a big thank you, @jakwings, for the unit tests. Far too few changes to this project include relevant tests to help avoid regressions.

**Comment by krader1961** [comment]
Squash merged as commit 2d5eaed745892a5e035caf7ccc02d27044f344fb

**Comment by ridiculousfish** [comment]
Is there a reason this included uppercase characters and numbers? Those aren't in keywords, so it's a minor optimization to omit them (we can avoid expanding the token if we find a capital letter).

**Comment by jakwings** [comment]
Because there could be escape sequences, like `\U00000066` ("f"). And I forgot to modify the code comment.

**Comment by ridiculousfish** [comment]
Ok, makes sense

**Pull request closed without merging**
