### PR TITLE
Add favicon for web config

### PR DESCRIPTION
**Pull request by NathanJang**
Addresses #1043 and #1936. Adds a simple favicon to suppress 403 messages from before. It's a white Courier `f` on the web config's background colour. Perhaps someone else can design a prettier icon.

### CODE REVIEW

**Comment by NathanJang** [comment]
[Here](https://gist.github.com/NathanJang/9bd25522fd1d5dc554dc) is the psd for reference.

**Comment by ridiculousfish** [comment]
Thanks. I crushed it down from ~18KB to 192 bytes, hehe.

**Comment by ridiculousfish** [comment]
Merged as 4b8febd44e0e6949acf2ca3bc7efba38ad50edae

**Comment by NathanJang** [comment]
:+1:

**Comment by frederickjh** [comment]
As a web developer I wanted to add that the file added in the commit above will not fix this for all web browsers as the name is favicon.png Some browser insist on looking for favicon.ico. Other will look for this if a link is not given in the html to point to the favicon.png. The best solution are to a) include only a favicon.ico or b) include both the favicon.ico and favicon.png The first link below explains a good way to include both and the second link explains why you should.

More information:  [What is currently the best way to get a favicon to display in all browsers that support Favicons?](http://stackoverflow.com/a/37321/6079319)  and [favicon.png vs favicon.ico - why should I use PNG instead of ICO?](http://stackoverflow.com/a/1344147/6079319)

**Comment by frederickjh** [comment]
Currently viewing fish_config with fish version 2.2.0 on Ubuntu 14.04.4 it spews this message:

```
::ffff:127.0.0.1 - - [18/Mar/2016 22:31:26] code 403, message Forbidden, path /favicon.ico
```
over and over again. As you see Google Chrome is looking for **favicon.ico** which I presume is because the **index.html** does not have a link for the favicon.ico nor favicon.png in the `<head>` section.

**Comment by floam** [comment]
how about a new icon for everything that needs one? the OS X app, bash.exe, etc? The problem with the current logo is it does not resize well over those sizes.

**Pull request closed without merging**
