### PR TITLE
Fire fish_postexec event on tokenization error

### PR DESCRIPTION
**Pull request by PerBothner**
Fixes issue #6816 "shell integration with tokenization error"

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

CHANGELOG.md note could be:
A tokenization error (such as command-line containing just `)`) now raises the `fish_postexec` event, as documented.

### CODE REVIEW

**Comment by faho** [comment]
So I've been thinking about this, and I think it would be nicer to introduce a *new* event if there's an error.

The reason being that it's not entirely clear that postexec handlers would be useful if nothing was actually executed.

Your function would then just register for both events.

**Comment by PerBothner** [comment]
A distinct signal for error would also work. Wold it be only for tokenization errors (corresponding to my patch), or also other kinds of errors (which would require other changes)?

**Comment by faho** [comment]
>A distinct signal for error would also work. Wold it be only for tokenization errors (corresponding to my patch), or also other kinds of errors (which would require other changes)?

I would imagine all kinds of errors that cause us not to execute a command - I think that might be

- tokenization (i.e. the syntax is wrong)
- empty variable-as-command - e.g. `$PAGER file` if $PAGER is unset
- empty globs - `ls *.nonexistent`

But I think for now just the tokenization will suffice.

**Comment by ridiculousfish** [comment]
In addition to faho's suggestions, please move the code to after where `reader_shell_test` is invoked. [Here](https://github.com/fish-shell/fish-shell/blob/d278ff4e45879d8570d7632914595622598fe0d3/src/reader.cpp#L2932) is where fish acts on the result of `reader_shell_test`.

**Comment by PerBothner** [comment]
Ok - I moved the `event_fire_generic` call as suggested (which I also initially considered) and renamed it to `fish_posterror`.

However, this is still one (less serious) problem: The error message is printed while we're still in input mode, so it is printed with the wrong style.  Fixing this using heuristics is no doubt possible, but it would be less complex/fragile to have an explicit `fish_preerror` event.  However, I'm not sure where it should go, given that the comment before `report_tokenizer_error` says "This is a hack".

**Pull request merged**
