### PR TITLE
Implemented 'replace-char' and bind for vim mode

### PR DESCRIPTION
**Pull request by erthalion**
I've implemented 'replace-char' command for 'r' binding in vim mode. I hope it will be correct enough.

### CODE REVIEW

**Comment by tannhuber** [comment]
@kballard: I've tested @erthalion's PR successfully for a long time. Is there a chance to merge?

I apologize for being impatient. But the lack of replace confuses me almost every day. :-)

**Comment by kballard** [comment]
Offhand, the current version looks ok. But I actually haven't relatively little familiarity with the insert code, and I'd feel more comfortable if someone else (such as @ridiculousfish) chimed in.

**Comment by ridiculousfish** [comment]
I am sorry that I let this slide for so long. Let's tackle after 2.2.

**Comment by tannhuber** [comment]
Great!

**Comment by ridiculousfish** [comment]
Revisiting this. kballard's [post](https://github.com/fish-shell/fish-shell/pull/1595#issuecomment-56876640) about implementing this using key bindings is very compelling. An example benefit is that the `fish_mode_prompt` can be trivially taught about replace mode - something that would be harder if we baked it into the core read loop.

Still the cursor positioning is a problem, and so is the behavior of `self-insert`. For example, typing r followed by right arrow will attempt to self-insert the escape sequence for right arrow, which ends very badly.

I propose fixing this by splitting the input queue into a "command list" and a "character list." Most functions will prefer to dequeue from the command list first, and then the character list if the command list is empty. But crucially, self-insert will only dequeue from the character list. This lets us implement replace as:

    bind -m replace-one r force-repaint
    bind -M replace-one -m default '' delete-char self-insert backward-char force-repaint

which seems very elegant.

**Comment by ridiculousfish** [comment]
Instead of that, I made `R_SELF_INSERT` simply dequeue until it finds a real character, then put all of the readline functions back. This avoids messing with the input queue, for the time being. Things may get stickier with capital-R replace.

**Comment by ridiculousfish** [comment]
lowercase r-replace went in as 2109af0987ce6daab95daa053199ab4f7cafb970. Speak up if it doesn't work and thanks to everyone in this thread.

**Comment by tannhuber** [comment]
Awesome! Thank you very very much!

**Comment by martinklepsch** [comment]
I just installed from master via `brew unlink fish; brew install --HEAD fish` but pressing `r` does not let me replace the character under the cursor. Instead it seems to be ignored and whatever character is pressed  next is evaluated. E.g. `re` moves cursor to end of current word and stays in normal mode.

```
-> fish -v
fish, version 2.2.0-127-g299a383
```
https://github.com/fish-shell/fish-shell/commit/299a383d98f67fdd8ec5ce91f72b5d560ef4441e the latest rev.

**Pull request closed without merging**
