### PR TITLE
Add sysctl completions

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by faho** [comment]
Wow, I did not see this, and opened PR #2214 instead with my own attempt.

My idea was to just use the variable's value as description, so I just did `sysctl -a | tr '=' '\t'`

**Comment by pickfire** [comment]
I hope that the completions can be optimized for speed as some pasting took a long time.

**Comment by faho** [comment]
Since #2214 is merged, this is probably obsolete.

**Comment by ridiculousfish** [comment]
Yes, thanks

**Pull request closed without merging**
