### PR TITLE
add support for ANSI "bright" colors

### PR DESCRIPTION
**Pull request by krader1961**
This adds support for the ANSI x3.64 "bright" colors in the basic sixteen
color palette. This is especially useful when trying to use the base colors
as a background color. The "bright" variants tend to be more useful as
background colors compared to the non-bright variants.

This also fixes a bug in so far as palette number 7 is actually grey and
not white whereas palette number 15 is white. At least on the terminal
emulators on which I've tested this change (Ubuntu xterm & uxterm, Mac
OS X Terminal & iTerm2).

Resolves issue #1464.

### CODE REVIEW

**Comment by jaspernbrouwer** [comment]
I don't believe "normal" at index 7 is a bug. A normal color is opposed by a bright color, which makes sense IMHO if you take index 7 ("gray" or "normal white") as normal text color and index 15 ("white" or "bright white") as bold or emphasized text.

As far as I know all terminals use index 7 as normal text color.

**Comment by jaspernbrouwer** [comment]
Other than that, :+1: for adding the full 16 palette!

**Comment by krader1961** [comment]
> I don't believe "normal" at index 7 is a bug.

Then should it's associated RGB value be changed? Because at the moment it's a bit schizophrenic :-)

**Comment by krader1961** [comment]
FYI, Closing this since, as you can see in the history above, I managed to totally bollox this branch. Somehow the ID of the original change changed when I pushed it. I really need to learn more about effectively using git (we use Perforce at day job).

**Pull request closed without merging**
