### PR TITLE
added mvn.fish - basic version without improvements

### PR DESCRIPTION
**Pull request by jschneider**
As mentioned in #2352

### CODE REVIEW

**Comment by jschneider** [comment]
@faho suggested:

It probably only takes one "command" - if that's the case, what I always do is put them into a local variable (called "commands", unsurprisingly), and then do complete -c $COMMAND -n "not __fish_seen_subcommand_from $commands" -a "$SOMECOMMAND" -d "$SOMEDESCRIPTION" - see e.g. the timedatectl completions

You can cut on some sed invocations by using "-e EXPRESSION" to add multiple expressions to a single sed

complete's "-o" is for old-style single-dash options (like find's "-name") that can't be grouped (unlike, say ls -lah) - does maven really use that?

For all plugins at the bottom - are those always all installed? Is there a way to generate that list? Or wouldn't it be nice to add descriptions (either via the "-d" option, or by feeding the "-a" option something like "option\tdescription\noption\tdescription" with \t being a tab character and \n being a newline)

**Comment by faho** [comment]
>Some of the plugins come by default, most are automatically downloaded if necessary. Automatically generation would be great, but that seems to be quite complicated (for me).

Then it'd probably be nice to get some descriptions at least for the not-totally obscure ones.

**Comment by jschneider** [comment]
I am working on generating an improved documentation.

**Comment by jschneider** [comment]
Okay, I am done so far.
Any feedback on the new list?

**Comment by faho** [comment]
That's certainly a list. The main issue here is that we currently don't check which of these plugins is installed, so every one of them will be mentioned regardless. If we'd need to be parsing xml or start maven, I'd be okay with just not checking for now, but if there's another way it'd be nice.

**Comment by jschneider** [comment]
There is no such concept as "installed plugins" in Maven.
All plugins are available on all (most) systems all the time. They are automatically downloaded when called for the first time.

The plugins in the list are the default plugins provided by Maven itself, the plugins from MojoHaus which is a set of default plugins used by a lot of people and two or three plugins I have added myself, that are quite common (e.g. android).

**Comment by faho** [comment]
In that case, mind squashing this up (make a branch from master, check it out and do `git merge --squash`)? I could also do it but in that case the commit would be attributed to me.

We'll leave the theoretically impossible (parsing xml with regex) for later.

**Comment by jschneider** [comment]
Didn't exactly understand what you expected.
Therefore I squashed the commits into one and pushed it to the feature branch.
But also merged the feature branch with --squash to my master branch. Hope one of these things is what you expected ;-)

**Comment by faho** [comment]
> Therefore I squashed the commits into one and pushed it to the feature branch.

Yeah, that seems to work. I'm a bit overly cautious because I'm sometimes not completely sure what git or github will do with a particular operation.

Merged with rebase as 054fb228540efc9d502d8a217f6189fe049de61b. Danke sehr!

**Pull request closed without merging**
