### PR TITLE
Automatically add include paths for ncurses on Cygwin

### PR DESCRIPTION
**Pull request by Philipp15b**
See #1453. I'm no expert on build systems, so this should be checked well.

### CODE REVIEW

**Comment by zanchey** [comment]
I'm trying to reproduce the problem that this was introduced for, and I'm struggling to get my head around the ncurses situation on Cygwin (which seems to be different on x86 and x86_64?!). `libncurses-devel` on my x86_64 system certainly contains the right headers/libraries in /usr/include & /usr/lib. fish builds and runs find with the patch in this PR reverted. @Philipp15b and @xfix, do you guys run Cygwin in 32-bit or 64-bit mode?

**Comment by Philipp15b** [comment]
At the time of the pull request I was running Cygwin in 32-bit mode, but I'm now using the cygwin `fish` package with 64-bit Cygwin. 

I tried to build d018ef39e1abf63dfde80e07f4160d88f76f5e4f but `make` fails with this error:
> g++: error: unrecognized command line option ‘-rdynamic’

**Comment by zanchey** [comment]
Yes, I have a patch for that that I haven't committed yet because I haven't had a chance to test on OS X.

Try with the following:

```patch
diff --git a/configure.ac b/configure.ac
index 49ff391..b8119fe 100644
--- a/configure.ac
+++ b/configure.ac
@@ -210,9 +210,18 @@ CXXFLAGS="$CXXFLAGS -Wall -Wno-sign-compare"
 # This is needed in order to get the really cool backtraces on Linux
 #
 
-if test `uname` != "Darwin"; then
-   LDFLAGS_FISH="$LDFLAGS_FISH -rdynamic"
-fi
+AC_MSG_CHECKING([for -rdynamic linker flag])
+prev_LDFLAGS="$LDFLAGS"
+LDFLAGS="$LDFLAGS -rdynamic"
+AC_LINK_IFELSE([AC_LANG_PROGRAM([[]],[[]])],
+               [
+                AC_MSG_RESULT([yes])
+                LDFLAGS_FISH="$LDFLAGS_FISH -rdynamic"
+               ], [
+                AC_MSG_RESULT([no])
+                LDFLAGS_FISH="$LDFLAGS_FISH"
+               ])
+LDFLAGS="$prev_LDFLAGS"
 
 #
 # On Cygwin, we need to add some flags for ncurses.
```

**Comment by zanchey** [comment]
I've had another look, and this commit is basically a noop on contemporary Cygwin - `libncurses10` is for ABI compatibility only, and `libncursesw10` provides all the expected links. Backed out as 6ec58a2 - I'm trying to minimise the differences between platforms and I don't think this is needed any more. Thanks anyway!

**Pull request closed without merging**
