### PR TITLE
Fix a capitalization error and add a link

### PR DESCRIPTION
**Pull request by jacobherrington**
## Description

I just submitted a PR to fix a few issues in CONTRIBUTING.MD, so I took
a few minutes too look over README.md as well. This is the only room 
for improvement I noticed.

~~Fixes issue #~~

## TODOs:

~~- [ ] Changes to fish usage are reflected in user documentation/manpages.~~
~~- [ ] Tests have been added for regressions fixed~~
~~- [ ] User-visible changes noted in CHANGELOG.md~~

### CODE REVIEW

**Comment by mqudsi** [comment]
Thanks for this, but the logic in what text is hyperlinked and what text isn't doesn't make sense in the changed source. In particular, "this" would to either be dropped or included in the hyperlink.

**Comment by jacobherrington** [comment]
@mqudsi Thanks for your opinion. I was trying to make a low-touch change, but I agree with you.

**Comment by mqudsi** [comment]
Thanks for the fast turn around, @jacobherrington.

**Comment by zanchey** [comment]
Merged with squash/rebase as 0aedd47a..35c01bcb.

Thanks!

**Pull request closed without merging**
