### PR TITLE
add database completion for pacman

### PR DESCRIPTION
**Pull request by f1u77y**

### CODE REVIEW

**Comment by faho** [comment]
Nice, can't believe I missed this.

There's [a hack I used](https://github.com/f1u77y/fish-shell/blob/35f453b12f31131d3f2426cc053f354e0c6c5a69/share/completions/pacman.fish#L27-L29) to get fish to offer the options instead of files (since that's what it falls back on if no completion matches). Mind adding that for -D as well, since it doesn't do anything without either --asexplicit or --asdepends?

**Comment by f1u77y** [comment]
ok, understood. but does it mean there's no way to do that without such a hack? i think that not only pacman but much more programs need that

**Comment by faho** [comment]
Squashed merge as 1a3bcf63bc46575adb33bd0cdeacc98b8341ca68. Thanks for this!

**Comment by faho** [comment]
>but does it mean there's no way to do that without such a hack?

Currently not. We're trying to rework the completion system with #478.

>i think that not only pacman but much more programs need that

Surprisingly few, actually. Pacman essentially uses "options" as "subcommands". "-S" specifies an operation, a command. For other programs, this would look more like "apt install $PACKAGE". This is a rather uncommon usage pattern. (Theoretically `pacman $PACKAGES -S` works as well, but there's no way for us to tell what we should complete before the command has been given)

**Pull request closed without merging**
