### PR TITLE
clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**
## Description

Talk about your changes here.

This just runs the code through clang-tidy to clean it up.

### CODE REVIEW

**Comment by zanchey** [comment]
`readability-else-after-return` and `modernize-use-auto` actually reduce readability in my view, but I don't do much in this area of the code.

**Comment by neheb** [comment]
@krobellus you're overthinking it. This is supported natively by CMake:

```
set(CMAKE_CXX_CLANG_TIDY clang-tidy -fix -checks=)
```

**Comment by neheb** [comment]
Ran all of the commits through git clang-tidy.

**Comment by ridiculousfish** [comment]
I ended up taking this except for `modernize-use-auto` and `readability-else-after-return` where I agree with zanchey. Thank you and thanks for breaking these into separate commits as well. Merged as 1102b83b2d5bdf7018705c8a882edf6d3f133149

**Pull request closed without merging**
