### PR TITLE
Various hg completion updates

### LINKED ISSUE #2517: mercurial command shortforms not supported by completions
the out of the box completions for mercurial does not support partial commands. In mercurial, the following are all the same (anything more than 3 characters of the command):
hg clo, hg clon, hg clone

fish requires one to first tab and wait for the command to be expanded before completing the parameters which shouldn't be required.

### PR DESCRIPTION
**Pull request by danielmatz**
I revisited the hg completions and made a number of fixes and improvements.

* Fixed #2517.  The arguments and switches now complete for all abbreviated versions of command names.  The only limitation is that user created aliases are not supported.  Specifically, they are neither properly completed nor do they shadow the completions of other commands.  If a user creates an alias for `hg stat`,  he'll still get completions for `hg status` no matter what `hg stat` actually does.
* Fixed a minor issue where the completed aliases for remote repository paths had a trailing space character.
* Improved detection of when a subcommand was needing to be completed.
* Improved detection of the current subcommand for completing its options.
* Replaced uses of `cut`, etc., with the new `string` builtin.
* Several changes to reflect the latest version of Mercurial.  Added completions for a few new things, and stopped completing a few deprecated things.
* Added proper handling for the `-R|--repository` and `--cwd` global switches, and now all completions grab information from the right repository and path.

If anyone has any feedback, I'd love to hear it.

Using the new `string` builtin was generally really nice.  One observation...  I used to pipe multi-line output to `cut` to split it and select one of the resulting tokens for each line.  One liner, pretty simple.  With the new `string split`, I had to use a for loop to split each line individually and then grab the token I wanted.  Is there a better way to do that?

### CODE REVIEW

**Comment by faho** [comment]
This looks like some fine work overall! Since you've used string a bit, could you offer some criticism? Either open dedicated issues or join https://gitter.im/fish-shell/fish-shell or our IRC channel (which I'm still trying to get used to).

I've noticed a couple of things myself, including the lack of a "-f" option (like `cut -f`) for `string split`, which together with our list-handling makes it a bit awkward.

I'll try to do a more thorough review over the next few days.

**Comment by danielmatz** [comment]
An additional thought on the new `string` builtin...  There is a similar issue to the one we've both noticed with `string split` when using `string match`.  Often I'd only want to print one of the groups in the regular expression, but there's no option to select what to print.  It's all or nothing.  So again I had to use a for loop over the lines, run `string match` on each line, and then echo the right array element.

**Comment by faho** [comment]
> Often I'd only want to print one of the groups in the regular expression, but there's no option to select what to print

What you can do in that case is use `string replace` instead - i.e. `string replace -r ' (.*) ' '$1'`.

**Comment by danielmatz** [comment]
Well, yes, but I'd have to make a pattern that matches the entire line, otherwise it seems to only replace the substring that matches.

That is:

```fish
$ string replace -r -- "(-R|--repository) +([^ ]+)" '$2' "hg -R /path/to/repo status"
hg /path/to/repo status
$ string replace -r -- ".* (-R|--repository) +([^ ]+) .*" '$2' "hg -R /path/to/repo status"
/path/to/repo
```

Which I guess is OK.  But another downside is that now it just passes through any lines that don't match the pattern at all.

```fish
$ string replace -r -- ".* (-R|--repository) +([^ ]+) .*" '$2' "foo bar baz"
foo bar bar
```

Which makes sense for `string replace`, but makes things awkward if I'm really just trying to match some substrings and extract them.

**Comment by faho** [comment]
>I guess I just need to do a string match first to narrow down the lines, and then put those through string replace.

Still a tad long, though. Personally, I'd like to have `string` as a simple solution for the most common use-cases of sed, grep and cut (and maybe some others - `wc -m` is `string length`). Especially given that sed is kind of awkward to use with shell variables - since you can't guarantee that they won't contain the separator char in most cases.

I'll try to get to this today.

**Comment by faho** [comment]
Looks good to me. Squashed-merge as 3b53abe. Nice work!

**Pull request closed without merging**
