### PR TITLE
Handle multiple slashes in wildcard string

### LINKED ISSUE #3185: Tab completion of a//b crashes
Tab completion of a path containing consecutive `/` characters causes fish to crash.

### Reproduction Steps:

`$ a//b<TAB>`

### Expected behavior:

Fish tries to complete the path as if it were spelled `a/b`

### Observed behavior:

```
fish: src/wildcard.cpp:986: void wildcard_expander_t::expand_literal_intermediate_segment_with_fuzz(const wcstring&, DIR*, const wcstring&, const wchar_t*): Assertion `c->completion.substr(segment_start, segment_len) == wc_segment' failed.
fish: 'fish' terminated by signal SIGABRT (Abort)
```

### Additional information:

-

---
Fish version: `fish, version 2.3.0`

Operating system: Arch Linux, fish installed from the distribution package

Terminal or terminal emulator: `tmux` running inside `urxvt`

### PR DESCRIPTION
**Pull request by llwu**
We'd like to assume that directories are delimited by single slashes,
which we did, at src/wildcard.cpp:753:

```
const size_t segment_start = original_wildcard_len + this->original_base.size() -
    wc_remainder_len - wc_segment.length() -
    1;  // -1 for the slash after our segment
```

This commit backs up that assumption by consolidating consecutive
slashes in the wildcard before creating the expander.

Fixes #3185

### CODE REVIEW

**Comment by llwu** [comment]
* I considered computing segment_start as simply base_dir.length(). However, this wouldn't always work, since base_dir would be deduplicated of slashes and c->completion would not. Thus 'a//b//c' would still fail.

Making sure c->completion contains no consecutive slashes would be make the aforementioned computation easier (hopefully) and make the output more visually appealing (no more a//b//c -> "a//b/charlie/delta (description)"). Even better if there's already a function to do this!

This is something I could look into when I get back to my machine tonight.

**Comment by ridiculousfish** [comment]
We're supposed to be handling this in `wildcard_expander_t::expand`, I need to check why it's not working.

**Comment by llwu** [comment]
It is handled for the recursive step (i.e. it skips empty segments and recurses with one slash). However, there is a hack when generating the completions in 558:try_add_completion_result (at 581 uses the ORIGINAL wildcard, which was not processed at all before)

**Comment by llwu** [comment]
Basically, the original wildcard being const means the options are

* Pass a preprocessed string to the constructor (I actually think this is pretty clean)
* Cope with multiple slashes (ugly but hackable around)
* Remove dependence on original wildcard (this would require refactoring and would probably not be a huge win)

**Comment by krader1961** [comment]
> this would require more refactoring and would probably not be a huge win, hence why I just did the processing at the start

Note that a huge amount of the fish code contains functions that are too long or complex. Run `make lint-all` to get an idea of the magnitude of the problem. Refactoring can be a huge win by virtue of simply making the code easier to understand. I'm all for simple changes that solve the immediate problem but sometimes the better choice is the one that involves more work.

**Comment by llwu** [comment]
I agree, this file has a lot of occurrences of the string "Hack" which should probably be looked into. Although in any case, I've also designed this particular commit to hold up well in the long term, so I hope it's a reasonable starting point.

**Comment by floam** [comment]
I edited this PR for you - the title should be some kind of subject line or descriptive thing - Fixes #nnnn can go anywhere in the body and it will work (work to let people find that bug, and also for the merge of this PR to cause the automatic resolution/closing of that bug.)

I think i'll go ahead and merge in the PR template.

**Comment by ridiculousfish** [comment]
I decided to address the tangled logic more directly, so this isn't needed any more. Thanks for the contribution nevertheless.

**Pull request closed without merging**
