### PR TITLE
Update cargo completion

### PR DESCRIPTION
**Pull request by xosdy**
## Description

Fix completion in latest cargo.

### CODE REVIEW

**Comment by faho** [comment]
Do you have an example for the new output?

Mine looks like:

```literal
Installed Commands:
    bench
    build
    check
    clean
    doc
    fetch
```

with cargo 1.28.0.

**Comment by xosdy** [comment]
New output will print:

```
Installed Commands:
    bench                Execute all benchmarks of a local package
    build                Compile a local package and all of its dependencies
    check                Check a local package and all of its dependencies for errors
    clean                Remove artifacts that cargo has generated in the past
    doc                  Build a package's documentation
    fetch                Fetch dependencies of a package from the network
    fix                  Automatically fix lint warnings reported by rustc
    generate-lockfile    Generate the lockfile for a project
    git-checkout         Checkout a copy of a Git repository
```

with cargo 1.29.0-nightly (0ec7281b9 2018-08-20).

**Comment by faho** [comment]
Hah, that's actually much more useful to us, because we can turn the other stuff into the description, by turning the whitespace inbetween into a single tab character.

Something like

```fish
cargo --list | tail -n +2 | string replace -r '\s*(\S+)\s*(\S.*)?$' '$1\t$2'
```

should do.

**Comment by faho** [comment]
Very nice, thank you!

**Pull request merged**
