### PR TITLE
A grab-bag of documentation additions

### PR DESCRIPTION
**Pull request by faho**
I've added a few notes here and there to the docs.

The reason for this PR is that I don't consider myself a great writer and would appreciate any criticism and wording suggestions.

6834f79 was recently discussed on fish-users - I'm not sure we should disown the IRC channel entirely, though.

### CODE REVIEW

**Comment by krader1961** [comment]
FWIW, monitoring a mailing list, GitHub, and one IM is all the load I'm willing to shoulder for something that doesn't pay my bills. I have no interest in monitoring  additional sources of questions and problem reports. So if we continue to support both IRC and gitter.im I'll stop monitoring the former and monitor the latter. Note that if we drop gitter.im I'll be happy to continue monitoring the IRC channel; I'm only going to monitor one of them.

**Comment by krader1961** [comment]
Also, monitoring stackoverflow and potentially stackexchange. Do we really need two IM mechanisms?

**Comment by faho** [comment]
Merged as 8081e9f..7c4f553 (man I love git). Thanks for the suggestions!

**Comment by ridiculousfish** [comment]
Thanks for doing these faho!

**Pull request closed without merging**
