### PR TITLE
Default install directory for repo install + log out/in

### PR DESCRIPTION
**Pull request by josephrocca**

### CODE REVIEW

**Comment by faho** [comment]
Sorry, no, the default is /usr/local.

**Comment by josephrocca** [comment]
Oh, strange. Ran the commands in the readme:
```
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install fish
```
on a fresh install of Ubuntu 18.04 and it went into `usr/bin`.

Should add the note about logging in and out in any case.

**Comment by faho** [comment]
Yes, that's because the *package* has it set to /usr/bin.

The default when building yourself, which is what the README is about, is /usr/local/bin.

Either way, no matter which way around we mention this someone will try to change it. So let's just keep it as it is.

**Comment by josephrocca** [comment]
Ah, so I probably disagree here then. I'd say most people building it themselves won't need to be told what `chsh` is. Most people will be using the packages. Optimising for friendliness to the average user is the way to go I think. I might be missing something though.

**Pull request closed without merging**
