### PR TITLE
make testing on local servers hermetic

### PR DESCRIPTION
**Pull request by krader1961**
I noticed while fixing issue #2702 that the fish program being tested
was sourcing config.fish files outside of the current build. This also
happens when Travis CI runs the tests but isn't an issue there because
of how Travis is configured to execute the tests. This change makes it
possible for an individual to run the tests on their local machine secure
in the knowledge that only the config.fish and related files from their
git repository will be used.

### CODE REVIEW

**Comment by krader1961** [comment]
The Travis failure is unrelated to this change. It's due to my previous change, already merged and included in this change, that affects the timing of the bind.expect tests. Despite @ridiculousfish's attempt to fix the timing that test is still flaky under Travis (but not my Mac OS X or Ubuntu servers).

**Comment by krader1961** [comment]
My grep-fu must have been weak that day as I missed two references to /usr/local/bin/fish. Fixed.

**Comment by zanchey** [comment]
Rather than this approach, perhaps it would be better to make it possible to test fish without using `make install` first. That would also close #469, and I think it can be done pretty easily.

**Comment by krader1961** [comment]
@zanchey write "... I think it can be done pretty easily.". I'd love to see that. When I started working on this that was my intent. I thought one or two symlinks in the source tree would be sufficient. After spending at least four hours on that approach to solving the problem I gave up. This solution is far simpler to implement and understand than anything involving symlinks. And if you're going to instead actually copy the files so fish can find them then you might as well use the `make install` approach since that's already setup and known to work.

And upon reflection I might have misunderstood @ridiculousfish's comment:

> This will use the installed fish instead of the built fish when running tests.

Yes, yes, it does. That is precisely what the Travis CI environment does. That's the only reason the tests work in Travis. To allow the tests to be run using `./fish` from the top of the source tree would require reorganizing the source tree or doing the equivalent of `make install` only copying the files somewhere else.

This change is simple in comparison. It leaves the Travis CI configuration unchanged. Anyone who wants to run the tests on their local server today is already relying on the "installed fish" -- that's the problem. This change makes it trivial to run the tests without having to install an untested change.

**Comment by krader1961** [comment]
Does anyone feel strongly about whether the directions for running tests hermetically should be in the *README.md* file in addition to the wiki? I was thinking about moving all of that, including the existing directions for doing a build, into the wiki and replacing that text with a link to the wiki.

**Comment by ridiculousfish** [comment]
I hope the directions for running the tests locally can be just `make test`. If the test setup is complicated then people won't run them. Testing the installed fish is of course not very useful, though it happens to work in Travis. 

@krader1961 can you elaborate on what made the symlink approach difficult? Would it help if fish had command line arguments for the data and sysconf dirs?

**Comment by krader1961** [comment]
@ridiculousfish: How would `make test` work if you haven't already run `./configure` to create the *Makefile*. And if you have to run configure then it's pretty easy to point it somewhere else (e.g., `./configure --prefix=/tmp/fish.test`). Honestly, I don't understand the pushback on this change. Any developer who is making regular changes should script running the tests to avoid making stupid errors (I have a `test-fish` script for the purpose). And a casual contributor is really unlikely to run the tests on their system.

**Comment by krader1961** [comment]
As for "what made the symlink approach difficult" I don't recall all the specifics but it basically boils down to the fact the source directory structure doesn't match the installed directory structure. Keep in mind that when the existing tests run `./fish` the shell treats the top of the source tree like the `./configure --prefix=` install point with respect to finding the support files. I couldn't get symlinks to bridge the gap.

**Comment by ridiculousfish** [comment]
Maybe I'm missing something. The problem as I understand it is that `make test` will build a fish executable, and then runs the tests against a different fish executable. So if I introduce a bug in fish, the tests won't catch it.

Today we have a problem where the tests source some installed files. That's clearly bad and we ought to fix it. But it seems like this is moving in the wrong redirection: increasing our reliance on what's installed, instead of decreasing it.

I hope that casual contributors can and do run the tests, and so we ought to make running the tests as foolproof as possible. That will even encourage contributors since it gives them more confidence in their changes.

**Comment by krader1961** [comment]
The problem is not that the wrong fish binary is being used. The fact that *tests/interactive.fish* and *tests/test.fish* depended on */usr/local/bin/fish* did not cause the tests to rely on that binary. The problem is the existing test setup relies on the installed support files.

This change decreases the reliance on the installed fish by completely removing that dependency. In other words, to test you simply configure things so the code ends up in something vaguely analogous to a chroot environment.

**Comment by krader1961** [comment]
Also, I forgot to mention another benefit of this change. It means you're actually testing the result of "installing" the binary and its supporting files. Which means we're increasing our confidence during the unit test phase of development that things will actually be laid out in the expected manner when a real install is done.

**Comment by ridiculousfish** [comment]
I think what krader likes about this approach is that it tests fish in a sane environment, instead of a bizarro one in the source directory. By using `--prefix`, you can install fish separately from the system fish, and so there won't be interference; furthermore this procedure also exercises the install process so it makes our tests more realistic and gives us more coverage. Did I capture that correctly?

Those are all great benefits. In my view the disadvantages are:

1. Requiring `make install` before `make test` is seriously weird and backwards feeling
2. If you forget to `make install`, you'll be testing the fish that is installed instead of what you just built, so you may miss bugs
3. Requiring a --prefix when testing is just one more complication in the test process. krader said he already has a script to manage this stuff.

Those combined are a showstopper IMO.

That said, the idea of leveraging the install machinery to build a "chroot" environment is really great. What would you think about factoring the Makefile so that it can install into $DESTDIR *or* into a little chroot somewhere in the fish source tree, depending on whether you're doing `make install` or `make test`? This gives us the nice hermetic test environment, while keeping the simple `make test` procedure.

**Comment by krader1961** [comment]
> Requiring make install before make test is seriously weird and backwards feeling

Agreed but it was the simplest solution to the current situation.

> If you forget to make install, you'll be testing the fish that is installed instead of what you just built, so you may miss bugs

But that's no worse than the present situation.

> What would you think about factoring the Makefile...

Are you okay with `make test` always doing the equivalent of `./configure --prefix=$PWD/test_prefix; make install`? That's effectively what my `test-fish` script does (albeit installing to */tmp/fish.test* rather than the source tree).

**Comment by krader1961** [comment]
Also, my previous proposal would necessitate changing the Travis config as not doing so would result in building fish twice and only using one of the builds.

**Comment by ridiculousfish** [comment]
> Are you okay with make test always doing the equivalent of ./configure --prefix=$PWD/test_prefix; make install

That's the idea, but I think we can do the moral equivalent of `./configure --prefix` without actually needing to re-run ./configure! This can be achieved with a [target specific variable](https://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html):

    test: INSTALL_LOC = ./test_root
    test: install-force
        # run the tests

    install: INSTALL_LOC = ${DESTDIR}
    install: install-force

    # install-force installs for either testing or the real deal
    install-force:
        $(INSTALL) -m 755 -d $(INSTALL_LOC)$(sysconfdir)/fish

so we gently redirect the install target into a test root without having to re-./configure. What do you think?

**Comment by krader1961** [comment]
Interesting idea to leverage a makefile target specific variable. I haven't needed something like that in several years because at $dayjob you never run a test on your workstation. Tests are always run in a container in the cloud. This is my first serious commitment to an open-source project in several years and it requires a different mind set. Give me a couple of days to verify whether that is a viable approach.

**Comment by krader1961** [comment]
I'm closing this PR and will open a new one. While addressing @ridiculousfish's concerns I felt compelled to fix several other test bogosities (such as `make test` polluting my personal fish history). So I'm going to squash my commits, rebase against the current project head, and issue a new PR.

**Comment by zanchey** [comment]
> Would it help if fish had command line arguments for the data and sysconf dirs?

This would actually be helpful in solving a few other problems, I think.

**Pull request closed without merging**
