### PR TITLE
string repeat: allow omission of `-n`

### PR DESCRIPTION
**Pull request by lavafroth**
## Description

`string repeat` will expect the first positional argument as the count if it is not supplied through the `-n` flag.

Fixes issue #9332

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by krobelus** [comment]
this history looks more complicated than necessary, can you simplify it (remove merge commits, squash commits as appropriate)

**Comment by lavafroth** [comment]
Sure thing.

**Review by henrikhorluck — COMMENTED** [review]
Thank you for your contribution! I found a minor behaviour change that we can avoid, and some minor code style nits, but otherwise LGTM!

This needs relnotes and documentation updates in `CHANGELOG.rst`, `doc_src/cmds/string-repeat.rst` and `doc_src/cmds/string.rst`. The signature change is in the linked issue so should be straightforward. I can deal with that if you would prefer not to.

**Comment by lavafroth** [comment]
I have committed the suggested changes.

**Comment by henrikhorluck** [comment]
Merged, thanks!

**Pull request merged**
