### PR TITLE
xcode project changes & fish_key_reader target

### LINKED ISSUE #3193: fish_key_reader not in fish.app, Mac fish installer
This is an apparent oversight: After releasing fish 2.3.1, it was noticed that while `fish_key_reader` was assumed to be shipped in our packages, in reality the tool is neither in fish.app or our official OS X installer. Actually the xcode project did not get taught to build a fish_key_reader binary in the first place. Only the Makefile was addressed.

A `fish_key_reader` target needs to be created in the xcode project and and the `base` target needs to be modified to include it.

### PR DESCRIPTION
**Pull request by floam**
Fixes #3193: Adds a target for fish_key_reader to the xcode project. 

Further updated xcodeproj format to xcode 6.x format, removed old broken Makefile target and also nonfunctional fish_tests target. I let Xcode apply it's recommended suite of compiler flags/warnings to the schemes, but did not let xcode enable code signing by default when it asked for that change (though I plan to do that myself sometime soon and submit a PR.)

### CODE REVIEW

**Comment by krader1961** [comment]
Running just `xcodebuild` in the project root dir succeeds as does building it with the Xcode GUI. Running `xcodebuild install DSTROOT=/tmp/fish_build` (from the *Makefile* and *README.md*) fails with

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: symbols referenced by relocation entries that can't be stripped in: /Users/krader/projects/3rd-party/fish-shell/build/UninstalledProducts/macosx/libpcre2.a(pcre2_compile.o)
```

Building an app bundle produces a result that looks correct. Running the fish binary results in `__fish_bin_dir`, etc., being set correctly.

Also, FYI, using either the CLI or GUI the "build_documentation" target fails with "Lexicon_filter not found, ignoring it". But that happens without this change so just FYI in case it's something easy to fix.

OS X 10.11.6 Beta, Xcode 7.3.1

**Comment by krader1961** [comment]
Ping? This is starting to smell of dead fish which is a shame since it fixes multiple problems with the macOS build :smile:

**Comment by floam** [comment]
I was a little apprehensive due tithe fact this was generated by Xcode 8 which is a beta. But that's correct it was working ok on Xcode 7 for you @krader1961?

**Comment by krader1961** [comment]
Using xcodebuild version 7 works for me. And `xcodebuild install DSTROOT=/tmp/fish_build` now succeeds. As does just `xcodebuild`. But neither invocation is building fish_key_reader -- just fish and fish_indent.

**Comment by floam** [comment]
What scheme is it building? If you pick the correct one (fish.app or base) does that fix it?

I'm ~~kind of~~ very confused as to what we're trying to do with `install` here. It seems entirely broken and is shoving crap into `/tmp/` (I am not setting `DSTROOT`). Seemingly on purpose?

**Comment by floam** [comment]
Huh, is this how it's supposed to be done? Why aren't we building for Archive when doing a release?

**Comment by krader1961** [comment]
Running `xcodebuild -target fish.app` succeeded and appeared to build fish_key_reader until I did `make clean`. Then it failed with `ld: library not found for -lpcre2`. I also did `make distclean` and the subsequent xcodebuild still failed in the same manner. I have no idea why we're "building for Archive when doing a release". I never use Xcode to build fish unless asked to do so.

**Comment by krader1961** [comment]
It's been a whole month since the last update to this PR. What's the status of it? If it isn't going to be merged or updated in the immediate future it should be closed.

**Comment by floam** [comment]
Apologies. I'm looking this back over. It looks like I accidentally removed some manpage stuff from the project.

**Comment by floam** [comment]
This did rot quite a bit. I'll submit a new PR if I redo it.

**Pull request closed without merging**
