### PR TITLE
Rsync completions stringification and command calling

### PR DESCRIPTION
**Pull request by faho**
## Description
These are assorted rsync changes, some of which were stuck in my pipeline for a bit, so they'll need some testing.

Fixes issue #3337.

Possibly fixes issue #1872.

Work towards #2450.

### CODE REVIEW

**Comment by ivan** [comment]
I've tested this and see two regressions:

1) This isn't working for some partial paths on a remote; e.g. if you have a directory "Trash" in your HOME,

```
rsync -av user@host:Tr<TAB>
```

shows completions for the home directory instead of "Trash".  This seems to happen for paths that start from the home directory, instead of from `/`.

2) Hitting TAB completes a directory without the trailing slash that should show up, because it seems to see the remote path without the slash:

```
# rsync -av at@ra:/home/at/builds<TAB>
…at/builds  (Remote path)  …at/builds/
```

**Comment by faho** [comment]
>rsync -av user@host:Tr<TAB>

I actually did not know you could do that. Yes, the new regexp will not handle that correctly.

>2) Hitting TAB completes a directory without the trailing slash that should show up, because it seems to see the remote path without the slash:

This is with or without your alias?

**Comment by ivan** [comment]
That's without my alias.

**Comment by faho** [comment]
This needs some more attention. Closing for now.

**Pull request closed without merging**
