### PR TITLE
add support for ANSI "bright" colors

### PR DESCRIPTION
**Pull request by krader1961**
This adds support for the ANSI x3.64 "bright" colors in the basic sixteen
color palette. This is especially useful when trying to use the base colors
as a background color. The "bright" variants tend to be more useful as
background colors compared to the non-bright variants.

This also fixes a bug in so far as palette number 7 is actually grey and
not white whereas palette number 15 is white. At least on the terminal
emulators on which I've tested this change (Ubuntu xterm & uxterm, Mac
OS X Terminal & iTerm2).

Resolves issue #1464.

### CODE REVIEW

**Comment by krader1961** [comment]
This replaces PR #2560 which I botched due to my inexperience using git.

**Comment by krader1961** [comment]
I've added a second commit to remove "normal" from the basic 16 color name table since that entry isn't actually used and its presence is confusing.

**Comment by ridiculousfish** [comment]
Apologies for the delay on this.

Removing `normal` from the list means that it won't appear in `set_color --print-colors`, which in turn means you can't tab-complete `set_color normal`. Unless I've misunderstood, let's put it back.

**Comment by krader1961** [comment]
You are correct, @ridiculousfish. I should have noticed that my change altered the output of `set_color --print-colors`. I've added another change to reinstate it. Albeit in a different manner which the associated comment in the change should explain. While including "normal" in the named color table achieves the desired result it is extremely misleading unless otherwise invalid values are used for the palette index and RGB attributes. Better in my opinion to special-case it here as is done elsewhere in the code.

**Comment by ridiculousfish** [comment]
Merged with rebase as 7322c9c5916f2332286e935dbb506d5025b70636 . Thanks!!

**Pull request closed without merging**
