### PR TITLE
implement a prompt_hostname function

### LINKED ISSUE #3480: sample fish prompts call `hostname` too often
Some of the sample fish prompts (in *share/tools/web_config*) run `hostname` every time the prompt is displayed. That command can be slow if, for example, there is a problem with DNS. All of the prompts should use this pattern:

```
# Just calculate this once, to save a few cycles when displaying the prompt
if not set -q __fish_prompt_hostname
        set -g __fish_prompt_hostname (hostname|cut -d . -f 1)
end
```

That's from *share/functions/fish_prompt.fish*. Obviously we can now do it slightly faster using the `string` builtin.

This issue was triggered by issue #3479.

### PR DESCRIPTION
**Pull request by krader1961**
_Quick sanity check please that I didn't introduce a typo._

Standardize how the host name is included in the prompts that do so.

Fixes #3480

### CODE REVIEW

**Comment by faho** [comment]
Did you forget to commit the function?

**Comment by floam** [comment]
Should this maybe be `prompt_hostname`? Simply for discoverability to match `prompt_pwd`?

**Comment by krader1961** [comment]
> Did you forget to commit the function?

Oops, yes, stupid `git commit -a` doesn't include new files. Fixed.

**Comment by floam** [comment]
Is splitting on ',' from `hostname` output always equivalent to using `hostname -s`?

**Comment by krader1961** [comment]
> Should this maybe be prompt_hostname? Simply for discoverability, and to match prompt_pwd?

Agreed. Changed.

**Comment by krader1961** [comment]
> Is splitting on '.' from hostname output always equivalent to using hostname -s?

It's supposed to be since the definition of `hostname -s` is to convert a FQDN to a simple host name.

**Comment by floam** [comment]
In no case can the FQDN be something like "www.mysite.com" and `hostname -s` and the simple host name be "myserver"?

**Comment by krader1961** [comment]
If by simple host name you mean what is returned as the `nodename` by the uname(3) then "yes" in theory. In practice probably not because a) that value is supposed to be the network name and should match whatever `gethostname()` returns. If it doesn't the system is misconfigured and that isn't our problem.

**Comment by faho** [comment]
>Is splitting on ',' from hostname output always equivalent to using hostname -s?

First of all, that's what we currently do, so there's no regression here. Secondly, this allows us to fix it in one place if we ever figure out a better solution.

Thirdly: Probably not. This is probably one of those things where there's a super-rare super-complicated edge case that some people get really passionate about (maybe some way to make it recursive, or dependent on locale?). We'll get an issue and then we can work it out. Or they can just override the function.

**Comment by floam** [comment]
>First of all, that's what we currently do, so there's no regression here

We used to use `hostname -s` here:

```fish
   # Just calculate these once, to save a few cycles when displaying the prompt
    if not set -q __fish_prompt_hostname
        set -g __fish_prompt_hostname (hostname -s)
    end
```

**Comment by faho** [comment]
Yeah, but in the other prompts we didn't. This was inconsistent.

**Comment by floam** [comment]
It looks like most of the sample prompts are not using this.

**Comment by floam** [comment]
Er, I'm totally mistaken. I was on Integration_2.4.0 and thought I was on master. And I mistakenly pushed two commits I shouldn't have. Reverting.

**Pull request merged**
