### PR TITLE
Account for mktemp failures

### PR DESCRIPTION
**Pull request by ericonr**
## Description

Discussed in #7477, catches when `mktemp` errors out and exits the script / function.

I can try to add some error case that exports `TMPDIR` to some place that can't be written, if you find it necessary.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by mqudsi** [comment]
Why don't we just add a tests function called `mktemp`? We need to do that anyway to get the tests to pass on older macOS versions that don't support the same syntax that Linux and newer macOS do.

**Comment by faho** [comment]
>Why don't we just add a tests function called mktemp?

We would still have to add `or return 1` everywhere, because the function won't return out of the calling function.

>We need to do that anyway to get the tests to pass on older macOS versions that don't support the same syntax that Linux and newer macOS do.

As far as I'm aware, all these uses work on macOS and linux - the issue was stuff like too short templates or using templates with *files* instead of directories and such.

**Comment by ericonr** [comment]
I don't really have a horse in this race, I'm only extending the patch from my previous PR :)

So I'm happy to proceed with whatever's decided.

**Comment by faho** [comment]
Okay, I merged this because it's a good thing by itself. Making a compatibility function can be done later, and isn't immediately necessary as far as I can tell.

**Comment by mqudsi** [comment]
Agreed. Thanks, all!

**Pull request merged**
