### PR TITLE
git_prompt: Allow overriding informative status via git config

### LINKED ISSUE #5551: Prompt with git information takes too much time to appear in a large git project
Fish version: 2.7.1
OS: Ubuntu 16.04
Terminal: Default
Does the problem appear in shell entered by `sh -c 'env HOME=$(mktemp -d) fish'`? No

To reproduce the issue, use this configuration:
```
  set -g __fish_git_prompt_show_informative_status true
  set -g __fish_git_prompt_showcolorhints true
```
And have the git information as a part of the prompt. In particular I'm using [this prompt function](https://github.com/oh-my-fish/theme-cbjohnson/blob/master/fish_prompt.fish)

Clone a large git project (e.g. https://github.com/WebKit/webkit) and cd into it. The prompt takes very long to appear, and I can't open any other terminals until I kill it or wait for it. Even after it has appeared for the first time, it becomes very slow to enter commands for some reason. Typed characters take a long time to appear, making the command line useless.

### PR DESCRIPTION
**Pull request by faho**
If either of the two git config variables:

- bash.showDirtyState
- bash.showUntrackedFiles

is explicitly set to false, we will disable informative status, and
fall back on the non-informative version (most likely still with
either dirty or untracked files, since we already use the variables
for that).

These vars are read by the official git prompt, so we use them instead
of inventing our own "fish.showInformativeStatus".

(Note: This also uses $__fish_git_prompt_showdirtystate and friends,
but only when there's nothing set in git, and there's really no
reason to set those to false if using the informative status)

Fixes #5551.

[ci skip]

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by floam** [comment]
Cool! It's too bad they didn't originally just call these e.g "shell.showDirtyState", but using the variable that are meaningfully in use makes sense.

**Comment by faho** [comment]
The big questions here:

- Do we add another option to just disable informative status, but keep displaying dirty and untracked state? This is more important than I thought because those just do "is dirty" and "there are untracked files" in a boolean manner, which as it turns out is _much_ faster than actually counting like the informative status does. Git allows just adding arbitrary options, so we could call it `fish.showInformativeStatus`, or we could keep the "bash." prefix. I've been unable to find other things that do this, with a variable name we could reuse.

- How do we document this?

**Comment by zanchey** [comment]
The git prompt is the single most configurable part of fish; it probably deserves promoting to `fish_git_prompt` and documenting as a proper command.

**Comment by faho** [comment]
Merged with the addition of the "bash.showInformativeStatus" variable as 15cf45a2a..354c6b1b6

**Comment by max-sixty** [comment]
This works great! Thanks!

**Pull request closed without merging**
