### PR TITLE
escape job commands

### PR DESCRIPTION
**Pull request by elyashiv**
## Description

Talk about your changes here.

Fixes issue #9808 

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by zanchey** [comment]
A test here might be helpful?

**Comment by elyashiv** [comment]
Sure. I wasn't so sure how and where to add one...

Where are the tests for jobs?

**Comment by elyashiv** [comment]
I think I managed to add a test.

**Comment by faho** [comment]
Thanks, merged!

**Pull request merged**
