### PR TITLE
Remove 'open' function

### PR DESCRIPTION
**Pull request by floam**
As discussed in #2561, it really seems like providing this open wrapper isn't very helpful. This PR removes the tool, and associated junk.

Users would be better off creating an 'open' alias or abbr for xdg-open
or using the system open pretty much everywhere.

Fixes issue #2561

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM.

**Comment by zanchey** [comment]
-1, as mentioned in #2561, at least for the 2.x series.

**Comment by krader1961** [comment]
My original comment before I changed it to a simple "LGTM" was an extensive rant about the dangers of making this type of change in a minor release. Yet we have little choice because the current structure of the project makes major releases so infrequent that we have little choice but to make these types of changes in a minor release. Perhaps it is time to change that. Perhaps we should switch to a model where major releases happen more often with support for the previous major release. Eventually we might even have releases designated as "LTS" (long term support).

**Comment by krader1961** [comment]
So we either decide that it is time to make major releases more frequently, in which case this type of change is deferred to the next major release, or we maintain the status quo and this change should be merged in the 2.x branch.

**Comment by faho** [comment]
@floam: Considering that the "better solution" you came up with is just the solution we have now, do you still want this? Or would you prefer to just remove the open man page on platforms where we don't use it?

**Comment by floam** [comment]
I'd still rather not provide it. That was a serious brainfart when I mentioned aliases in response to someone saying it won't work in their scripts.

**Comment by floam** [comment]
Closing - let's only do #3615

**Pull request closed without merging**
