### PR TITLE
Sample prompts

### PR DESCRIPTION
**Pull request by faho**
## Description

This is basically a first pass on the sample prompts.

It removes:

- classic and classic+status - they are just subsets of classic+vcs
- debian chroot - it's just classic plus a function that I don't think is used much (and if it is it should be added to the others as well)
- lonetwin and screen savvy because they are just slight variations on classic
- justadollar because it's unhelpful and easy to build yourself

and performs some light cleanup on the others. It renames the prompts named after people who did not contribute them directly to fish.

Work on #7884.

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
Screenshot of all the prompts after this:

Screenshot_20210403_100641

We are now down to 10, from 16.

**Comment by ridiculousfish** [comment]
Thanks for tackling this. Lots of good cleanup here.

I think we should have at least one simple prompt (not necessarily justadollar, but similarly simple). Some users may prefer a simple prompt, and don't want to learn how to build it; or they can use the simple prompt as a starting point to build from.

**Comment by faho** [comment]
>I think we should have at least one simple prompt (not necessarily justadollar, but similarly simple)

Sure, but I would argue that minimalist is much better in that role. Let me quote the full source:

```fish
# name: Minimalist
# author: ridiculous_fish

function fish_prompt
    set_color $fish_color_cwd
    echo -n (basename $PWD)
    set_color normal
    echo -n ' ) '
end
```

My fear is that justadollar is confusing to people, because it doesn't even contain $PWD. It's also not good as a starting point because it doesn't even show that $PWD exists, or that `set_color` is a thing.

By contrast going from minimalist to something justadollar-like is just removing the first three (or two) lines, which should be intuitively understandable.

Not that I'm married to minimalist in particular - I don't love showing only the last component of $PWD. My preferred "very simple" prompt would be something like `echo -n (prompt_pwd) '$'`.

But I would quite like to remove justadollar because it's a disservice to those who pick it accidentally.

**Comment by faho** [comment]
Alright, I renamed the Classic+VCS prompt to "Default" and added a "Simple" prompt that's the baseline I would expect - it's basically what you get when you look for a nice default $PS1 for bash:

```fish
function fish_prompt
    # This is a simple prompt. It looks like
    # alfa@nobby /path/to/dir $
    # with the path shortened and colored
    # and a "#" instead of a "$" when run as root.
    set -l symbol ' $ '
    set -l color $fish_color_cwd
    if fish_is_root_user
        set symbol ' # '
        set -q fish_color_cwd_root
        and set color $fish_color_cwd_root
    end

    echo -n $USER@$hostname

    set_color $color
    echo -n (prompt_pwd)
    set_color normal

    echo -n $symbol
end
```

Once you've seen this, you should be able to figure out how to make all sorts of prompts.

**Comment by krobelus** [comment]
I appreciate quiet prompts; the `$ ` one is nice when sending terminal contents to someone else because people recognize the dollar as prompt, and other prompt information is usually not relevant. But I agree it need not be in our samples.

I'd shave off the `fish_is_root_user` part of the simple prompt, to make it even simpler.
Or is it normal for people to copy over their prompt to root as well?

**Comment by faho** [comment]
>I'd shave off the fish_is_root_user part of the simple prompt, to make it even simpler.
Or is it normal for people to copy over their prompt to root as well?

This is what `\$` in $PS1 in bash does. The default $PS1 on arch is `[\u@\h \W]\$`, so it does this (and also the weird thing of only printing the basename for $PWD).

This is another one of those things that are most useful when they are the default - people don't tend to customize root much, but when they pick a prompt from `fish_config` it should still make clear that it is root.

We could probably get by with adding a helper function called `prompt_symbol`. Takes two args for the user symbol and the root symbol, and then calls `fish_is_root_user` and prints the corresponding symbol. That doesn't do the PWD color, however, but we could also leave it out for this prompt. Either leave it at $fish_color_cwd or don't color it, or hard-code a different color.

**Comment by zanchey** [comment]
https://github.com/fish-shell/fish-shell/pull/1351 re Debian chroot prompt

**Comment by faho** [comment]
>#1351 re Debian chroot prompt

So the argumentation there was that we don't want to make the default more complicated, so it should be in a separate prompt.

I disagree pretty strongly with that, because, like I've said numerous times: This is most useful when it's the default. When you need to specifically configure it you most likely won't, and then you'll never see it.

It's also a super cheesy solution because it is specific to debian. Any good solution here should probably also work for other kinds of virtualization.

I would argue for:

- Make a "machine id" function
- Add it to the default prompt

I've argued for this in the past with #6398. Note also that Debian apparently defaults to showing chroots for bash.

I don't think a separate prompt is of much use.

**Comment by faho** [comment]
Alright. The perfect being the enemy of the good, I have now merged this.

It doesn't solve *all* issues with the sample prompts, but it is an improvement.

**Pull request merged**
