### PR TITLE
fix __fish_list_current_token not recognizing ~ as $HOME

### PR DESCRIPTION
**Pull request by Axlefublr**

### CODE REVIEW

**Comment by Axlefublr** [comment]
it's not gonna hurt if I elaborate: I'd expect `cd ~/.config` to display the contents of .config, but it doesn't because it doesn't recognize ~ as home, which is incredibly annoying

I will argue that not seeing dotfiles and dotdirectories is also annoying, but I can see how not using the -A flag for the ls is a design choice. However I'm gonna jump up thrice if you agree that it's a good idea to change the ls in there to `ls -A` instead

**Comment by henrikhorluck** [comment]
I cannot reproduce your error, even in `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` (note you probably want to add another file to your temp home's `.config` there, only `fish` exists by default).

Tab-completing with `cd ~/.config/` already correctly displays the contents of `~/.config/` for me on  `master`, and it also works on `3.6.1`. This works regardless of whether `AppleShowAllFiles` is set or not (I am on macOS)

**Comment by Axlefublr** [comment]
what's completely hilarious is that "$HOME/.config" does work, but $HOME/.config doesn't

the former being a situation you would practically never find yourself in

**Comment by zanchey** [comment]
The full right answer here would be #751, probably as a subcommand of `path`.

**Comment by Axlefublr** [comment]
Thank you for merging! 

Was scared that this was going to be a situation of "we can't do it perfectly so we won't do it at all", so it's nice to see the feature being merged at least in this simplified fashion for the time being

**Pull request merged**
