### PR TITLE
git completions: Parse git status --porcelain

### PR DESCRIPTION
**Pull request by faho**
## Description

This is much faster on large repositories, as it allows us to do a lot
more with a single git call.

It also makes it easy to add descriptions to distinguish modified
files from untracked ones.

TBD is if all commands now have the right kinds of files.

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

@thomcc: How does this work for you?

### CODE REVIEW

**Comment by faho** [comment]
I just remembered that I have a reasonably full clone of qt lying around, and the benchmarks aren't looking great:

- `git add <TAB>` takes 60ms before, 510ms after

- `git checkout <TAB>` takes 530ms before and after

In both cases, this is because the new code descends into submodules while the old didn't, and qt's repo is submodule _heavy_ (I have 48 here, I think there's more available).

After adding `--ignore-submodules=all` to the `git status` invocation, this changes to 54ms for `add` and 72ms for `checkout`.

The question then obviously becomes if submodules are useful as arguments - it seems `git add qtbase`, `git reset qtbase` and `git checkout qtbase` (when a file inside the submodule "qtbase" changed) do nothing - no error, no change in staging, so at least there it's completely superfluous.

But when is it not?

Man, git is complicated!

**Comment by faho** [comment]
Okay, I added "--ignore-submodules=all" because I couldn't find any command where it's useful.

If we do end up finding one, we can activate it there via an argument.

**Comment by faho** [comment]
I have now merged this. There are still a bunch of possible optimizations for the git completions on large repositories - for instance we can cut down on `git branch` calls by doing the remote/local filtering ourselves. But those can be done at a later time.

**Comment by mqudsi** [comment]
@faho `git checkout <TAB>` causes `error: option \`porcelain' takes no value`

**Comment by faho** [comment]
@mqudsi: `git --version`? It's possible this is still too new to use, so we'd either have to wait or try to use the v1 format instead.

**Comment by faho** [comment]
Okay, so this needs https://github.com/git/git/commit/1ecdecce621009a4d039d061d514056501d0ed8f, which was first included in git 2.11.0, which was released in november 2016.

So... what should we do about that? We could 

- rewrite this to use the v1 format (i.e. just `git status --porcelain`, since adding a "=1" will error out just like this did) - which is a bunch of work

- fall back on the older logic if git isn't new enough - which is kinda complicated

- just silence stderr here and hence not offer files when git isn't new enough - which is easy, but also kind of a crap thing to do

**Comment by faho** [comment]
>rewrite this to use the v1 format (i.e. just git status --porcelain, since adding a "=1" will error out just like this did) - which is a bunch of work

It's not too bad. I think I basically have this already. Please try my [git-status-v1 branch](https://github.com/faho/fish-shell/tree/git-status-v1)!

**Comment by mqudsi** [comment]
@faho I'm on git version 2.14.1 so this may be something else.

**Comment by mqudsi** [comment]
Nevermind, I have so many ssh sessions open that I can't tell which is which any more. That was under git 2.7.4, which is actually the latest available for Ubuntu LTS (16.04) unfortunately. That means a non-negligible number will be locked out without one of your suggested workarounds.

**Comment by faho** [comment]
> That was under git 2.7.4, which is actually the latest available for Ubuntu LTS (16.04) unfortunately. That means a non-negligible number will be locked out without one of your suggested workarounds.

Can you try my branch (https://github.com/faho/fish-shell/tree/git-status-v1) on that? I believe it should work on that (possibly down to 1.7.2), and if it doesn't it's pointless.

**Comment by mqudsi** [comment]
Just did. I think you've got it. Had a hard time testing though, there's something off about using `./fish` instead of installing since switching to cmake.

**Pull request merged**
