### PR TITLE
Improve clarity and grammar of Introduction doc page

### PR DESCRIPTION
**Pull request by mattdutson**
## Description

When reading through the [Introduction doc page](https://fishshell.com/docs/current/index.html) I noticed some miscellaneous grammar and wording issues. So, I've started going through and making some minor revisions. To be clear, I am **not** modifying the structure or high-level content. I'm just improving the clarity and presentation.

This PR covers the first ~10% of the page. I thought I'd get feedback before I spend any more time on this.

Fixes issue # N/A

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by IlanCosman** [comment]
Read over about 75% of the changes. Vast majority seem like improvements to me, and the rest purely arbitrary. 👍 from me for what that's worth.

**Comment by faho** [comment]
Thanks!

**Comment by mattdutson** [comment]
Cool, I'll go over the rest over the next few weeks and submit another PR when done.

**Comment by zanchey** [comment]
Yes, this is great.

**Pull request merged**
