### PR TITLE
Here comes Sphinx

### PR DESCRIPTION
**Pull request by ridiculousfish**
fish should migrate from Doxygen to [Sphinx](http://www.sphinx-doc.org). I want to ensure we agree on the plan before I continue to work on it.

## Why Sphinx

1. The current docs build pipeline [is the worst](https://github.com/fish-shell/fish-shell/blob/master/build_tools/build_lexicon_filter.sh). Sphinx makes this stuff radically simpler.

2. Sphinx has momentum: it's used by LLVM, Linux kernel, Python (of course), and many smaller projects.

3. Sphinx is highly pluggable, themeable, and in my experience easier to work with than Doxygen. For example, the configuration is Python instead of a generated Doxygen file.

## Example output

[Here](http://ridiculousfish.com/sphinx-demo/) is the output of porting our existing docs to Sphinx with the "nature" theme. Obviously the HTML is highly themeable so do not get hung up on its appearance.

## Try it out

Check out this PR, install sphinx (for me that was `sudo pip3 install -U sphinx`) rerun CMake, and then from the CMake build directory:

    ninja sphinx-docs ; open sphinx-root/html/index.html
    ninja sphinx-manpages ; man ./sphinx-root/man/fish.1

## Left to do

1. Some recent doc updates are left out of this PR
2. We should make our own fish-specific theme
3. Teach the install target about the man pages
4. Does the autotools build have to support building Sphinx? @zanchey

### CODE REVIEW

**Comment by zanchey** [comment]
My plan is to drop Autotools for 3.1, so I wouldn't worry about adding it in there.

The lexicon filter is (to my mind anyway) equally beautiful and terrifying, but does give an impressive up-to-date syntax highlighting capability. I see Sphinx supports FishShellLexer, but I'm not sure how "pluggable" these lexers are.

**Comment by faho** [comment]
>I want to ensure we agree on the plan before I continue to work on it.

I agree that we want to move away from the current system.

Rst is acceptable (and much more used than doxygen), sphinx is a tad slow but I could live with it.

Also I don't have a better alternative, so sphinx it is!

>Obviously the HTML is highly themeable so do not get hung up on its appearance.

I think it's time for a refresh anyway.

>I see Sphinx supports FishShellLexer, but I'm not sure how "pluggable" these lexers are.

Doesn't look too bad: https://bitbucket.org/birkenfeld/pygments-main/src/ed1dd2b941ea271dd64d9e527bcf04f367952967/pygments/lexers/shell.py?at=default&fileviewer=file-view-default#shell.py-763:832.

Pygments is also a well-known highlighter.

>Some recent doc updates are left out of this PR

When was the cut-off? The bulk of the commits are from december 19th, so `git log --since"19.12.2018" doc_src` shows 24 commits touching doc_src since then.

That's not too bad (especially considering 5 of those are for the vcs-prompt stuff, which is entirely new, and so doesn't have merge conflicts), but the longer we keep this forked/separate, the more problems we'll run into.

So what's the plan?

Merge this:

- [ ] now
- [ ] when it's done
- [ ] some other milestone

After it's merged, keep doxygen:

- [ ] not, remove immediately
- [ ] until sphinx is good and ready
- [ ] indefinitely

In between adding sphinx and removing doxygen, add doc changes to:

- [ ] sphinx only
- [ ] both
- [ ] doxygen only

Also, how much do you care about comments about the current state? I get some warnings, some unhighlighted bits and the search is great.

**Comment by ridiculousfish** [comment]
Thanks @faho and @zanchey. I think it makes sense to incorporate doc changes since the branch, merge it now, and then fix the warnings. We can then work on packaging it into the installer, a fish theme, and a highlighter probably based on `fish_indent`.

**Comment by floam** [comment]
It seems not fun but possible to do the highlighting in Python with ctypes/libfish

**Pull request closed without merging**
