### PR TITLE
Add arguments to set prefered server config.

### PR DESCRIPTION
**Pull request by ppggff**
## Description

This patch add 3 arguments to `fish_config`,
It let user do some basic setup for the server.

Usage:

```sh
fish_config [tabname] [<4|6> <host> <allowed_client>]
```

* `4|6`: ipv4 or ipv6
* `host`: the host IP that server listen on, could be `0.0.0.0`
* `allowed_client`: IP of allowed client, could be `*`
* Three arguments must use together

Examples:

```sh
fish_config "4 0.0.0.0 \*"
fish_config "4 192.168.10.201 \*"
fish_config "4 192.168.10.201 192.168.10.200"
fish_config "functions 4 192.168.10.201 192.168.10.200"
```

Fixes issue #1916 ([fish_config] Listen on non-localhost interfaces)

## TODOs:
- [ ] No check for new arguments
- [ ] Newbie to python
- [ ] Flexibility or better design
- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by krader1961** [comment]
Thanks for tackling this but the CLI is very awkward and non-standard. It normally shouldn't be necessary for the user to specify whether IPv4 or IPv6 is to be used as it can be inferred from the addresses. Similarly, most of the time it should be sufficient to just provide the single address to allow to connect to the service. It would be better to use the `argparse` module to implement these as normal unix style flags with only the `--allowed-client` (or whatever it gets named) being required to enable a non-local connection.

**Comment by zanchey** [comment]
There's been a lot of discussion about allowing remote access to the fish_config server over the years. The current architecture allows code execution by any authenticated client, which is why remote connections are explicitly denied. I don't think that the current cleartext authentication solution is enough to protect our users.

**Comment by krader1961** [comment]
> I don't think that the current cleartext authentication solution is enough to protect our users.

I think that if we mandate the `--allowed-client` flag to specify a single source IP address that can connect it's probably safe enough. We definitely should not allow specifying the interfaces to listen on without that flag. And we should probably restrict it to a literal IP address -- host names not allowed. Then the documentation should make it crystal clear that if you use this feature you run the risk of being attacked as long as the service is running. It would also be a good idea to add a timeout that shuts down the service if no requests are seen in the past N minutes. With N being on the order of five minutes.

**Comment by ppggff** [comment]
Yeah, I will try to make it more standard. 
How about:

* `--host <IP address>` : only literal IP address allowed, default: `localhost`, support `0.0.0.0`?
* `--allowed-client`: only literal IP address allowed, default: `localhost`, support `*`?

**Comment by krader1961** [comment]
No objection to allowing the special `0.0.0.0` for `--host` to mean bind to all interfaces. In fact, that should be the default if `--allowed-client` is specified by the user and it isn't `localhost` or `127.0.0.1`.  Also, `--allowed-client` must not allow any wildcards. It must default to localhost and can only be specified once. The only hostname it should allow is `localhost`. All other values must be a literal IPv4 or IPv6 address. We have to be highly restrictive because this feature opens up a security hole even with those restrictions. Without those restrictions you might as well just publish your username and password. This feature is meant solely for people using fish on headless servers. Such individuals won't have any trouble dealing with things like an explicit IP address.

**Comment by ppggff** [comment]
I think it's unsafe to use `0.0.0.0` as default for `--host` when `--allowed-client` is specified (not `localhost` or `127.0.0.1`). If user has more then one interface, he may expose `fish_config` to outside by forgetting set `--host`. We'd better make default setting to `localhost` at all times.
Maybe user could specify `--allowed-client` multiple times?

And since `localhost` is allowed for IP address, may be we should add a argument to specify whether IPv4 or IPv6 is to be used? such as `--ipv4` and `--ipv6`, maybe use both?

**Comment by krader1961** [comment]
> I think it's unsafe to use 0.0.0.0 as default for --host when --allowed-client is specified...

I don't understand your reasoning. If `--allowed-client` is specified then only connections from that address will be allowed by the `fish_config` service. It doesn't matter which interface the request arrives at. Binding to all interfaces in that case should not make us any more vulnerable. Since we're not using UDP there isn't any practical way for an attacker to spoof the request. The whole point of the rules I spelled out is the default is to only bind to the loopback interface and thus only accept connections from a browser on the same host. If the user wants to allow connections from a specific host other than the system `fish_config` is running on they need to provide the IP address of that host. Presumably that IP address is assigned to their laptop or desktop workstation. If it isn't then the responsibility is theirs for allowing a system not under their control to access the `fish_config` service. If they do provide the address of their laptop or workstation it's silly to also require them to specify which interface of the headless server the IP traffic will route through.

**Comment by zanchey** [comment]
I do not want to take a patch which enables remote access to fish_config without significantly improving the authentication of requests. It is not tenable to release software in 2017 that does not have strong protections on remote access.

I would consider something that protects against passive interception but not man-in-the-middle attacks (eg digest authentication) but really both endpoints need to be mutually authenticated to some degree.

**Comment by faho** [comment]
@ppggff: Sorry, but we're going to need authentication before we enable something like this.

Because of that, I'm closing this. If you ever sort that out, we'd be happy to merge it.

**Comment by ppggff** [comment]
@faho ok, thanks

**Pull request closed without merging**
