### PR TITLE
Move fish_history to $XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by jeffkowalski**
Add new functions path_get_data and path_create_data which parallel existing
functions path_get_config and path_create_data.  The new functions refer to
XDG_DATA_HOME, if it is defined, or ./local/share if not.

Modify history_filename to use the new function path_get_data.

As a consequence, fish_history will now be located in XDG_DATA_HOME,
not XDG_CONFIG_HOME.

Note that these changes mirror what is already used in
fish-shell/share/tools/create_manpage_completions.py, which stores the
completions in XDG_DATA_HOME

This change matches recommendations in the xdg basedir spec at
http://standards.freedesktop.org/basedir-spec/basedir-spec-0.7.html
($XDG_DATA_HOME defines the base directory relative to which user specific data
files should be stored. If $XDG_DATA_HOME is either not set or empty, a default
equal to $HOME/.local/share should be used.)

It addresses suggestions from the following issues:

1. Don't put history in $XDG_CONFIG_HOME #744
   fish-shell#744

2. Fish is placing non-config files in $XDG_CONFIG_HOME #1257
   fish-shell#1257

3. Move non-config data out of $XDG_CONFIG_HOME #1669
   fish-shell#1669

### CODE REVIEW

**Comment by faho** [comment]
CI is failing because it can't find history samples - I think you might also have to adapt the tests.

Other than that - there doesn't seem to be any migration here. It would be nice if the old history would be moved to the new path.

**Comment by jeffkowalski** [comment]
@faho thanks for pointing out the CI failure.  I was running the tests locally in the wrong way (and still had the legacy directory around), so I had gotten different results.  I updated the test source code to match the changes in the earlier commit.
As well, I implemented a migration step that works during in the "sudo make install" command.
CI's passing now.  Hope the changes are satisfactory.  Comments welcome.

**Comment by faho** [comment]
The Makefile is not the right place to implement the migration - for one, it won't be done for people installing fish via a package manager (i.e. pretty much all linux users). Also, touching anything outside of DESTDIR for `make install` is very surprising and bad form. There's some place where we try to import bash's history (if there is no fish history), that's probably the right place to do it.

(Note that I'm not reviewing the code itself since my C++ is so rudimentary it hurts)

**Comment by jeffkowalski** [comment]
Thanks for the pointer, @faho.  I've removed the implementation from the makefile and implement it in the source instead.  I plan to modify `reader.cpp: reader_import_history_if_necessary`, adding in a new step to import the old history.  I don't plan to remove the file from the old `.config/fish/` location though.

**Comment by jeffkowalski** [comment]
@faho, the new implementation of the history migration follows your suggestion and parallels the migration of the bash history file, all implemented in the fish executable itself, no longer in the make or installation steps.  Ready for your review.

**Comment by jeffkowalski** [comment]
@faho, this pull request had no conflicts a couple weeks ago, and now needs resolution.
How would you like me to proceed with the patch?
If you agree the contents are OK, perhaps close this pull request and I'll open another with a consolidated patch?

**Comment by zanchey** [comment]
I'd prefer @ridiculousfish to cast eyes over this, but I am happy with it.

**Comment by ridiculousfish** [comment]
Let me review

**Comment by ridiculousfish** [comment]
I think this is the right thing to do on Linux but I'm honestly not thrilled about it on OS X, since now we scatter stuff even more widely. I wonder if on OS X we should use a directory `~/.fish`.

**Comment by faho** [comment]
>I wonder if on OS X we should just use a directory ~/.fish on OS X.

For everything or just the "data" stuff? Especially for the former I'd dislike it for support reasons - it'd mean having to ask people what system they are running before telling them where the files are (and in case of config.fish, that'd happen a lot).

Isn't there anything that puts stuff into ~/.local/share on OSX? Because even if there's a few things it'd be one less directory in your $HOME (which is the reason for that spec in the first place).

**Comment by jeffkowalski** [comment]
@ridiculousfish, I use Linux primarily, not OSX, so I'm not an expert here, but it appears to me that on OSX fish *already* stores its generated_completions in ~/.local/share, so we have some precedent to use that directory:
```share/tools/create_manpage_completions.py:976:        xdg_data_home = os.getenv('XDG_DATA_HOME', '~/.local/share')```

To echo @faho, I wouldn't advocate for using ~/.fish, since homedir pollution is exactly what drives the use of ~/.local/share/* ~/.config/* and XDG.

**Comment by zanchey** [comment]
I agree that this is the right thing to do; I'm happy to merge it if @ridiculousfish is happy.

**Comment by ridiculousfish** [comment]
Go ahead and merge - sorry this fell off my radar. Thanks!!

**Comment by zanchey** [comment]
I merged this with rebase as 297188..226cdc6a28b - thanks!

**Comment by faho** [comment]
This should probably be mentioned in the release notes.

**Comment by jrobeson** [comment]
oh, this happened! I saw #1940 and went looking to see if this was talked about. I can't wait for a new release that carries this change :)

**Pull request closed without merging**
