### PR TITLE
Fix "Error: target STRING not available" error in fish_clipboard_paste for xclip

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
## Description

Talk about your changes here.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by krobelus** [comment]
when does this error happen?

**Comment by EmilySeville7cfg** [comment]
When I paste empty line

**Comment by krobelus** [comment]
That works for me; these commands run without that error

	echo -n | xclip -selection clipboard
	xclip -selection clipboard -o

maybe there is something wrong with your environment?
Which kind of system is this on?

**Comment by EmilySeville7cfg** [comment]
My environment is:

- Fish version: 3.3.1-682-g0cd3ed4b8-dirty (built from source)
- OS version: Linux Mint 20.2 Cinnamon

**Comment by zanchey** [comment]
https://github.com/astrand/xclip/issues/38

**Comment by krobelus** [comment]
OK as far as I can tell this error shouldn't happen for an empty line.
According to [this comment](https://github.com/neovim/neovim/issues/2642#issuecomment-163522558), it happens when the clipboard contains non-text, like an image.

It also happens on Wayland (if the clipboard hasn't been used before) but that shouldn't be the case here.

Anyway, the change looks good. I'd summarize the reason in the commit message but that's not essential

**Comment by zanchey** [comment]
Merged with rebase/commit message edits here:
To github.com:fish-shell/fish-shell.git
   1d1bee3ba..077f1f257  master -> master

Thanks!

**Pull request closed without merging**
