### PR TITLE
send smkx/rmkx when entering/leaving interactive mode

### PR DESCRIPTION
**Pull request by zanchey**
A possible fix for #2139. I would appreciate some testing, and also feedback on whether this is the right place to send these codes.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
This causes a visible flicker when you first begin typing on iTerm2, as if the cursor temporarily jumps to the beginning of the line. It looks OK on Apple Terminal.

If I move the call above the `s_reset()` above in the same function, the flicker goes away. Does putting it there still fix st?

**Comment by pickfire** [comment]
> If I move the call above the s_reset() above in the same function, the flicker goes away. Does putting it there still fix st?

What do you mean by that?

I have tested on `urxvt`, `xterm` and `lxterminal` in Linux, it seems there are no flickering.

**Comment by ridiculousfish** [comment]
It flickers in iTerm2.

**Comment by pickfire** [comment]
No, I mean what do you mean to call above `s_reset()`...

How did you prevent the flicker?

**Comment by ridiculousfish** [comment]
zanchey's fix adds a call to `tputs()` in `reader_readline()`. My suggestion is to move the call site from its proposed location to further up in the same function, before the call to `s_reset()` on line 3087, which prevents the flicker in iTerm2. My hope is that zanchey can verify the fix still works for st terminal.

**Comment by pickfire** [comment]
Do you mean:

```diff
@@ -3098,6 +3098,14 @@ const wchar_t *reader_readline(int nchars)
     exec_prompt();

     reader_super_highlight_me_plenty();
+
+    /* Send the smkx sequence if defined to enable arrow keys etc.
+     See https://github.com/fish-shell/fish-shell/issues/2139 and
+     http://invisible-island.net/xterm/xterm.faq.html#xterm_arrows
+    */
+
+    tputs(keypad_xmit, 1, &writeb);
+
     s_reset(&data->screen, screen_reset_abandon_line);
     reader_repaint();
```

I have tested it on `st` and other terminal, it works too.

**Comment by zanchey** [comment]
Yes, that works nicely; I have rebased the branch.

**Comment by ridiculousfish** [comment]
New PR looks fine in iTerm2 and Apple Terminal :+1: Thanks!

**Pull request closed without merging**
