### PR TITLE
Clear ONLCR to/and optimize general x movement

### PR DESCRIPTION
**Pull request by mqudsi**
This isn't as much a performance improvement as a code cleanup issue, as
one could argue whether we move to zero more often than not after a
newline in interactive mode.

Thanks to @PerBothner for figuring out why ~ONLCR didn't work last time
around (3f820f0) to work around the issue pointed out by @nbuwe in
#4505.

### CODE REVIEW

**Comment by PerBothner** [comment]
This patch seems to be still adjusting c_iflag but should be changing c_oflag.

**Comment by mqudsi** [comment]
You're right. I reverted and stashed the code a few times and based my fixes on the wrong version.

**Comment by mqudsi** [comment]
I fixed this to use `o_flag` and the fallout from that and verified everything now works. However, it completely breaks all existing tests which include hard-coded ansi sequences (the `expect` tests).

**Comment by faho** [comment]
This doesn't just break the tests. Try ctrl-d to exit, you'll see our ⏎ marker appear on a new line.

**Comment by faho** [comment]
Okay, closing this one for now.

**Pull request closed without merging**
