### PR TITLE
Improve pushd completions

### PR DESCRIPTION
**Pull request by donkopotamus**
Add completions for rotating and swapping the stack.

### CODE REVIEW

**Comment by faho** [comment]
Otherwise, this looks nice. If you want, you can implement my suggestions, if not, I can also do that afterwards.

**Comment by faho** [comment]
Oh, one more thing - my rewritten cd-completions already show just a directory in the description (the associated CDPATH entry), so it'd be nice to prefix the plus descriptions with something.

**Comment by donkopotamus** [comment]
"Rotate to <directory>" perhaps ... I'll have a look at this tomorrow

**Comment by faho** [comment]
@donkopotamus: Ping? Do you want to take care of this or should I?

**Comment by donkopotamus** [comment]
I'm happy to take care of it, I'm just off for the week :-).

**Comment by donkopotamus** [comment]
@faho Have amended commit to:

-  no longer use `test`
- put *Rotate to ...* in description
- I'll alter to no longer use `sed` when `string replace` is release.

**Comment by faho** [comment]
I've pushed this as e75108fc4c and added ec74479d44 with completions for `pushd -n` (i.e. rotate the other way around), switched it to string and indented it with fish_indent.

Thanks!

**Comment by donkopotamus** [comment]
@faho Just a note ... I considered adding the negative completions too, but I found in actual practice that it cluttered the suggestions (every directory is now mentioned twice) for little benefit ... every negative rotation is equivalent to a positive one.

Also, the implementation of `__fish_complete_pushd_minus` in ec74479d447b7f54e59896e786243d98b6925728 doesn't look right ... a negative index counts from the end so eg -1 should display the last member of `$dirstack`

**Comment by faho** [comment]
>a negative index counts from the end so eg -1 should display the next to last member of $dirstack (and -0 will be the last member)

Nope - "-1" is the _last_ member of a list, there is no -0. This is the same as in python. (`set a (seq 1 10); echo $a[-1]`).

(There is a missing "\n", though)

It seems to me more like pushd behaves differently - it actually seems to use `-0` - while "+0" does nothing.

**Comment by donkopotamus** [comment]
@faho That is exactly my point. I was describing how negative indices for pushd should work, not how they work in fish.  It doesn't seem to me that that is what commit ec74479d447b7f54e59896e786243d98b6925728 is doing?  Instead, for `-1` it shows `dirstack[1]`, for `-2` it shows `dirstack[2]` ... (and it doesn't show -0 at all).

**Comment by faho** [comment]
Wait a minute - you mean that negative indices start at "-0" while positives start at "+1" (with "+0" being a no-op) _isn't_ a bug? That's expected behavior from something named "pushd"?

**Comment by faho** [comment]
And yes, the negative completion is borked, sorry. I pushed it out too quickly.

**Comment by donkopotamus** [comment]
@faho Well, positives do actually start at `+0`, once you consider the fact that `pushd` doesn't operate over `$dirstack` ... it operates over `$PWD $dirstack`.  Thus `+0` maps to `$PWD`, while `+1` maps to the first element of `$dirstack`.

(Which also makes +0 a no-op ... similarly `-(count $dirstack)` also corresponds to `$PWD` and is a no-op)

**Comment by faho** [comment]
> it operates over $PWD $dirstack

But that's utterly useless! `cd $PWD` is by definition not a useful thing to do - it has no effect whatsoever.

Anyway, if that's something a pushd is expected to do, then that's probably what we should do (this is a minor thing that's not worth breaking user expectations - and those users are mostly switching from other shells that have that behavior).

I've got a patch for the completions in the pipeline.

**Comment by faho** [comment]
Fixed by 98b33d7.

**Pull request closed without merging**
