### PR TITLE
Add missing sed -e flags

### PR DESCRIPTION
**Pull request by hauleth**
Current suggestions are missing `-e` flag of `sed` commant that issues many
errors while completing commands such as `rbenv install` this pull request
should fix that.

### CODE REVIEW

**Comment by faho** [comment]
Which sed behaves this way? GNU sed takes the first non-option argument as expression anyway, so it's not necessary for linux tools (like emerge or cower), and I don't recall anyone on OSX complaining about it, so I don't think e.g. the `brew` completions are broken.

**Comment by hauleth** [comment]
I have `sed (GNU sed) 4.2.2` on Ubuntu 15.04 and it fails with error when trying to complete (whai have I tested):

- `apt install`
- `apt-get install`
- `rbenv install`

**Comment by faho** [comment]
`apt install` and then tab or `apt <TAB>` or `apt insta<TAB>`?

**Comment by faho** [comment]
Also, `sed` 4.2.2 is the newest version, and the `apt install <TAB>` completions already have "sed -e".

What errors?

**Comment by hauleth** [comment]
Ok. I found bug. It was caused by mine function `alias _=less`. Closing as irrevelant.

**Pull request closed without merging**
