### PR TITLE
Add BSD specific arguments for tr command completion

### PR DESCRIPTION
**Pull request by buo**

### CODE REVIEW

**Comment by faho** [comment]
From [the man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/tr.1.html), it seems like this is a BSD thing that OSX has inherited.

Could you adjust the check to try `tr --version` and assume BSD if it fails and GNU otherwise? And while you're at it, it'd be nice if you could move the GNU-specific options into that section. That way we'd have precise completions _everywhere_.

(This is similar to what the `sysctl` completions currently do)

Thanks!

**Comment by buo** [comment]
Thanks for the point, and I amended the commit.

**Comment by buo** [comment]
Additionally, BSD `tr` has all arguments including the GNU-specific ones, so this case is a little bit different from the `sysctl` completions.

**Comment by faho** [comment]
It however lacks the long options.

**Comment by buo** [comment]
Oh, yes! I will add some more codes. Thank you so much.

**Comment by faho** [comment]
Squash-merged as 3472a39. Thanks!

**Pull request closed without merging**
