### PR TITLE
Add string-replace-fewer-backslashes feature

### LINKED ISSUE #5474: `string replace` in regex-mode requires waaaay too many backslashes for the replacement
(I could swear we already discussed this somewhere, but I can't find it. Anyway I'm pretty sure it's been closed, and I want to rerun it)

`string replace -r` currently does an additional unescaping pass on the replacement (see the `interpret_escapes` function in builtin_string.cpp), and just the replacement.

That means  if you e.g. want to add a backslash to any a or b, you'll have to do this:

```fish
string replace -ra '([ab])' '\\\\\\\$1' a
```

with one or two backslashes, it just prints "a", with three to six backslashes, it prints `$1`. With seven to ten, it prints the desired `\a`.

If we removed `interpret_escapes` instead:

- one or two backslashes prints `$1`

- three or four prints `\a`

- five or six prints `\$1`

- seven or eight prints `\\a`

This is explainable - `\` is an escape character in fish even in single-quotes, so `\\` is reduced to just `\` before it reaches fish. `\$` isn't reduced, because `$` doesn't need to be escaped. So both `\$` and `\\$` result in `\$` being passed to fish.

Similarly, `\\\$` and `\\\\$` reduce to `\\$`, which is taken by string to mean "a literal backslash, and then the dollar replacement".

The major issue with this is backwards-compatibility. There is, as far as I can see, no way to make a common subset to easily write expressions that work with both interpretations.

So we'd have to do something:

-  `string replace --real-regex` or `string replace --regex --replacement-without-annoying-backslashes`
- or a feature flag
- or break stuff and tell people to check $version

I still feel like this is worth it, simply because the current behavior is ridiculous.

### PR DESCRIPTION
**Pull request by faho**
This disables an extra round of escaping in the `string replace -r`
replacement string.

Currently, to add a backslash to an a or b (to "escape" it):

    string replace -ra '([ab])' '\\\\\\\$1' a

7 backslashes!

This removes one of the layers, so now 3 or 4 works (each one escaped
for the single-quotes, so pcre receives two, which it reads as one literal):

    string replace -ra '([ab])' '\\\\$1' a

This is backwards-incompatible as replacement strings will change
meaning, so we put it behind a feature flag.

The name is kinda crappy, though.

Fixes #5474.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [X] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

----

We really should think about documenting feature flags better!

### CODE REVIEW

**Comment by floam** [comment]
I'm kind of opposed to adding more feature flags. I don't think a meaningful number of people are going to opt-in to test features against their scripts; I think we should just break it.

**Comment by faho** [comment]
>I think we should just break fix it.

The main problem is that there is no way to write cross-compatible expressions. If you need a backslash in the replacement, you'll need to write two different ones.

So without a feature flag, which allows testing via `status test-feature`, you'll have to read version numbers, or try and retry. Which isn't great!

But I admit there is this question how far we want to take this system - do we want to put everything even slightly backwards-incompatible through it? Or do we only do it for huge stuff (like `?`)? Or do we freeze the flags as they are now and never add anything, and remove the  system itself eventually?

Personally, I'd like to see a better deprecation cycle!

**Comment by floam** [comment]
Could the feature flags be used to test for the new behavior without actually requiring users to configure something to get the saner `string replace` behavior? Making it possible to change the behavior isn't actually even required - you just could always have `status test-feature string-replace-fewer-backslashes` exit 0 on fish 3.1.0.

**Comment by faho** [comment]
>Could the feature flags be used to test for the new behavior without actually requiring users to configure something to get the saner string replace?

We could default it to on.

Also, as a note to myself:

>I'm pretty sure we'd have to fix the paste escaping in fish_clipboard_paste

Do that!

**Comment by mqudsi** [comment]
@floam yes, imho the feature flags should all default to on in fish 3.0 and users should be able to temporarily opt in to the legacy behavior while updating their scripts by disabling the features in question. The discoverability otherwise approaches zero.

**Comment by faho** [comment]
I've just merged this as-is. It's not a huge deal if you do use backslashes in the replacement expression (and none if you don't), but this way people at least get a fighting chance to handle it, and defaulting it to on seems like a bigger precedent that I don't want to handle on something this small.

**Pull request merged**
