### PR TITLE
Fix completions/ls.fish

### PR DESCRIPTION
**Pull request by kamektx**
## Description

Add -l option to GNU ls.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
`-l` [is in POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html#top), so it should be added to all instead of just GNU ls.

**Comment by kamektx** [comment]
Dear faho,

ls other than GNU ls already has the -l option completion enabled, so it should be fine as is.

If it bothers you, you can remove 'complete -c ls -s l -d "Long listing format"' on lines 33 and 117 and add it on line 18.

**Comment by faho** [comment]
>ls other than GNU already has the -l option completion, so it should be fine as is.

Then we don't need to add it multiple times - it should be available for all, so it can just be in the general part.

Please adjust the PR. You can add new commits to your branch and they'll show up here, I'll then squash them up when I merge it.

**Comment by kamektx** [comment]
I made the following changes;
- Remove 'complete -c ls -s l -d "Long listing format"' lines from GNU and non-GNU sections, and add it to shared section.
- Remove --scontext and --lcontext options. (what are these?)
- Arranged the completions of shared and GNU ls sections in alphabetical order. I didn't arrange non-GNU ls section.
- On -c description,  "Sort (-t) by modified time and show time (-l)" -> "Sort by changed time, (-l) show ctime"
- On -u description, "Sort (-t) by access time and show time (-l)" -> "Sort by access time, (-l) show atime"
- On -t description, "Sort by modification time, most recent first" -> "Sort by modified time, most recent first"

**Comment by faho** [comment]
> Remove --scontext and --lcontext options. (what are these?)

Please put them back. They are selinux-related (and I think therefore won't appear in your man page if you don't have it). See https://linux.die.net/man/1/ls

**Comment by kamektx** [comment]
I reverted --lcontext and --scontext options. 
Thank you for letting me know!

**Comment by faho** [comment]
Merged, thanks!

**Pull request merged**
