### PR TITLE
Improved french translations; minor completion corrections

### PR DESCRIPTION
**Pull request by PenegalECI**
## Description

Hello, there.

This PR, as the title says, globally improves the french translations for fish, and a bit more : 
* it adds translations;
* it improves much pre-existant fuzzy ones, and drops some when they are clearly saying something completely different from the english string, but I was unable to correctly translate them – I did that to prevent confusing users, as this way it will show them the english text instead of a completely aberrant french text, but I did not drop them when it was not crystal clear for me that the translation was aberrant;
* it corrects some completions, mainly typos; _please note that `.po` files are now out of sync with the code and will need to be re-synced_, but I don't know how to do that, nor how to make it keep existing translations, so, instead of messing with the code, I prefer letting someone with the required knowledge to do it;
* it adds translation guidelines for other french translators, to help keeping the whole translations coherent;
* it tries to harmonize multiple versions of the same message, the archetype being messages like _display help_, _display help then quit_, _displays a help message_…

I went through the whole file multiple times to be sure that the current translations are roughly consistent, but there are probably some errors left.

Note: I first opened PR #4464 for this, but there were a Travis build failure and numerous useless commits, but I finally find a way to correct both.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by PenegalECI** [comment]
Merged resolution of conflicts for completions of tar and apt-listchanges.

**Comment by floam** [comment]
It would be better if you could regenerate things yourself as part of this PR and test it. Let us know if you need instruction.

**Comment by PenegalECI** [comment]
@floam, were you able to write these instructions?

**Comment by PenegalECI** [comment]
@floam, nevermind, I was able to regenerate them alone. I might add it was about time, given the diff on them.

**Comment by PenegalECI** [comment]
Travis builds fail on segfaults. I did not change the code, apart of some minor corrections on completions, so I don't think this comes from my work. What should I do now?

**Comment by zanchey** [comment]
The macOS build doesn't use translations, so that might be why it passes.

Crash is here:

```
Thread 1 (Thread 0x559b9dc0 (LWP 11511)):
#0  0x558b2264 in ?? () from /lib32/libc.so.6
#1  0x55865baf in vfwprintf () from /lib32/libc.so.6
#2  0x559080a3 in __vswprintf_chk () from /lib32/libc.so.6
#3  0x080bce69 in vswprintf (__ap=0xffec72dc "^", 
    __fmt=0x8274474 L"%ls: “%ls” is not a valid variable name", __n=256, 
    __s=0xffec6e30 L"") at /usr/include/bits/wchar2.h:320
#4  append_formatv (target=L"", 
    format=format@entry=0x8274474 L"%ls: “%ls” is not a valid variable name", va_orig=va_orig@entry=0xffec72dc "^") at src/common.cpp:443
#5  0x080bcf47 in vformat_string (
    format=format@entry=0x8274474 L"%ls: “%ls” is not a valid variable name", va_orig=va_orig@entry=0xffec72dc "^") at src/common.cpp:458
#6  0x0812d30d in append_syntax_error (errors=errors@entry=0xffec73f4, 
    source_location=source_location@entry=6, 
    fmt=0x8274474 L"%ls: “%ls” is not a valid variable name")
    at src/parse_util.cpp:744
#7  0x0812d54f in parse_util_expand_variable_error (token=L"\xfdd2^", 
    global_token_pos=5, dollar_pos=0, errors=0xffec73f4)
    at src/parse_util.cpp:898
#8  0x0812e134 in parse_util_detect_errors_in_argument (node=..., 
    arg_src=L"$^", out_errors=out_errors@entry=0xffec73f4)
    at src/parse_util.cpp:1035
#9  0x0812e95a in parse_util_detect_errors (buff_src=L"echo $^", 
    out_errors=out_errors@entry=0xffec7450, 
    allow_incomplete=allow_incomplete@entry=false, out_tree=out_tree@entry=0x0)
    at src/parse_util.cpp:1116
#10 0x081647dd in test_error_messages () at src/fish_tests.cpp:3621
#11 0x08083453 in main (argc=1, argv=0xffec8b94) at src/fish_tests.cpp:4363
```

**Comment by PenegalECI** [comment]
Now there is another one:
```
==11680==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000005e (pc 0x2b751a2a9820 bp 0x7ffdc88aa440 sp 0x7ffdc88a9288 T0)
    #0 0x2b751a2a981f  (/lib/x86_64-linux-gnu/libc.so.6+0xa581f)
    #1 0x2b751a267f47 in vfwprintf (/lib/x86_64-linux-gnu/libc.so.6+0x63f47)
    #2 0x2b751a277ce5 in vswprintf (/lib/x86_64-linux-gnu/libc.so.6+0x73ce5)
    #3 0x5e39dc in append_formatv(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, wchar_t const*, __va_list_tag*) /home/travis/build/fish-shell/fish-shell/src/common.cpp:443:18
    #4 0x5e3734 in vformat_string(wchar_t const*, __va_list_tag*) /home/travis/build/fish-shell/fish-shell/src/common.cpp:458:5
    #5 0x757b3b in append_syntax_error(std::vector<parse_error_t, std::allocator<parse_error_t> >*, unsigned long, wchar_t const*, ...) /home/travis/build/fish-shell/fish-shell/src/parse_util.cpp:744:18
    #6 0x756448 in parse_util_expand_variable_error(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, unsigned long, unsigned long, std::vector<parse_error_t, std::allocator<parse_error_t> >*) /home/travis/build/fish-shell/fish-shell/src/parse_util.cpp:898:13
    #7 0x75a06b in parse_util_detect_errors_in_argument(parse_node_t const&, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<parse_error_t, std::allocator<parse_error_t> >*) /home/travis/build/fish-shell/fish-shell/src/parse_util.cpp:1034:17
    #8 0x75b425 in parse_util_detect_errors(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<parse_error_t, std::allocator<parse_error_t> >*, bool, parse_node_tree_t*) /home/travis/build/fish-shell/fish-shell/src/parse_util.cpp:1116:24
    #9 0x80231f in test_error_messages() /home/travis/build/fish-shell/fish-shell/src/fish_tests.cpp:3621:9
    #10 0x80231f in main /home/travis/build/fish-shell/fish-shell/src/fish_tests.cpp:4363
    #11 0x2b751a225f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
    #12 0x45d88b in _start (/home/travis/build/fish-shell/fish-shell/fish_tests+0x45d88b)
```

I tried to look at the functions involved but did not understand what the matter is, though my C(++) level is only a bit above zero. Does someone understand how translations could cause that?

**Comment by zanchey** [comment]
Usually the problem is that the translation doesn't match the message ID in terms of field formatting eg the original string is `Something %ls does not match something else %ls` but the translation reads `Something %ls is not right`. When the message gets formatted the missing field causes a crash.

I am suspicious of the following in `po/en.po`:

```gettext
#: src/parse_constants.h:262
#, fuzzy, c-format
msgid "$%lc is not a valid variable in fish."
msgstr "%ls: “%ls” is not a valid variable name"
```

But fuzzy-formatted fields shouldn't get compiled in as translations.

**Comment by PenegalECI** [comment]
Ah, damn these fuzzy translations! From it, I only got crappy translations, and now this… I'll check the translations for these mismatches.

**Comment by PenegalECI** [comment]
At last, it passed the builds! Are some additional corrections neede, or can it be merged?

**Comment by PenegalECI** [comment]
No activity for 3 days? What's happening, guys?

**Comment by PenegalECI** [comment]
Is there a problem with the PR? Are you busy reviewing it?

**Comment by faho** [comment]
I'm terribly sorry for the delay, it seems we've all been busy.

I've merged it now, thank you very much for your work!

**Comment by PenegalECI** [comment]
@faho: Oh, don't be that sorry; I was only wondering if there was something happening, as fish is usually a very active project. Thanks anyway for the merge.

**Pull request merged**
