### PR TITLE
move __fish_complete_svn_diff into the completion script

### PR DESCRIPTION
**Pull request by ammgws**
## Description

One of the tasks from #5279.

It was commented out in the svn completion script because it was not working at some stage, but it has been reported that it works now, so adding it.

### CODE REVIEW

**Comment by faho** [comment]
This is commented out because "-x" didn't actually do what it was supposed to.

It has since been fixed, so it should actually be alright to turn it on again.

**Comment by ammgws** [comment]
I can't personally test it, but I'll take your word for it. Re-added.

**Comment by ammgws** [comment]
Hmm cannot seem to resolve these merge conflicts ...

**Comment by faho** [comment]
Merged this, along with most of your cleanup PRs. Thanks!

**Pull request merged**
