### PR TITLE
(WIP) Remove dependencies and use std ones instead

### PR DESCRIPTION
**Pull request by InfyniteHeap**
## Description

Some of containers, like `Lazy` and `OnceCell` which are provided by third-party crate `once_cell`, have their equivalent implementation in standard library: `LazyLock` and `OnceLock`.

Use std rather than third-party crates seems better because std can provide safer and more stable implementations.

The only thing that should be noticed is that the MSRV will be `1.80.0`, because it was this version that first introduced `LazyLock` in std.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
> The only thing that should be noticed is that the MSRV will be 1.80.0, because it was this version that first introduced LazyLock in std.

That's a NAK.

**Comment by InfyniteHeap** [comment]
> > The only thing that should be noticed is that the MSRV will be 1.80.0, because it was this version that first introduced LazyLock in std.
> 
> That's a NAK.
> 
> We do not want to increase MSRV at this time.
> 
> I'm sorry that you've invested all this work, but that's something you should have asked about before.
> 
> If you want to replace lazy_static *with* once_cell or vice-versa that would be cool.

Ok, I got it. But can I try fixing the `Arc<RefCell<T>>` in `src/env/environment_impl.rs`?

I read the comments above this struct, but I still think this exists a vulnerability about thread safety. `lazy_static!` seems cannot provide the safety guarantee, yet it seems helped this struct to avoid from thread-safe checking. In my view, it can be replaced with `Arc<RwLock<T>>`. What do you think?☺️

**Comment by faho** [comment]
>Ok, I got it. But can I try fixing the Arc<RefCell<T>> in src/env/environment_impl.rs?

If you can do that without increasing MSRV, sure.

If you want to add another dependency, I would suggest asking about that first.

**Comment by InfyniteHeap** [comment]
> >Ok, I got it. But can I try fixing the Arc<RefCell<T>> in src/env/environment_impl.rs?
> 
> If you can do that without increasing MSRV, sure.
> 
> If you want to add another dependency, I would suggest asking about that first.

Ok, I got it!

**Pull request closed without merging**
