### PR TITLE
set does not need -x for PATH

### PR DESCRIPTION
**Pull request by nhooyr**

### CODE REVIEW

**Comment by krader1961** [comment]
Thanks for contributing but we're not going to merge this. Using `-x` doesn't cause any problems if PATH is already exported and is needed if for some reason it wasn't in the environment when fish was started. It's also almost always better to be explicit in such situations about what is intended.

**Comment by nhooyr** [comment]
But in other parts of the docs, $PATH is set without -x? Perhaps those should be updated?

**Comment by krader1961** [comment]
> But in other parts of the docs, $PATH is set without -x? Perhaps those should be updated? 

It depends on the context but, yes, in general environment vars should always be set with the -x option even when that might be redundant.

**Comment by nhooyr** [comment]
@krader1961 then can I create a new PR for that?

**Comment by krader1961** [comment]
Sure but no guarantee it will be merged since, as I said, the context matters. I can't think of a good example off the top of my head but it's conceivable there is an example in our code that doesn't use `-x` when setting an env var where not doing so is safe and unambiguous.

**Comment by nhooyr** [comment]
Ah, turns out they were interactive examples, not `config.fish` examples. However, right here https://fishshell.com/docs/current/tutorial.html#tut_lists it should probably be specified that if you set it in `config.fish`, you should use `-x`.

Also, here it is not specified https://fishshell.com/docs/current/index.html#initialization but it is with`config.fish`. Does being a login shell matter?

**Comment by krader1961** [comment]
> Does being a login shell matter?

Not for the example you linked to. That one should include the `-x` in my opinion. On the other hand the tutorial example you linked to probably shouldn't have the `-x` flag added. That's because the focus there is on dealing with the path as an array of pathnames and presupposes you've already exported it. So, like I said earlier, context matters.

**Comment by nhooyr** [comment]
Ok, I'll update this PR to modify the docs for the login shell example.

**Pull request closed without merging**
