### PR TITLE
Search for addition known_host files

### PR DESCRIPTION
**Pull request by sysbot**
User have the ability to specify additional host files via UserKnownHostFile directive in .ssh/config. This patch will search for them and include them in the known hostnames.

### CODE REVIEW

**Comment by faho** [comment]
@sysbot: Ping?

**Comment by faho** [comment]
I'm closing this for now. If you're back again, please answer the last question (is "known_hosts**2**" automatically valid if "known_hosts" is) and we'll see if we can get this merged.

**Comment by zanchey** [comment]
The answer is no, but I think we can merge this with that expansion removed.

**Comment by krader1961** [comment]
@zanchey and @sysbot: I don't have any objection to the general idea but this is now failing unit tests. It could also be improved considerably since constructs like `grep ... | awk` and `grep ... | sed` can almost always be rewritten to omit the grep pipeline since both awk and sed support selecting lines that match a regex. Too, the `egrep` and `sgrep` invocations should be replaced by `__fish_sgrep` (assuming the grep pipelines are even necessary).

If no one is going to follow through on updating this to a state where it can be merged I recommend opening an enhancement issue so we don't lose track of a good idea and closing this PR.

**Comment by faho** [comment]
I'm sorry, this won't work - it's reading a file called "config" while not necessarily in the .ssh directory. All options you pass to egrep here are unnecessary, the sgrep should be __fish_sgrep (if at all) and string is nicer for this.

I'll take a crack at implementing this, but as-is this won't be merged. Sorry.

**Pull request closed without merging**
