### PR TITLE
fix flakey test

### PR DESCRIPTION
**Pull request by krader1961**
I've run this more than twenty times through Travis CI (by adding/removing
a comment line). Without this tweak the longest sequence seems to be
around six successful runs.

### CODE REVIEW

**Comment by krader1961** [comment]
And, of course, as soon as I decide the test is robust and create a pull-request Travis fails the exact same test, again. Let's see if doubling the problematic escape delay makes this reliable....

P.S., I really wish we could gain more insight into the Travis CI test environment. I've never seen this fail on either my OS X or Ubuntu machines. Even when using ASAN and overloading the system with lots of CPU bound processes.

**Comment by krader1961** [comment]
This is now passing reliably in my branch and I believe is ready to merge.

**Comment by faho** [comment]
@krader1961: There's two new tests in there - could you split them out into a separate commit?

**Comment by krader1961** [comment]
Sure, but they're just validating, in a more direct fashion, that the timeout var is set to the expected value. In trying to make this test pass reliably I was starting to wonder if that was true. Those lines really should have been in my original change that introduced the var.

**Comment by ridiculousfish** [comment]
Merged with rebase as 83d3c9fc04f9f9f4b0868e4d348b47a205530d19 - thanks!

**Pull request closed without merging**
