### PR TITLE
More concise way of getting the hostname.

### PR DESCRIPTION
**Pull request by mwfogleman**

### CODE REVIEW

**Comment by faho** [comment]
Humm... seems to be supported by GNU hostname (from inetutils) and [OSX hostname](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/hostname.1.html), which seems to be the same as [FreeBSD hostname](http://www.unix.com/man-page/freebsd/1/hostname/).

How about the other prompts? This seems to already be done in lonetwin, user_host_path and terlar, while the `cut` is present in screen_savvy, classic, informative, debian_chroot, pythonista, classic_git and classic_status. nim and sorin both seem to just print the full hostname.

Mind adjusting these too (including the last two, I'm betting that's an oversight, not actually a design decision)? They are in share/tools/web_config/sample_prompts/.

**Comment by faho** [comment]
I can't find the cygwin man pages - @andrex-e-schulman: Is "-s" supported in cygwin's `hostname`?

**Comment by zanchey** [comment]
It's supported in Cygwin, but not on Solaris. The POSIX standard is `uname -n` instead.

**Comment by faho** [comment]
Oh, GNU hostname also seems to fail here - mine prints "localhost" with "-s", but "fordprefect" (i.e. the actual hostname) without it. `uname -n` works.

@zanchey: We support Solaris? I did not know that.

**Comment by zanchey** [comment]
We don't not support Solaris, if that makes any sense. Unfortunately my Solaris VMs keep exploding in showers of `SUNWfoo`.

**Comment by andrex-e-schulman** [comment]
In Cygwin, both `uname -n` and `hostname -s` are supported and give the same result.  Both come from required packages (coreutils and hostname, respectively) so will always be present in a non-broken installation.  I guess it's a toss-up which one to use.

**Comment by mwfogleman** [comment]
Faho, is this what you were asking for?

I'm pretty new to the project and much of the above commentary and the tests are opaque.

I realize this is a yak shave so no worries if it is deemed unnecessary or harmful.

**Comment by faho** [comment]
@mwfogleman: Yes, except s/hostname -s/uname -n/g, as per the discussion above.

**Comment by mwfogleman** [comment]
On my machine, uname -n gives me the same as hostname without the -s option.

**Comment by faho** [comment]
On mine it behaves better - `hostname -s` prints "localhost", ´uname -n` prints the actual hostname.

**Comment by zanchey** [comment]
Merged with squash as 233c443 - thank you!

**Comment by mwfogleman** [comment]
Will this work on all systems? I am pretty sure it won't work on mine. It may be worth reverting this.

**Comment by zanchey** [comment]
What system are you running? I didn't read your reply closely enough - my apologies.

**Comment by mwfogleman** [comment]
Darwin / OS X El Capitan. uname -n would be too verbose for the prompts - it gives the whole network setup.

**Comment by faho** [comment]
In that case, `uname -n` doesn't work on one system, `hostname -s` doesn't on another, so we should back this out completely.

**Comment by mwfogleman** [comment]
Precisely. Sorry for submitting a regression! :)

**Comment by zanchey** [comment]
Yes - I hadn't tried it on my OS X system. I'll revert it.

**Comment by zanchey** [comment]
Reverted as b776327. Sorry!

**Comment by faho** [comment]
One possibility to cut the `cut` calls is to introduce our own function that does either `hostname -s` or `uname -n` depending on the OS. We could even check `uname` once on startup and set a $OS variable or so - it's unlikely to change at run-time (or even after build-time, for that matter).

**Pull request closed without merging**
