### PR TITLE
Rewrite __fish_complete_cd

### PR DESCRIPTION
**Pull request by faho**
This no longer uses "eval" (which is scary), and is a bit shorter (which
is nice).

I'd appreciate testing since there's bound to be a ton of edge-cases.

Sorry for the noise, I'll throw pillows at myself for the appropriate amount of time, as soon as I can figure out how to do that (maybe that's what selfie-sticks are good for?).

### CODE REVIEW

**Comment by lledey** [comment]
`realpath` is not available on OS X so it just throws an error, and there is apparently no easy way I could find to reproduce the behavior, except maybe make it a builtin (bash seems to have a `realpath` module but not included by default).

**Comment by faho** [comment]
Hmm... I think in this particular case (`realpath .`), we should just be able to get away with replacing it with "$PWD" (as I've already done further down), since fish sanitizes that anyway - or is there anything I'm missing?

**Comment by lledey** [comment]
If "$PWD" is sanitized and trustworthy it should not make any difference I think.

**Comment by faho** [comment]
Anyone to test this, particularly on OSX?

It fixes #2299 and probably part of #2300, so I'd like to merge it.

**Comment by lledey** [comment]
I personally haven't found any issue with this on OS X, but I only used it in "classic" cases so maybe you should get feedback from other people too.

**Comment by ridiculousfish** [comment]
I'll be glad to review it (once I'm done with the strings mega-patch!)

**Comment by faho** [comment]
Oh, this would also fix (the cd-part of) #562 - as I said in #2300, there seems to be a more general part of the problem, since selecting from the menu works, while directly entering (e.g.) "/tmp/[" and pressing TAB will complete, but not escape the "[".

**Comment by faho** [comment]
@ridiculousfish: Ping? I've been using this since I proposed it and haven't stumbled over any more bugs, but I'd rather have someone check it because there could be a ton of edgecases.

**Comment by ridiculousfish** [comment]
Assigning to myself to remember to review it.

**Comment by faho** [comment]
The merge conflict is because of the sgrep thing, btw.

**Comment by faho** [comment]
@ridiculousfish: Ping?

**Comment by ridiculousfish** [comment]
Sorry for the delay...I added one more comment. I think it should be good to go after addressing that.

**Comment by faho** [comment]
Squashed rebase merge as 0a99772572ab8632f103f05570da707683980d17.

I've tried listing all the bugs this fixes or improves, but I'm not sure I caught them all.

Thanks for the review!

**Comment by ridiculousfish** [comment]
This is a sweet fix. Thanks for taking it on!

**Pull request closed without merging**
