### PR TITLE
actually fix #1435

### LINKED ISSUE #1435: Vi key bindings don't work when set in config.fish
Steps to reproduce:
1. Add the line `fish_vi_key_bindings` to `~/.config/fish/config.fish`.
2. Open fish. The shell won't respond to any keys (including <kbd>i</kbd>, <kbd>a</kbd>, etc.), so I can't type anything into the prompt.

The key bindings work as expected when I open the shell without this line in my config, and instead call `fish_vi_key_bindings` in the shell.

### PR DESCRIPTION
**Pull request by despairblue**
As far as I can see, the only mention of this is in https://github.com/fish-shell/fish-shell/issues/1435.

Just thought it should be in the docs.

### CODE REVIEW

**Comment by faho** [comment]
The current suggestion - `fish_vi_mode` - will work and also enable the vi-mode indicators, so it's better than creating a fish_user_key_bindings function, so this isn't necessary.

**Comment by faho** [comment]
Okay, the fish_vi_mode docs mention fish_vi_mode, but the main ones (index.hdr.in) don't - they suggest `fish_vi_key_bindings`. The issue here is that if you use f_v_m, you can't easily switch back (or rather you can, but then you need to erase the indicator variable as well), so for temporarily switching, f_v_k_b is indeed the easier choice.

So, in other words, we need a `fish_emacs_mode` function to get out of vi-mode.

**Comment by despairblue** [comment]
Ah, haven't noticed that `fish_vi_key_bindings` and `fish_vi_mode` are two different strings. I should read past the second word in a variable 😄 

Then I actually meant to add a reference in [index.hdr.in](https://github.com/fish-shell/fish-shell/blob/master/doc_src/index.hdr.in) to [fish_vi_mode.txt](https://github.com/fish-shell/fish-shell/blob/master/doc_src%2Ffish_vi_mode.txt), since I was actually reading the `command line editor` section and couldn't figure out how to enable the vi mode for all instances. I tried adding `fish_vi_key_bindings` to config.fish and in the end had to google to find a solution. I think a link there would make it easier for other people who read the docs and prefere the vi bindings.

Is cross referencing supported? Should I open another PR?

**Comment by faho** [comment]
@despairblue: I'm working on fixing this (by nixing/neutering fish_vi_mode and making `fish_vi_key_bindings` the preferred way to switch) in #2918. At that point adding to the docs seems superfluous.

**Comment by despairblue** [comment]
awesome, got it.

**Pull request closed without merging**
