### PR TITLE
Use svg instead of png to get better image quality

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by xfix** [comment]
Merged with rebase, b31305b..3c0902b. Thank you for contributing to the fish shell :+1:.

**Comment by zanchey** [comment]
We were discussing this in #1775 - it actually looked worse on my system, although now I can't tell the difference!

**Comment by PeterDaveHello** [comment]
Screenshot?

**Comment by zanchey** [comment]
They're now virtually identical; something in the Chrome renderer must have improved between 38 and 39.

**Comment by PeterDaveHello** [comment]
that's fine

**Pull request closed without merging**
