### PR TITLE
cmake: import corrosion as an in-tree dependency

### PR DESCRIPTION
**Pull request by zanchey**
Importing corrosion into the tree makes running the build on package builders a
lot more straightforward, and since we're not planning to do a release with it,
it never needs to be shipped in an official tarball.

### CODE REVIEW

**Comment by zanchey** [comment]
This does slow down the CMake portion of the build a bit.

**Comment by krobelus** [comment]
> This does slow down the CMake portion of the build a bit.

not for incremental builds, right?

**Comment by zanchey** [comment]
> > This does slow down the CMake portion of the build a bit.
> 
> not for incremental builds, right?

Correct, only when CMake needs to regenerate (and there's some commentary about this not applying to CMake 3.19).

The alternative is to package corrosion for our use, which might not be too hard.

**Comment by mqudsi** [comment]
I hate (working with) git submodules with a passion but I wonder if this might not be a good candidate for that, especially if it's short-term? It'll prevent polluting the main repo history and avoid bloating its size (but I checked and this barely registers, has no huge binaries, etc.)

**Comment by zanchey** [comment]
I think I can come up with an alternative solution.

**Pull request closed without merging**
