### PR TITLE
curses: Just use our hardcoded xterm-256color entry as the fallback

### PR DESCRIPTION
**Pull request by faho**
The values we would try are:

xterm-256color, xterm, ansi, dumb

This is a pretty useless list, because systems without "xterm-256color" but with "ansi" basically don't exist, and it is very likely that the actual terminal is more xterm-compatible than it is ansi.

So instead we just use our xterm-256color definition, which has a high likelihood of being basically correct.

### CODE REVIEW

**Comment by faho** [comment]
I am *this close* to just ditching any and all reading of the terminfo database.

I have [a script](https://gist.github.com/faho/db2d7630a6d25492245c2340858c22de) that tries to figure out how different terminfo entries actually are, and the answer is they barely are.

The trick is that you need to filter out a lot of entries - those for 1980s hardware terminals and those invented by ncurses (as well as various variants that just repeat the same information).

E.g. there is an "ms-terminal" entry for Microsoft's terminal, which is useless because that terminal uses xterm-256color and to a first approximation *nobody* sets $TERM (nor should they). It is also just flat out incorrect in some ways, like claiming that "cursor_down" is `\E[B`. It isn't, it behaves like xterm.

Or the tmux entry which claims that exit_attribute_mode is `\E[m^O` when the xterm sequence just works. Or the rxvt entry, which *does* have some legitimate differences in terms of keys, but also has the two parts of exit_attribute_mode swapped - which is not a functional difference.

I am extremely disillusioned with the entire terminfo system and would like to get away from it.

**Comment by krobelus** [comment]
Agreed, thanks.

terminfo seems like a needless indirection; instead of standardizing a terminfo sequence-name it's easier to standardize the actual escape-sequences, because that one needs to exist regardless.

I don't know much about this; if there is a chance a user wants to keep terminfo for now (as workaround), we could start with an `ignore-terminfo` feature flag? I guess we might find that when we turn it on, things will already work better on average across the userbase, since we'll no longer read wrongly configured values. It's probably fine to change it on `master`, as a trial balloon

**Review by krobelus — APPROVED** [review]

**Comment by zanchey** [comment]
> I have [a script](https://gist.github.com/faho/db2d7630a6d25492245c2340858c22de) that tries to figure out how different terminfo entries actually are, and the answer is they barely are.

kitty is the only modern terminal I know of that maintains a terminfo.

**Comment by krobelus** [comment]
I think foot too, and both support querying terminfo capabilites via `XTGETTCAP`.
Querying the terminal directly instead of reading a terminfo file seems like the best approach.

**Pull request merged**
