### PR TITLE
Restore and save colors

### PR DESCRIPTION
**Pull request by terlar**
It would be nice to have the option to save and restore colors. This is
my first attempt at this. The default saved `fish_load_colors` is the
output of the `fish_save_colors` on a clean environment running fish.

Any ideas or suggestions to improve on this or is it good enough and a
feature we want?

### CODE REVIEW

**Comment by maxnordlund** [comment]
I actually wrote something like this not to long ago, to sync my color theme between work and home. It does it slightly differently though. In my case it is always save to the same file (in my dotfiles repo).

https://github.com/maxnordlund/dotfiles/blob/master/fish/functions/theme.fish

**Comment by faho** [comment]
@maxnordlund: You're actually missing fish_pager_color*. I'd do something like 

```fish
set -n | string match "fish*_color_*" | while read  color; echo "set -U $color $$color"; end
```

(or use grep if you're not using git fish).

The important things being that you get the pager colors as well and that you don't have worry about variables containing "color" as part of a value, including history.

**Comment by faho** [comment]
Thinking more about this, this can be done without having to resort to `source` or `eval`.

```fish
function export_color
	set -l file ~/.config/fish/theme
	if set -q argv[1]
		set file $argv[1]
	end
	set -n | string match "fish*_color_*" | while read color
		echo $color $$color > $file
	end
end

function import_color
	for file in $argv
		while read var value; echo "set $var to $value"; end < $file
	end
end
```

**Comment by maxnordlund** [comment]
Darn it, I knew I missed something. Thanks for the heads up @faho

**Comment by krader1961** [comment]
I recommend this PR be closed without merging. The core issue is that universal vars are not in fact universal since they are based on a "machine ID". See issue #1912. The solution is to support truly universal vars.

**Comment by pickfire** [comment]
What about resetting the colors that I have set?

**Comment by faho** [comment]
@krader1961: The UVar thing is but one facet of this. However the rest of it isn't as complete as I'd like either - full theme support would need a bit more:

- A way to add themes to the theme picker in fish_config

- A way to name themes

- A way to save themes (which something like this could be used for, but not this exactly - basically `funcsave` for themes)

This is too stop-gappy for my taste (and can be trivially added locally), so I'm rejecting this PR. Sorry it's taken so long.

**Pull request closed without merging**
