### PR TITLE
implement `mcd` command

### LINKED ISSUE #2847: add a "mcd" (menu change directory) command
I've never liked the prevd/nextd model for navigating my cd history. And the pushd/popd model, while easier to reason about, is quite limiting. So long ago I wrote a `mcd` (menu change directory) function for ksh (Korn shell).  When I switched to zsh a few years ago I ported that function. Now that I'm using fish full-time I decided it was time to write a fish version of `mcd`. I'm opening this issue to see if enough people think it is useful enough to be included in the standard fish package.

Below is the function. You can put this in _~/.config/fish/functions/mcd.fish_ to autoload it or put it in another file and explicitly source it. Here is an example of what it looks like:

screenshot 2016-03-22 18 47 19

Notice that this can also effectively replace the `dirh` command since, if you just press [enter] or [ctrl-D] at the prompt, it does nothing other than show you your recent `cd` history.

_I've removed the first version of the function that was in my original post. It's been replaced by the updated version in the attachment below._

### PR DESCRIPTION
**Pull request by krader1961**
Fixes #2847

This implements a menu based change directory command having both modal and modeless behaviors.

### CODE REVIEW

**Comment by MrHalfman** [comment]
Warning: mcd is a command that already exists on many linux distributions. This change may have unexpected side effects.

Maybe you will have to consider using another name for this command?

**Comment by faho** [comment]
>mcd is a command that already exists on many linux distributions

The "mcd" I can find is part of the "mtools" package, a "collection of utilities to access MS-DOS disks from GNU and Unix without mounting them". It's used to change the "MSDOS directory".

Personally, I don't see why this is useful (why wouldn't you just mount it and use the normal utilities?), but it's nice not to trample over other utilities' names.

`fcd` (for "fast cd" or "fish cd") seems to be free.

**Comment by faho** [comment]
Or "scd" for "select cd".

**Comment by krader1961** [comment]
Okay, I'd prefer not to have all the characters in the command name typed by the same hand so I'll change it to `cdh`. Googling `cdh command` didn't find any commands by that name.

**Comment by krader1961** [comment]
Merged as 8cc4639ea6 after renaming it to `cdh` and adding some documentation.

**Comment by LindyBalboa** [comment]
Hi. First thanks for the work. Looks nice and native for fish. I'm curious though, how does this feature stack up against fasd and z?

**Comment by faho** [comment]
@LindyBalboa: This is so simple that it isn't really competing with fasd and z. It's literally just reading a number to select a previously visited (in that session) directory. There's no "real" menu that you can navigate with your keys, there's no persistent history, there's no "frecency". It's just a nice and simple thing that you can use if you want, or completely ignore.

**Pull request closed without merging**
