### PR TITLE
Allow restricting abbreviations to specific commands

### LINKED ISSUE #9411: abbr: Allow restricting to a specific command's arguments
This is very much a nice-to-have, it does not need to be in the initial release with "Mega abbr".

One of the examples in #9313:

```fish
function git_c
    string match --quiet 'git c ' -- (commandline -j); or return 1
    echo checkout
end
abbr -a git_c --position anywhere --regex c --function git_c
```

This is supposed to allow adding abbreviations for git subcommands. It would be cool if this could be

```fish
abbr --add --commmand git c checkout
```

Which allows us to save the regex, makes for easier and more correct matching and allows arbitrary transformations with arbitrary regexen without marking everything as not-an-error.

(Currently `abbr hahaha --regex '.*' --function false` will cause commands to always be marked as valid because the regex matches and it can't know that the function would fail. This is probably correct - I don't think we can run the function before and marking things as invalid even tho they could still match an abbr feels weird?)

Note that this would always be restricted to a command *argument* - because otherwise the command won't match. I don't think we need to add `--position argument` or require `--position anywhere` just for this. I also don't think we'd need to walk a command's wrap chain (i.e. `function g; git $argv; end` would need to have the abbrs specified again).

### PR DESCRIPTION
**Pull request by faho**
## Description

This allows defining abbreviations that are only triggered when the current command matches, so you can define

```fish
abbr --add --commmand git c checkout
```

Which turns `c` into `checkout` but only for `git`. This can also be combined with `--function`, expanding a git *subcommand*, replacing git aliases, would be something like

```fish
function git_checkout
    set -l opts version h/help C= c=+ 'exec-path=?' html-path man-path info-path p/paginate \
        P/no-pager no-replace-objects bare git-dir= work-tree= namespace= super-prefix= \
        literal-pathspecs glob-pathspecs noglob-pathspecs icase-pathspecs
    # skip command and abbr token
    set -l toks (commandline -xpc)[2..-2]
    argparse $opts -- $toks 2>/dev/null
    or return

    set -q argv[1]
    and return 1

    echo checkout
    return 0
end

abbr --command=git co --function git_checkout
```

(because, as always, options are complicated!)

One limitation of the current implementation is that the command is *not* part of the abbr "ID", the "name" still needs to be unique across commands.

I believe that's acceptable for now, the available workaround is `--regex`, and this could be lifted in future. For a specific abbr to be used with multiple commands you can specify `--command` multiple times and any of these will be allowed (including an empty command, indicating the command position).

Also parsing the command out could be made easier by additional options to `commandline` - `--current-command` and `--current-arguments` (for everything *after* the command).

And the function could be made more useful if you could pass arguments, so you can do multiple git aliases easily without writing a function for each - `abbr --command git co --function 'git_alias checkout'`. But that's out of scope for this issue.

Fixes #9411 
Previous attempt at #9412 

## TODOs:

- [x] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm awaiting this for years 🤩👍

**Comment by ccoVeille** [comment]
Thanks again for this PR. It would make things so easier.

> One limitation of the current implementation is that the command is not part of the abbr \"ID\", the \"name\" still needs to be unique across commands.

What are the next steps? About these limitations? Do you have plan? Is there an opened issue about it?

Thanks

**Comment by faho** [comment]
> What are the next steps? About these limitations? Do you have plan? Is there an opened issue about it?

Let's first ship this and see how it works out.

The "limitations" here are idle musings, there's no need to open an issue about them. If it ends up being a common problem, we can handle it then.

**Comment by g0t4** [comment]
I assume this isn't intended to work with nested subcommands? 

i.e.:
```shell
docker compose d<TAB>
docker image p<TAB>
```

**Comment by faho** [comment]
Correct. The shell cannot determine what is a subcommand and what isn't. E.g. in `git -C log merge`, the "merge" is the subcommand, while in `git -P log merge` it's "log".

You'll have to write a function that knows `docker`.

**Pull request merged**
