### PR TITLE
allow the history file to be configurable

### LINKED ISSUE #102: Allow history file name customization
To have separate histories when using e.g. screen or logging in to a machine via multiple sessions, it should be possible to customize the history file name, for example using an environment variable. See https://github.com/ekoeppen/fish-shell/commit/ccfac2cfb9ccea02d71420968214b6f16db76bc4 for a possible implementation.

### PR DESCRIPTION
**Pull request by krader1961**
Introduce a HISTFILE variable in the same vein as bash and zsh to allow the user to specify where interactive commands are logged. The default file name is unchanged.

Resolves #102.

### CODE REVIEW

**Comment by jrobeson** [comment]
and now everybody is happy! :)

**Comment by ridiculousfish** [comment]
Also, you're supposed to be able to set a custom history filename via `read -m`, though I don't think that feature is very useful.

But I think the most important consequence is that anyone who uses `HISTFILE` in bash or zsh, and then invokes fish, will find that their history has been stomped into an incompatible fishy format. That's very serious, and for that reason (if we do this) we ought to use a variable name other than HISTFILE.

**Comment by faho** [comment]
>But the most important consequence is that anyone who uses HISTFILE in bash or zsh, and then invokes fish, will find that their bash/zsh history has been stomped into an incompatible fishy format. That's very serious, and for that reason (if we do this) we ought to use a variable name other than HISTFILE.

How about just clearing the variable on start, before we ever write history?

**Comment by ridiculousfish** [comment]
@faho You mean don't inherit it from the environment?

**Comment by faho** [comment]
Well, basically, yeah. Exporting HISTFILE is a mostly wrong thing to do.

Of course it'd also be possible to just call it FISH_HISTFILE or FISH_HISTORY_FILE.

**Comment by ridiculousfish** [comment]
I guess we're also vulnerable to the reverse problem, where exporting HISTFILE from fish, and then invoking bash, would cause bash to stomp our history.

**Comment by faho** [comment]
So a different name it is!

**Comment by floam** [comment]
How do ZSH/Bash avoid hurting each-other? They often have compatible formats but easily don't if either is storing the timestamps.

**Comment by krader1961** [comment]
> How do zsh/bash avoid hurting each other? 

Well, I imagine for the most part zsh users don't invoke interactive bash shells and vice-versa. Too, 99.9% of users never set HISTFILE. 

> Well, basically, yeah. Exporting HISTFILE is a mostly wrong thing to do.

Except that I can easily imagine someone who uses this feature wanting to export HISTFILE before launching a bunch of related interactive shells. Perhaps they have a need to partition some of their work for security reasons.

> ... we ought to use a variable name other than HISTFILE.

In retrospect I agree. I was overly discounting the likelihood of someone who might be transitioning from bash/zsh to fish exporting HISTFILE then invoking an interactive fish from one of those shells. Too, in general we should always be using a *FISH_* or "fish_" prefix (optionally with a leading underscore) to minimize clashes except where interoperability is required or useful (e.g., PATH).

**Comment by faho** [comment]
>Too, 99.9% of users never set HISTFILE. 

And even if they do, they may not read it, while fish tends to expose history more (suggestions and our default history-search bindings). Or if they do, they customize it in both.

>Too, in general we should always be using a FISH_ or "fish_" prefix (optionally with a leading underscore) to minimize clashes except where interoperability is required or useful (e.g., PATH).

Yes, though while we're bike-shedding, I'd like it if we could only use the leading underscore (or "dunderscore" for a doubled one in python-speak) for private things the user isn't expected to alter. This wouldn't be one as it's an explicit customization point.

My favorite would therefore be "fish_history_file" - more verbose than "HISTFILE", but less screaming and consistent with our other variable names ("fish_function_path"). Though "FISH_CLIPBOARD_CMD" is the obvious exception here.

**Comment by krader1961** [comment]
Right, just as within Python (where no sane person uses double-underscore prefixes), a single underscore signifies a private, don't modify, read only if you have a good reason, variable. To the extent that fish is not currently consistent on this point it's something we should work to improve.

As for the name of the var I'm leaning towards FISH_HISTFILE because it is easier to discover -- anyone looking for the fish equivalent of the bash HISTFILE var will naturally search for that string. And all uppercase to make it clear that you can export it before starting an interactive shell.

**Comment by pickfire** [comment]
Yeah, I will say that **99.99%** of users won't use the `HISTFILE` and I think it is against the **The law of discoverability**.

**Comment by gechr** [comment]
This also solves https://github.com/fish-shell/fish-shell/issues/1156#issuecomment-180871315 in a much neater way, i.e. as with `bash`, I'd just be able to set the following and be done with it:

```fish
set -gx fish_history_file /dev/null
```

With regards to discoverability, I'd lean towards @faho's proposal and name the variable `fish_history_file`, but in the docs include something like "This is the fish equivalent of bash/zsh's `HISTFILE` environment variable.", which solves both problems; users can find the variable by searching and the variable name remains consistent with other fish naming conventions.

**Comment by krader1961** [comment]
Closing this for the moment because the plan has become more ambitious and will probably take a couple of weeks to implement.

**Comment by gechr** [comment]
@krader1961 Any news on the updated plan?

**Comment by krader1961** [comment]
> Any news on the updated plan?

I wasn't comfortable making significant changes to the code until it was cleaned up: both the visual style and being able to lint it. So I've been side-tracked working no fixing those issues. I still have this as a branch in my local repo that I'll get back to working on real soon now.

**Comment by gechr** [comment]
Glad to hear it! Thanks for the update.

**Pull request closed without merging**
