### PR TITLE
Port composer completions to Python 3

### PR DESCRIPTION
**Pull request by jtojnar**
We need to provide Python version explicitly, otherwise the command will fail. Also since Python 2 is nearing its end of life, I ported the completions to Python 3.

### CODE REVIEW

**Comment by zanchey** [comment]
Which platform are you on? I presume it no longer provides Python 2, and does not provide Python 3 via a `python` executable... https://lwn.net/Articles/792718/ bites again.

Unfortunately we are stuck here. macOS doesn't provide `python3` by default.

**Comment by zanchey** [comment]
I suppose one option is to check `command -q python` and `command -q python3`, and use whatever is available.

**Comment by jtojnar** [comment]
We have `python` aliased to `python3`, I just thought it would be better to be explicit. But if this is a problem, I can change the called program back to `python`, the Python 3 code works on Python 2 too.

**Comment by faho** [comment]
We already have a helper function for this: `__fish_anypython`. https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_anypython.fish

**Comment by faho** [comment]
Tho I do suppose if a script won't work with python2 `__fish_anypython` won't work. We might have to remove python2 from that at some point.

**Comment by jtojnar** [comment]
Thanks. That seems to work as well.

**Comment by faho** [comment]
Merged, thanks!

**Pull request merged**
