### PR TITLE
2019

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by faho** [comment]
Sorry, but the docs have been migrated to `sphinx_doc_src` and are now built with sphinx.

I'll add the relevant changes instead, thanks for notifying us!

**Comment by simon04** [comment]
Thank you! :smile:

**Comment by zanchey** [comment]
Unfortunately, this is wrong. Axel has not committed any code since 2009. Really it should be copyright 2010-2019 fish contributors, or perhaps "ridiculousfish and others".

**Comment by faho** [comment]
>Really it should be copyright 2010-2019 fish contributors, or perhaps "ridiculousfish and others".

@zanchey Please check what I actually committed:

>Copyright (C) 2005-2009 Axel Liljencrantz
Copyright (C) 2009-2019 fish-shell contributors

I let them overlap because I have no idea when "fish-shell contributors" took over. I think since that's nebulous enough Axel would be included.

**Comment by zanchey** [comment]
Great, thanks!

**Pull request closed without merging**
