### PR TITLE
workaround broken groff man page config

### LINKED ISSUE #2673: The strange `‐` in the example of `help test`, which should be `-`
When you print `help test` in fishshell, it will print usage and an example:

```
Example
       if test ‐f foo.txt
               echo foo.txt exists
       else if test ‐f bar.txt
               echo bar.txt exists
       else
               echo foo.txt and bar.txt do not exist
       end
```

Can you find anything strange? Perhaps not.

But if you just copy and paste it to fish, and run it, it will show two errors:

```
test: Missing argument at index 2
test: Missing argument at index 2
```

The `‐` is not the same as the normal hyphen `-` !!! (You can copy  it and search in page)

It can be a big problem for newbies of fish like me, I copied it to my shell and spent several hours to figure out why my `if test` doesn't working. 

(I'm afraid there are similar issues in other examples, could you do a global search on the codebase when you fix it?)

### PR DESCRIPTION
**Pull request by krader1961**
## Description

I tested this on macOS Sierra (where it fixes the problem) and Ubuntu 16.04 where it's harmless.

Fixes #2673

### CODE REVIEW

**Comment by floam** [comment]
Why not use -Tascii?

**Comment by floam** [comment]
@MarkGriffiths Any input?

**Comment by krader1961** [comment]
> Why not use -Tascii or latin1?

Because I have no idea what that does if the input contains non-ASCII chars. And we definitely do not want to favor one of the ISO 8859 encodings. I'm pretty confident this PR is the correct fix. It's the behavior we get on any distro that has updated groff to one of the three versions released in the past six years.

**Comment by floam** [comment]
I didn't realize we have UTF-8 encoded manpages.

**Comment by floam** [comment]
Do we?

**Comment by krader1961** [comment]
It doesn't matter if we currently do or don't have man pages with non-ASCII chars. It's a Unicode world and we shouldn't make changes that make it harder to use Unicode.

**Comment by floam** [comment]
I think the think with roff-encoded pages is that any kind of complicated symbol should never need to rely on the character set to be represented. It's possible things slip through.

**Comment by faho** [comment]
This seems like a nicer fix than I had imagined was possible here, and it seems to be harmless on my system.

@floam: I think you're overthinking it - this isn't about any theoretical "complicated symbols". We don't have those, and if we had they'd most likely be (correctly) encoded as UTF-8 non-ASCII. Even if they weren't, that'd be another bug.

What this needs to address is nroff messing up our perfectly good ASCII characters by replacing them with "nicer" non-ASCII versions, in the particular case where it's a special character to any program - that mostly means "-", because that is used to start an option. If this replaces :biking_man: with a slightly different version, that's not important. You can copy/paste it, and it'll work and look the same. Even if it doesn't look quite the same, it's a really small visual issue, and it will most likely appear the same in the commandline (where you pasted it) and in the programs output (when you execute that commandline). But if you copy what turns out to be an en-dash instead of "-", it won't be parsed correctly and will change the behavior of whatever commandline you use it in.

Nobody is using :poodle: as a special character. Everyone and their dog is using "-".

(Also, technically all of our man pages are UTF-8, both when rendered on my system and in the repo)

So: :+1:.

**Comment by floam** [comment]
@faho right - that's why I think Tascii is the simpler fix.

**Comment by floam** [comment]
The only question about such symbols was that @krader1961 didn't know what would happen if he used `-Tascii` - my answer is nothing would.

Consider that this output is good without needing to manually translate things:

```
 nroff -Tascii -man -c /usr/local/share/fish/man/man1/functions.1 | cat -s
```

**Comment by faho** [comment]
@floam: 

>The only question about such symbols was that @krader1961 didn't know what would happen if he used -Tascii - my answer is nothing bad would.

That doesn't seem likely. For one, it'd be a change on all platforms, even those that aren't currently broken. Secondly, my groff man page says this:

>utf8   Unicode character set in UTF-8 encoding.  This mode has the most useful fonts for TTY mode, so it is the best mode for TTY output.

Which doesn't seem great for ascii.

Plus, your answer was basically "we currently don't have non-ascii characters so it doesn't matter". I'm betting that this wouldn't work if we had any, while the proposed solution seems likely to because it shouldn't affect them.

In essence, I'm wary of doing something as drastic as setting the output encoding, while this PR does what the working platforms already do.

**Comment by floam** [comment]
Add UTF-8 symbols to one of the pages and it still outputs fine with `-tascii` -- that's kind of to be expected with UTF-8. 

My points about symbols being divorced from the character set is that typically there should be more "Roffy" way of specifying some particular character. 

I can think of only one downside with -Tascii: the bullet points don't render as prettily.

**Comment by krader1961** [comment]
> Add UTF-8 symbols to one of the pages and it still outputs fine with -Tascii -- that's kind of to be expected with UTF-8.

No, it is not expected since UTF-8 is explicitly not ASCII. That `-Tascii` silently passes through non-ASCII characters is surprising. It would also presumably mean that if we did embed non-ASCII symbols using a roff escape sequence it would not be rendered or rendered differently. Which is exactly what happens as you noted with respect to bullet points.

**Comment by floam** [comment]
So, after noticing the bullet point thing (which uses a unicode dot of some sort with `-Tutf8`, and a 'o' with the ASCII formatter, I'd say that probably is enough to warrant this more complicated (to me) fix because I like the behavior more. I didn't notice that at the very start.

**Pull request merged**
