### PR TITLE
Fix curses includes on platforms offering real libcurses

### LINKED ISSUE #4503: cmake build broken on solaris
cmake searches for (and finds) `wcsdup`, but the subsequent build is broken. For reference, a clean autotools build works fine by comparison.

Also, pcre2's cmake script is doing something that the autotools build script doesn't, as it throws errors about incorrect flags (`-f`, `-F`, `-x) to `grep`.

```
mqudsi@solaris ~/f/build> cmake ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /opt/csw/bin/gcc
-- Check for working C compiler: /opt/csw/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/csw/bin/c++
-- Check for working CXX compiler: /opt/csw/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Curses: /usr/lib/libcurses.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ctermid_r
-- Looking for ctermid_r - found
-- Looking for include file curses.h
-- Looking for include file curses.h - found
-- Performing Test HAVE_STRUCT_DIRENT_D_TYPE
-- Performing Test HAVE_STRUCT_DIRENT_D_TYPE - Failed
-- Looking for dirfd
-- Looking for dirfd - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for flock
-- Looking for flock - not found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for futimes
-- Looking for futimes - not found
-- Looking for getifaddrs
-- Looking for getifaddrs - not found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for getpwent
-- Looking for getpwent - found
-- Looking for gettext
-- Looking for gettext - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for killpg
-- Looking for killpg - found
-- Looking for include file libintl.h
-- Looking for include file libintl.h - found
-- Looking for lrand48_r
-- Looking for lrand48_r - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for mkostemp
-- Looking for mkostemp - not found
-- Looking for include file ncurses/term.h
-- Looking for include file ncurses/term.h - found
-- Looking for DIR
-- Looking for DIR - not found
-- Looking for shm_open
-- Looking for shm_open - found
-- Looking for include file siginfo.h
-- Looking for include file siginfo.h - found
-- Looking for include file spawn.h
-- Looking for include file spawn.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for std::wcscasecmp
-- Looking for std::wcscasecmp - not found
-- Looking for std::wcsdup
-- Looking for std::wcsdup - not found
-- Looking for std::wcsncasecmp
-- Looking for std::wcsncasecmp - not found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file stropts.h
-- Looking for include file stropts.h - found
-- Looking for struct
-- Looking for struct - not found
-- Looking for struct
-- Looking for struct - not found
-- Looking for sys_errlist
-- Looking for sys_errlist - not found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/sysctl.h
-- Looking for include file sys/sysctl.h - not found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file term.h
-- Looking for include file term.h - not found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for wcscasecmp
-- Looking for wcscasecmp - found
-- Looking for wcsdup
-- Looking for wcsdup - found
-- Looking for wcslcpy
-- Looking for wcslcpy - not found
-- Looking for wcsncasecmp
-- Looking for wcsncasecmp - found
-- Looking for wcsndup
-- Looking for wcsndup - not found
-- Looking for _nl_msg_cat_cntr
-- Looking for _nl_msg_cat_cntr - not found
-- Looking for _sys_errs
-- Looking for _sys_errs - not found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of struct winsize
-- Check size of struct winsize - done
-- Looking for TIOCGWINSZ
-- Looking for TIOCGWINSZ - not found
-- Check size of wchar_t[8]
-- Check size of wchar_t[8] - done
-- Using bundled PCRE2 library
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8")
-- Found Readline: /usr/include
-- Found Editline: /usr/include/editline
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for strerror
-- Looking for strerror - found
-- Configuring done
-- Generating done
-- Build files have been written to: /export/home/mqudsi/fish-shell/build
mqudsi@solaris ~/f/build> make -j12
Scanning dependencies of target CHECK-FISH-BUILD-VERSION-FILE
Scanning dependencies of target muparser_project
Scanning dependencies of target pcre2-32
[  1%] Creating directories for 'muparser_project'
[  2%] No download step for 'muparser_project'
[  2%] No update step for 'muparser_project'
[  3%] No patch step for 'muparser_project'
[  4%] Performing configure step for 'muparser_project'
[  4%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_auto_possess.c.o
[  5%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_compile.c.o
[  6%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/pcre2_chartables.c.o
FISH_BUILD_VERSION=2.6.0-727-g798ad36
[  7%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_config.c.o
[  7%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_context.c.o
[  7%] Built target CHECK-FISH-BUILD-VERSION-FILE
[  8%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_dfa_match.c.o
Scanning dependencies of target build_fish_pc
[  9%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_error.c.o
Scanning dependencies of target BUILD_MANUALS
[ 10%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_find_bracket.c.o
[ 12%] Generating fish.pc
[ 12%] Generating doc_src/commands.hdr
[ 12%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_jit_compile.c.o
[ 13%] Built target build_fish_pc
[ 14%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_maketables.c.o
[ 14%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_match_data.c.o
[ 15%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_match.c.o
[ 16%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_newline.c.o
[ 17%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_ord2utf.c.o
[ 18%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_pattern_info.c.o
[ 18%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_serialize.c.o
[ 19%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_string_utils.c.o
[ 20%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_study.c.o
[ 21%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_substitute.c.o
[ 21%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_substring.c.o
[ 24%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_tables.c.o
[ 24%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_ucd.c.o
[ 25%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_valid_utf.c.o
[ 25%] Building C object pcre2-10.22/CMakeFiles/pcre2-32.dir/src/pcre2_xclass.c.o
[ 26%] Generating lexicon_filter
grep: illegal option -- F
grep: illegal option -- x
grep: illegal option -- f
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- F
grep: illegal option -- x
grep: illegal option -- f
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
[ 26%] Generating share/man
      doxygen file: /export/home/mqudsi/fish-shell/Doxyfile.help
   input directory: /export/home/mqudsi/fish-shell/build/doc_src
      input filter: /export/home/mqudsi/fish-shell/build/lexicon_filter
  output directory: /export/home/mqudsi/fish-shell/build/share
          skipping:
doxygen is not installed, so documentation will not be built.
[ 27%] Built target BUILD_MANUALS
[ 28%] Linking C static library libpcre2-32.a
[ 28%] Built target pcre2-32
[ 29%] Performing build step for 'muparser_project'
make: Warning: Ignoring DistributedMake -j option
make: Warning: Ignoring DistributedMake -j option
make: Warning: Ignoring DistributedMake -j option
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParser.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParser.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserBase.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserBase.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserBytecode.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserBytecode.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserCallback.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserCallback.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserDLL.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserDLL.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserError.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserError.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserInt.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserInt.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserTest.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserTest.cpp
/export/home/mqudsi/fish-shell/build/muparser-build/obj/bk-deps g++ -c -o muParser_lib_muParserTokenReader.o -DNDEBUG    -I/export/home/mqudsi/fish-shell/muparser-2.2.5/include -D_UNICODE=1 -Wno-switch -O2 /export/home/mqudsi/fish-shell/muparser-2.2.5/src/muParserTokenReader.cpp
rm -f lib/libmuparser.a
ar rcu lib/libmuparser.a muParser_lib_muParser.o  muParser_lib_muParserBase.o  muParser_lib_muParserBytecode.o  muParser_lib_muParserCallback.o  muParser_lib_muParserDLL.o  muParser_lib_muParserError.o  muParser_lib_muParserInt.o  muParser_lib_muParserTest.o  muParser_lib_muParserTokenReader.o
ranlib lib/libmuparser.a
[ 29%] Performing install step for 'muparser_project'
make: Warning: Ignoring DistributedMake -j option
make: Warning: Ignoring DistributedMake -j option
/opt/csw/bin/ginstall -c -d /export/home/mqudsi/fish-shell/build/muparser-build/dst/lib
/opt/csw/bin/ginstall -c -m 644 ./lib/libmuparser.a /export/home/mqudsi/fish-shell/build/muparser-build/dst/lib
/opt/csw/bin/ginstall -c -d /export/home/mqudsi/fish-shell/build/muparser-build/dst
for f in include/muParser.h  include/muParserBase.h  include/muParserBytecode.h  include/muParserCallback.h  include/muParserDLL.h  include/muParserDef.h  include/muParserError.h  include/muParserFixes.h  include/muParserInt.h  include/muParserStack.h  include/muParserTemplateMagic.h  include/muParserTest.h  include/muParserToken.h  include/muParserTokenReader.h; do \
if test ! -d /export/home/mqudsi/fish-shell/build/muparser-build/dst/`dirname $f` ; then \
/opt/csw/bin/ginstall -c -d /export/home/mqudsi/fish-shell/build/muparser-build/dst/`dirname $f`; \
fi; \
/opt/csw/bin/ginstall -c -m 644 /export/home/mqudsi/fish-shell/muparser-2.2.5/$f /export/home/mqudsi/fish-shell/build/muparser-build/dst/$f; \
done
/opt/csw/bin/ginstall -c -d /export/home/mqudsi/fish-shell/build/muparser-build/dst/lib/pkgconfig
/opt/csw/bin/ginstall -c -m 644 build/autoconf/muparser.pc /export/home/mqudsi/fish-shell/build/muparser-build/dst/lib/pkgconfig
[ 30%] Completed 'muparser_project'
[ 30%] Built target muparser_project
Scanning dependencies of target fishlib
[ 31%] Building CXX object CMakeFiles/fishlib.dir/src/autoload.cpp.o
[ 34%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_bind.cpp.o
[ 34%] Building CXX object CMakeFiles/fishlib.dir/src/builtin.cpp.o
[ 35%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_block.cpp.o
[ 36%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_builtin.cpp.o
[ 36%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_bg.cpp.o
[ 36%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_cd.cpp.o
[ 37%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_command.cpp.o
[ 38%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_commandline.cpp.o
[ 39%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_complete.cpp.o
[ 39%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_contains.cpp.o
[ 40%] Building CXX object CMakeFiles/fishlib.dir/src/builtin_disown.cpp.o
/export/home/mqudsi/fish-shell/src/builtin.cpp: In function ‘void builtin_print_help(parser_t&, io_streams_t&, const wchar_t*, output_stream_t&)’:
/export/home/mqudsi/fish-shell/src/builtin.cpp:203:36: error: ‘wcsdup’ was not declared in this scope
     wchar_t *str = wcsdup(h.c_str());
                                    ^
gmake[2]: *** [CMakeFiles/fishlib.dir/build.make:87: CMakeFiles/fishlib.dir/src/builtin.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:391: CMakeFiles/fishlib.dir/all] Error 2
gmake: *** [Makefile:128: all] Error 2
```

### PR DESCRIPTION
**Pull request by mqudsi**
There were several issues with the way that the include tests for curses.h
    were being done that were ultimately causing fish to use the headers from
    ncurses but link against curses on platforms that provide an actual
    libcurses.so that isn't just a symlink to libncurses.so

    In particular, the old code was first testing for curses's curses.h and then
    falling back to libncurses's implementation of the same - but that logic was
    reversed when it came to including term.h, in which case it was testing for
    the ncurses's term.h and falling back to the curses' term.h header. Long story
    short, while cmake will link against libcurses.so if both libcurses.so and
    libncurses.so are present (unless CURSES_NEED_NCURSES evaluates to TRUE, but
    that makes ncurses a hard requirement), but we were brining in some of the
    defines from the ncurses headers, causing SIGSEGV panics when fish ultimately
    tried to access variables that weren't exported or were mapped to undefined
    areas of memory in the other library.

    Additionally it is an error to include termios.h prior to including the plain
    Jane curses.h (not ncurses/curses.h), causing errors about unimplemented types
    SGTTY/chtype. So far as I can tell, both curses.h and ncurses/curses.h pull in
    termios.h themselves so it shouldn't even be necessary to manually include it,
    but I have just moved its #include below that of curses.h

Closes #4503

### CODE REVIEW

**Comment by mqudsi** [comment]
@zanchey can you look at https://github.com/fish-shell/fish-shell/commit/fea1597a27b9d73cdceaa500b7bc34b9fb7c6edf? I came across your CMake pull request regarding the same: https://gitlab.kitware.com/cmake/cmake/merge_requests/1464#note_346850

**Comment by faho** [comment]
Stupid question from someone entirely without Solaris experience: Do we want "real curses", or do we want ncurses? I mean the latter is what we use on other platforms. Is there any compelling reason to pick the former?

**Comment by zanchey** [comment]
@mqudsi, I copied the version I submitted in PR to our local tree in f5209deacc9a24fa2c4a1f020558f704f08a03ae, so using `CHECK_INCLUDE_FILES` should be fine.

**Comment by zanchey** [comment]
> Stupid question from someone entirely without Solaris experience: Do we want "real curses", or do we want ncurses?

Not a stupid question at all! I think using ncurses is fine - it's shipped on literally every platform and is much better maintained. NetBSD would still need the tparm fixed-args hack (or the magic flag set to make it behave like tparm elsewhere, which is probably saner).

**Comment by mqudsi** [comment]
@zanchey thanks!
@faho I don't think there's any benefit or detriment either way (besides a hard dependency on a library that may not be installed out of the box), but the real issue fixed here is that we were mixing-and-matching the headers from ncurses with the not-abi-compatible binaries from not-ncurses causing `SIGSEGV`s. 

My initial fix actually just added `SET(CURSES_NEED_NCURSES TRUE)` above `FindCurses` which caused fish to link against `libncurses.so` instead of `libcurses.so`.

I'm not sure if the old build system ended up using real curses or new curses.

**Comment by zanchey** [comment]
The autoconf build ended up pulling in ncurses, so I suspect this will turn up new and exciting behaviour.

**Pull request merged**
