### PR TITLE
Update README | chsh -s /usr/bin/fish

### PR DESCRIPTION
**Pull request by onrea**
https://github.com/fish-shell/fish-shell/issues/669#issuecomment-38395980

### CODE REVIEW

**Comment by bpinto** [comment]
What about using:
```
grep -q '^/usr/local/bin/fish$' /etc/shells; or echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish
```

We could add a `which fish` to be more thorough.

**Comment by geoff-codes** [comment]
I usually usually advocate putting `which fish >/dev/null 2>&1 && exec fish -il` at the end of `.profile`/`.bash_profile` instead of using `chsh`, since:
- It doesn't require modifying `/etc/shells`, which requires sudoer privileges one way or another (either directly, or by invoking the package manager).
- It doesn't depend on `fish` being installed/symlinked at `/usr/bin/fish`,`/usr/local/bin/fish`, or anywhere else; it just needs to be in the PATH somewhere.

This does means working at `SHLVL=1` all the time, but the overhead is extremely minimal.

**Comment by faho** [comment]
How about just mentioning /etc/shells, i.e.

>Substitute /usr/local/bin/fish with whatever path to fish is in your /etc/shells file.

?

**Comment by faho** [comment]
I've now simply mentioned /etc/shells like I proposed. Thanks for the idea!

**Pull request closed without merging**
