### PR TITLE
completions: fix scp remote path when /bin/ls does not exist

### PR DESCRIPTION
**Pull request by rnhmjoj**
## Description

This should fix issue #6724 
I gave a quick look and figured out what the problem was.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by faho** [comment]
Could we not rely on $PATH and just use `ls`?

**Comment by rnhmjoj** [comment]
How would you do that? I honestly don't know.

**Comment by faho** [comment]
Just use `ls` instead of `/bin/ls`.

`ssh` starts a shell, so that should have a working $PATH.

**Comment by rnhmjoj** [comment]
> ssh starts a shell, so that should have a working $PATH.

Ok, that was pretty obvious. I was somehow conviced a shell or executable were needed.

**Comment by faho** [comment]
Merged, thanks!

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request merged**
