### PR TITLE
Customisable extra configuration, completion and function directories

### LINKED ISSUE #2113: Support homebrew's vendor completions needs
From #1485, languitar writes:

>Is it possible to redefine this path via build system configuration arguments? I am currently implementing fish completion support for OS X homebrew and in homebrew each program is installed into a separate folder and the prefix is formed by symlinking things together. Right now the vendor completion path points into the isolated installation prefix of fish and will therefore never match to any other completions symlinked into the actual prefix. So, making this configurable would be a great help in this situation.

>the actual install prefix for fish is e.g. `/usr/local/Cellar/fish/HEAD` and things are symlinked together into `/usr/local`. So I would just want to reconfigure things so that `/usr/local/share/fish/vendor_completions.d` ends up on `fish_complete_path`.*

This bug tracks figuring how to best support this scenario.

### PR DESCRIPTION
**Pull request by zanchey**
- Add options to the autotools build to set the path for the "vendor"
   or "extra" configuration snippets, functions and completions
   directories.
 - Remove the vendor_completions directory from the Xcode build, as
   these are relocatable and compiling the paths in does not make sense.

This allows packaging tools like Homebrew and Nix to use a common
directory outside of the main prefix for third-party completions, and
to make these available for programmatic discovery through `pkg-config`.

Closes #2113.

Documentation changes to come.

r? @languitar @ridiculousfish @amluto and anyone else who is interested - I'll post in the Homebrew thread as well and try and see if this meets their needs.

### CODE REVIEW

**Comment by justinmayer** [comment]
Nice work, David.  :+1:

**Comment by krader1961** [comment]
Squash merged as 484c1484c9ae01354b1910bae5ed8a729e00b3be with two trivial typos (one in a comment, one in the docs) fixed and slight editing for consistency in the docs. Yay! We're one step closer to a 2.3.0 release.

**Comment by zanchey** [comment]
`snippets` is giving me the willies; can we just call it `conf` instead? @faho

**Comment by krader1961** [comment]
FWIW, I'm not a fan of "snippets" either but admit I don't have a strong counter-proposal.

**Comment by faho** [comment]
>snippets is giving me the willies; can we just call it conf instead?

In this case "extraconfdir" would work, but "configuration snippets" is usually what the files in these directories are called (see the prior art in IIRC systemd and Xorg).

**Comment by faho** [comment]
>snippets is giving me the willies; can we just call it conf instead?

In this case "extraconfdir" would work, but "configuration snippets" is usually what the files in these directories are called (see the prior art in IIRC systemd and Xorg).

**Comment by faho** [comment]
>snippets is giving me the willies; can we just call it conf instead?

In this case "extraconfdir" would work, but "configuration snippets" is usually what the files in these directories are called (see the prior art in IIRC systemd and Xorg).

**Pull request closed without merging**
