### PR TITLE
Added fish_sequence_key_delay_ms to set time to wait between sequence key presses (#7401)

### PR DESCRIPTION
**Pull request by yanshay**
## Description

This resolves issue #7401

When binding key sequences, currently, fish waits indefinitely for sequence to complete. So if one wants to press only a single character which is a beginning of a sequence, that character will not appear. To make it appear need to press another character, not in the sequence and then backspace. Not very reasonable.
For example, if using 'kj' to exit insert mode in fish vi mode, if one presses 'k' it will not show until another key is pressed, so to type 'k' at end of command need to press 'k', then another character and then backspace. Not to speak that to enter kj as characters its even more difficult.

The solution introduced here is to set fish_sequence_key_delay_ms variable (along the lines of fish_escape_delay_ms) which is the time to wait for the next key in a sequence. Once that time passes the key will be output as usual. By default the behavior is as today and setting the key changes the behavior.

I wrote the code and tested it manually. If you expect it to enter future versions I will update documentation and changelog as well, and will try to add tests for the new behavior.

I also think it's worth considering making this the default behavior using some reasonable value. 

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
I finally got a chance to test this.

Thanks, this seems like solid work! I'll be adding some docs and tests, and we'll see if a default timeout makes sense - nvim sets it to 1 second.

**Comment by faho** [comment]
Tagging for 3.7.0 because it's *possible* to backport, and would be cool to have - but it would require some work.

**Comment by yanshay** [comment]
When will 3.7 come out?

**Comment by faho** [comment]
"When it's done".

I'm afraid experience shows we can't really do estimates.

**Comment by yanshay** [comment]
Can I back-port this PR?
If I recall correctly I originally implemented it on top of 3.6 branch and only later had to contribute to master.
I use it all the time (practically whenever I type J or K on command line which is probably quite a few times an hour ...)

**Comment by faho** [comment]
> Can I back-port this PR?

If you want, you can do it, otherwise I'll see once I get the time.

You'll want to target [the Integration_3.7.0 branch](https://github.com/fish-shell/fish-shell/tree/Integration_3.7.0).

**Comment by yanshay** [comment]
> You'll want to target [the Integration_3.7.0 branch](https://github.com/fish-shell/fish-shell/tree/Integration_3.7.0).

Maybe I misunderstood something.

I thought you tagged it to 3.7, therefore it won't come out in 3.6.2.
Is 3.7 is going to be based on Master (with more rust code, and my PR was adjusted for that)?
So if I want it to be released in 3.6.2 shouldn't I merge it to Integration 3.6.2?

**Comment by faho** [comment]
> I thought you tagged it to 3.7, therefore it won't come out in 3.6.2

3.7.0 is going to be the next C++-based release. We decided that it was a bit much for a 3.6.2. Integration_3.7.0 is branched from Integration_3.6.1, not master.

The rust-based version will probably be 4.0, *possibly* 3.8.

**Comment by yanshay** [comment]
> We decided that it was a bit much for a 3.6.2.

'it' meaning this change? So no point in submitting a PR for this on 3.6.2?

**Comment by faho** [comment]
>  Or do you mean there isn't going to be a 3.6.2?

There isn't going to be a 3.6.2. What was intended for 3.6.2 became a bit much for a patch release, and so we're going to call it 3.7.0 instead.

**Comment by yanshay** [comment]
I submitted a PR with back-port to 3.7.0 : #10008

**Pull request merged**
