### PR TITLE
 Append paths from /etc/manpaths and /etc/manpaths.d/* to MANPATH, for #1092

### PR DESCRIPTION
**Pull request by smammy**
* Only append paths if `MANPATH` is already set, to match behavior of macOS `path_helper` utility.
* Use the same technique as is used above to set PATH from /etc/paths and /etc/paths.d/*.

## Description

* I updated the patch so that it only modifies `MANPATH` if it is already set, per feedback. Thanks to @ridiculousfish, @floam, and @faho.
* There's clearly some refactoring that could be done between the `/etc/paths` and `/etc/manpaths` code right above it, but I figure that should be a separate change.

Fixes issue #1092

## TODOs:

- [ ] Changes to fish usage are reflected in user documenation/manpages.
- [ ] Tests have been added for regressions fixed

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Is there a reason for wanting to set MANPATH now? Just out of curiosity.

Also `/usr/libexec/path_helper` doesn't modify `MANPATH` unless it's set. This will set it unconditionally.

**Comment by floam** [comment]
Yeah from [inspecting the source](https://opensource.apple.com/source/shell_cmds/shell_cmds-198/path_helper/path_helper.c.auto.html), the only way to get `path_helper` to provide a `$MANPATH` for you is with it already existing in the environment.

`begin; set -lx MANPATH ''; path_helper -c; end`

**Comment by faho** [comment]
>Is there a reason for wanting to set MANPATH now?

It's probably worth noting that we set MANPATH in the `man` function. This executes `manpath` to figure out the path. Does that not use the helper?

**Comment by smammy** [comment]
Hi folks, thanks for the feedback. The reason to set `MANPATH` at init time is that the `manpath` command doesn't use `path_helper`, and in fact ignores `/etc/manpaths` and `/etc/manpaths.d/*`.

I misread the `path_helper` manpage; now I see that indeed `MANPATH` is only populated if if *is set already* when `path_helper` is called. I'm not really sure why that is; no justification is given.

It sounds like we want to replicate the behavior of `path_helper` in `fish.config`, so I updated my patch so that MANPATH is only updated if it's set to begin with.

**Comment by ridiculousfish** [comment]
Thanks, updated patch looks good to me.

**Comment by ridiculousfish** [comment]
> It's probably worth noting that we set MANPATH in the man function. This executes manpath to figure out the path. Does that not use the helper?

No, I think `manpath` does not use path_helper.

fish's `man` function prepends to MANPATH but only for the duration of `man`. The reason is so that fish's builtins get picked up by `man`, but only within fish (if you invoke bash from fish, you don't want fish's man pages to show up within bash)  So what `man` does is still right.

**Comment by ridiculousfish** [comment]
Thanks!

**Comment by smammy** [comment]
No problemo! Keep up the good work.

**Pull request merged**
