### PR TITLE
new pt_BR translations

### PR DESCRIPTION
**Pull request by frnogueira**

### CODE REVIEW

**Comment by faho** [comment]
First of all: Thank you for doing this!

Secondly: I don't speak portuguese (any variant) - "lua" means "moon", right?

I can't help but notice that you favor a somewhat more "native" style - translating "file" as "arquivo" and such. The question I always have when that is used is: Is that the usual way? Is it consistent with what other programs are doing? 

For example, I'm german. If someone were to translate "PC" to "persönlicher Rechner", that would technically be correct, but also really weird - "PC" is absolutely common in german, and using a translated term would cause more issues than it solves. There's been a german magazine that tried to use a simplified vocabulary and it was horrible, helping neither new users nor old ones. They actually translated "driver" to the equivalent of "control program".

**Comment by faho** [comment]
Also, have you looked at #1675? That's been proposed a year ago but is stuck in our pipeline for some reason.

**Comment by frnogueira** [comment]
Hi!

Lua is moon... ;)

I am leader of ubuntu brazilian translators and translator of GNOME too. I used this terms to translate..

**Comment by faho** [comment]
I've now squash-merged this as 6e3ea5b2eab26ce2006d59c3a5829e87d05d4bc4. Thanks!

**Comment by zanchey** [comment]
#1675 was blocked on finding a better way of implementing xgettext.

**Pull request closed without merging**
