### PR TITLE
Improve systemctl completions

### LINKED ISSUE #1393: Completions for systemctl --user
Currently, the systemctl completions work great for system instance completions but not at all for user instance completions. It would be kind of nice if fish could detect the `--user` flag and complete user instance units when applicable.

### PR DESCRIPTION
**Pull request by faho**
This adds support for user-mode and fixes an assumption - in systemctl, options can come before commands.

`systemctl --user status` works, as does --quiet or --all.

Fixes #1393.

### CODE REVIEW

**Comment by faho** [comment]
Also, does anyone mind if I remove the descriptions from unit completions?

I feel like "alsa-restore.service (Service)" isn't all too helpful. It's just repetition, after all, and removing it can simplify the code quite a bit.

**Comment by zanchey** [comment]
Are there times when the type isn't obvious e.g. mounts or sockets? Is the name always printed as `alsa-restore.service`? If the answers are no and yes respectively then I think that's a good change to make.

**Comment by faho** [comment]
I've never seen any case where systemd doesn't print the type - it's also mandatory as part of the filename, and for all arguments except for:

- ".target" when used with `systemctl isolate`
- ".service" with any other operation that takes a unit name

So yeah, it's just duplication.

**Comment by ridiculousfish** [comment]
Merged as 5a9b1b1b57f8ce6e56d66770758a5b2611a3a1fe - sorry for the delay, and thanks!!

**Pull request closed without merging**
