### PR TITLE
completions: speed up kdeconnect-cli device discovery

### PR DESCRIPTION
**Pull request by ammgws**
Over 150 times faster now. Also added device name and status to the completion description.
This is done by using the `--shell-device-autocompletion` flag provided by `kdeconnect-cli`.

**Before**
```
>time complete -C"kdeconnect-cli -d"
-d689ccf9fd5f3272d	Device ID
-d689ccf9fd5f3272d	Device ID
________________________________________________________
Executed in    4.04 secs      fish           external
   usr time   24.87 millis    2.08 millis   22.79 millis
   sys time   14.60 millis    0.12 millis   14.48 millis
```

**After**
```
>time complete -C"kdeconnect-cli -d"
-d689ccf9fd5f3272d	Pixel 4 (paired)
________________________________________________________
Executed in   22.38 millis    fish           external
   usr time    9.54 millis    2.04 millis    7.51 millis
   sys time   11.23 millis    0.00 millis   11.23 millis
```

### CODE REVIEW

**Comment by faho** [comment]
`kdeconnect-cli --shell-device-autocompletion=zsh` outputs nothing for me, while `kdeconnect-cli -l --id-only` shows my device's id.

Sure is fast tho.

**Comment by ammgws** [comment]
That's a shame. I'm on Arch too.

**Comment by ammgws** [comment]
This is the code for that flag:
```
    } else if (parser.isSet(QStringLiteral("shell-device-autocompletion"))) {
        //Outputs a list of reachable devices in zsh autocomplete format, with the name as description
        const QStringList devices = blockOnReply<QStringList>(iface.devices(true, false));
        for (const QString &id : devices) {
            DeviceDbusInterface deviceIface(id);
            QString statusInfo;
            const bool isTrusted = deviceIface.isTrusted();
            if (isTrusted) {
                statusInfo = i18n("(paired)");
            } else {
                statusInfo = i18n("(unpaired)");
            }

            //Description: "device name (paired/unpaired)"
            QString description = deviceIface.name() + QLatin1Char(' ') + statusInfo;
            //Replace characters
            description.replace(QLatin1Char('\\'), QStringLiteral("\\\\"));
            description.replace(QLatin1Char('['),  QStringLiteral("\\["));
            description.replace(QLatin1Char(']'),  QStringLiteral("\\]"));
            description.replace(QLatin1Char('\''), QStringLiteral("\\'"));
            description.replace(QLatin1Char('\"'), QStringLiteral("\\\""));
            description.replace(QLatin1Char('\n'), QLatin1Char(' '));
            description.remove(QLatin1Char('\0'));

            //Output id and description
            QTextStream(stdout) << id << '[' << description << ']' << endl;
        }
```

What does this return for you?

`qdbus org.kde.kdeconnect /modules/kdeconnect/devices/yourdevice org.kde.kdeconnect.device.isTrusted`

and

`qdbus org.kde.kdeconnect /modules/kdeconnect org.kde.kdeconnect.daemon.devices)`

**Comment by faho** [comment]
>qdbus org.kde.kdeconnect /modules/kdeconnect org.kde.kdeconnect.daemon.devices)

What looks like a 16-digit hex number. 5219...

>qdbus org.kde.kdeconnect /modules/kdeconnect/devices/yourdevice org.kde.kdeconnect.device.isTrusted

Replacing "yourdevice" with that hex, it returns `true`.

(also we have usable completions for `busctl`, so tbh I prefer using that instead - dbus is just so frickin verbose)

**Comment by ammgws** [comment]
Weird, no idea why `kdeconnect-cli --shell-device-autocompletion=zsh` doesn't work for you then.

TIL about `busctl`. Looks so much better!

**Comment by faho** [comment]
Ah, okay. When `kdeconnect-cli -l` would print the device is "paired *and reachable*" `kdeconnect-cli --shell-device-autocompletion=zsh`  prints the device is "paired". When `-l` prints just "paired", `--shell...` fails (prints nothing, returns 1)

**Comment by ammgws** [comment]
Most of the commands are for using with a connected device, so perhaps it makes sense for it not to complete? Or we could just fallback to `kdeconnect-cli -l` if `kdeconnect-cli --shell-device-autocompletion=zsh` returns 1.

**Comment by faho** [comment]
The device *is* connected tho? It's lying right next to me, there's no rhyme or reason to when it shows up or doesn't, and kdeconnect seems to work without a hitch?

Is this not sending out a beacon or so that full `-l` would?

**Comment by ammgws** [comment]
Yeah this morning mine didn't show up with --shell... either until I opened the app on my phone and sent a ping (the latter might be unnecessary)
> not sending out a beacon

I guess this is the difference between the two:

```...
 blockOnReply(iface.acquireDiscoveryMode(id));
            QThread::sleep(2);
        }
        const QStringList devices = blockOnReply<QStringList>(iface.devices(reachable, false));
```

**Comment by ammgws** [comment]
I ended up adding a fallback to the slower option when the first returns 1.

**Comment by faho** [comment]
Yeah, that should work. Thanks!

**Pull request merged**
