### PR TITLE
GitHub PR Template

### LINKED ISSUE #3195: Track status of documentation, release-note follow-through on PRs
We should ~~keep PRs open until we merge~~ try to better keep track of changes to docs, CHANGELOG.md, and tests by using GitHub tasks.
 
By closing PRs before required work associated with them is complete, we're letting things slip through the cracks and lose track of stuff. GitHub tasks (checkboxes) seem like a decent solution which will show up outside the PR itself and affect our milestone completion.

### PR DESCRIPTION
**Pull request by floam**
This adds a PR template. This PR itself is an example of pasting the template in that template.

~~Fixes 3195.~~ 
(the tasks below, are what the template brings in.)

----

### TODOs:

- [ ] New stuff and changes in usage have been documented
- [ ] Regression fixes have had tests added to the suite.

### CODE REVIEW

**Comment by zanchey** [comment]
I think this is a great idea but I'm worried about scaring off potential contributors. One thing I really like about the [Homebrew pull request template](https://github.com/Homebrew/homebrew-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is that the steps are easy to follow and (generally) immediately actionable.

I can think of two ways to improve the situation:
 - Flesh out either `CONTRIBUTING.md` or the Wiki with explanation about what changes need tests and documentation and how to get started would be helpful
 - Change the checklist to be something like "I have updated the documentation (or asked for help on how to do so)"

**Comment by krader1961** [comment]
In addition to @zanchey's points I'm worried this encourages people to put information into the PR comment that should be in the git commit message. I'm dubious the task list will do anything other than add noise and administrative overhead. I'd prefer to simply have a comment in the template that tells a contributor we expect the change to conform to the style guide, documentation and unit tests to be updated, and points them at *CONTRIBUTING.md* for details.

**Comment by floam** [comment]
> I think this is a great idea but I'm worried about scaring off potential contributors. 

I agree. I don't know why it seemed fine me to me that submitting a quick PR with your fix should have that "trail of tears" vibe.

**Comment by floam** [comment]
I'm abandoning #3195 regarding when we close PRs.

**Pull request closed without merging**
