### PR TITLE
Handle EINTR/EAGAIN in readb()

### PR DESCRIPTION
**Pull request by kballard**
I don't know if this is actually correct. But it seems like a reasonable thing to do. @ridiculousfish or anyone else with knowledge here, is this something that we should do, or is there a good reason to treat EINTR/EAGAIN as if the terminal closed?

### CODE REVIEW

**Comment by krader1961** [comment]
I agree with @ridiculousfish. You need to open an issue that describes how to reproduce this problem. Your change to __VOMIT_ON_FAILURE__ is dubious. Your solution is even more suspect. When you open an issue please elaborate on "We definitely hit this case on starting the shell." What did you observe? What was your environment?

**Comment by krader1961** [comment]
You also say

> I slapped a perror() in there and I got "Resource temporary unavailable" spewed quite a lot during the startup. I'm not sure why, and I'm also not sure why it doesn't seem to cause any issues. Behavior seems identical in my limited testing with this PR than without.

Where did you insert the perror() call? And if your change appears to have no functional effect on the behavior of fish why should this change be merged? You say

> We definitely hit this case on starting the shell.

Okay, I don't doubt you saw a problem but I can't tell from that statement what the problem was let alone that this change will fix that problem. As I said earlier you really need to open an issue that tells us what you observed and, ideally, how to reproduce the problem if you can do so.

**Comment by kballard** [comment]
This code is a year old. I don't remember it anymore. All I remember is this change seemed necessary at the time to produce the desired behavior, and it worked in my testing. I can't explain it anymore without basically recreating the change from scratch to figure out why I did it this way. This should have been reviewed a year ago, rather than waiting so long.

**Comment by krader1961** [comment]
I hear you. I have two, much simpler, changes pending acceptance and I'm also a bit annoyed at how long it's taking. Having said that if you're no longer interested in pursuing getting this change accepted, and since you seem to be saying it's no longer needed, can you please close this PR?

**Comment by ridiculousfish** [comment]
@krader1961 I'm sorry for the delay with your PRs. We really appreciate your contributions. I've gone and reviewed them both.

In the future please feel free to ping me in the PR if it's taking excessively long, I am prone to lose track of the state of things.

**Comment by faho** [comment]
This has unfortunately become stale - nobody remembers what it's there for anymore. If the problem appears again, we'll still have this archived. But for now, it doesn't appear like we'd merge it.

Sorry, @kballard!

**Comment by kballard** [comment]
@faho I know that, in general, `EINTR` means the read should be retried, but this code treats `EINTR` as if the terminal closed, which is wrong. I don't remember why this was meaningful. I don't know if it's possible for `read()` to return `EINTR` if there's already data available to satisfy the request; if it can't, maybe I had some situation where I was calling `readb()` before there actually was data available (because I wanted to block until there was), but I'm not sure why I would have done that.

Looking at this now, I do think that the handling of `EAGAIN` is pointless. That shows up when using non-blocking I/O, but we're not using non-blocking I/O, and if stdin somehow does get set to non-blocking I imagine a lot of stuff will blow up.

I'm not sure offhand why I modified `VOMIT_ON_FAILURE` instead of just changing `read_blocked()`. I *believe* this is because I thought that `VOMIT_ON_FAILURE` should not affect handling of `errno` by the calling code, but I don't know why I thought it was important to handle that in the macro instead of doing it in each function that cares about preserving `errno`. I *do* think `read_blocked()` should preserve `errno`, because it's just a wrapper around `read()` that blocks `SIGCHLD` for the duration. But I don't know offhand if any other functions could benefit from this.

**Comment by krader1961** [comment]
Perhaps __VOMIT_ON_FAILURE__ had a different implementation when you wrote this patch (I'm too lazy to look at the change history). But today it doesn't modify errno unless it actually calls __VOMIT_ABORT__ and in that case we shouldn't care that errno was modified. So modifying that macro to save/restore errno is pointless today and thus there are no other functions that could benefit from that portion of this change.

As for the EINTR case that should be impossible modulo any bugs in fish or supporting libraries or the OS kernel. Having said that it might be reasonable to "harden" that code path in a fashion similar to what you proposed in this change to report the unexpected EINTR and maybe ignore it. But that's something I'd want to think about and discuss because it is far to easy for such strategies to paper-over real bugs that should result in a full-stop and instead continuing to run and cause other problems.

Can we assume you're no longer using a custom fish built with this patch? If not can you reproduce the problem using a standard fish binary?

**Pull request closed without merging**
