### PR TITLE
fix handling of non-ASCII chars in C locale

### LINKED ISSUE #2802: glibc mbrtowc() function fails when locale is C or POSIX; this breaks the read builtin command
Ctrl + Shift + T opens a new tab in gnome-terminal. The current working directory in this new tab usually is the same as the one in the previously active tab. But it is not when the current working directory contains a German umlaut.

### Reproduction Steps:

```
# Create directory with umlaut and change into it
cd /tmp/
mkdir Tür
cd Tür/
# Now: Press Ctrl+Shift+T
```

### Expected behavior:

`pwd` is `/tmp/Tür`

### Observed behavior:

`pwd` is `/home/<myuser>`

### Additional information:

---
Fish version: `2.2.0-675-g5e09411`

Operating system: Ubuntu Wily with fish's nightly PPA

Terminal or terminal emulator: `GNOME Terminal 3.16.2`

### PR DESCRIPTION
**Pull request by krader1961**
The relevant standards allow the mbtowc/mbrtowc functions to reject
non-ASCII characters (i.e., chars with the high bit set) when the locale
is C or POSIX.  The BSD libraries (e.g., on OS X) don't do this but
the GNU libraries (e.g., on Linux) do. Like most programs we need the
C/POSIX locales to allow arbitrary bytes. So explicitly check if we're
in a single-byte locale (which would also include ISO 8859 variants)
and simply pass-thru the chars without encoding or decoding.

Fixes #2802.

### CODE REVIEW

**Comment by jakwings** [comment]
Have you tried working in the C/POSIX locale, without any problem with spacing/auto-completion/cd/pwd?

This patch has some serious side-effects: (screenshots)




▲cd: Could not set PWD variable
▲fish: Tried to print invalid wide character string
▲cd: The directoy 'T?r' does not exist
▲pwd outputs nothing

**Comment by floam** [comment]
I've been thinking about this - especially given the Python warmup exerercise - and I guess it makes no sense to me. 

So - I like how Python does this. I get that this is a shell. 

Why would it be the right thing, on an ASCII locale, single byte locale to be trying to feed it inherently incompatible and ambiguously defined data?Choppinp up unicode bytecode sending random out-of-range codepoints? 

Why not just replace these with question mark so people can see there is clearly a problem and fix it?

Python's tough love unicode love I liked more.

**Comment by krader1961** [comment]
> Have you tried working in the C/POSIX locale...

Yes, I currently have two shells running in the C locale with this patch: one on OS X and one on Ubuntu. I haven't yet reproduced what you're seeing but I do see that I overlooked calls to functions like wcstombs(). However, the "Tried to print invalid wide character string" errors you're seeing would occur without my change and make my point that fish more or less requires a UTF-8 locale. Interestingly, if the writestr() function that is producing those errors has a commented out loop that calls the writech() function I patched. If it used that rather than wcstombs() then my change would produce sensible behavior without errors.

**Comment by krader1961** [comment]
Also, @jakwings, this change was not intended to make fish behave correctly in the C/POSIX/ISO-8859 locales in every conceivable scenario. The only way to do that is to essentially make fish ignore the locale environment variables and always use a UTF-8 encoding (at least with respect to **LC_CTYPE**). The scope of this change is only to make it behave reasonably when reading and printing strings of bytes by treating every byte value as a legal code point. Thus avoiding the understandable, if odd, choice of the GNU libc team to treat bytes with the high bit set as invalid in the C/POSIX locales.

**Comment by krader1961** [comment]
> Why would it be the right thing, on an ASCII locale...

Because, @floam, there is no such thing as an ASCII locale. There is the C locale (aka POSIX). Which historically treated every byte value from 0 thru 255 as valid. When Unicode was introduced it encoded a few "wide" characters using the existing ISO-8859-1 standard. This meant that some, but not all, characters with the high bit set were valid Unicode code points. Some people (e.g., the GNU) team decided it would be best if the C/POSIX locale was redefined to mean just the range of ASCII code points (0 thru 127). While other teams (e.g., the BSD folks) decided to retain the legacy semantics.

That is why we have the current mess that results in fish behaving differently depending on whether it is running on a BSD or GNU based distro.

**Comment by jakwings** [comment]
> The only way to do that is to essentially make fish ignore the locale environment variables and always use a UTF-8 encoding

Yeah, and fish internally use `wchar_t` (its size is implementation dependent)… So I always have a question: Which locales does fish support by default?

**Comment by krader1961** [comment]
> Which locales does fish support by default?

Your question isn't sufficiently precise. For example, if you're working at a company like Google it would be interpreted to mean what locales has the project been localized to? Which includes most notably language translations for strings emitted by the project. The reality is that fish implicitly expects a UTF-8 locale regardless of the language. Consider its handling of "\uXXXX" sequences in strings and the L'\x23CE' wide-char literal embedded in the code for reporting when a newline wasn't present in the previous command output.

Not to mention the *utf8.cpp* file and all the unicode fallback code in *fallback.cpp*.

**Comment by floam** [comment]
>Because, @floam, there is no such thing as an ASCII locale. There is the C locale ...
That's the reasoning?

I'm referring to al locale identifiers of POSIX platfroms which either  named ASCII or, alternatively, have a strictly defined collation order and character se which is the same as ASCII, such as C and en_US.ASCII. 

Later if  I mention a UTF-8 locale I will likely mean a locale ending with "UTF-8".

 > Which historically treated every byte value from 0 thru 255 as valid.
I b

**Comment by krader1961** [comment]
> I'm referring to al locale identifiers of POSIX platfroms which either named ASCII 

There is no locale named "ASCII". Can you provide links to documentation which says otherwise? You will find blog posts such as http://mywiki.wooledge.org/locale that talk about the C/POSIX locale as being synonymous with ASCII. Those documents are generally ignorant of the history that results in the current mess we have to deal with.

**Comment by floam** [comment]
I'll say it again, I'm referring to all locale identifier which are either named ASCII or shared properties of ASCII.

A POSIX identifier is named by this format: `[language[_territory][.codeset][@modifier]]`. 

An example of a POSIX identifier with "ASCII" in the name is again, `en_US.ASCII`

**Comment by jakwings** [comment]
Right, it's obvious that nowadays most of us are using UTF-8 locales. I'm just think without presumption. `\uXXXX` and `\UXXXXXXXX` means we can specify Unicode codepoints. `L` is the prefix for `wchar_t` arrays. But UTF-8 is not the only encoding for Unicode characters, there are also UTF-16, UTF-32, etc..

Fish convert bytes to `wchar_t[]` according to the current locale, and `wchar_t` [does not mean Unicode](https://stackoverflow.com/questions/6300804/wchars-encodings-standards-and-portability). So fish is quite confusing here. Only `env_universal_common.cpp` is including `utf8.h`.

Does fish support the C/POSIX locale? I guess it is expected to work well with ASCII characters so that users can run it on almost any operating system. But the reality is there are non-ASCII characters everywhere, and fish behave unpleasantly in this locale. Mixing locales is dangerous, and hardly can we see `LC_*` written in the official fish scripts. `printf` and `read` might happen to be locale-sensitive, I don't know.

**Comment by krader1961** [comment]
FWIW, @floam, I did some research and learned that some distros provide `*.US-ASCII` locales. Presumably to make it explicit that they only recognize code points in the range 0x00 thru 0x7F. Unlike the C locale which historically meant the range 0x00 thru 0xFF but some implementations have redefined to mean US-ASCII. I couldn't find any mentions of locale names like `en_US.ASCII` but since these names are arbitrary it wouldn't surprise me if some distro decided to use that naming convention rather than `en_US.US-ASCII`.

@jakwings: There are very few fish commands that are not sensitive to the locale. The obvious ones are `read`, `printf` and `echo`. But nearly all commands are affected because the locale controls how things like string comparisons and sorting behave. The best we can do is provide reasonable, understandable, behavior if the locale is C (or US-ASCII, POSIX, ISO-8859-x). That behavior cannot be considered to be "correct" for all users and situations since non ISO-8859 characters in the aforementioned locales by definition don't exist.

I'm going to modify this change to implement Python's encode/decode "replace" on error behavior. That is, replace the offending wide character with a question-mark rather than emitting the low byte of the wide char. I'll also tackle making the code which uses functions like **wcstombs()** behave reasonably in single-byte locales just as I've done for **wcrtomb()**.

**Comment by floam** [comment]
Haven't seen it mentioned but as far as character sets go, UCS4 has some convenient properties.

**Comment by floam** [comment]
en_US.US-ASCII is what I had meant. I somehow collapsed a "20" away when I typed it unfortunately.

**Comment by jakwings** [comment]
> Which locales does fish support by default?

Answers to my own question:

Since fish provides `\uXXXX` and `\UXXXXXXXX` (also supported by `printf`), and a comment in `printf`'s source code `src/builtin_printf.cpp (402)` tells us:

> If `__STDC_ISO_10646__` is defined, then it means wchar_t can and does hold Unicode code points, so just use that. If not defined, use the %lc printf conversion; this probably won't do anything good if your wide character set is not Unicode, but such platforms are exceedingly rare.

So let's just assume that fish officially support Unicode, not locales which conflict with Unicode, but C/POSIX is an exception.

Why is the C locale special? For issue #2802, it is because we can deal with bytes directly (0x00-0xFF), though this is not the C locale is invented for. More importantly, fish has already chosen C as the default locale.

---

> But nearly all commands are affected…

Oh yes, I forgot fish use `wchar_t` everywhere… so the input/output is always sensitive to the locale. For string comparisons, I've looked into the source code of builtin functions and find that fish just compares `wchar_t` values directly (with locale-insensitive functions like `strcmp`, `wcscmp` and `std::search`). Not much specially done for different locales. Anyway, the encoding of input/output matters.

> That is, replace the offending wide character with a question-mark rather than emitting the low byte of the wide char.

Now we know that C/POSIX is an important locale, and other locales that conflict with Unicode is unimportant. If only C/POSIX and Unicode locales are supported, how about replacing invalid code points (not wchar_t values) into escaped characters `\uXXXX` or `\UXXXXXXXX`?

**Comment by anordal** [comment]
I like it. Being encoding agnostic is always forgivable.

> treating every byte value as a legal code point

The `C.ISO-8859-1` interpretation, if we can call it that.

> I like how Python does this

I think they fucked up, actually. Python3 assumes ASCII when the locale is C. Which causes a lot of code to *not work* in the C locale (we're talking code that should have been perfectly encoding agnostic, and indeed is in python2). Which is unacceptible. So what does one do? Sprinkle the code with `'UTF-8'` arguments all over the place…

The assumption that C == ASCII is probably not going to be safe before [C.UTF-8](https://sourceware.org/glibc/wiki/Proposals/C.UTF-8) has completely replaced C as the default locale on all relevant platforms (it's not yet in glibc).

**Comment by krader1961** [comment]
@anordal I must be misreading what you wrote:

> The assumption that C == ASCII is probably not going to be safe before C.UTF-8 has completely replaced C as the default locale on all relevant platforms (it doesn't exist yet in glibc).

The problem is that the GNU team did in fact decide C == ASCII (rather than its traditional meaning of all single byte values). They presumably did so to avoid any ambiguity about the single byte code points Unicode adopted from ISO-8859-1.

**Comment by krader1961** [comment]
@jakwings: I just noticed that you wrote this:

> Why is the C locale special? For issue #2802, it is because we can deal with bytes directly (0x00-0xFF), though this is not the C locale is invented for. More importantly, fish has already chosen C as the default locale.

Being able to deal with all single byte values (0x00  - 0xFF) is precisely why the C locale was originally invented. That's because prior to the concept of locales, and the supporting library code was introduced, almost every program written in C treated every value representable by the `char` data type (i.e., a single byte) as legal. So the very first libc implementations that provided support for locales (mostly of the ISO-8859 variety) also implemented a "C" locale which would provide the behavior most of the existing programs expected.

Fish most definitely does not use C as the default locale. As currently written it doesn't even work sensibly in that locale. The current fish code implicitly expects a UTF-8 based locale. And even then it incorrectly, or at least badly, handles a lot of corner cases. Such as when decoding invalid UTF-8 sequences.

**Comment by jakwings** [comment]
> Being able to deal with all single byte values (0x00 - 0xFF) is precisely why the C locale was originally invented.

With the C locale, should the terminal choose ASCII or ISO-8859-X? Reading bytes is one thing, but segmenting&displaying characters is another. I think locale is used to indicate how to deal with characters instead of arbitrary bytes. The C locale just happens to read one byte per character unit, with least surprises for the traditon. Hence `read -n Nchars` read exactly N bytes, however, the definition of valid characters is unknown, well, may be just 0x00-0xFF to bash and fish.

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap07.html#tag_07_02 says:

… The tables in Locale Definition describe the characteristics and behavior of the POSIX locale for data consisting entirely of characters from the portable character set and the control character set. **For other characters, the behavior is unspecified**.

> Fish most definitely does not use C as the default locale. As currently written it doesn't even work sensibly in that locale. As currently written it doesn't even work sensibly in that locale. The current fish code implicitly expects a UTF-8 based locale.

You're right. I misinterpret `wsetlocale(LC_ALL, L"")` as "using the fallback locale C/POSIX" before.
In fact, fish starts with the user-preferred locale, by inspecting `LANG` or `LC_*`. So there is no true default. Using the Unicode charset is the best bet. I do hope only UTF-8 and C is supported, then we don't need wchar and wstring, and this issue may be solved more gracefully.

**Comment by krader1961** [comment]
> With the C locale, should the terminal choose ASCII or ISO-8859-X?

Generally anyone using the C locale should have their terminal configured for a ISO-8859 locale, with ISO-8859-1 being the safest choice. But the reality is that any non-ASCII, non-UTF-8, locale poses problems. Keep in mind that setting any of the locale env vars in your shell has absolutely no effect on your terminal. Which is why anything other than UTF-8 these days is a bad idea outside of very limited use cases. In practice the C locale should be viewed only as a way to have the program handle raw UTF-8 without having any actual knowledge that it is UTF-8. As long as the program doesn't need to perform any manipulation of the non-ASCII code points (e.g., conversion to uppercase) things should mostly work.

There is a good argument to be made for programs to only use UTF-8 internally rather than wide character types like wchar_t and you'll find many people who advocate for that. The problem is a practical one with two big problems. First, the MS-Windows API. Second, the lack of good support in standard libraries like libc for UTF-8 other than serialization and deserialization. In other words, you won't find support for doing things like sorting UTF-8 or doing string operations like converting to uppercase.

**Comment by jakwings** [comment]
> The problem is a practical one with two big problems. First, the MS-Windows API. Second, the lack of good support in standard libraries like libc for UTF-8 other than serialization and deserialization.

This is not a big deal if you don't mind some perfermance cost on Windows. Conversion between different encodings is already troublesome.

> In other words, you won't find support for doing things like sorting UTF-8 or doing string operations like converting to uppercase.

In http://en.cppreference.com/w/cpp/header/locale
`std::toupper(std::locale)`, `std::tolower(std::locale)`, `std::collate`
Sorting: http://en.cppreference.com/w/cpp/locale/collate

**Comment by jakwings** [comment]
It seems that `std::locale` is still a future technology for OS X's official build tools.

**Comment by krader1961** [comment]
@jakwings: Please take another look. I've rewritten the **wgetcwd()** function to use the fish specific **str2wcstring()** function (like most of the fish code) rather than calling **mbstowcs()** (it was the only function to do so). That fixes the problem you were seeing.

I would not be surprised if there are other places in the code that still exhibit strange behavior in the C locale. But this change in its present form passes all unit tests and seems to behave reasonably even when dealing with non-ASCII path names. So unless someone can show how this change introduces new problems I think it should be merged.

**Comment by jakwings** [comment]
Mostly fine, much better than before. But auto-completion and globbing are broken now in the C locale.

Before this patch, fish shows `\Xhh` for non-printable characters in auto-completion. Now it doesn't show anything, and `echo T*` doesn't find "Tür" nor "Tür".

**Comment by jakwings** [comment]
OK, the problems in my comment above only happens when I suddenly change locale to C in a directory whose name contains non-ASCII characters.

**Comment by krader1961** [comment]
Thanks for testing, @jakwings. It would take major changes to the code to have it do the "right thing" in all situations when changing on the fly between UTF-8 and other encodings. For example, it would require dynamically recoding wide char strings that represent cached information (e.g., the values assigned to vars). That effort and complexity cannot be justified. All I'm trying to do here is make fish behave sensibly when it is started in a non-UTF-8 locale even if UTF-8 data is then fed into it (e.g., as a path name from getcwd()). At this point I think the change meets the stated goals and further improvements should be deferred until someone comes forward with a compelling need for better support of the C locale. So if no one objects I'll merge this in a couple of hours.

**Comment by jakwings** [comment]
Personally I suggest doing only all those necessary to fix that `read` function in #2802, until a POSIX master wants to work all day with the C locale.

**Comment by krader1961** [comment]
Closed via merge of c2f1df1d4af0c7e633528cb4c8caa79ef04b0b5a

**Pull request closed without merging**
