### PR TITLE
Add grub-file and grub-install completions

### PR DESCRIPTION
**Pull request by moverest**

### CODE REVIEW

**Comment by krader1961** [comment]
I'm not a fan of having options after the description but I don't see any obvious problems with this change. So LGTM. I'll merge in a day or two unless @faho or someone else sees a problem.

**Comment by faho** [comment]
>I'll merge in a day or two unless @faho or someone else sees a problem.

Nah. In fact I'll go a step further and merge it now.

**Comment by faho** [comment]
>I'm not a fan of having options after the description

In this particular case, I'm actually a fan:

```fish
complete -c grub-install -l target -d 'Install GRUB for given platform' -a 'arm-efi\t arm-uboot\t arm64-efi\t i386-coreboot\t i386-efi\t i386-ieee1275\t i386-multiboot\t i386-pc\t i386-qemu\t i386-xen\t ia64-efi\t mips-arc\t mips-qemu_mips\t mipsel-arc\t mipsel-loongson\t mipsel-qemu_mips\t powerpc-ieee1275\t sparc64-ieee1275\t x86_64-efi\t x86_64-xen\t' -x
```

However, I mostly like it because of the way it looks when wrapped - github happens to wrap after the description. I'd probably make that explicit by breaking after it:

```fish
complete -c grub-install -l target -d 'Install GRUB for given platform' \
-a 'arm-efi\t arm-uboot\t arm64-efi\t i386-coreboot\t i386-efi\t i386-ieee1275\t i386-multiboot\t i386-pc\t i386-qemu\t i386-xen\t ia64-efi\t mips-arc\t mips-qemu_mips\t mipsel-arc\t mipsel-loongson\t mipsel-qemu_mips\t powerpc-ieee1275\t sparc64-ieee1275\t x86_64-efi\t x86_64-xen\t' -x
```

That looks nice and clean, with both the description and the candidates being visible.

If the description were last, it would be easier to overlook after the big chunk of candidates.

What I don't particularly like is how the "-x" is squeezed in there, almost as if @moverest is ashamed of it, but that's such a minute nit that it's not worth holding the PR for.

**Comment by moverest** [comment]
I like the idea of putting the options on a new line.

I find the `-x` at the end easier to read. At a glance, I can tell which options lack `-r`, `-x` or `-f` when it's at the end of the line. I can read the description and only then tell if the option requires a argument. Whereas, if it's before the description, I have to go back and re-read the line. Plus, it sets it apart from `-s`. But, if you want it before the description, I'll do that for the next ones. I'm not against one way or the other.

**Pull request merged**
