### PR TITLE
Solaris fixes

### PR DESCRIPTION
**Pull request by zanchey**
This branch adds some commits which improve the build on Solaris, and produce a working binary.

I added some compile-time tests to the configure script.

### CODE REVIEW

**Comment by zanchey** [comment]
The reason I didn't just merge this is that I'd like some review of a couple of things:

1. The `std::` namespace checks - do these make sense? Is there a better way of doing it?
2. The `flock` fallback and the cppcheck warning - again, are these reasonable or are there obvious errors?
3. Does the check for a threadsafe `errno` look sane?

Thanks!

**Comment by krader1961** [comment]
I took a look at this and didn't see any obvious problems; although, that this is even needed makes me sad. It makes me wonder if building fish on Dynix/PTX, the SysV based OS of my previous employer Sequent Computer Systems, would require the same changes.

I ran `make test` with this PR on macOS and FreeBSD 12. Both passed without any obvious problems. However, running `make lint-all` on macOS reports the following new warnings from oclint:

```
/Users/krader/projects/3rd-party/fish-shell/src/fallback.h:137:9: 'LOCK_SH' macro redefined
/Users/krader/projects/3rd-party/fish-shell/src/fallback.h:138:9: 'LOCK_EX' macro redefined
/Users/krader/projects/3rd-party/fish-shell/src/fallback.h:139:9: 'LOCK_UN' macro redefined
/Users/krader/projects/3rd-party/fish-shell/src/fallback.h:140:9: 'LOCK_NB' macro redefined
```

Regarding the flock fallback I wouldn't have bothered given what I know about how flock is being used by fish. However, since you've implemented a fallback we might as well retain it until such time as its use it removed or otherwise revised.

The thread-safe errno check looks okay to me.

**Comment by krader1961** [comment]
Also, the attempt to suppress some flock warnings is failing for me on macOS with homebrew installed cppcheck 1.76.1:

```
[src/env_universal_common.cpp:601] information (unmatchedSuppression):
 Unmatched suppression: flockSemanticsWarning
```

**Comment by krader1961** [comment]
As the comment I added to that cppcheck output says that warning can probably be ignored. Cppcheck seems to be broken in this regard. I only mention it in case you've made a typo.

**Comment by zanchey** [comment]
> However, running make lint-all on macOS reports the following new warnings from oclint:

I think that's a furphy; those are only defined when HAVE_FLOCK is undefined, which will mean that those constants aren't available.

**Comment by jblachly** [comment]
Latest commit (sorry about delay) builds on illumos (smartos) with gcc.
However, zero is not a valid size_t argument to getcwd on many unixes.

Below will fix. Apart from what now looks like an ANSI error (30m<CR>), fish shell is now working 💯 %  !!!! 
:-) 👍  to all the commiters - I don't know which commits fixed the very bizarre errors related to `access(2)` returning ENOENT and/or EACCES.

```
james@fish-build:~/fish-shell$ git diff
diff --git a/src/wutil.cpp b/src/wutil.cpp
index 3d8c914..2cff992 100644
--- a/src/wutil.cpp
+++ b/src/wutil.cpp
@@ -129,7 +129,7 @@ bool wreaddir_for_dirs(DIR *dir, wcstring *out_name) {
 const wcstring wgetcwd() {
     wcstring retval;

-    char *res = getcwd(NULL, 0);
+    char *res = getcwd(NULL, PATH_MAX);
     if (res) {
         retval = str2wcstring(res);
         free(res);
```

**Comment by jblachly** [comment]
Also @zanchey after looking closely I think it was your `-pthread` commit that fixed the spewing of errors...

**Pull request merged**
