### PR TITLE
Add pkgng command completions

### LINKED ISSUE #1054: Add pkgng completion
https://wiki.freebsd.org/pkgng

Could be nice for FreeBSD 10 release.

### PR DESCRIPTION
**Pull request by xfix**
Fixes #1054.

### CODE REVIEW

**Comment by faho** [comment]
I think we've noticed everything. Here's a list of my criticism (with obsolete points stricken):

- Options-before-commands (`pkg --rootdir $path add $package`)

- ~~Redundant descriptions ("Package")~~

- Incompleteness (can also be done later since this seems to cover most cases already)

- ~~Unnecessary version~~

- ~~Inhibiting fuzzyness~~ 

Merge when you feel it's okay - though I'd suggest squashing.

**Comment by xfix** [comment]
@faho: Okay, I think I fixed the thing about "options-before-commands"

**Comment by faho** [comment]
Yeah, this should work. If you're confident, merge!

**Comment by faho** [comment]
>(and thinking about it, I found a flaw in my code about code like -4c, but eh, this could be difficult to deal with within fish shell framework, and I don't think many people would do that)

Depends on how pkg handles this - if it only recognizes arg-needing options as the last in the group (i.e. "-4c" is okay, "-c4" isn't), then you can just add another "\*" - `case -\*{{o,j,c,r,C,R}`

**Comment by xfix** [comment]
``-c4`` is okay, it's a single parameter, ``-c`` with value ``4``, while ``-4c`` is two parameters, ``-4`` and ``-c``, and it awaits a value for ``-c``.

**Comment by xfix** [comment]
Merged with rebase in any case (although I didn't notice your code comment until too late).

(it was a while since I did anything in fish shell)

**Comment by faho** [comment]
So it's like:

- If an option group ends with an option that takes an argument, we need to skip the next arg

- If an option that takes an arg is anywhere else, it takes the rest of the group as argument (or only the next letter)

Well, this is a bit quirky but should be doable.

**Comment by faho** [comment]
>Merged with rebase in any case (although I didn't notice your code comment until too late).

Yeah but you seem to have fixed it right away. Nice work!

**Comment by faho** [comment]
> If an option group ends with an option that takes an argument, we need to skip the next arg

This should almost work just by adding another "\*" between the "-" and the argument-taking shortopts like I commented above: `case -\*{o,j,c,r,C,R}`. The only part that wouldn't be working is if you have an argument-taking opt and an argument to that that looks like an argument-taking opt in the same group (e.g. "-cr"). I'd be okay with that since it seems like all argument-taking opts take directories, so the edge-case is only triggered if the user wants to use a directory named "r" or similar.

**Comment by xfix** [comment]
@faho: Option `-j` is a jail identifier.

(and by the same logic, it's unlikely the user will want to use even one option, not to say many of those global options)

**Comment by faho** [comment]
>Option -j is a jail identifier.

Which doesn't make much of a difference - or is "c" or "R" a typical jail identifier?

If you want, fix it, if not, okay.

**Comment by xfix** [comment]
@faho: No, but darthvader may be a jail identifier. ``-jdarthvader`` is fine.

**Comment by faho** [comment]
Yeah, you're right.

**Pull request closed without merging**
