### PR TITLE
Fastabbr2 - Electric B<SPACE> (Optimize abbr more)

### PR DESCRIPTION
**Pull request by faho**
As before, this is another attempt at making abbr fast.

And as before, I might have missed something so testing is appreciated!

Bailing out early turned out to be a massive improvement - possibly enough that we don't need to warn people not to call `abbr` in config.fish anymore (of course it's still going to be faster, but it's probably going to be fast enough for most cases).

The other commit changes more code and has less of an impact, but it also changes it to a style I find more readable.

@alphapapa: This is what I was talking about, please test!

### CODE REVIEW

**Comment by zanchey** [comment]
LGTM!

**Comment by ridiculousfish** [comment]
Nice

**Comment by pickfire** [comment]
Looks nice, it works but not sure how to benchmark it.

**Comment by faho** [comment]
@pickfire: You'll want something like `fish --profile abbr.log -c 'source SOMETHING_WITH_ABBRS_IN_IT.fish'; sort -k 2 --numeric-sort abbr.log`. Then before the `source`, you can `source` this version of abbr.fish (or the older one if you've built with this). Instead of the builtin profiling you can also use `time`, of course, but it's less granular.

If you want to test the case where there's new abbreviations, you'll need to `set -e fish_user_abbreviations`.

**Comment by faho** [comment]
Merged, thanks!

**Pull request closed without merging**
