### PR TITLE
completions: shorten descriptions

### PR DESCRIPTION
**Pull request by dundargoc**
Work on https://github.com/fish-shell/fish-shell/issues/6981

### CODE REVIEW

**Comment by faho** [comment]
Note: It's entirely okay to shorten multiple completions in one PR. Please add more commits instead of opening separate PRs.

**Comment by dundargoc** [comment]
Noted. I'll close this then?

**Comment by faho** [comment]
No, it's fine. I merged the others already.

Just next time don't open five PRs in quick succession.

**Comment by faho** [comment]
If you have anything more coming up, just push to this branch - I'll keep this one open for that.

**Comment by dundargoc** [comment]
I don't have any more completion shortening in me left :)

**Review by floam — APPROVED** [review]

**Comment by floam** [comment]
This is a lot of help, thanks @dundargoc.

**Pull request merged**
