### PR TITLE
fish_should_add_history function

### PR DESCRIPTION
**Pull request by BCNelson**
## Description

Adding a function `fish_should_add_history` to check if an item should be added to the history. I think that there need to be alot more discussion on how this feature should work. I would also welcome feedback on hope I implemented the feature.

Fixes issue #5924

## TODOs:
- [ x ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
I think the biggest question here is how many possibilities this should expose.

Here's what happens currently:

1. If you are running a normal shell, things are typically saved to disk (that's a mode of "disk")
2. If you have turned on private mode, things are "saved" to memory - so they are available in the current session but disappear after
3. If an entry starts with " ", it is an "ephemeral" entry

That last part was changed in #1383. Before, any ignored history entry was actually ignored - you would run ` echo foo` with the leading space, and it was gone *immediately*. There was absolutely no way to recall it, ever.

This was an issue if you made an error in such a command and wanted to run it again with fixes, so you would have to e.g. copy-paste it from the terminal into the terminal again.

So what we did was store it, in memory, until you run another command. So if you execute ` echo foo` and realize it should have been ` echo bar`, you can correct your mistake, but it's still gone.

And this PR here now allows you to both skip entirely, which has these downsides, and select the other kind of saving - so you could store things on disk even in private mode.

With that in mind, I would simplify this:

I would expose two possibilites: Stored as normal or ephemeral.

If `fish_should_add_history` returns 0, the entry is stored as normal, whether that's on disk or in memory (in private mode).

If it returns anything else, the entry simply becomes the ephemeral entry.

**Comment by BCNelson** [comment]
> 1. If you are running a normal shell, things are typically saved to disk (that's a mode of "disk")
> 2. If you have turned on private mode, things are "saved" to memory - so they are available in the current session but disappear after
> 3. If an entry starts with " ", it is an "ephemeral" entry

That tracks with what I understood from the code

> And this PR here now allows you to both skip entirely, which has these downsides, and select the other kind of saving - so you could store things on disk even in private mode.

That is not entirely accurate. `fish_should_add_history` is only evoked when the history item would normally be saved to disk. If the command starts with `L" "` or we are in private mode the items history mode is `ephemeral` or `memory` respectively.

> With that in mind, I would simplify this:
> 
> I would expose two possibilites: Stored as normal or ephemeral.
> 
> If fish_should_add_history returns 0, the entry is stored as normal, whether that's on disk or in memory (in private mode).
> 
> If it returns anything else, the entry simply becomes the ephemeral entry.

I don't love these limitations because it removes one of my uses cases. That being after I run the `clear` to remove the large output of a previous command I don't need the clear command stored in history because the screen is cleared and a never need or want to run `clear` immediately after.

**Comment by faho** [comment]
>That being after I run the clear to remove the large output of a previous command I don't need the clear command stored in history because the screen is cleared and a never need or want to run clear immediately after.

To be clear: The only limitation here would be that, right after you run `clear`, you could press up-arrow and it would show `clear`. As soon as you run another command that `clear` is gone.

The reason I don't want to expose commands being ignored entirely is that then we end up in the same situation as with space - people run a thing, notice that they want to run it again but now they can't.

And it's easy to put the fault on them, because they "could have made the right decision" - "why didn't you set it up correctly", but this is the sort of decision that's quite unclear at the time where it's made and is an undue burden to put on users.

Compare this to history size - that's also a popular knob in other shells, and it's also a decision users need to make long ahead of where it actually matters, because at some point you end up hitting that limit, and once you notice it and notice you chose wrong you would have to use your time machine to go back  to make the correct decision. So, we simply don't play, and we simply don't offer that option.

---

In your case could just press ctrl-l, which will also run `clear` but not via an actual commandline so it never enters history to begin with.

**Comment by BCNelson** [comment]
> In your case could just press ctrl-l, which will also run clear but not via an actual commandline so it never enters history to begin with.
Fair enough

Another potential problem with my implementation is that the logic around when `fish_should_add_history` is run is complex. It can be summed up simply as whenever a history item would be persisted to disk it is run. However the simplicity of that statement is deceptive as the logic around saving to disk is not straight forward nor, as far as I know, document in one place.

An option that was brought up in [#5924](https://github.com/fish-shell/fish-shell/issues/5924#issuecomment-502176484) by @ridiculousfish is to have a default implementation of `fish_should_add_history` that does all of the logic around the saving of history. This does require branching on the return of `fish_should_add_history`.

**Comment by BCNelson** [comment]
@ridiculousfish @faho What are your thoughts on the future of this PR?

Also I have found over the past month, ctrl-l has inconsistent behavior. I have tried in Konsole, vscodes Terminal and Gnome terminal sometimes it does clear the screen. However sometimes it moves the prompt to top of the screen but keeps the history so you can scroll to in still in the terminal. Do you have an other suggestions to get the desired behavior. If not I would still benefit from allowing multiple returns from the functions

**Comment by faho** [comment]
>What are your thoughts on the future of this PR?

I still believe that the modes this exposes should be simplified.

It should not be possible to override private-mode with this (i.e. no forcing "save to disk").

I also remain unconvinced that it's wise to allow not saving something *at all* - experience has shown that that exacerbates mistakes and people end up regretting it. I don't want to include a footgun when the alternative is to minorly inconvenience some extremely specific use case (you'll see the temporary entry until you run something else).

So I'm still of the opinion that it should return 0 for "save however you would save" and "don't save except temporarily as the last entry".

Other than that, I'm okay with the idea. I think this the right way to allow this to be configured, instead of a cheesy variable.

---

>Also I have found over the past month, ctrl-l has inconsistent behavior.

This is probably down to the behavior of `clear`, which sends terminal-specific escape sequences.

Typically it sends one that means "clear the screen", and in some cases it will then *also* send "clear the scrollback buffer" - which is a fricking terrible decision, so we try to work around it. It appears that may be incomplete.

You can try `clear -x`, which, depending on your `clear` might skip the clearing of the scrollback, or you can try `bind \cl 'clear; commandline -f repaint'` without our hacks.

**Comment by faho** [comment]
I'm going to close this for the time being as it has conflicts.

If anyone wants to work on it, be my guest.

**Pull request closed without merging**
