### PR TITLE
pacman completion: Turn into regular completion

### PR DESCRIPTION
**Pull request by faho**
This used to be a function because we didn't have complete -w

Use that and it becomes a bit simpler.

This also simplifies the code in a few other ways (like removing a
useless-use-of-cat)
and adds comments about a few edgecases.

Note that a few of the wrappers (like yaourt) have their own options which need to be added, but I don't use them.

### CODE REVIEW

**Comment by faho** [comment]
Urgh, sorry, this is garbage.

**Comment by faho** [comment]
Sorry, _that_ was garbage. I had checked out the wrong branch.

**Comment by pickfire** [comment]
It seems that it is the same thing. Any inprovement?

**Comment by faho** [comment]
This PR didn't need changes, I just noticed pacman completions weren't working and closed it, then I noticed they weren't working because I had checked out my master branch instead of my pacman-commpletions branch and reopened it.

It doesn't change much from current fish-shell master, mostly it makes the completion normal, removing the need for a __fish_complete_pacman function - we now have wrapping completions for that.

**Comment by ridiculousfish** [comment]
Looks good. Merged as 882f4714ac75732cb69999ea4ab82e8662f53031. Thanks!

**Pull request closed without merging**
