### PR TITLE
Add explanation on abbreviations vs aliases with `sudo`

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by faho** [comment]
This isn't actually *correct* as such.

If you have an abbreviation "v" for "vim", you can't really do `sudo v`, because we currently only expand abbreviations in command position.

That makes this misleading, which is why I'm rejecting this. Thanks anyway!

**Comment by lucatrv** [comment]
Sorry I realized it only now! I was referring to issue #7044 and for some reason got convinced that abbreviations were always expanded... now I tested it and found out that it's not the case. Could this be addressed in future, for instance by expanding them not only in command position but also after `sudo`? Or otherwise do you have any other advice that could be reported in the documentation on how to correctly work with `sudo` since aliases cannot be used? Thanks

**Comment by faho** [comment]
>Could this be addressed in future, for instance by expanding them not only in command position but also after sudo?

#5003

**Comment by faho** [comment]
>  Or otherwise do you have any other suggestion that could be reported in the documentation on how to correctly work with sudo since aliases cannot be used?

Enter whatever you want, press alt+s. This adds or removes a `sudo` prefix.

Use abbreviations that already have `sudo` included or start a root shell. Whichever works for you.

**Pull request closed without merging**
