### PR TITLE
Allow null character input (\x00) to be bound to action

### PR DESCRIPTION
**Pull request by krackers**
Fixes issue #3189 by removing dependence on a predefined empty string mapped to self-insert as a fallback bind pattern when no other could be matched. Input mapping matcher is also modified to properly handle null-character maps.

### CODE REVIEW

**Comment by krader1961** [comment]
I'm curious, @krackers, why you closed this? I was going to review it in a couple of hours.

**Comment by krackers** [comment]
The unit tests seem to have failed :(. I'll investigate and reopen once I get them working

**Comment by krader1961** [comment]
Okay. If you haven't read it take a look at the [CONTRIBUTING](https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md) guidelines. For example, running `make test` on your local system is usually a good thing to do before pushing a commit.

**Comment by krackers** [comment]
Thank you. I'll be sure to do that next time!

I'm actually kind of unclear at what specifically went wrong in the bind unit test though. Could you please take a look at the travis-ci output and provide a suggestion?

**Comment by krader1961** [comment]
The *bind.expect* test timed out due to not finding the expected output from the fish process. When this happens to only one of the three test environments it is usually a transient problem and simply forcing the test to be rerun succeeds. In your case all three test environments failed in the same way so you change has either broken existing behavior or exposed a bug in the unit test. See https://travis-ci.org/fish-shell/fish-shell/builds/144841857

**Comment by floam** [comment]
Did you notice the compiler warning?

```
src/input.cpp:548:10: warning: address of 'default_selfinsert_mapping' will always evaluate to 'true'
      [-Wpointer-bool-conversion]
    if (&default_selfinsert_mapping) {
    ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Pull request closed without merging**
