### PR TITLE
Fix multi-line prompt resize

### LINKED ISSUE #2320: Multi-line prompts are repeated when the terminal window is resized. (repeat of #321)
This bug is still occurring with both multi-line and single-line prompts.

### PR DESCRIPTION
**Pull request by Eyenseo**
There is one 'issue' with this fix:
While resizing a multi-line prompt the cursor, prompt and content of the
terminal is moving upwards to the top of the terminal. I guess the reason
for that is that the terminal is seeing that something is written to it
and decides that it needs to scroll to keep everything visible.

Please review it for compatibility - I tried it with termite on archlinux. I tested multi and single line prompts with resizes that didn't interfere with the prompt and interfered with it. 

There **should** be a problem with terminals that do not soft wrap. I do not know how to check for that so a fix for these kinds of terminals has to come from someone else. But it should be stright forward to do see line 1190 1200 of the s_reset function. 

Edit: Fixes #2320

### CODE REVIEW

**Comment by krader1961** [comment]
@Eyenseo, Is there an open issue for this change? If not please open one that documents the problem this is attempting to fix. Include screen shots, [asciinema captures](https://asciinema.org/) or whatever else would help someone understand the issue. Then update the commit comment to include a line like "Fixes #123456".

**Comment by Eyenseo** [comment]
@kballard the issue is #2320 - as specified in the title I also included the number in my first comment for convenience

**Comment by Eyenseo** [comment]
I see that travis fails - which standard are you targeting? I thought it was C++11 as I used your build system and nothing failed ...

**Comment by krader1961** [comment]
My apologies, @Eyenseo, I was looking for a "Fixes #2320" or similar line in the body of the comment and completely missed the reference in the title. FWIW, putting such a line in the body of the commit comment is preferable to putting it in the summary because a) that's what we're conditioned to look for and b) the issue will be automatically closed when the change is merged.

You can click on the "Details" link next to where it says "The Travis CI build failed" to get details about the nature of the problem.

**Comment by floam** [comment]
fish uses some C++11 features, and the goal is to move towards C++11 - it currently is in a bit of limbo and may compile as just about anything.

**Comment by Eyenseo** [comment]
@krader1961 no worries! Thank you for the explanation, I will keep that in mind for the next time :)
@floam I see, gcc moved to default to C++11 so that was what I expected was set by you in the makefile

Could someone explain me why the test failed? I can't execute that test myself I get:
```
fish-shell/src/fish_tests.cpp:657: undefined reference to `io_chain_t::io_chain_t(std::tr1::shared_ptr<io_data_t> const&)'
collect2: error: ld returned 1 exit status
```

**Comment by Eyenseo** [comment]
ok I got it to compile with C++11 and am failing no tests

**Comment by krader1961** [comment]
I can't explain why you're getting that build failure but the Travis CI tests are now failing with this:

> [DEBUG] timeout; buffer=fish: src/screen.cpp:1184: void s_reset(screen_t*, screen_reset_mode_t): Assertion `prompt_layout.line_count >= 1' failed.\r\n

So your change is causing an `assert()` to trigger.

**Comment by Eyenseo** [comment]
@krader1961 ah ok thank you (first time I have to work with travis in this way)

**Comment by krader1961** [comment]
I patched your change into my local repo and `make test` fails in the same fashion as Travis CI is reporting.

**Comment by Eyenseo** [comment]
@krader1961 Yes I changed the behaviour of the `calc_prompt_layout` function - I reverted that back my code checks for that case too so I have no problem with it being that way.

**Comment by ridiculousfish** [comment]
Thanks for taking this on! I have to test this fix on termite - I'm not able to reproduce #2320 currently on iTerm2.

**Comment by krader1961** [comment]
@ridiculousfish, This is starting to smell from neglect :smile:. I have concerns about the change due to its introduction of `nullptr` (not currently used in the fish code base), what appear to be some lint issues, and the hardcoding of escape sequences (e.g., line 614 of *screen.cpp*). Also, I made only a half-hearted attempt to reproduce the problem and was unable to do so. So it's an open question whether or not this fix is still relevant.

@Eyenseo, If you build and run fish from git master can you still reproduce the problem this change is intended to fix? If so can you provide instructions in issue #2320 that would help others reproduce the problem?

**Comment by floam** [comment]
Our codebase is mostly a bunch of old C. As a C++ project I don't think we should be judging nullptr problematic.

**Comment by krader1961** [comment]
> As a C++ project I don't think we should be judging nullptr problematic.

The `nullptr` symbol was introduced by C++11 (the C++ 2011 standard) which is not available in C++03 that we expect out code to be compatible with. So it is clearly problematic unless we're going to change out minimum supported C++ standard.

**Comment by Eyenseo** [comment]
@krader1961 The bug has not been fixed in the master branch. This pull request still works as advised.

**Comment by ridiculousfish** [comment]
When I test this with a multiline prompt, it causes window resizing to reliably erase output from previous commands, on iTerm2.  I think we need a different approach here.

**Comment by Eyenseo** [comment]
@ridiculousfish I'll close this

**Pull request closed without merging**
