### PR TITLE
change how redirections are formatted

### LINKED ISSUE #2899: `fish_indent` converts `2>&1` into `2>& 1` (note the space)
Using `fish_indent` from git head as I type this I noticed that it converts `2>&1` into `2>& 1`. Is that really what we want for the canonical form of a file descriptor redirection?

This came to my attention as part of doing a final sanity check of the `make style` target I'm introducing to ensure code matches the style guide.

### PR DESCRIPTION
**Pull request by krader1961**
Modify `fish_indent` to emit redirections without a space before the target of
the redirection; e.g., "2>&1" rather than "2>& 1" as the former is clearer to
humans.

Fixes #2899

### CODE REVIEW

**Comment by krader1961** [comment]
@ridiculousfish I think a sanity check from you is a good idea since I'm changing the logic of code you wrote a couple of years ago.

**Comment by ridiculousfish** [comment]
There's a fair amount of other changes in this commit - which part should I look at?

**Comment by krader1961** [comment]
Yeah, sorry about that. I needed to understand how the parser tokenizes the text so I added a bunch of code to produce a nicely formatted display of the parse tree. The heart of the fix is at line 159 in *fish_indent.cpp*:

```
if (prev_node_type != parse_token_type_redirection)
{
    append_whitespace(node_indent, do_indent, *has_new_line, out_result);
}
```

The rest of the change is lint and style cleanup of nearby code.

**Comment by krader1961** [comment]
Also, I can see the logic for deciding if whitespace should be emitted becoming increasingly complicated and will likely need to be a distinct function in the future. But for now I think the inline `if()` is okay.

**Comment by ridiculousfish** [comment]
Gotcha. This will also reformat this:

    cmd > /tmp/out.txt ^ /dev/null

into

    cmd >/tmp/out.txt ^/dev/null

and similarly for input. Do we like that change?

If not, we can only do this with fd-style redirections by using `parse_node_tree_t::type_for_redirection` and and limiting this fix to TOK_REDIRECT_FD.

**Comment by krader1961** [comment]
I normally don't insert a space even for the pathname case to be consistent with the fd case. But if you or anyone else feels the space improves readability of the former I'm happy to make fish_indent treat the two cases differently.

**Comment by krader1961** [comment]
Also, the TOK_REDIRECT_FD symbol isn't exposed in the parse tree; see `parse_token_type_from_tokenizer_token()`. So limiting it to just that case would involve either adding that data to parse_token_type_t or having fish_indent use the `redirection_type_for_string()` function that is currently only used by *fish_tests.cpp*.

**Comment by ridiculousfish** [comment]
One could get the parent of the node, which will be a `symbol_redirection`, and then pass that to `parse_node_tree_t::type_for_redirection` to determine the redirection. That's the only non-test client of `redirection_type_for_string`

**Comment by ridiculousfish** [comment]
(But I also don't care one way or the other about that space.)

**Comment by krader1961** [comment]
Okay, I decided to keep the "no space" behavior for both cases since consistency seems compelling to me. Merged as 4ff8e6e7818747d805ac44be0a36aedef4deaa5c (I augmented the test).

**Comment by ridiculousfish** [comment]
Thanks!

**Pull request closed without merging**
