### PR TITLE
adds dnf completions for package installs

### PR DESCRIPTION
**Pull request by erdosboti**
On Fedora 23 I experienced that yum autocompletions works but dnf doesn't. Adding this dnf file seems to solve the issue.

### CODE REVIEW

**Comment by faho** [comment]
Doesn't dnf accept the exact same arguments as yum? In that case it'd be a bit simpler to just use `complete -c dnf -w yum`, no?

**Comment by erdosboti** [comment]
To be honest I'm new to Fedora and also did not really look into fish internals, so I guess what you suggest must be the correct solution :)

**Comment by faho** [comment]
I maybe should have explained that - the "-w" or "--wraps" option inherits completions from another command.

It makes fish handle dnf completions just like yum, which seems to be the right thing.

**Comment by faho** [comment]
Merged as bb932a0a0a9d860af5311714cad40660489b6556. Thanks!

**Pull request closed without merging**
