### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tobiasmuehl**
I also needed the autoconf package on my system, so adding it to the general template

### CODE REVIEW

**Comment by zanchey** [comment]
You shouldn't need `autoconf` unless you're building from git master - is this what you're trying to do?

**Comment by krader1961** [comment]
I would argue this isn't really needed. Anyone who has built open source code more than once knows that there are some near universal prerequisites. But if people feel mentioning the need for tools like __autoconf__ is helpful to people new to the process this change should be broader. I would break the package prerequisites into two or more groups. The first would include the generic development tools (e.g., __autoconf__, __make__, __gcc__) needed to build fish. The others would focus on specific subsystems needed by fish (e.g., __ncurses_dev__).

**Comment by tobiasmuehl** [comment]
yes, should one not build from master?

Kurtis Rader <notifications@github.com> schrieb am Fr., 18. Dez. 2015 01:16:

**Comment by krader1961** [comment]
> yes, should one not build from master?

Yes, @tobiasmuehl, you should build from the master branch if you're intending to contribute changes to the project or even to simply verify whether a problem you're seeing has already been fixed. Otherwise you should not be building fish from the head of the master branch but should instead be using a pre-built package for your OS. The question is whether or not the documentation really needs to mention every prerequisite; including those like __gcc__, __make__, and __autoconf__ that are required to build nearly every open source project.

Also, when contributing a change it is customary to use a meaningful name for your branch ("patch-1" isn't meaningful).

**Comment by ridiculousfish** [comment]
"built open source code more than once" is definitely not a requirement for building fish, and new users reporting what would have helped them is exactly the sort of thing that makes fish better. Merged as d6d3977f3d66dad6fdc77b648c4e96f2c1043154 . Thanks!

**Pull request closed without merging**
