### PR TITLE
Update visual vi key bindings

### PR DESCRIPTION
**Pull request by maxfl**
* Add home/end, $/0 keys
* Add (c)hange key
* Add j/k keys for up/down

### CODE REVIEW

**Comment by maxfl** [comment]
@krader1961, I've used \$ and \^ as you suggested. I also updated the other places where unicode codes were used.

Could you also clarify what you mean when you say 'these bindings are already defined elsewhere in this file'? Maybe I'm misunderstanding something but I see no duplicate definition with these keys. The definitions I see are applied to the different modes 'normal' and 'visual' and therefore the are defined twice.

**Comment by krader1961** [comment]
> Maybe I'm misunderstanding something but I see no duplicate definitions with these keys. 

Run `grep -n -- -of-line beginning-of-line share/functions/*_key_bindings.fish`. Are you perhaps looking at an out of of date copy of the file? In mine I see

```
fish_vi_key_bindings.fish:54:  bind \x24 end-of-line
fish_vi_key_bindings.fish:55:  bind \x5e beginning-of-line
fish_vi_key_bindings.fish:56:  bind 0 beginning-of-line
fish_vi_key_bindings.fish:57:  bind g\x24 end-of-line
fish_vi_key_bindings.fish:58:  bind g\x5e beginning-of-line
fish_vi_key_bindings.fish:59:  bind \e\[H beginning-of-line
fish_vi_key_bindings.fish:60:  bind \e\[F end-of-line
```

**Comment by maxfl** [comment]
Here is the file I'm looking at is from this merge request:
https://github.com/maxfl/fish-shell/blob/originmaster/share/functions/fish_vi_key_bindings.fish
and there are no these lines:
Do you see this lines in 'Files changed' tab in this discussion?

**Comment by krader1961** [comment]
I have no idea what I was looking at last night. I now see that the lines I was asking @maxfl to remove were in fact replaced by his change with __for__ loops.

LGTM, :+1:

**Comment by faho** [comment]
Merged with rebase. Thanks!

**Pull request closed without merging**
