### PR TITLE
Add `read --delimiter`

### PR DESCRIPTION
**Pull request by faho**
## Description

This adds a `--delimiter` (or "-d") option to builtin read. It allows the same thing that setting $IFS does. It falls back to $IFS if the option wasn't given.

There's some issues left here:

- Specifying multiple characters - `echo abcdbce | read -d 'bc' foo bar baz` sets $foo to "a", $bar to "d" and $baz to "ce". That seems highly unintuitive. This behavior existed previously, but this is the chance to fix it.

- Specifying the delimiter as "-dDELIM" works as long as that DELIM isn't empty (`''`). In that case, it needs to be specified as `-d ''` or `--delimiter=''` or `--delimiter ''`.

Work towards #4156.

## TODOs:

- [x] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added
- [ ] User-visible changes noted in CHANGELOG.md

Since this is backwards-compatible (only adding a feature), we could add it to 2.7.

### CODE REVIEW

**Comment by krader1961** [comment]
> That seems highly unintuitive.

It is both unintuitive and different from how `string split` behaves. For a minor release we only have two choices: keep the current behavior or make it compatible with `string split` but only if `--delimiter` is used rather than `$IFS`. In fish 3.0 we could also change how it behaves when using IFS.

As for the issue with using an empty delimiter not much we can do about that. It could be partially mitigated by specifying `optional_argument` rather than `required_argument`. But that only works if another flag follows `-d`. I prefer we outright fail if we can't unambiguously tell whether a value was given for the flag.

BTW, we should also modify `string split` to accept more than one delimiter. At the moment if you do something like `string split ab` it splits on `b`. Which itself is weird since I would have expected `a`.

**Comment by faho** [comment]
>keep the current behavior or make it compatible with string split but only if --delimiter is used rather than $IFS.

I was leaning towards doing it for --delimiter. But I'd like to see how this is used currently. Maybe there's logic behind the current behavior? Or it's possibly just unintended (i.e. what we could call a "bug" if nobody was using it).

>It could be partially mitigated by specifying optional_argument rather than required_argument. But that only works if another flag follows -d.

Yes, I tried that. I'd consider it worse.

>BTW, we should also modify string split to accept more than one delimiter. At the moment if you do something like string split ab it splits on b. Which itself is weird since I would have expected a.

One thing that's important to note is that this uses IFS semantics - which is basically a "set of delimiter-characters" - any character in that is a delimiter by itself. `string split` on the other hand can split on multi-character things - only the entire thing is a delimiter.

So e.g. `string split "..." "a...b...c"` will result in "a", "b", and "c" as three distinct elements.

We could obviously make these consistent. If I had to pick I'd rather have string's semantics (and maybe add a `--delimiter` option there that can be given more than once).

**Comment by krader1961** [comment]
Ugh! I did not know that `string split` behaved that way. The man page doesn't document that behavior. Not even by way of an example. I can't find a single place where more than a single character is used in Fisherman or OMF scripts. There are only three such uses in the fish code: completions/git.fish, completions/defaults.fish, completions/pygmentize.fish. The first is trivial to do another way. The second would work without change if we made it behave like `read`. And the third appears to be an error since pygmentize doesn't produce names separated by ", " (at least not the version on Ubuntu 16.10).

My vote is to have `read` behave like `string split`: a multi-char delimiter is used literally rather than split into single char delimiters. But accept more than one `-d` flag so you can get IFS like semantics.

**Comment by faho** [comment]
>The man page doesn't document that behavior. Not even by way of an example.

We should probably make that clearer, yes. The man page says it "splits each STRING on the separator SEP", i.e. it doesn't mention that SEP is a set of characters. That by itself would probably be understood correctly, but once you compare it with IFS....

>There are only three such uses in the fish code: completions/git.fish, completions/defaults.fish, completions/pygmentize.fish.

I'm quite sure that I've done something like splitting on " = " before, but it's possible that was just in my own scripts.

I do believe that multi-char delimiters are useful.

>My vote is to have read behave like string split: a multi-char delimiter is used literally rather than split into single char delimiters. But accept more than one -d flag so you can get IFS like semantics.

Okay. Should we merge this before or do it as part of this change? (As a note, I'll be gone on the weekend)

**Comment by krader1961** [comment]
I think it should be changed to behave like `string split` when given a `--delimiter` but retain the current behavior when falling back to IFS.  Don't bother implementing support for more than one `-d` flag. Let's wait till we see a couple good use cases before we generalize like that. This way we don't risk breaking any existing uses while making it more flexible and consistent with `string split`. It also means you should be able to simply call the existing `split_about()` function to do the job. Also, you might consider renaming the flags to `-S` and `--sep` for consistency with `string split` terminology.

**Comment by faho** [comment]
>Also, you might consider renaming the flags to -S and --sep for consistency with string split terminology.

That terminology is only used in the documentation (there is no such _option_ to `string split`), so I'd rather change that. Both because of the `cut` precedent and because of the capital "S" - there will be confusion with "-s" if we use that.

**Comment by krader1961** [comment]
@faho, I don't think this is sufficiently compelling to include in our final 2.x release. I recommend deferring to the 3.0 release.

**Comment by krader1961** [comment]
@faho, I'd still like to see this merged but I'm closing because it needs to be rebased on the `major` branch since we shouldn't merge any more feature changes on the `master` (i.e., 2.7.0) branch. At this point in time only bug fixes and completion scripts should be merged to `master`.

**Pull request closed without merging**
