### PR TITLE
New informative Git prompt implementation

### PR DESCRIPTION
**Pull request by haarts**
**UPDATE**: This branch can now be merged as per https://github.com/fish-shell/fish-shell/pull/978#issuecomment-23671826 comment. 

I've created this pull request as a direct result of the discussion in #880 (especially [this](https://github.com/fish-shell/fish-shell/pull/880#issuecomment-19737984) part).

In summary I (think I have) achieved 4 goals:
1. **Convention over configuration**: Lots of configuration parameters have been removed favor of sane defaults.
2. **Clarity**: The code has been split in several functions and the control flow has been simplified. Also variables have gotten sane names. 
3. **Modularity**: Functions can be overwritten. Think building blocks!
4. **No magic**: I removed the color and char setting methods and replaced them with default `set_color` calls.

There are three things which need more attention;
1. On the bottom of the file are a couple of lose ends. Annotated with FIXME's.
2. The function `__fish_git_prompt_show_upstream` is complex and I could use some help there.
3. I would love for ppl to test this implementation.

I would especially like the view of @zanchey, @terlar and @mariuszs on this subject.

A quick prompt to test this:

    function fish_prompt
      printf '['
      set_color green
      printf '%s@%s:' (whoami) (hostname|cut -d . -f 1)
      set_color 23f
      printf '%s' (prompt_pwd)
      set_color normal
      set -l os
      set -l git_dir (git rev-parse --git-dir ^/dev/null; set os $status)
      if test $os -eq 0
         printf ']%s ' (__fish_git_prompt_new)
      else
         printf '] '
      end
    end

### CODE REVIEW

**Comment by krader1961** [comment]
Can this PR be closed? It hasn't had an update in more than a year. In my day job any proposed change that hasn't had been modified in the past month is considered dead.

**Comment by faho** [comment]
There's some really nice ideas in here, but there's also some rather bad parts (like calling ´sh` for string handling, a feature I'm not actually sure is in POSIX).

I'd rather someone (maybe me, let's see if I can find the time) use this as inspiration for a new attempt than merge it as-is.

Sorry this has been open for so long, and sorry for the rejection!

**Comment by lloeki** [comment]
@faho maybe this is closer to what you're looking for in such a PR

**Comment by lloeki** [comment]
@faho maybe #1757 is closer to what you're looking for in such a PR

**Comment by SaswatPadhi** [comment]
This is a suggestion from #2824.

The idea is to display the number of branches on the prompt too.
Something like `(master↑1↓2⎇3|●3✖4✚5…6)`.

I have raised an issue at [zsh-git-prompt#82](/olivierverdier/zsh-git-prompt/issues/82) to see what the author thinks of it.

But we could also add this as an additional feature which would disabled by default, but can be enabled by users who want it -- so people switching from other shells won't be surprised.

**Pull request closed without merging**
