### PR TITLE
The great vcs prompt renaming and documentationing

### PR DESCRIPTION
**Pull request by faho**
## Description

This renames the vcs-prompt functions and adds documentation.

`__fish_X_prompt` becomes `fish_X_prompt`.

The variables and helper functions have not been renamed.

Shims have been added at the old names. We can add deprecation warnings and remove them later, if we so decide.

Fixes issue #5586.

## TODOs:

- [X] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

This PR is mainly in case I missed anything - a reference to the old name perhaps.

(also 1337 additions.. nice!)

### CODE REVIEW

**Comment by mqudsi** [comment]
Just to be clear, this includes committing to supporting them and maintaining backwards compatibility the same way we would with any builtins or functions?

**Comment by floam** [comment]
Why not just call it `git_status`?

**Comment by faho** [comment]
>Just to be clear, this includes committing to supporting them and maintaining backwards compatibility the same way we would with any builtins or functions?

Yup.

I mean it's not like we've changed these willy-nilly before.

>Why not just call it `git_prompt`?

Because it's nice to tell people that this comes from fish. I could conceivably imagine an external command called `git_prompt` (though it would probably be called `git-prompt` instead to be accessible via `git prompt`).

**Comment by faho** [comment]
(Also the title was that way on purpose. I thought it was funny :smiley_cat:)

**Pull request merged**
