### PR TITLE
Fix index out of bounds

### PR DESCRIPTION
**Pull request by EMayej**
Fixes issue #

array out of bounds

dirh encounters out of bounds error when current dir is the first one in history.

### CODE REVIEW

**Comment by krader1961** [comment]
I suspect you are using fish on OS X/macOS. Does `type seq` return "/usr/bin/seq" or some other path? If you are using fish on that OS, without GNU coreutils installed, the problem you're reporting is not surprising. But before merging your fix I'd like to ensure we understand the problem.

P.S., This is a good example for why I like to see a fix associated with an open issue that includes the details I just asked for 😸

**Comment by EMayej** [comment]
Yes I'm on macOS.
And the problem indeed comes from seq.
Could I close this pull request and create an issue?

I have another idea. 
How about this? I guess calculate index for 25 times is acceptable.
```
    set -l dirc (count $dirprev)
    if test $dirc -gt 0
        for i in (seq $dirc)
            printf '%2d) %s\n' (math $dirc - $i + 1) $dirprev[$i]
        end
    end

    echo (set_color $fish_color_history_current)'   ' $PWD(set_color normal)

    set -l dirc (count $dirnext)
    if test $dirc -gt 0
        for i in (seq $dirc)
            printf '%2d) %s\n' $i $dirnext[$i]
        end
    end

```

**Comment by EMayej** [comment]
Alright. How can I remove the second commit?

**Comment by krader1961** [comment]
No need to open an issue since we now have enough context to evaluate this PR. Since your changes haven't been merged you could simply `git rebase -i` and delete the last commit. Then `git push -f`. Or you could use `git revert` to revert the second commit. Or, and this is what I recommend in this specific instance, just leave it alone. When I, or someone else, merges it we'll just ignore the second commit. In fact, I'll probably do that in a few minutes after I've taken another look at your first commit and satisfied myself that it is correct.

**Comment by EMayej** [comment]
OK. I'll just leave it as that.

For the first commit, I just add "if test .... end" to wrap up some lines. Old lines just get new indentation.

**Comment by krader1961** [comment]
Fixed by merged commit 85cd372a4ecdc95e68139e87892437f7ecc66809 (only the first of the two commits in this PR).

**Pull request closed without merging**
