### PR TITLE
Implement `history search` glob searches

### PR DESCRIPTION
**Pull request by krader1961**
Instead of treating the search term as a literal string to be matched
treat it as a glob. This allows the user to get a more useful set of
results by using the `*` glob character in the search term.

Partial fix for #3136

### CODE REVIEW

**Comment by ridiculousfish** [comment]
What's the benefit of building this into `history` directly instead of just `history | grep` ?

**Comment by krader1961** [comment]
Consider commands that span multiple lines: `history | grep` does not handle those correctly. It also means that if you want to see only the N most recent commands that match the search criteria you then need to also pipe the output through `head` or `tail` (depending on whether you're doing `history --reverse`). Here is one example I chose at random to show how this works:

```
$ h 'while *mkdir'
Wed 04-26 16:11  while read t f
if test $t = d
mkdir $f
else
touch $f
end
end < ../f
```

Note that `h` is my alias for `builtin history search -R -20 --show-time="%a %m-%d %R`. And I only had one command containing "while" followed by "mkdir" with arbitrary text between the two words.

It might be harder to justify adding the ability to search history using a PCRE. But supporting simple glob searches is a) trivial to implement, b) useful, c) very unlikely to break any existing history searches people are doing. If this enhancement isn't going to be merged then the associated issue should be updated with the reason why and closed.

**Comment by krader1961** [comment]
Also, if this change is rejected it would be nice if the performance bogosity in `history_item_t::matches_search()` involving case insensitive searches that this PR also fixes was independently fixed.

**Comment by krader1961** [comment]
Please merge or reject this change. If you reject it please close #3136 as "will-not-fix" so that others are not mislead into thinking that implementing the feature will be merged. Or add a comment to that issue explaining why this particular implementation was not acceptable and suggesting other approaches that might be acceptable.

I also have a fix for #4366 involving the `$history` variable but have been putting off turning it into a PR pending resolution of this issue.

**Comment by mqudsi** [comment]
Looks good to me.

**Comment by mqudsi** [comment]
_I don't know why Travis isn't able to test this. I think we can ignore this CI failure._

**Comment by krader1961** [comment]
Thanks, @mqudsi, for merging this. Should I bother trying to get my fix for #4366 merged? That issue hasn't been commented on or classified since it was opened so it's not obvious to me that I should expend any effort getting my fix merged.

**Pull request merged**
