### PR TITLE
Add a new complete-until command

### PR DESCRIPTION
**Pull request by romaia**
When binding the <tab> key to the 'complete' command, and pressing <tab>
multiple times, the default behaviour is to cycle through all the possible
options.

This adds the 'complete-until' command, that will not do this, but will
instead, complete until the common prefix, and do nothing more.

This is an alternative to the pull request proposed on pull #974 by @gfxmonk

### CODE REVIEW

**Comment by gfxmonk** [comment]
Can any project member provide a response on merging this? It's pretty unobtrusive, and a huge help to those who dislike the default behaviour.

**Comment by xfix** [comment]
This was already fixed by #1282. Closing.

**Comment by gfxmonk** [comment]
@xfix, I believe that bug is about _restoring_ the "cycle through all completions" behaviour, which was broken at some point. This PR is about adding a binding which intentionally does _not_ cycle through all completions, because many people want to be able to press `tab` and have it only complete the longest common prefix if there are multiple matches (as most other shells do).

**Comment by ridiculousfish** [comment]
Yeah, that matches my understanding too - reopening.

**Comment by ridiculousfish** [comment]
I think this is obviated by the new pager. Closing. Please speak up if you think something remains to be done here.

**Pull request closed without merging**
