### PR TITLE
Don't resolve symlinks with cd

### PR DESCRIPTION
**Pull request by ridiculousfish**
This teaches fish to maintain a virtual PWD, similar to other shells. It no longer resolves symlinks.  #3350 for more.

`pwd -P` can be used to access the physical (resolved) working directory. This is part of the shell spec.

(This ended up being pretty straightforward.)

This PR is an opportunity for discussion / pushback.

### CODE REVIEW

**Comment by zanchey** [comment]
I think `//./someshare` is valid on Windows, although perhaps @mqudsi can clarify whether that's something you can actually navigate to.

I'm not strongly attached to the existing behaviour, but I think it's worth noting somewhere in the `cd` documentation the problems this causes as you outlined in https://github.com/fish-shell/fish-shell/issues/1957#issuecomment-75812336.

**Comment by mqudsi** [comment]
@zanchey not exactly.

`//servername/share/` is an smb/cifs path under Windows. `\\.\` is a kernel-level construct known as a dos device path. To backtrack, a path like C:\foo is dos-style path only valid in user mode. Kernel mode paths start with `\\` followed by a namespace. `.` is the namespace for dos-style paths, so `C:\foo` becomes `\\.\C:\foo` when mapped into kernel namespace. Other namespaces include `?`, `??`, smb server paths, and more.

The paths are symbolically linked to the NT namespace path in the registry, but that's not a file-level symbolic link but rather a device/volume-level symbolic link that is a layer or two of abstraction apart from the filesystem.

Much more info here: https://blogs.msdn.microsoft.com/jeremykuhne/2016/05/02/dos-to-nt-a-paths-journey/

**Comment by luispabon** [comment]
One use case where fish's default behaviour breaks user flow.

When working in Golang, it expects all your projects and their dependencies to live in `$GOPATH` (by default this is `~/go/src`), and we normally organise different workspaces by symlinking from somewhere into `$GOPATH`. This is all well and good until you try to `cd` into one such directory to compile a go app, which makes running go a hassle under fish. It just won't work unless we run the go binary through a different shell, or change the direction of symlinks (from `$GOPATH` to my workspace).

**Comment by ridiculousfish** [comment]
Merged as 786c0c5abb936eeb10eae45b508132a313bc8abc

**Comment by justinlindh** [comment]
I'd noticed this change after upgrading my fish shell today. Since symlinks are no longer being resolved, the "jump" plugin shows the path of the symlink. The argument whether this is desired behavior or not isn't one I want to get into (nor am I qualified to), but for anybody else who just wants their jump plugin to resolve the symlinked path, a quick fix is to add the following line to `jump.fish` (mine is at `~/.local/share/omf/pkg/jump/functions/jump.fish`, using omf).
```
cd $MARKPATH/$argv[1]
cd (pwd -P)
```

**Pull request merged**
