### PR TITLE
Darkmode for docs and webconfig

### PR DESCRIPTION
**Pull request by faho**
## Description

This uses the prefers-color-scheme media query to choose between a dark and a light colorscheme for both the docs and fish_config. It's pure css, no script or anything.

If you want to test drive it without having to build the docs yourself, I've uploaded a version of the docs (sadly not fish_config, it's a static site) at https://bean.solutions/fish-doc/.

To see the changes, you'll have to set your dark mode preference or open up the devtools and force-enable it there. Firefox on linux should "just work" if you have a dark system colorscheme, chromium needs to be started as `chromium --force-dark-mode`.

Some screenshots:

### fish_config

Screenshot 2021-06-02 at 18-32-20 fish shell configuration
Screenshot 2021-06-02 at 18-32-31 fish shell configuration
Screenshot 2021-06-02 at 18-42-22 fish shell configuration
Screenshot 2021-06-02 at 18-32-47 fish shell configuration

#### The docs
Screenshot 2021-06-02 at 18-33-35 The fish language — fish-shell 3 2 2-356-gad3873079 documentation
Screenshot 2021-06-02 at 18-33-49 Interactive use — fish-shell 3 2 2-356-gad3873079 documentation
Screenshot 2021-06-02 at 18-34-05 The fish language — fish-shell 3 2 2-356-gad3873079 documentation

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by IlanCosman** [comment]
I think I like what Dark Reader does a bit more:

Screenshot (1)
Screenshot (2)

The really deep blue background feels rather oppressive, and I prefer a more gray-black than bluish-black. I think that's also more in line with what most text editors use.

**Comment by faho** [comment]
One thing I would like to know is how well it works with older sphinx versions - I think there's been a semi-recent change to footnotes?

**Comment by faho** [comment]
@IlanCosman How about something more like this
Screenshot 2021-06-02 at 18-56-06 The fish language — fish-shell 3 2 2-356-gad3873079 documentation

I would prefer to keep the blue tint because we also have one in the light version, and it has a bit of a nautical theme.

**Comment by IlanCosman** [comment]
@faho Much nicer! And I agree with the nautical vibe. I'd say make the background a bit lighter and more blue, and it would be good to go 😄

**Pull request merged**
