### PR TITLE
Globally improved french translations

### PR DESCRIPTION
**Pull request by PenegalECI**
## Description

Hello, there.

This PR, as the title says, globally improves the french translations for fish, and a bit more : 
* it adds translations;
* it improves pre-existant fuzzy ones, and drops some when they are clearly saying something completely different from the english string, but I was unable to correctly translate them – I did that to prevent confusing users, as this way it will show them the english text instead of a completely aberrant french text, but I did not drop them when it was not crystal clear for me that the translation was aberrant;
* it corrects some completions, mainly typos, and reflected the corrections in the `fr.po` file;
* it adds translation guidelines for other french translators, to help keeping the whole translations coherent;
* it tries to harmonize multiple versions of the same message, the archetype being messages like _display help_, _display help then quit_, _displays a help message_…

I went through the whole file multiple times to be sure that the current translations are roughly consistent, but there are probably some errors left.

As a side note, when opening this PR, Github showed me several commits behind my last merge from `upstream/master`; I tried to `rebase`, but it changed nothing, only showing me `noop`. I was unable to correct that, and, as only my changes are shown in this PR, I didn't bother with it, but, if it's a problem and you can show me how to correct it, I'll happily do it.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by PenegalECI** [comment]
Er… Help? Someone? The typo I fixed in the `hg` completions added a duplicated string in the `fr.po` file, which makes the Travis build fail. What should I do? Let the typo or regenerate the .po files? In the second case, I'll need help.

**Comment by mqudsi** [comment]
Just in case I'm not understanding you, the issue here is that there is a duplicate source string, not the translation. `:29936` defines the string "ignore changes in the amount of white space" and on `:

Isn't this sufficient?

```diff
9c9
< #
---
> #
31c31
< #
---
> #
29934a29935
> #: /tmp/fish/implicit/share/completions/hg.fish:432
30130,30133d30130
<
< #: /tmp/fish/implicit/share/completions/hg.fish:432
< msgid "ignore changes in the amount of white space"
< msgstr "Ignorer les changements de nombre de blancs"
```

**Comment by PenegalECI** [comment]
This should do it, but I'm starting to think that the manual changes I made on the english strings in `fr.po` made it out of sync with the other `.po` files, and that I should revert these changes and let a fish developper regenerate the PO files from the completion files I changed, after merging this PR.

**Comment by PenegalECI** [comment]
Closed to solve the conflict and re-open a clean PR.

**Pull request closed without merging**
