### PR TITLE
Add --follow-tags completion for git push

### PR DESCRIPTION
**Pull request by evuez**
## Description

Adds the `--follow-tags` option for `git push`.

## TODOs:
- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by floam** [comment]
Can you try to shorten the string? It doesn't fit in a 80 character-wide window.

**Comment by evuez** [comment]
I shortened it, I think it's still understandable.

**Comment by floam** [comment]
Thanks! Merged.

**Comment by zanchey** [comment]
Cherry-picked for 2.7.0 as 6d350409b353e2f47afab62287acabe73511d87e.

**Pull request merged**
