### PR TITLE
Remove phone number.

### PR DESCRIPTION
**Pull request by ffdd**

### CODE REVIEW

**Comment by xfix** [comment]
How did that even happen...

**Comment by ridiculousfish** [comment]
Looks like this was my handiwork. How embarrassing. Thanks for catching this.

**Comment by ffdd** [comment]
Not sure, but cute nonetheless! 📟

rey.sc

**Comment by pickfire** [comment]
Very cute, I didn't even know that someone can left a phone number in the git log. :fish:

**Pull request merged**
