### PR TITLE
Escape commas when expanding command substitutions

### PR DESCRIPTION
**Pull request by shayaviv**
Fixes issue #5048.

## TODOs:
- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by faho** [comment]
This breaks ordinary comma output, which is why you had to adjust the test.

Sorry, it's not a workable approach.

**Comment by shayaviv** [comment]
@faho Would you mind giving a specific example for a command output (not an error message) that this change breaks?

@krobelus If it's not too much trouble, I'd like to get you opinion too before we trash this.

**Comment by faho** [comment]
>@faho Would you mind giving a specific example for a command output (not an error message) that this change breaks?

... the test you had to adjust?

```
function t
    test $argv[1] -eq 5
end
t 5,2
```

This function now prints `in function 't' with arguments '5\,2'`. The comma is now escaped. It shouldn't be.

This is simply the wrong place to handle this.

**Comment by krobelus** [comment]
On Fri, Feb 11, 2022 at 06:32:04AM -0800, Shay Aviv wrote:
> 2. Commas need to be escaped, because they *are* special.

I agree that commas are special sometimes but the conclusion "commands need
to be escaped" is wrong. The output of a command subtitution should not be
escaped. It should be exactly what the command would print.

> You can test this without my changes:
>    ```console
>    ~> echo {1,2,3}
>    1 2 3
>    ~> echo {1\,2,3}
>    1,2 3
>    ```

You are fixing one case but breaking others that don't want escaping, like

	echo (string join , 1 2 3)

The real fix is probably somewhere in src/expand.cpp. Doesn't seem straightforward.

**Comment by faho** [comment]
>The string after with arguments is escaped by design. You can test this without my changes: 

Of course, yes. However now it is escaped *differently*, and for a character that doesn't need to be escaped here.

This makes escaping uglier than it needs to be and changes e.g. what `string escape` and completions do!

Do `string escape --no-quoted 5,2`. It now prints `5\,2`.

Do

```fish
complete -c foo -xa '5,2 5,3'
```

and complete. It now completes as `5\,2` and `5\,3`.

This applies to *all* completions, so even filenames with `,` are used as `5\,2` in the commandline.

This doesn't technically "break", but it makes all of this a little more ugly.

>Commas need to be escaped, because they are special. You can test this without my changes: 

They aren't special in a way that they need to be escaped everywhere. They are only special inside braces.

----

This simply is not the right solution, not even in concept.

This isn't a personal slight against you, sometimes you try the wrong thing. You could fill books with all the wrong approaches I've tried over the years. It happens.

But it shouldn't be merged. Sorry!

**Comment by shayaviv** [comment]
I'm not trying to convince you my solution is good - I just wanted to clear things up. Thanks for your time and consideration 🙂

**Comment by krobelus** [comment]
Oh I see, this is a bit like https://github.com/fish-shell/fish-shell/pull/6059, which we had to revert because we (still) can't tell whether the characters in question need escaping. Adding backslashes to `,` might not make a difference, but it makes things quite ugly.

**Pull request closed without merging**
