### PR TITLE
Improvements to __fish_print_hostnames

### PR DESCRIPTION
**Pull request by faho**
This is basically #2313 and #2764 rolled into one.

One improvement is reading ssh's KnownHostsFiles - configured in the ssh_config files, these contain additional hosts and are hence a nice source of info.

Another is ignoring hosts set to 0.0.0.0 from /etc/hosts (or `getent hosts`), which might be a lot of useless entries if you use hosts-based blocking.

Because this reads configuration I don't really have I'd appreciate some testing (@zanchey?).

@sysbot, @floam: Thanks for the ideas! Mind taking a look at my attempt?

### CODE REVIEW

**Comment by floam** [comment]
Hm, it's taking about 1000ms to execute vs. my 15-25.

And the output is a bit messed up: 

#2764
screenshot 2016-02-26 at 9 00 14 pm

#2767 
screenshot 2016-02-26 at 9 00 21 pm

first few lines of my hosts file: 
```
# Hosts File: Original File

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
127.0.0.1	AaronPad
255.255.255.255	broadcasthost
::1             localhost 
```

**Comment by faho** [comment]
@floam: Thanks for the feedback! Seems neither are ideal.

Let's first try to see if all hosts that should be there are there - do both contain "swingset"? Is that a host you'd like to be there?

Regarding the duration, I too have noticed that it's not 100% snappy, but I chalked it up to my massive hosts file. Maybe it's the overly complicated regex.

**Comment by floam** [comment]
swingset should be there. However that is from known_hosts, not /etc/hosts. So for instance it is missing AaronPad. And with a few more hostnames thrown in, it's missing everything I can add as well:
```
##
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
127.0.0.1	AaronPad
255.255.255.255	broadcasthost
::1             localhost 
10.0.0.137	spm-linux
10.0.0.102	apm-sbs08
10.0.0.2		hp2910al
10.0.0.3		tz400
```

```
__fish_print_hostnames                                   1230ms  Sat Feb 27 02:54:36 2016
::1












localhost


swingset

Hostname
swingsetdevelopment.com```

**Comment by floam** [comment]
Tweaked the regex, looking better: 

```
...
		string match -r '^[^#^: \t]+.*$' </etc/hosts | string match -r $renonzero \
...
```

```
__fish_print_hostnames                                  1189ms  Sat Feb 27 03:02:39 2016
localhost
AaronPad
broadcasthost
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
local
```

**Comment by floam** [comment]
Removing one regexp and simplifying this gives me the same output (here's the full deal, I've been cropping it. Hostname: should go away.) and reduces the runtime by around 500ms. 

```fish
    else if test -r /etc/hosts
        # Ignore commented lines
        string match -r '^[^0^.^#^: \t]+.*$' </etc/hosts | string replace -r '[0-9.]*\s*' '' | string split " "
    end```


```
localhost
AaronPad
broadcasthost
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
local

swingset

Hostname
swingsetdevelopment.com

spm
71.19.144.151
aaron.gy
10.0.0.137
10.0.1.3
nuc.local
2601:7:1500:316:eea8:6bff:fef4:b70d
10.0.1.123
fuller.prgmr.com
2605:2700:0:2::4713:9054
closet.aaron.gy
github.com
192.30.252.131
closetnas.local
2601:7:1500:316:208:9bff:fed6:64b6
10.0.1.7
[smallpartsmfg.com]:11001
[173.11.16.193]:11001
24.22.1.32
2601:7:1500:20d:208:9bff:fed6:64b6
2601:7:1500:20d:eea8:6bff:fef4:b70d
tsmusicfest.com
50.112.242.83
10.0.1.92
2601:7:1500:b8e:208:9bff:fed6:64b6
2601:7:1500:b8e:eea8:6bff:fef4:b70d
2601:7:1500:b8e:5423:dfbc:fecb:147b
10.0.1.6
67.170.142.69
10.0.1.5
spm-linux
icculus.org
74.81.175.20
10.0.0.1
ada.cs.pdx.edu
2610:10:20:208::103
10.0.0.2
10.0.0.3
10.0.0.171
10.0.0.118
smallpartsmfg.com
173.11.16.193
192.168.10.1
192.30.252.128
192.30.252.130
192.30.252.129
                                                               448ms  Sat Feb 27 03:12:59 2016
````

Otherwise, it takes ~1100ms to run.

**Comment by floam** [comment]
err, I said earlier swingset belongs there but that's not the case. It's from the declaration in `ssh_config`, not a hostnames. Same thing with 'spm' there. 

```
Host swingset
   Hostname ...

Host spm
...
```

**Comment by faho** [comment]
@floam: You'll want to replace the `string match` with `grep -v '^\s*0.0.0.0\|^\s*#\|^\s*$'` - that's much faster.

>err, I said earlier swingset belongs there but that's not the case. It's from the declaration in ssh_config, not a hostnames. Same thing with 'spm' there. 

Sure it's not acceptable as a hostname? Or maybe just for ssh? I.e. does `ssh swingset` work?

**Comment by floam** [comment]
I deleted that comment right when I made it as I kind of brain-farted. Yes it will work with ssh but not ping. It's probably worth keeping there.

**Comment by floam** [comment]
72cd6f5:

::1 is back, spurious "Hostname" still there. And the linebreaks which have not much practical consequence. 

```
localhost
AaronPad
broadcasthost
::1












localhost
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
::1

localhost
local

swingset

Hostname
swingsetdevelopment.com

spm
71.19.144.151
aaron.gy
10.0.0.137
10.0.1.3
nuc.local
2601:7:1500:316:eea8:6bff:fef4:b70d
10.0.1.123
fuller.prgmr.com
2605:2700:0:2::4713:9054
closet.aaron.gy
github.com
192.30.252.131
closetnas.local
2601:7:1500:316:208:9bff:fed6:64b6
10.0.1.7
[smallpartsmfg.com]:11001
[173.11.16.193]:11001
24.22.1.32
2601:7:1500:20d:208:9bff:fed6:64b6
2601:7:1500:20d:eea8:6bff:fef4:b70d
tsmusicfest.com
50.112.242.83
10.0.1.92
2601:7:1500:b8e:208:9bff:fed6:64b6
2601:7:1500:b8e:eea8:6bff:fef4:b70d
2601:7:1500:b8e:5423:dfbc:fecb:147b
10.0.1.6
67.170.142.69
10.0.1.5
spm-linux
icculus.org
74.81.175.20
10.0.0.1
ada.cs.pdx.edu
2610:10:20:208::103
10.0.0.2
10.0.0.3
10.0.0.171
10.0.0.118
smallpartsmfg.com
173.11.16.193
192.168.10.1
192.30.252.128
192.30.252.130
192.30.252.129
```

**Comment by faho** [comment]
Where are the empty lines and the "Hostname" coming from? Which part?

**Comment by floam** [comment]
> Where are the empty lines and the "Hostname" coming from? Which part?

"Hostname" is from ~.ssh/config. 

```
Host swingset
   Hostname swingset.private.com
```

> The empty lines are from the last string replace:

**`grep -v '^\s*0.0.0.0\|^\s*#\|^\s*$' /etc/hosts`**
```
127.0.0.1	localhost
127.0.0.1	AaronPad
255.255.255.255	broadcasthost
::1             localhost 
10.0.0.137	spm-linux
10.0.0.102	apm-sbs08
10.0.0.2		hp2910al
10.0.0.3		tz400
127.0.0.1	localhost
127.0.0.1	localhost.localdomain
255.255.255.255	broadcasthost
::1		localhost
127.0.0.1	local
```

**`grep -v '^\s*0.0.0.0\|^\s*#\|^\s*$' /etc/hosts | string replace -r '[0-9.]*\s`**
```
localhost
AaronPad
broadcasthost
::1             localhost 
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
::1		localhost
local
```
**`grep -v '^\s*0.0.0.0\|^\s*#\|^\s*$' /etc/hosts | string replace -r '[0-9.]*\s*' '' | string trim`**
```
localhost
AaronPad
broadcasthost
::1             localhost
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
::1		localhost
local
```

**`grep -v '^\s*0.0.0.0\|^\s*#\|^\s*$' /etc/hosts | string replace -r '[0-9.]*\s*' '' | string trim |string replace -ra '\s' '\n'`**
```
localhost
AaronPad
broadcasthost
::1












localhost
spm-linux
apm-sbs08
hp2910al
tz400
localhost
localhost.localdomain
broadcasthost
::1

localhost
local
```

**Comment by faho** [comment]
>::1             localhost 

Urgh, yeah - we replace every whitespace character with a newline, so that'll cause empty lines. Adding a "+" suffices.

>"Hostname" is from ~.ssh/config. 

That's from the `awk`ward part of the script then. Never really got into that. I'll try a replacement.

**Comment by zanchey** [comment]
The good news is that this change doesn't appear to lose any hostnames from my configurations.

However, it adds quite a few:
 - hashed hosts from `known_hosts` (formatted like `|1|0O6Gp+3ihP9Ojr8AzhuLZPg3IlM=|uirvqJ7q8Fd+JxdCQW96qGv/6+g=`)
 - commented-out hosts from `known_hosts` (like `#coromandel`)
 - hosts with custom ports (e.g. `[localhost]:2200`) - although this is probably helpful in some cases, it will never match (unless you start with `[l`) and is not the correct syntax for most commands that expect a hostname.

**Comment by floam** [comment]
`ssh-keygen -l -f ~/.ssh/known_hosts` may be more reliable and easier to parse than woking on the file directly.

**Comment by faho** [comment]
>hashed hosts from known_hosts (formatted like `|1|0O6Gp+3ihP9Ojr8AzhuLZPg3IlM=|uirvqJ7q8Fd+JxdCQW96qGv/6+g=`)

I'm not sure how much of that we can depend on - for now I'm trying out ignoring everything with a "|", "[" or "=" in it.

>ssh-keygen -l -f ~/.ssh/known_hosts may be more reliable and easier to parse than woking on the file directly.

Doesn't seem to help too much since it mostly seems to be a rearrangement of the format.

>hosts with custom ports (e.g. [localhost]:2200) - although this is probably helpful in some cases

Do you mean you get literally `[localhost]`, with the brackets? Otherwise, if "localhost" is known to ssh, e.g. `ping localhost` should work, no? `ssh localhost` doesn't then automatically use the custom port?

**Comment by zanchey** [comment]
> Do you mean you get literally [localhost], with the brackets?

Yes.

**Comment by faho** [comment]
@zanchey: Please try again.

(Man, this is way more complicated than I assumed)

**Comment by zanchey** [comment]
LGTM!

**Comment by faho** [comment]
@floam: How's it looking for you now?

**Comment by faho** [comment]
I've now merged this as a5f5e6c1ef3f8faece23f7bfc2ea0be04cf345c8..fbd53f2da1af69058b16320265364257a11571df. Thanks for the comments!

**Pull request closed without merging**
