### PR TITLE
aliases: add completion

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
## Description

Simple [`aliases`](https://github.com/sebglazebrook/aliases) completion.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Review by mqudsi — COMMENTED** [review]
What is `aliases` in this context?

**Comment by EmilySeville7cfg** [comment]
@mqudsi, they are [aliases](https://github.com/sebglazebrook/aliases) literally for Bash.

**Comment by mqudsi** [comment]
If it's for bash, then no one will be using it on fish, right?

**Comment by EmilySeville7cfg** [comment]
From my understanding [this command](https://github.com/sebglazebrook/aliases#usage) can be run from any shell: it just creates file with aliases. But I understand that primary usage will be in Bash anyway.

**Comment by faho** [comment]
Yeah this doesn't appear to be useful with fish, as it stands. The one command this currently completes does basically nothing on its own. It also has an *extremely* generic name and could easily clash with other things of the same name.

So I'm going to do a very rare thing for completions and reject this. Sorry!

**Pull request closed without merging**
