### PR TITLE
Improve pager wraparound

### LINKED ISSUE #3115: Accessing the last element in the completion menu should be possible by just using arrow-up
### Reproduction Steps:
1. `git format-patch --<tab><tab><tab>`
### Expected behavior:

Accessing `--textconv` should be possible by just pressing arrow-up once.
### Observed behavior:

Trying to access `--textconv` requires me to either press arrow-down a lot of times or narrow the list down manually by typing parts of the command.
### Additional information:

Going back to the first suggested option by pressing arrow-down on the last one works.

---

Fish version: 2.3.0

### LINKED ISSUE #4669: down-line in pager doesn't wrap
Hello,

Seems that last update (2.7.1) broke circular tab completions

See this example,
(first command pressing lot of TAB)
(second command pressiong lot of SHIFT-TAB)
https://asciinema.org/a/bShqIYrla3TCMwILAyAZShYRs

As we can see the first completion doesn't return to the beginning

### PR DESCRIPTION
**Pull request by faho**
## Description

This fixes a few cases where the pager didn't correctly wrap around.

It fixes #4669, in that moving down now also wraps around if the current selection is the last row in the last column. The same goes for moving "east" (e.g. via "forward-char") and "west" (e.g. via "backward-char").

It also fixes #3115, by allowing up to move into the pager if nothing is selected. So up from the first element will still jump into the commandline (which we might want to change, since it's the only way to do so), while up from the commandline will jump to the last element in the pager.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by laughedelic** [comment]
Cool :+1: Does it work the same with 
* <kbd>tab</kbd>/<kbd>shift-tab</kbd>,
* <kbd>↓</kbd>/<kbd>↑</kbd> and
* <kbd>ctrl-n</kbd>/<kbd>ctrl-p</kbd>?

**Comment by faho** [comment]
@laughedelic: Of course this is independent of the particular _key_ - this modifies the pager's movement function, so any binding that calls any bind function that then moves the pager selection with one of the affected directions will be affected.

>↓/↑ and
>ctrl-n/ctrl-p?

These are bound to "up-or-search"/"down-or-search" respectively, which are wrapper functions that call the "up-line"/"down-line" bind functions. So yes, they are fully affected.


>tab/shift-tab

These are bound to "complete" and "complete-and-search", which call the pager movement with "direction_next"/"direction_prev". They aren't affected, but there's nothing particularly wrong with them as far as I'm aware.

**Comment by laughedelic** [comment]
OK. Thanks for clarifying!

**Comment by faho** [comment]
This needs some adjustment to the tests - I didn't notice that we had some in src/fish_tests.cpp (I always forget about that, and I don't think `ninja` updated that correctly).

The first failure is moving west. Let's say the pager looks like this:

```
[1] 2  3  4  5
6   7  8  9  A
B   C  D  E
```

(with [] denoting the cursor position on the `1`)

and move "west"? Currently, this goes to `5`, while moving "east" then goes to `6`. With this, it goes to `E` instead (i.e. the last filled column in the last row). Moving east then returns one to `1`. 

So moving east or west just iterates in (western) reading-order - go through all the columns, then go to the next row and the starting column. Whereas now it does that, except it gets stuck in the last row.

This makes it so that east/west reverse each other, which is a nice property. On the other hand, that "column memory" feature is now gone as far as I can tell.

**Comment by faho** [comment]
Merged as 13079911..12c249ab.

I originally used github's conflict resolution feature, but that adds a merge commit, which is kinda superfluous when I could just directly change the changelog commit to resolve the commit.

**Pull request closed without merging**
