### PR TITLE
Rename sgrep to __fish_sgrep

### PR DESCRIPTION
**Pull request by faho**
Makes it harder to cause issues with aliases, see fish-shell#2245

Now with less unrelated stuff (see #2250).

### CODE REVIEW

**Comment by faho** [comment]
I'll merge this once #2313 has been taken care of.

**Comment by faho** [comment]
Merged with rebase (and removing a lone mention from the docs) as b85a8bbbfed56f603dca5d6da85858f9c973b669.

**Comment by zanchey** [comment]
This is probably worth noting in the release notes, so I've added the "needs docs" label for now.

**Comment by zanchey** [comment]
Also, is it time to look at the `string` function for most of these uses?

**Comment by faho** [comment]
Yeah, it is. Though `string match` doesn't have a "-v" (ignore matches) option.

**Pull request closed without merging**
