### PR TITLE
Change safe_strerror to only work for glibc

### PR DESCRIPTION
**Pull request by neheb**
Other platforms have thread-safe strerror implementations.

Amusingly, The %m format in glibc is threadsafe whereas strerror is not.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

I know this to be true of at least Windows, macOS, FreeBSD, musl, and uClibc-ng.

### CODE REVIEW

**Comment by neheb** [comment]
This comment, dated 2019, says that strerrror under glibc is not yet thread safe: https://sourceware.org/bugzilla/show_bug.cgi?id=447#c3

**Comment by zanchey** [comment]
The concern is not about thread safety, but about async-signal safety - see http://man7.org/linux/man-pages/man7/signal-safety.7.html etc - so I'm not sure this is appropriate,

**Comment by neheb** [comment]
Hmm maybe strerror_l is a better function to use.

**Comment by faho** [comment]
Yeah, no. This is one of those things that require extensive testing, especially on less common platforms (this includes Solaris and NetBSD).

And since there doesn't seem to be any actual benefit (apart from it being a bit cleaner), that does not seem to be worth it.

So I'm rejecting this.

(unless of course I've misunderstood and there is an actual issue this solves)

**Comment by neheb** [comment]
Amusingly, POSIX requires %m to be available to syslog(3). Having it available elsewhere is a convenient extension.

**Pull request closed without merging**
