### PR TITLE
wait for processes by their name

### PR DESCRIPTION
**Pull request by s417-lama**
Implement #4848 and refactored the code in wait command.

We can now specify the process name and wait for jobs with its name, like:
```
$ for i in (seq); sleep 10 &; end
$ wait sleep
```

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Nice tests! Can you please update `doc_src/wait.txt` to reflect these changes?

**Comment by s417-lama** [comment]
I reflected the changes to `doc_src/wait.txt` :)

**Comment by s417-lama** [comment]
Although I committed the fix for the bug, I think I misunderstood the error in [test](https://travis-ci.org/fish-shell/fish-shell/builds/357951616).

I expect the behaviour like below:
```
$ for i in (seq 2 4); ls | sleep $i | cat > /dev/null &; end
$ sleep 3 | cat &
$ sleep 1 &
$ wait -n cat
$ jobs | wc -l
3
```
However, the failed test seems to behave
```
$ for i in (seq 2 4); ls | sleep $i | cat > /dev/null &; end
$ sleep 3 | cat &
$ sleep 1 &
$ wait -n cat
$ jobs | wc -l
2
```
Was one of the jobs finished immediately?
I tried many times, but I cannot reproduce the error in my local environment.

**Comment by s417-lama** [comment]
This might be related to #4778 or #4540

**Comment by mqudsi** [comment]
If you run `jobs` after each line you can see what's what.

**Comment by s417-lama** [comment]
I cannot reproduce the bug although I tried the test many times :_(

After merging the current master branch I run the script below, but it never breaks in my environment.

```
set n 3
while [ $n = 3 ]
    for i in (seq 2 4); ls | sleep $i | cat > /dev/null &; end

    echo "jobs 1."
    jobs

    sleep 3 | cat &

    echo "jobs 2."
    jobs

    sleep 1 &

    echo "jobs 3."
    jobs

    wait -n cat
    set n (jobs | wc -l)

    echo "jobs 4."
    jobs

    wait

    echo "---"
end
```

How do we deal with this bug?

**Comment by faho** [comment]
Urgh... github's conflict resolution UI is quite confusing - I didn't see any issues in the test, which is why travis failed. Plus it only allows adding a merge commit.

Okay, back to using git on the CLI.

**Comment by faho** [comment]
Urgh... Sorry, I missed a change in the tests, which is why they are now failing!

Readding that line!

**Comment by mqudsi** [comment]
I think waiting for processes by name is messy and brittle and job ids should always be used.

**Pull request merged**
