### PR TITLE
Death of mimedb

### PR DESCRIPTION
**Pull request by zanchey**
Fix for #2229 (and #1400).

### CODE REVIEW

**Comment by lledey** [comment]
The `check-legacy-binaries` rule in Makefile.in should be updated to warn about existing mimedb binary (and fishd too while we're here).

**Comment by ridiculousfish** [comment]
Reviewed, looks good :+1:

**Comment by zanchey** [comment]
Merged, thanks!

**Comment by ridiculousfish** [comment]
Woohoo!

**Pull request merged**
