### PR TITLE
Rework how the mode is reported in fish_vi_mode

### LINKED ISSUE #1988: Vi mode replaces prompt options
Whatever prompt I am using with git info showing, going into `vi mode` with `fish_vi_mode` removes any git info.

I am using fish-HEAD from homebrew so
```
$ fish --version
fish, version unknown
```

Setting the prompt with `fish_config` after having started `fish_vi_mode` does not change the prompt either.

### PR DESCRIPTION
**Pull request by ridiculousfish**
Add a new function fish_mode_prompt which (if it is defined) has its output
prepended to the left prompt. Rather than replacing the prompt wholesale, make
fish_vi_mode define this function. This enables vi mode to interoperate nicely
with custom prompts. Users who want to change how the mode is reported can
either redefine this function or erase it entirely. Fixes #1988.

### CODE REVIEW

**Comment by jaredgrubb** [comment]
Makes sense. +1

**Comment by zanchey** [comment]
Works well. It messes up the "nim" sample prompt but I think we can live with that. Should the mode indicator remain even if we shorten the rest of the prompt to "> "?

What's the right way to customise this stuff? Add `fish_vi_prompt` to `config.fish` and then also add the custom `fish_mode_prompt` function to `config.fish`? `funcsave` etc. do not work at the moment.

I think I'd prefer that `fish_mode_prompt` was defined in the usual way and guarded with `if set -q __fish_vi_mode` or similar.

**Comment by ridiculousfish** [comment]
I amended the commit incorporating zanchey's idea. This should make `funcsave` work as expected.

**Comment by ridiculousfish** [comment]
This was merged to master as 767742c and Integration_2.2.0 as 064ad7b

**Comment by tomisme** [comment]
Would it be possible to allow fish_mode_prompt to be multi-line? I can see [here](https://github.com/fish-shell/fish-shell/commit/767742c7e7ee53c8aa7950f928d551c63d69448f#diff-fb8e469614fa016859aefbb53f3fc3b1R1009) that there's some concatenation going on.

**Comment by zanchey** [comment]
I think you'd be better off erasing `fish_mode_prompt` and building a switch on `fish_bind_mode` into your existing `fish_prompt`.

**Comment by tomisme** [comment]
Ah, I knew there would be a better way! Thanks.

**Pull request closed without merging**
