### PR TITLE
fix raw_string_to_scalar_type locale handling

### LINKED ISSUE #3334: printf(1) locales broken between 2.3.0 and 2.3.1
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**OS/terminal used**: FreeBSD, OS X 

## Reproduction steps

2.3.0 functions as designed/expected:

```
> set -x LC_NUMERIC "fr_FR.UTF-8"; builtin printf "%f" 5.55
5,550000
```

2.3.1 fails to take LC_NUMERIC into account:
```
> set -x LC_NUMERIC "fr_FR.UTF-8"; builtin printf "%f" 5.55
5.550000
```

### PR DESCRIPTION
**Pull request by krader1961**
## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documenation/manpages.
- [ ] Tests have been added for regressions fixed

Fixes #3334

### CODE REVIEW

**Comment by faho** [comment]
This test fails on my system:

```diff
Testing file printf.in ... fail
Output differs for file printf.in. Diff follows:
--- printf.tmp.out      2016-09-05 00:59:20.364227104 +0200
+++ printf.out  2016-09-03 23:11:36.323718109 +0200
@@ -15,4 +15,5 @@
 a
 fe
 1.230000e+00
-4.560000e+00
+3,450000e+00
+4,560000e+00
Error output differs for file printf.in. Diff follows:
--- printf.tmp.err      2016-09-05 00:59:20.364227104 +0200
+++ printf.err  2016-09-03 23:11:36.303718016 +0200
@@ -1,2 +1 @@
 2,34: value not completely converted
-3,45: value not completely converted
```

$LANG is de_DE.UTF-8, other locale vars are unset, though that doesn't seem to matter. OS is Archlinux.

**Comment by krader1961** [comment]
The problem is almost certainly that you don't have locale fr_FR.UTF-8 installed on your system. So the question is how to perform the tests that verify comma/decimal inversion in floating point string representation is handled correctly given that we can't control which locales are installed. Any ideas, @faho?

**Comment by krader1961** [comment]
We could certainly march through a list of locales which use a comma as the decimal mark and use the first one we find installed on the system. But that is only slightly less fragile than the current situation and adds considerable complexity.

**Comment by faho** [comment]
>The problem is almost certainly that you don't have locale fr_FR.UTF-8 installed on your system.

Yes, it is.

Is there any way we can see if the locale is installed and skip the test if it isn't? On my system `locale -a` lists locales, but I'm not sure if it's portable.

**Comment by krader1961** [comment]
> Yes, it is.

Is it literally "fr_FR.UTF-8" or is it perhaps "fr_FR.utf8"? I'm betting the latter (or some other variant). That's because what I found doing controlled tests on Travis is that the locale names vary in whether the encoding is written as ".UTF-8", ".UTF8", or ".utf8". And my change expected it to be ".UTF-8" which isn't true in two of the three Travis environments we use when running our unit tests.

I merged commit 363fa0a59 that should fix the problem you're seeing, @faho. Let me know if it does not. My fix assumes `locale -a` is generally available. If it turns out not be then we'll need to open an issue to discuss how to deal with locale specific tests.

**Comment by faho** [comment]
This fixes the failure. Thanks!

>Is it literally "fr_FR.UTF-8" or is it perhaps "fr_FR.utf8"? I'm betting the latter (or some other variant).

`locale -a` writes the latter even if I define the former. Both are acceptable as a setting.

**Pull request merged**
