### PR TITLE
Kill etc/config.fish

### PR DESCRIPTION
**Pull request by faho**
(Sorry, I know this is a bit late)

Like @amluto asked for in #2498, remove etc/config.fish by appending the code to share/config.fish.

This improves life for packagers as there's one less file in etc (thought of as user/admin territory in recent years). Also there's one less file for _us_ to worry about.

It might be nice to nix these two remaining things entirely but I'm not too sure about that.

While I was at it, I've also stringified it, which is why I'd like a quick check from someone else.

### CODE REVIEW

**Comment by krader1961** [comment]
lgtm

**Comment by zanchey** [comment]
Perhaps we should leave a skeleton file in `etc/config.fish` - something along the lines of:

```
# config.fish
# Put system-wide fish configuration entries here
# or in .fish files in conf.d/

# This file is run by all fish instances.
# To include configuration only for login shells, use
# if status --is-login
#    ...
# end
# To include configuration only for interactive shells, use
# if status --is-interactiv
#   ...
# end
```

**Comment by faho** [comment]
@zanchey: If I understand correctly, packagers would prefer not to have files in /etc at all (for "stateless systems" and to have one less file to backup if it changed), so that would kind of defeat the point.

Though we should probably still create the directory.

@amluto: Did I get that right?

**Comment by amluto** [comment]
A bunch of the actual empty-/etc stuff is being done in the OSTree project,
and I don't know too much about the fine details.  But I don't have a
strong preference between omitting the file and leaving in a placeholder.
As long as fish is fully functional without anything in /etc, everyone wins
:)

**Comment by zanchey** [comment]
r+

As a packager I'm not fussed by no-op files, but as a systems admin I'd like to have a template or example available.

**Comment by faho** [comment]
Merged as 6288f89. Thanks!

**Pull request closed without merging**
