### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by faho**
This adopts the Contributor Covenant Code of Conduct.

There's no email address given because we do not, currently, have a project email address that I'm aware of.

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [N/A] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by damani42** [comment]
Nice, it's a good idea to add a code of conduct.

**Comment by neheb** [comment]
I'll just leave this here: https://www.phoronix.com/scan.php?page=news_item&px=FreeBSD-Code-of-Conduct-2020

**Comment by faho** [comment]
>I'll just leave this here: https://www.phoronix.com/scan.php?page=news_item&px=FreeBSD-Code-of-Conduct-2020

@neheb I'll admit I have no idea why you're leaving it there.

**Comment by neheb** [comment]
This CoC was disliked by many FreeBSD users. That's why.

**Comment by faho** [comment]
>This CoC was disliked by many FreeBSD users

It's not the same?

https://web.archive.org/web/20180213113526/https://www.freebsd.org/internal/code-of-conduct.html is the old FreeBSD one. This one is quite substantially different.

**Comment by ammgws** [comment]
Is there actually a need for this though?

**Comment by ammgws** [comment]
@R2robot This is where I'm coming from: https://drewdevault.com/2020/01/17/Effective-project-governance.html

**Comment by zanchey** [comment]
Having suggested this (in private, which is certainly less helpful) some years ago, I am strongly in support.

> Is there actually a need for this though?

As a professional in a tightly regulated occupation, and an active volunteer with a number of formal organisations, it really surprises when participants in a moderate-sized volunteer project don't agree on a (very basic) standard of behaviour. It seems like releasing an open source project without a license.

There have not been any public incidents requiring the enforcement of a code of conduct but after an incident is the worst time to realise you need to lay out some expectations.

In the wider community there have been a number of members of marginalised groups who have indicated the importance of a code of conduct.

In my view (and I'm happy to be told otherwise, publicly or privately) regular contributors and committers generally adhere to the standards set out in this patch, and I don't see that is creates an onerous obligation to participate. On the other hand, I hope that it will provide what mjg59 calls "a list of behaviours that are unlikely to occur within that community".

**Comment by ammgws** [comment]
Fair enough. I guess I am just naive enough to trust participants in our established community to stay civil. Although the kind of people who would make hurtful comments are likely to knowingly ignore code of conduct anyway.

On that note, perhaps it should mention specifically _how_ one can contact the project team when they want to keep the reporting itself private. If there's no project email address, then could gitter be used instead? (Assuming it has private messaging?)

**Comment by faho** [comment]
>Fair enough. I guess I am just naive enough to trust participants in our established community to stay civil.

You know, I used to think that as well. I was wrong, and I apologize for it.

Because there is very much disagreement on what "civil" (if that's even the right word) *means*. There are a lot of places on the internet where, for instance, transphobic behavior is considered acceptable.

And so, by adopting a Code Of Conduct that says so, we make it clear that this is not one of those places.

--------------

>On that note, perhaps it should mention specifically how one can contact the project team

The template includes "contact the project team at <email address>". I left it out because we don't currently *have* such an address.

We might want to create one.

>keep the reporting itself private

Reporting should obviously be confidential.

>could gitter be used instead? 

I'm not sure about that - gitter is another service that you need to agree to the ToS of, it requires another account,...

Email is ideal because everyone already has it.

**Comment by ammgws** [comment]
> Reporting should obviously be confidential.
> Email is ideal because everyone already has it. We might want to create one.

Well I guess that's decided then :P

**Comment by mqudsi** [comment]
I don't see anything that could be considered objectionable in the proposed CoC. As an old-school denizen of teh interwebs, I too like to continue to believe in the innate goodness of people but I think it's important to distinguish that technical and ethical competencies do not necessarily go hand-in-hand. While the internet of old was in many ways a meritocracy and the majority of BDFL-led organizations absolutely _have_ avoided doing anything that goes beyond the line that divides being politically incorrect from being a bigot/bully, it is important to acknowledge that there are absolutely are communities that have fallen victim to being unable to either see or act when such inappropriate behaviour did arise because it came from individuals who either were or had become too valuable to chastise. 

If such a code of conduct makes it clear to both members of a project and others interacting with the organization or using its product that they can expect at least some level of decency, I don't see why not. Basic decency aside, it is in the best interest of the community/organization itself and the spread of its product/ideology to be positively perceived in the community and to be a force of good, not evil.

As to this *specific* CoC being proposed in this PR, I think it's fine. I think having one is better than having a perfect one and obviously (as mentioned) organizations will ultimately do what they want but even if they either have an incomplete CoC that doesn't go into each and every do/don't or else chooses to be lenient and give second chances for repeat offenders, the fact that the CoC is there, is agreed to by all contributors/members, and hasn't been repealed in a revert commit says volumes. 

If this CoC were to go into the nitty gritty and delve into controversial specifics like refraining from using certain terminology because of _perceived_ etymological origins or requiring the usage of certain grammars or whatnot, I could see why people might be up in arms about it. But this is about as harmless and uncontroversial a CoC as one could find and I'm more than happy to see it added. 

(Now with my developer hat on, however, I do have nitpicks about the line wrapping inconsistencies and would certainly love to see a `gq` applied to the document before its merged!)

**Comment by faho** [comment]
>(Now with my developer hat on however, I do have nitpicks about the line wrapping inconsistencies and would certainly love to see a gq applied to the document before its merged! Also: Oxford commas, please!)

This is from a template github provides. I would assume keeping it the same to ease diffing to be more important than minor formatting nitpicks.

**Comment by zanchey** [comment]
On the mailing list, [Pim Dennedal asks](https://sourceforge.net/p/fish/mailman/message/37048288/):

"Why not adopt v2"?

**Comment by faho** [comment]
>"Why not adopt v2"?

Because Github still provides 1.4 as the template.

I've now upgraded to 2.0. Note that, as the commit message states, this includes an "[INSERT CONTACT METHOD]" stub that we would have to fill in.

**Comment by sorairolake** [comment]
Why is the file format Markdown instead of reST?

Related PR: #7057

**Comment by faho** [comment]
Again: Because that is the format this is provided in, and we want to allow diffing with the original.

**Comment by sorairolake** [comment]
@faho I understand. Thanks for answering.

**Comment by ridiculousfish** [comment]
Thank you for taking the lead on this @faho and apologies for my absence on this matter as I took a bit of a GitHub break. I also am very strongly in support, I wish we had done it a while ago and regret not taking action when zanchey raised it privately.

Regarding the contact method stub, I am not sure how other OSS projects manage it. I think it would be OK to delete that sentence for now. I will set up MX records for `fishshell.com` so we can have shared addresses (and private ones if you want!)

**Comment by faho** [comment]
Okay, merged as 0b3b4f3d9. That's it, then.

**Pull request closed without merging**
