### PR TITLE
If $PWD is empty then use $HOME

### LINKED ISSUE #2298: Getting Assertion `wd[len - 1] == L'/'' failed over SSH
Locally everything works fine, but when I ssh into and start writing "c" (that's only letter which triggers it) then I get this assert
```
fish: src/path.cpp:148: bool path_get_cdpath(const wcstring&, wcstring*, const wchar_t*, const env_vars_snapshot_t&): Assertion `wd[len - 1] == L'/'' failed.
```

```
#0  0x00007f2a148eb5f8 in raise () from /usr/lib/libc.so.6
#1  0x00007f2a148eca7a in abort () from /usr/lib/libc.so.6
#2  0x00007f2a148e4417 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007f2a148e44c2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00000000004acb64 in path_get_cdpath (dir=L"AUR", out=out@entry=0x7f2a1439eda0,
    wd=0x70aaf8 <std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> L"", env_vars=...)
    at src/path.cpp:148
#5  0x000000000045e074 in autosuggest_validate_from_history (item=..., detector=..., working_directory=L"", vars=...) at src/highlight.cpp:532
#6  0x0000000000476b68 in threaded_autosuggest (this=0x836df0) at src/reader.cpp:1468
#7  threaded_autosuggest (ctx=0x836df0) at src/reader.cpp:1522
#8  0x00000000004af7c0 in iothread_worker (unused=<optimized out>) at src/iothread.cpp:135
#9  0x00007f2a151f74a4 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f2a149a112d in clone () from /usr/lib/libc.so.6
```

Using latest git just compiled, but it also happens with previous versions.

### PR DESCRIPTION
**Pull request by davispuh**
Fixes #2298 

Basically when fish is opened over SSH or from login tty then $PWD will be empty and that causes assert in `path_get_cdpath` because `wd` is empty `""`· So just use $HOME when $PWD is empty.

### CODE REVIEW

**Comment by zanchey** [comment]
Surely using `wgetcwd` is more appropriate here?

**Comment by davispuh** [comment]
I don't know why $PWD is used...

**Comment by zanchey** [comment]
I think it's a reasonable change (using `wgetcwd`), but I'd actually like to know how you reproduce the bug this is fixing.

**Comment by davispuh** [comment]
I actually found real cause. It's because fish used C locale but my $HOME path contains Unicode. I'll send another PR to fix that issue.

So anyway to reproduce this, create some user with Unicode $HOME path (eg. `/home/tēst`), then switch to that user `su -l user` and then type `~`, it will cause fish to crash.

**Comment by zanchey** [comment]
OK, I can reproduce this as follows:

```
mkdir ~/snowman☃
env HOME=~/snowman☃ LC_ALL=C fish
~
```

I'm not sure there's much fish can do here. If you want to use Unicode home directories, you should set a system-wide Unicode locale.

**Comment by faho** [comment]
@zanchey: Maybe just suppress the error, or at least only print it once?

In that test I got it every single time I entered a character, making the commandline unreadable.

**Comment by davispuh** [comment]
I agree with using Unicode locale (for that need #2381), but you need to tell user that it's his fault and it shouldn't crash `fish`. This PR fixes it quite good, because `fish` will still work and it will output message about failed `env_set_pwd`.

**Pull request closed without merging**
