### PR TITLE
Modify parser to accept 'begin' without ';'

### LINKED ISSUE #1248: New parser requires newline/semicolon after `begin`.
This used to work:

`begin true; end;`

Now it must be:

`begin; true; end`

This affects (for example) virtualfish in [virtual.fish#138](https://github.com/adambrenecki/virtualfish/blob/5dcb1fe705708df5564bbcec5cb563d961ecd3dd/virtual.fish#L138).

We should either note this in the release notes, or allow the old behaviour until fish 3.0.

### PR DESCRIPTION
**Pull request by snnw**
Modify parser to accept 'begin' without ';'

Examples that work as expected (even completions don't get confused):

$ begin true; end;
$ begin if true; end; end
$ begin if true; echo hi; end

The last example correctly expects another 'end' to match 'begin'.

Fixes #1248, includes tests.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
I appreciate that my hand-written parser is maybe overwrought and not easy to understand, but this really ought to be reflected in the grammar (e.g. the same way that `if` is handled) rather than by interposing into the token stream.

**Comment by snnw** [comment]
Fair point.  I'll take another look at the parser.

Does the following grammar look correct to you?  Still LL(2) right?
```
    block_statement = block_header  job_list end_command arguments_or_redirections_list
    block_header = for_header | while_header  | function_header | begin_header
    for_header = FOR var_name IN argument_list <TOK_END>
    while_header = WHILE job <TOK_END>
    begin_header = BEGIN | BEGIN <TOK_END>

    function_header = FUNCTION argument argument_list <TOK_END>
```

**Comment by zanchey** [comment]
I'll leave this to @ridiculousfish but when merging please update the commit message to include the original text.

**Comment by snnw** [comment]
I'll update with a real commit message later today.  It was late and I just wanted to push it out.

**Comment by snnw** [comment]
@ridiculousfish can I ping you on this?

**Comment by ridiculousfish** [comment]
Sorry, I let this slip!

Yes, that looks fine, except it can just be this:

    begin_header = BEGIN

You don't need to swallow any subsequent TOK_END, because the job_list (within the block) will swallow it.

**Comment by snnw** [comment]
If I do not swallow TOK_END in the begin_header, one of the indent tests fails:

```
Error: Wrong indent at index 5 in test #7 (expected 0, actual 1):
begin; end
foo
```

I'm not quite sure what is expected here, so I decided to leave the test as is.  Maybe we can safely change the test case?

**Comment by ridiculousfish** [comment]
Hmm, so probably this:

    begin ; end

is being indented like this:

    begin
        ;
    end

I think that should be harmless since the semicolon will be on the same line, and so won't be indented. But we ought to make sure that `fish_indent` doesn't produce that output.

**Comment by snnw** [comment]
`fish_indent` doesn't produce that output.  It always replaces `;` with `\n`.

However, I noticed that `begin; foo; end` gets indented as
```
begin
   foo
end
```
while `begin foo; end` gets indented as
```
begin foo
end
```

This is because there is no `TOK_END`, so no newline.

The push request is updated with both the simple begin_header production and a (admittedly hacky) fix for fish_indent.  @ridiculousfish PTAL?

**Comment by ridiculousfish** [comment]
This is looking really good!

I wonder if the fish_indent hack is really necessary. After all if the user omits the semicolon, perhaps it's because he wants it to be written on the same line. Perhaps we should be going in the other direction, i.e. `begin foo ; end` should be indented as just that, on one line, e.g. for this case:

    if begin set -q interactive[1]; or test "$editor" = fish; end
        # if body
    end

(Of course I'm not asking you to do that as part of this change, but it may be what we aim for).

What's your thoughts on removing the fish_indent change and allowing `begin foo; end` to be indented as

    begin foo
    end

I think I'm in favor.

**Comment by snnw** [comment]
Hmm, per #1248, this whole change is just for backwards compatibility.  I would agree that it's not worth the hack to have fish_indent work around it.  The end result is still readable enough.

We should probably spin off a separate bug for the general question of how fish_indent should handle `;`.  It would require some extensive changes to the parser (since `TOK_END` is used for both newlines and `;`., but I can see the benefit in keeping semicolons and newlines as the user wrote them.

The pull request should be merge-able up to 32f7a5d, so without the fish_indent changes.

**Comment by zanchey** [comment]
I've cherry-picked the first three commits as fd731fb, 9e8e5af and cb1e3c5, which allows us to close #1248 for 2.2.0. Would you open a new pull request (and close this one) for the additional change?

**Comment by snnw** [comment]
@zanchey thanks for the merge.  I'll close this PR. I'll hold off on opening a new one for the fish_indent change, as long as it's unclear which direction we're headed.

**Pull request closed without merging**
