### PR TITLE
Add sbt completions

### PR DESCRIPTION
**Pull request by laughedelic**
## Description

Added completions for [sbt](http://www.scala-sbt.org/) (Build tool for Scala projects).

## TODOs:

- [x] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Squash-merged as a43da0163a2e5b2e29a799382d4824996c80ebe5. Thanks!!

**Comment by ridiculousfish** [comment]
Err, I stripped out the CHANGELOG.md changes because I thought we constructed those at release time, but maybe that was my mistake.

**Comment by laughedelic** [comment]
Thanks. 

> Err, I stripped out the CHANGELOG.md changes because I thought we constructed those at release time, but maybe that was my mistake.

No problem. It was on the pull-request template TODO list, so I added it. Actually, there's a little more in eb05c39ea2506f8c07a9f507666d206d888a99fb: it fixes markdown list indentation of the other completions.

**Comment by ridiculousfish** [comment]
Ooh, nice. cherry-picked eb05c39ea2506f8c07a9f507666d206d888a99fb, thanks.

**Comment by zanchey** [comment]
We've been encouraging everyone to keep the CHANGELOG up to date - it was getting to the point where it was taking days to write up and delaying the release.

**Comment by laughedelic** [comment]
I think it's a very good practice. Although when many people edit same document, it's helpful to have some formatting guidelines.

**Pull request closed without merging**
