### PR TITLE
add history token builtin.

### PR DESCRIPTION
**Pull request by amosbird**
## Description
Outputs tokenized history commands. This is useful for tools like fzf to do
further filtering and completion.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Thanks for the PR. I think history is the wrong place for this. How about this:

1. `commandline --tokenize` is almost perfect except that you can't specify the contents of the commandline. So add an option to `commandline` that allows this (specifying the commandline to operate on). OR,

2. Add a `tokenize` option to `string`.

**Comment by krader1961** [comment]
Thanks for creating a PR that enhances the C++ code. It looks pretty good (just a couple of nits) but as @ridiculousfish said, and I agree, this feature would have more utility implemented as a `string` subcommand. Also, mind opening an [enhancement issue](https://github.com/fish-shell/fish-shell/issues/new)? It's always a good idea to associate non-trivial PRs with an issue as it gives people a chance to provide feedback on an idea before a lot of time is spent writing code that might not be merged :smile: But the good news is most of your change can be repurposed so not too much of your effort will be wasted.

**Comment by amosbird** [comment]
Thanks for the advice. I just opened #3823  :smiley:

**Comment by krader1961** [comment]
I'm going to close this since we do not want to do this as a new feature of the `history` command. I'd wait a couple of days for feedback on issue #3823 just in case anyone feels strongly that `string tokenize` is not the way to go or otherwise has an opinion about how it should behave. After that feel free to create a new PR.

**Comment by amosbird** [comment]
That's fair. I'll post my current usage there.

**Pull request closed without merging**
