### PR TITLE
Added <link rel for favicon.png so modern browsers know where to find it.

### PR DESCRIPTION
**Pull request by frederickjh**
This is a continuation of the fix for the 403 errors for the **favicon.ico** when fish_config is run.  A **favicon.png** was added in fish-shell/fish-shell#2048, however without a link in the `<head>` section modern browsers will still look for the older default **favicon.ico** and fish_config will spew out the error in the terminal.

The ideal solution would be to include both a **favicon.ico** and a **favicon.png**. The former for backward compatibility, the second as it has a higher quality. 
I attempted to also add the **favicon.ico** and a link to in index.html
`<link rel="shortcut icon" href="favicon.ico" />`
but then both images returned 403 errors. This commit fixes it for the majority of cases. I will leave it to someone that understands **webconfig.py** much better than I do to fix the 403 error for the favicon.ico  I converted the current **favicon.png** online to make the favicon.ico In case someone else want to finish this work.

More information:  [What is currently the best way to get a favicon to display in all browsers that support Favicons?](http://stackoverflow.com/a/37321/6079319)  and [favicon.png vs favicon.ico - why should I use PNG instead of ICO?](http://stackoverflow.com/a/1344147/6079319)

### CODE REVIEW

**Comment by frederickjh** [comment]
Related:

fish_config outputs (lots of) favicon.ico 403 errors  fish-shell/fish-shell#1936

**Comment by zanchey** [comment]
I can't reproduce the problem you're trying to fix in the current git master. The first commit adds a duplicate line - it's already in the head tag - and the only browser that doesn't support PNG favicons is old IE, AFAIK.

**Comment by jakwings** [comment]
One trick: Copy or rename favicon.png to favicon.ico
Most modern browsers don't care and will find out it is a png file and use it.

**Comment by krader1961** [comment]
I would ask that you open an [issue](https://github.com/fish-shell/fish-shell/issues/new) that describes the problem including how to reproduce it. That means documenting details such as the web browser you are using.

This change doesn't seem to do anything useful as far as I can tell. I am especially interested in knowing details about the environment in which you are using the fish shell as I've never observed the problem you're trying to fix. The URLs you provided talk about Microsoft IE6 which is so old, and idiosyncratic, that I don't think it is worth adding support for it now.

Also, this seems to be a cosmetic problem rather than a functional problem. Cosmetic problems should be fixed when doing so is reasonable and useful; e.g., typographical errors. But enhancing fish to not report harmless errors when interacting with a browser that is more than ten years old and known to be idiosyncratic seems like a waste of time.

**Comment by floam** [comment]
I imagine the actual place where the 403 would be encountered is on that initial meta-refresh redirector HTML document, which doesn't `<link>` any icon at all so some modern browsers may grasp for a favicon.ico.

**Comment by zanchey** [comment]
The initial meta-refresh document is on a file:/// URL, though.

**Pull request closed without merging**
