### PR TITLE
fish.cpp: check for fishd from old version and warn if reachable

### PR DESCRIPTION
**Pull request by zanchey**
Work on #1730.

Requesting review before merging - @ridiculousfish?

In particular, I am wondering whether just connecting to a socket that may not be under our control (see #1436) can cause problems - @amluto? It won't bother fish but could it conceivably bother other daemons?

### CODE REVIEW

**Comment by amluto** [comment]
There's an old hack I've used to do this more safely: connect a SOCK_DGRAM
socket instead.  It can do one of three things:

1. Succeed.  This means someone has a SOCK_DGRAM socket there (which would
be surprising), but servers aren't notified of client connections in this
case, because there aren't really datagram connections in the first place.

2. Fail with EPROTOTYPE.  This means someone's listening.  They aren't
notified because the connect call failed.

3. Fail with a different error.  No one's home.

**Comment by zanchey** [comment]
Rad. I'll update the patch.

**Comment by ridiculousfish** [comment]
Nice idea. The fix works great in my testing!

**Comment by zanchey** [comment]
@amluto, how does https://github.com/fish-shell/fish-shell/commit/b2367c5f850739c20bf26dc136241eafb843ea68 look?

**Comment by amluto** [comment]
Looks good to me.

**Comment by zanchey** [comment]
Merged with rebase as d1a56139e1d99530d.

**Comment by ridiculousfish** [comment]
Tests fine on OS X Yosemite :+1:

**Pull request closed without merging**
