### PR TITLE
[Ready] Update Mercurial completion

### PR DESCRIPTION
**Pull request by antonv6**
## Description

This update is based on hg 4.7, but most of the things this PR adds come from earlier versions. For example, -Z/--ignore-space-at-eol is from 4.4 and -i/--interactive for commit and revert was there since forever, just marked experimental until 4.5 (in case of revert).

Overall:

- new commands: convert, email, files, rebase, shelve, unshelve
- new flags (e.g. --interactive, --abort and --dry-run)
- updated command and flag descriptions
- completing more files for hg diff and revert
- completing hg blame as hg annotate and completing abbreviations of hg archive
- --style replaced by -T/--template
- more appropriate `complete` flags (-f, -r and -x)

Feedback is always welcome.

## TODOs:

- [x] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by faho** [comment]
>-f: ??? used for positional arguments a lot?

"-f" suppresses the built-in file completion logic. Without it, whatever completions your script adds,  fish will always add files.

So you need "-f" both when the thing you need to complete is not a file, but also when it is a certain subset of files.

For instance for `git add `, you don't want files that haven't changed, so you disable file completion and then generate the list of files in the script.

>-x is for things like --color=auto and --pager=always, where a parameter is always needed and is not a file, e.g.:

"-x" is just shorthand for "-rf".

Hope that helps!

**Comment by antonv6** [comment]
It did help, yes. Does the last commit look good?

Hmm, there seems to be a pattern with `-x` used for options that don't need arguments and the first word of description missing...

**Comment by faho** [comment]
>It did help, yes. Does the last commit look good?

Seems okay at a cursory glance.

Are you finished now?

**Comment by antonv6** [comment]
> Are you finished now?

Nope, I have more stuff to push. I was just waiting for an OK before committing on top of work that might've been incorrect.

I'll write a better description and mark this PR as ready soon (probably tomorrow). Oh, and I should probably add something to CHANGELOG.md about the changes.

**Comment by antonv6** [comment]
Now it's ready to be merged.

Here's my script to generate most of the completion file (although not everything). I just run merge tool on its output and hg.fish and update what's not in order. Hopefully the next person who touches hg.fish will find this PR.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from mercurial import (
    commands,
    cmdutil,
    error,
    extensions,
    ui as uimod,
)


fishcommands = [
    'add',
    'addremove',
    'annotate',
    'archive',
    'backout',
    'bisect',
    'bookmarks',
    'branch',
    'branches',
    'bundle',
    'cat',
    'clone',
    'commit',
    'config',
    'convert',
    'copy',
    'diff',
    'email',
    'export',
    'files',
    'forget',
    'graft',
    'grep',
    'heads',
    'help',
    'histedit',
    'identify',
    'import',
    'incoming',
    'init',
    'locate',
    'log',
    'manifest',
    'merge',
    'outgoing',
    'parents',
    'paths',
    'phase',
    'pull',
    'push',
    'qapplied',
    'qclone',
    'qdelete',
    'qdiff',
    'qfinish',
    'qfold',
    'qgoto',
    'qguard',
    'qheader',
    'qimport',
    'qnew',
    'qnext',
    'qpop',
    'qprev',
    'qpush',
    'qqueue',
    'qrecord',
    'qrefresh',
    'qrename',
    'qselect',
    'qseries',
    'qtop',
    'qunapplied',
    'rebase',
    'record',
    'recover',
    'remove',
    'rename',
    'resolve',
    'revert',
    'root',
    'serve',
    'shelve',
    'status',
    'strip',
    'summary',
    'tag',
    'tags',
    'unbundle',
    'unshelve',
    'update',
    'verify',
]


def printdesc(found):
    print 'function __fish_hg_commands'
    print '    for command in $commands'
    print '        switch $command'
    for cmd, entry in found:
        print '            case {}'.format(cmd)
        desc = entry[0].__doc__.splitlines()[0].rstrip()
        print '                printf "$command\\t{}\\n"'.format(desc)
    print '        end'
    print '    end'
    print 'end'


def printcmd(cmd, entry):
    print '# hg {}'.format(cmd)
    print 'for cmd in {}'.format(cmd)

    for arg in entry[1]:
        s = arg[0]
        l = arg[1]
        d = arg[3]
        if d.endswith(('(DEPRECATED)', '(EXPERIMENTAL)', '(ADVANCED)')):
            continue
        line = '    complete -c hg -n "__fish_hg_using_command $cmd"'
        if s:
            line += ' -s {}'.format(s)
        line += ' -l {}'.format(l)
        if len(arg) > 4:
            metavar = arg[4]
            if metavar == 'FILE':
                line += ' -r'
            else:
                line += ' -x'
        line += ' -d "{}"'.format(d)
        print line

    print 'end'
    print


def main():
    ui = uimod.ui.load()
    extensions.loadall(ui)
    found = []
    for cmd in fishcommands:
        try:
            _, entry = cmdutil.findcmd(cmd, commands.table, False)
        except (error.UnknownCommand, error.AmbiguousCommand):
            continue
        found.append((cmd, entry))
    printdesc(found)
    for cmd, entry in found:
        printcmd(cmd, entry)


if __name__ == '__main__':
    main()
```

**Comment by faho** [comment]
Very nice, merged! Thanks!

**Pull request merged**
