### PR TITLE
Add completions for helm

### PR DESCRIPTION
**Pull request by terlar**
This adds completions for helm. I have worked quite a lot on completions
recently and I am starting to find a pattern that seems to work for most
things. I have extensive ones for kubectl that I am working on. Perhaps
we can incorporate some of these methods and share to make it easier for
people to create completions.

About the useful changes:
=========================

- Using command works in any position and for several
  occurrences. Sometimes you want to use a global switch in front of the
  first command, that does not work with the usual
  `..._using_command`. This also ensures that you are using subcommands
  with options inbetween, but making sure they come in the correct
  order.
- Using option to check if an option is used.
- Using option with a certain value is used.
- I used a pattern for completing subcommands (and root level
  command). To make sure you don't get the completions again after
  having used them once. A common problem is when using just
  `__fish_seen_subcommand` is that you will get that same completion
  infinite amount of times.

Please let me know what you think and if you have any feedback.

About helm:
===========

helm - is a tool for managing Kubernetes charts. Charts are packages of
pre-configured Kubernetes resources.

See: https://github.com/kubernetes/helm

### CODE REVIEW

**Comment by krader1961** [comment]
I only skimmed the code and it looks okay from a style and correctness standpoint. I did not review it from a "is this the way we want to do things" viewpoint. I'm going to leave that to @faho or someone else.

**Comment by terlar** [comment]
I read up a bit more on the completions and found out that some of the things I suggested could be solved by utilizing `complete` `-a` and `-x` to add semantic completion for options with values. I revised all my usage of `-f` and substituted where possible. There still might be uses for something like a function checking for used option value. As some other options might depend on another option. Checking if a regular option is used could just utilize the `__fish_seen_subcommand_from`.

**Comment by faho** [comment]
I'm not a massive fan of depending on awk for anything, but I can see that builtins are a bit painful here, so I'm gonna merge this. Thanks!

**Comment by terlar** [comment]
I agree, but as you say, otherwise I would have to combine many different commands and it wouldn't be as clean, some of the things I guess could be replaced by a `string replace` but would be harder to understand what is going on. Perhaps a builtin for handling outputting "positional" arguments could be a thing. I could update it to use:

```
helm ls ^/dev/null | awk 'NR >= 2 { print $1"\tRelease of "$NF  }'
helm ls | awk 'NR >= 2 { print $1" "$2 }'
helm repo list | awk 'NR >= 2 { print $1 }'
helm search | awk 'NR >= 2 && !/^local\// { print $1 }'
helm search -l | awk 'NR >= 2 { print $1" "$2 }'

# vs
helm ls ^/dev/null | tail -n +2 | string replace -r '^([^\s]+)\s+([^\s]+\s+)+([^\s]+)' '$1\tRelease of $3'
helm ls | tail -n +2 | string replace -r '^([^\s]+)\s+([^\s]+).*$' '$1 $2'
helm repo list | tail -n +2 | string replace -r '^([^\s]+).*$' '$1'
helm search | tail -n +2 | string replace -r '^([^\s]+).*$' '$1' | string match -v 'local/*'
helm search -l | tail -n +2 | string replace -r '^([^\s]+)\s+([^\s]+).*$' '$1 $2'
```

What do you think? Perhaps it is worth it going built-in?

Thanks for the feedback, will keep in mind for further PR:s.

**Comment by zanchey** [comment]
The being-developed string tokenize tool might help.

**Pull request merged**
