### PR TITLE
Improve ssh completions/__fish_print_hostnames

### PR DESCRIPTION
**Pull request by faho**
## Description

This improves both correctness and performance of ssh completion.

Fixes issue #4377, #4374.

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

@zanchey: I'd like to add this to 2.7.0 if possible.

@ThomasAH: Please test. IIRC you should be able to just download the affected files and store them in ~/.config/fish/{completions,functions}.

### CODE REVIEW

**Comment by ThomasAH** [comment]
@faho: this is slower than your previous interim version
0.46s compared to 0.32s after applying the change mentioned in
https://github.com/fish-shell/fish-shell/issues/4374#issuecomment-327140257

New profile run:
```
23255   23255   ---> string replace -rfi '^\s*Host\s+' '' <$file | string trim | string replace -r '\s+' ' ' | string split ' ' | string match -v '*\**'
2319    28499   -> fish_vi_key_bindings
1961    30615   > builtin source /home/thomas/.config/fish/config.fish
25      34436   --> if test -r $file...
36230   36230   ------> nroff -c -man $mfish -t $rLL "$__fish_datadir/man/man1/$item.1" ^/dev/null
1233    37463   -----> set help (nroff -c -man $mfish -t $rLL "$__fish_datadir/man/man1/$item.1" ^/dev/null)
13      37507   ----> if test -e "$__fish_datadir/man/man1/$item.1"...
62      45569   -> for file in $ssh_configs...
60308   60308   ---> string replace -r '[#@| ].*' '' <$file \
36      60367   --> if test -r $file...
67228   67228   ---> string replace -r '[#@| ].*' '' <$file \
36      67318   --> if test -r $file...
77961   77961   ---> string replace -r '[#@| ].*' '' <$file \
33      78035   --> if test -r $file...
4302    79412   ----> for line in $help
837     120893  ---> __fish_print_help commandline
1379    122272  --> commandline -cpo
154     122426  -> set -l ssh_command $ssh_func_tokens (commandline -cpo)
244     224201  -> for file in $known_hosts...
1028    432955  > __fish_print_hostnames
```

**Comment by ThomasAH** [comment]
some tests of the full completion cycle:
I artificially created a longer ~/.ssh/known_hosts file (about 200000 lines) by concatenating it multiple times.
One host with a unique prefix is named "aqua", I use a stopwatch to manually measure "ssh aqu\<tab\>":

Plain 2.6.0: 80 seconds
2.6.0 + completions/ssh.fish from this PR: 42 seconds
2.6.0 + completions/ssh.fish + functions/__fish_print_hostnames.fish from this PR: 46 seconds
2.6.0 + completions/ssh.fish from this PR + functions/__fish_print_hostnames.fish from #4374: 46 seconds

For comparison (default versions from Debian jessie):
bash: less than 3 seconds (this would be great!)
zsh: 51 seconds (but with the PR fish is already slightly better than this)

**Comment by faho** [comment]
>Plain 2.6.0: 80 seconds

80 seconds, are you sure?

Note that the time in the profile is given in _micro_seconds (i.e. millionths of a second), so 

>1028    432955  > __fish_print_hostnames

means that 0.4s was spent in `__fish_print_hostnames` (the second column is the sum). 

That would mean that about 39s are spent somewhere else, which I doubt - for me a full completion is about .25s.

>@faho: this is slower than your previous interim version

Note that I never gave a full previous version. There have been numerous additional changes to `__fish_print_hostnames` since 2.6.0, which improve correctness, especially when your ssh config is more complicated - includes additional files and such.

**Comment by faho** [comment]
> I artificially created a longer ~/.ssh/known_hosts file (about 200000 lines) by concatenating it multiple times.

Oh, sorry. I should have read the entirety of your comment.

Yes, ideally this would be much faster still. But that's something that should be done generally, by improving the performance of `string` (and builtins in general). There's not much more to be done in this function, unless I'm missing some amazing speedup.

**Comment by ThomasAH** [comment]
> Note that I never gave a full previous version. There have been numerous additional changes to __fish_print_hostnames since 2.6.0, which improve correctness, especially when your ssh config is more complicated - includes additional files and such.

As I wrote somewhere: Yes, I prefer correctness above performance in this case, too.
And even with that huge known_hosts file there is no measurable difference, so maybe the difference was just a fluke.

> Yes, ideally this would be much faster still. But that's something that should be done generally, by improving the performance of string (and builtins in general). There's not much more to be done in this function, unless I'm missing some amazing speedup.

Other functions already use awk, so I translated the usage of string with a single awk script, which needs less than 1/10th of the time, I'd say this is an amazing speedup :)
```
    for file in $known_hosts
        if test -r $file
          # Ignore hosts that are hashed, commented or @-marked and strip the key.
          awk '$1 !~ /[|#@]/ {
            n=split($1, entries, ",")
            for (i=1; i<=n; i++) {
              # Ignore negated/wildcarded hosts.
              if (!match(entry=entries[i], "[!*?]")) {
                # Extract hosts with custom port.
                if (substr(entry, 1, 1) == "[") {
                  if (pos=match(entry, "]:.*$")) {
                    entry=substr(entry, 2, pos-2)
                  }
                }
                print entry
              }
            }
          }' $file
        end
    end
```

(tested with mawk and gawk)

**Comment by faho** [comment]
I merged this for now. Any further changes should wait for 3.0 - I'm wary of using awk, because there are weird implementations out there.

**Comment by ThomasAH** [comment]
> I'm wary of using awk, because there are weird implementations out there.
I know, that's why the code above looks a bit more complicated than it should be: To make it work with those weird implementations. Except for the `match` command it only uses things that are already used in `__fish_complete_man.fish`, and I'm not using the subexpressions available in some awk implementations.

So I'm very confident that it works even with weird or awkward awk implementations :)

**Comment by dzelionis** [comment]
I have posted my solution to the problem:
https://github.com/fish-shell/fish-shell/issues/4377

**Pull request merged**
