### PR TITLE
Vim-like emulation of `o' for visual mode

### PR DESCRIPTION
**Pull request by ferriff**
Implement a new function, `swap-selection-start-stop`: go to the other end of the highlighted text without changing the selection, the equivalent of `o` for vim visual mode.
Also add a default key binding to `o` in `fish_vi_key_bindings.fish'.

Here a snapshot of the vim documentation:
```
o                       Go to Other end of highlighted text: The current
                        cursor position becomes the start of the highlighted
                        text and the cursor is moved to the other end of the
                        highlighted text.  The highlighted area remains the
                        same. 
```

### CODE REVIEW

**Comment by ferriff** [comment]
Mmmhhh... not sure why the Travis CI buildl failed, local tests are successful.
Any advice is appreciated.

**Comment by krader1961** [comment]
Travis CI will sometimes fail for reasons unrelated to a change. I suspect the systems it is running on are sometimes overcommitted since the failures are always (AFAICT) random timeouts. See https://travis-ci.org/fish-shell/fish-shell/builds/117197841 for the failure related to your PR.

**Comment by ferriff** [comment]
Yep, I had already a look at that error, thanks for the confirmation (and for triggering the new checks, if you did, as I did not find how to do it). :)

**Comment by krader1961** [comment]
This looks okay from a quick review and it seems to work as expected (I pulled it into my local repo and built and tested it). So I have no objection to seeing it merged but would like a second opinion.

P.S., If you're willing to implement relatively obscure vim behaviors I would encourage you to fix the badly broken behaviors of far more common operations like the movement commands (e.g., "w" doesn't move to the start of the next word but rather the whitespace before it).

**Comment by ferriff** [comment]
OK I'll keep that in mind, I'll open a separate PR to fix "w" and others if I find them.
I haven't used fish long enough (< 3h? - already pretty much addicted!) to notice them all - but I managed to screw already some selections, so I've looked for fun at the code and found pretty easy to add `o'.

**Comment by faho** [comment]
This seems okay to me, but the function should be documented (in doc_src/bind.txt). While you are at it would be nice if you also added begin-selection, end-selection and kill-selection.

**Comment by krader1961** [comment]
Merged as squashed commit 168a156e5896fcaaf82a1b36587cde948f1765be. Thank you very much as another vi-mode user.

**Pull request closed without merging**
