### PR TITLE
Improve `gpg` completions

### PR DESCRIPTION
**Pull request by moverest**

### CODE REVIEW

**Comment by ridiculousfish** [comment]
thank you!

**Comment by zanchey** [comment]
I think this got wiped out with the merge of #6139. @moverest, are these gpg2-only, do you know?

**Comment by krobelus** [comment]
Here are the entries that I dropped when merging #6139 
Probably `delete-keys` is the same as `delete-key` which is already there but I'm not sure.

```
complete -c gpg -l card-status -d "Print card status"
complete -c gpg -l change-pin -d "Change pin"
complete -c gpg -l delete-keys -d "Remove keys from public keyring"
complete -c gpg -l delete-secret-keys -d "Remove keys from secret keyring"
complete -c gpg -l openpgp -d "Use strict OpenPGP behavior"
complete -c gpg -l server -d "Run in server mode"
```

**Comment by moverest** [comment]
@zanchey and @krobelus, you are probably right but I'm not sure yet.

From a quick glance at the man pages ([1.4](https://manpages.debian.org/testing/gnupg1/gpg1.1.en.html), [2.1](https://manpages.debian.org/testing/gnupg2/gpg2.1.en.html)), it seams like some options have been renamed (e.g. `--delete-key` doesn't appear on 2.1 but on 1.4) and some have been added (e.g. `--full-generate-key` only exists on 2.1).

**Comment by zanchey** [comment]
Fixed in 713c8f2d3.

**Pull request merged**
