### PR TITLE
Format

### PR DESCRIPTION
**Pull request by faho**
## Description

This runs `fish_indent` on fish, `clang-format` on C++, and [black](https://github.com/python/black) on python.

I would love it if we could agree that that's worth doing, and that we occasionally do so. If there are things wrong with the style, we should fix the tools to make it better or just live with a bit of weirdness as long as it's consistent weirdness.

I would also love to agree on black as the formatter for python - it's doing quite a nice job here!

## TODOs:

- [N/A] Changes to fish usage are reflected in user documentation/manpages.
- [N/A] Tests have been added for regressions fixed
- [N/A] User-visible changes noted in CHANGELOG.md

(This excludes fish_vi_cursor to not break #5849. I'd be happy to exclude any other files or handle any merge conflicts that come up because of this)

### CODE REVIEW

**Comment by faho** [comment]
I'd suggest looking at `git diff ` for classes of files, to get a feel for the kind of changes that aren't just whitespace it's doing.

Though one big thing is #3622 - fish_indent removes argument alignment. Personally, I've come around on that and no longer believe aligning arguments is worth all that much.

**Comment by zanchey** [comment]
`build_tools/style.fish` already runs `clang-format` and `fish_indent`, but it would be reasonable to add a Python formatter as well.

**Comment by zanchey** [comment]
Sounds fine to me.

**Comment by floam** [comment]
`clang-format` appears to make our Javascript look nicer FWIW.

**Comment by faho** [comment]
>clang-format appears to make our Javascript look nicer FWIW.

Huh... it somehow didn't occur to me that it would do JS as well. I suppose we should exclude the vendored stuff, though, right?

**Comment by faho** [comment]
Merged as 3bea947bb..c2970f961 (I removed the previous styling commits, rebased on master and ran style.fish again)

**Pull request closed without merging**
