### PR TITLE
Add completions for p7zip

### PR DESCRIPTION
**Pull request by sorairolake**
## Description

Add completions for [p7zip](http://p7zip.sourceforge.net/) command-line utils (`7z`, `7za` and `7zr`).

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
I think you should add `7z` here.

https://github.com/fish-shell/fish-shell/blob/a30630a1dfb490ef6a6458595a977b0c586cac70/share/tools/create_manpage_completions.py#L763-L774

**Comment by faho** [comment]
>I think you should add '7z', '7za' and '7zr' here.

@MaxVerevkin No need. Hand-written completions take priority over generated ones, so the files aren't used.

Adding them would add cruft to that script (and force you to jump through hoops if you wanted to use the generated version).

The reason to have exceptions in there is because the generated files don't make much sense and there's a huge number of them

**Comment by MaxVerevkin** [comment]
@faho 
Would it make sense not to generate an automated completion if manual completion already exists?

**Comment by faho** [comment]
No, because that wouldn't help much (save a couple of kilobytes of disk space I guess) and would in turn make looking at (e.g. because there are new options) or using the generated script (e.g. as a workaround) harder, plus it's more code.

**Comment by MaxVerevkin** [comment]
@faho 
On my machine `fish_update_completions` time decreased from 9.26 to 8.16 secs.

**Comment by MaxVerevkin** [comment]
> plus it's more code

Not really. https://github.com/fish-shell/fish-shell/pull/7221

**Comment by faho** [comment]
Merged, thanks!

**Pull request merged**
