### PR TITLE
Change natural number to whole number

### PR DESCRIPTION
**Pull request by aadibajpai**
## Description

It's a bit silly really, but the tutorial talks about how status codes are returned as natural numbers. Well, 0 is not a natural number, since natural numbers start from 1 but whole numbers start from 0.

Thanks 😄

### CODE REVIEW

**Comment by faho** [comment]
>since natural numbers start from 1 but whole numbers start from 0.

That depends *entirely* on which definition you look up. I've seen both, and in particular I've seen "whole numbers" include negative numbers.

Change it to "positive whole number" and you have a deal.

**Comment by aadibajpai** [comment]
> > since natural numbers start from 1 but whole numbers start from 0.
> 
> That depends _entirely_ on which definition you look up. I've seen natural numbers both with and without zero, and in particular I've never seen "whole numbers" not include negative numbers.
Interesting, in school we're taught that natural numbers are 1...∞ while whole numbers are 0...∞, no negative numbers anywhere (those are integers).
> Change it to "positive whole number" and you have a deal.
I'd be happy to do that (although 0 is not positive 😉)

**Comment by krobelus** [comment]
One could say "non-negative integer" to include zero.

However, I think this sounds too academic. I'd go with `numeric exit code` and perhaps add `between 0 to 255`.

**Comment by aadibajpai** [comment]
> One could say "non-negative integer" to include zero.
> 
> However, I think this sounds too academic. I'd go with `numeric exit code` and perhaps add `between 0 and 255`.

Personally I'd be okay with non-negative integer, describes it perfectly w/o the natural/whole ambiguity (I'm amazed that's a thing tbh).

**Comment by faho** [comment]
Yeah, that'll do.

Merged, thanks!

**Pull request merged**
