### PR TITLE
completions/pacman.fish: Update for pacman 5.2

### PR DESCRIPTION
**Pull request by akiirui**
## Description

pacman 5.2 has remove File Options `-s --search` and `-o --owns`.
Ref: [pacman: rework the UI of -F](https://git.archlinux.org/pacman.git/commit/?id=ff1ae94c102cab487444bcdb0c76ee489c11dfe8)

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by faho** [comment]
Also `--force` was removed, replaced with `--overwrite <glob>` (introduced in 5.1), in case you'd like to add that.

**Comment by akiirui** [comment]
I will refine this completions with latest man page.
Please waiting for....

**Comment by akiirui** [comment]
All done.

**Comment by faho** [comment]
Merged, thanks!

**Pull request merged**
