### PR TITLE
Update mix completion

### PR DESCRIPTION
**Pull request by janernsting**
Among others `mix escriptize` has not been supported since July 2014:
https://github.com/elixir-lang/elixir/issues/2468

### CODE REVIEW

**Comment by faho** [comment]
This seems like it should work, but there's also room for improvement.

First of all, why is there all that duplication with `help`? Why not just change `__fish_mix_needs_command` to also return 0 if the command is `help` (btw this will fail if there's an option before a command since it always expects a command to come as second word no matter what)?

Secondly this doesn't do much - it offers all the commands and their options, but it doesn't offer the arguments - what comes after `mix app.start`? What does it apply to? For example the [mix documentation](http://elixir-lang.org/docs/stable/mix/Mix.html) lists `mix run server.exs` - how do we complete that server.exs? Is it just a file?

Thirdly, since `mix` is a rather generic name, I'd appreciate a comment at the top that this is about an elixir tool.

Otherwise: Thanks for helping us keep completions up-to-date.

**Comment by janernsting** [comment]
1. `mix` itself does not accept any options (except for `-h`); only commands. `mix help` returns the applicable commands in a given project context. With regard to `mix help`, we can generate the items executing `mix help` prior to completion: it does not have to complete files (The invocation itself incurs a slight lag, however / 330ms). Unfortunately, this does not apply with regard to normal completion as some commands accept files and some don't.

  I would like to extend command completion in a way, such that project local commands are also considered for completion. For example, frameworks such as Phoenix provide [their own tasks/commands](http://www.phoenixframework.org/v0.10.0/docs/mix-tasks), which are currently not offered for completion. This could be achieved by removing the commands for which completions already exist from the list of applicable commands (`mix help --names | egrep -vx 'archive|clean|…') and use that filtered list to add those project local commands.
1. `mix app.start` does not accept any parameters. Regarding `mix run`: it receives a file name.
1. Point taken and applied.

**Comment by faho** [comment]
> mix app.start does not accept any parameters. Regarding mix run: it receives a file name.

Well, not just those two - every subcommand.

>This could be achieved by removing the commands for which completions already exist from the list of applicable commands (`mix help --names | egrep -vx 'archive|clean|…') and use that filtered list to add those project local commands.

1. Be sure to check if your grep options work on weird greps (not just a new GNU Grep, but what OSX and the BSDs use)

2. I've said before that fish should (i.e. it currently doesn't) coalesce duplicate completion options in such a way that if only one description exists it is kept (so ignoring the commands should be unnecessary) - or does `mix help` have a "--local-only" option to do the filtering (can't say I'm impressed by the documentation - I haven't found something resembling a manpage that just lists CLI options)?

**Comment by janernsting** [comment]
Sidenote: in oh-my-zsh, there is a [plugin to cache completion results](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/mix-fast).

**Comment by faho** [comment]
https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_packages.fish#L40 does similar things. Is `mix` slow like a java program or something?

Oh and if you wanted to do this, please use a filename that indicates this is for fish so people can find out what generated it.

**Comment by janernsting** [comment]
> > mix app.start does not accept any parameters. Regarding mix run: it receives a file name.
> 
> Well, not just those two - every subcommand.

I took a look at each subcommand to see if they are supposed to accept
files as parameters.

> >This could be achieved by removing the commands for which completions already exist from the list of applicable commands (`mix help --names | egrep -vx 'archive|clean|…') and use that filtered list to add those project local commands.
> 
> 1. Be sure to check if your grep options work on weird greps (not just a new GNU Grep, but what OSX and the BSDs use)

OSX and FreeBSD manpages include the options with matching
descriptions. I should use `sgrep -Evx '…'` instead.

> 2. […] does `mix help` have a "--local-only" option to do the filtering

Well, there is `mix local`. However, it ignores tasks that are defined
as part of the project and omits other valid tasks that appear to be
transitive dependencies of local tasks. I have to admit: this is not
straightforward.

> (can't say I'm impressed by the documentation - I haven't found something resembling a manpage that just lists CLI options)?

True, indeed. I attached the output for `mix help help`.

# mix help

Lists all tasks or prints the documentation for a given task.

## Arguments

    mix help                  - prints all tasks and their shortdoc
    mix help TASK             - prints full docs for the given task
    mix help --search PATTERN - prints all tasks that contain PATTERN in the name
    mix help --names          - prints all task names and aliases
                                (useful for autocompleting)

## Colors

When possible, `mix help` is going to use coloring for formatting
guides. The formatting can be customized by configuring the Mix
application either inside your project (in `config/config.exs`) or
by using the local config (in `~/.mix/config.exs`).

For example, to disable, one may:

    [mix: [colors: [enabled: false]]]

The available color options are:

  * `:enabled`         - shows ANSI formatting (defaults to `IO.ANSI.enabled?`)
  * `:doc_code`        - the attributes for code blocks (cyan, bright)
  * `:doc_inline_code` - inline code (cyan)
  * `:doc_headings`    - h1 and h2 (yellow, bright)
  * `:doc_title`       - the overall heading for the output (reverse, yellow, bright)
  * `:doc_bold`        - (bright)
  * `:doc_underline`   - (underline)


Location: /home/jan/socra/elixir/lib/mix/ebin

**Comment by janernsting** [comment]
> > mix app.start does not accept any parameters. Regarding mix run: it receives a file name.
> 
> Well, not just those two - every subcommand.

I took a look at each subcommand to see if they are supposed to accept
files as parameters.

> >This could be achieved by removing the commands for which completions already exist from the list of applicable commands (`mix help --names | egrep -vx 'archive|clean|…') and use that filtered list to add those project local commands.
> 
> 1. Be sure to check if your grep options work on weird greps (not just a new GNU Grep, but what OSX and the BSDs use)

OSX and FreeBSD manpages include the options with matching
descriptions. I should use `sgrep -Evx '…'` instead.

> 2. […] does `mix help` have a "--local-only" option to do the filtering

Well, there is `mix local`. However, it ignores tasks that are defined
as part of the project and omits other valid tasks that appear to be
transitive dependencies of local tasks. I have to admit: this is not
straightforward.

> (can't say I'm impressed by the documentation - I haven't found something resembling a manpage that just lists CLI options)?

True, indeed. I attached the output for `mix help help` (GitHub does not want me to attach it; goes wrong):

--- 
# mix help

Lists all tasks or prints the documentation for a given task.

## Arguments

    mix help                  - prints all tasks and their shortdoc
    mix help TASK             - prints full docs for the given task
    mix help --search PATTERN - prints all tasks that contain PATTERN in the name
    mix help --names          - prints all task names and aliases
                                (useful for autocompleting)

## Colors

When possible, `mix help` is going to use coloring for formatting
guides. The formatting can be customized by configuring the Mix
application either inside your project (in `config/config.exs`) or
by using the local config (in `~/.mix/config.exs`).

For example, to disable, one may:

    [mix: [colors: [enabled: false]]]

The available color options are:

  * `:enabled`         - shows ANSI formatting (defaults to `IO.ANSI.enabled?`)
  * `:doc_code`        - the attributes for code blocks (cyan, bright)
  * `:doc_inline_code` - inline code (cyan)
  * `:doc_headings`    - h1 and h2 (yellow, bright)
  * `:doc_title`       - the overall heading for the output (reverse, yellow, bright)
  * `:doc_bold`        - (bright)
  * `:doc_underline`   - (underline)

**Comment by janernsting** [comment]
> Is `mix` slow like a java program or something?

No, it is not like Maven. But IMHO a minimum of 300ms is quite a bothersome lag for completing subcommands.

**Comment by janernsting** [comment]
The cached results for `pacman`, `zypper`, `yum`, and `rpm` apply system wide. `mix` provides different tasks depending on the project it is executed in. Therefore, caching would have to take place on a per project basis.

The oh-my-zsh plugin stores output tasks in a file within the repo. It does not even feature a timestamp. Users are required to trigger a refresh of the cached results. :disappointed:

**Comment by faho** [comment]
>I took a look at each subcommand to see if they are supposed to accept files as parameters.

Not just files - _everything_. If it accepts some kind of target, we should complete that.

>OSX and FreeBSD manpages include the options with matching descriptions. I should use sgrep -Evx '…' instead.

If you mean "grep but without the massively annoying GREP_OPTIONS environment variable", that's `__fish_sgrep` now (someone used "sgrep" as an alias for `grep -r`, and it broke fish in new and interesting ways).

>Therefore, caching would have to take place on a per project basis.

Okay. Maybe based on the name of the project directory? `fish-(string replace "/" "" "$projectdir)-$typeofcompletion` or so? (Though that requires some trickery to figure out the project directory without calling `mix` - unless it's fast enough for that)

>But IMHO a minimum of 300ms is quite a bothersome lag for completing subcommands.

Yeah, that's not great.

>The oh-my-zsh plugin stores output tasks in a file within the repo. It does not even feature a timestamp. Users are required to trigger a refresh of the cached results. :disappointed:

In my experience, zsh requires users to do a ton of stuff. That's my main gripe with it, TBH.

**Comment by janernsting** [comment]
>> I took a look at each subcommand to see if they are supposed to accept files as parameters.

> Not just files - everything. If it accepts some kind of target, we should complete that.

I've to admit, I am not using `mix` enough, to say that there other types of completion targets (e.g. `mix deps.unlock` supports dependencies for which I cannot say how these can be determined).

> Okay. Maybe based on the name of the project directory? fish-(string replace "/" "" "$projectdir)-$typeofcompletion or so? (Though that requires some trickery to figure out the project directory without calling mix - unless it's fast enough for that)

That could be one way of attempting it. How would you go about regarding updating completions? As fish users do not have to manually activate this completion caching, they would not know about it in the first place, right?

AFAIK `mix` should only be invoked in the project's root directory (i.e. where the corresponding `mix.exs` file resides). The only exception applies to creating new projects which can not only be done through `mix new`, but also through `mix phoenix.new` or other custom tasks.

Currently, I can not come up with an elegant solution to the problem. One the one hand, I would like to update mix's completion support. On the other, I would prefer to have the completion deduced from the project's context which however takes at least 300ms; mitigation through caching could surely be done, but opens the issue of tainted caches and how these are dealt with from a user's perspective.

**Comment by faho** [comment]
Merged with rebase and squash as 8e3e2865772bccbc404c770557d3eb34c11cd30e - if you ever figure out how you want to handle the other stuff please open another PR.

Thanks!

**Comment by janernsting** [comment]
I found some promising approach to properly invalidate the mix cache: https://github.com/lexmag/dotfiles/blob/master/zsh/functions/_mix

Will try to look into this over the weekend.

**Comment by janernsting** [comment]
Hm, lexmag [feeds a zsh wildcard/globbed expression](https://github.com/lexmag/dotfiles/blob/master/zsh/functions/_mix#L4) `**/mix/tasks/*` to a function `last_modified` that determines, if the cache is tainted or not. Is there any way to mimic the globbed expressions with fish?

**Pull request closed without merging**
