### PR TITLE
fix discoverable default completions dir

### PR DESCRIPTION
**Pull request by xyb**
When I tried to fix homebrew's fish comletion issue in Homebrew/homebrew#45262, I found that the fish completions dir discoverable design based on pkg-config which described in [release 2.2.0](https://github.com/fish-shell/fish-shell/releases/tag/2.2.0) does not work at all. After have discussions with @zanchey (#2500) I think I have found how to fix it. Here it is.

### CODE REVIEW

**Comment by zanchey** [comment]
I like the simplicity of this approach, but I'm cautious about adding a runtime dependency on `pkg-config`, which is really a software developer's tool only. I'd prefer to make the `vendor_completions.d` directory configurable through `configure`, with a sensible default in the case of the Xcode build.

**Comment by xyb** [comment]
@zanchey I agree `pkg-config` is a compiler tool more than user tool, it's somehow weird related to tab completions. Are you suggesting a solution like add an arg `--completions-dir` something to `configure.ac` instead of `pkg-config`'s `completionsdir` variable, and use it customize config.fish? I like this but the description about `pkg-config` in release 2.2.0 will break.

**Comment by zanchey** [comment]
Yes, that's what I'm suggesting. Why would the `pkg-config` approach stop working? The .pc file is generated by `configure`.

**Comment by xyb** [comment]
@zanchey I mean this description about `pkg-config` will break:

> Fish now defines a default directory for other packages to provide completions.
> ... this path is discoverable with `pkg-config --variable completionsdir fish`.

We need modify the document `doc_src/index.hdr.in` in that case. Anyway, I'll change to the new way.

**Comment by xyb** [comment]
@zanchey updated.

**Comment by zanchey** [comment]
This still isn't the right approach - I definitely appreciate the work but I'm going to go about this in a different way, so I'm closing this for now. Thanks for helping to spur me on!

**Pull request closed without merging**
