### PR TITLE
Correction to make rule for fish_version

### PR DESCRIPTION
**Pull request by lrm29**
I noticed that the fish version number was not being updated when built from the git repository. Now if I touch FISH-BUILD-VERSION-FILE then fish_version.o is rebuilt.

### CODE REVIEW

**Comment by faho** [comment]
How do you see this? Both $FISH_VERSION and `fish --version` on my system print the right thing.

**Comment by krader1961** [comment]
Like @faho I'm curious how you managed to do a build with the wrong version definition. Your change is correct but for reasons I don't yet understand it doesn't seem to make a difference in practice. That is, while correct it doesn't seem to be necessary.

**Comment by lrm29** [comment]
I saw this after pulling a bunch of commits recently, building and installing. The version wasn't bumped.

I'm able to reproduce by:

- change README.md
- commit the change to git locally
- run make
- ./fish --version will not reflect your latest commit

**Comment by krader1961** [comment]
Wow! I can reproduce just by checking out a different branch after doing `make fish`. Strange that no one ever noticed this. Thanks. Merged as commit 83233ccc5a6ab8e7521133eebb771af6939750a8.

**Comment by lrm29** [comment]
Sure. We can't be having out of date fish lying around. Think of the smell!

**Pull request closed without merging**
