### PR TITLE
uniq and date completions

### PR DESCRIPTION
**Pull request by lordlycastle**
`uniq` and `date` completions added for OS X.

### CODE REVIEW

**Comment by lordlycastle** [comment]
Sorry, I might have messed up somewhere. I don't know why it's including previously pulled commits as well.

**Comment by floam** [comment]
Don't do all your work in master, or 'base' if it is what you use like a master.

You want to do work in feature branches, that start off fresh with no conflicting differences from the upstream master. You then submit pull requests of just these branches into upstream (here) or just merge them yourself into your own personal fork. 

For instance when you started this work you `git checkout -b uniq-date-completions` while in the master branch on your fork. That creates a new branch and switches you to it. If you get bored of it and don't finish, you can leave it there. `git checkout master`, and make a new branch diverging from that called `lordycastle/coolthing` for the next cool thing, just like the first one you did.. When these completions were looking good enough to submit, done you do a pull request for `lordycastle/uniq-date-completions` into fish-shell/master. On github. When they pull it in and accept it it will naturally make its way into your master branch next time you `git pull`. If they don't see the light and never accept it, it's OK to to just do your own merge into your own master branch and keep it it with better completions there.

**Comment by faho** [comment]
In this case, you can probably fix it like this:

```
git checkout master
git pull origin # update the master branch to the newest state of the main fish repo
git checkout base
git rebase master # try to apply your commits new on top of the master branch
```

If that doesn't work, this should:

```fish
git checkout master # get back to the master branch
git pull origin # update it to the latest state of the main repo (origin here might also refer to your clone, check `git remote`) 
git checkout -b 2807-fixup # make a branch to fix this, starting from master
git cherry-pick 64ada718eb3f6bdab3253a8f1491d28285850613 # get the commit you're interested in to that branch
git branch -D base # remove old branch
git checkout -b base # create a new branch with the same name and check it out
git push --force # overwrite the PR with the fixed version
```

However, in this case I can just cherry-pick the one commit myself.

**Comment by faho** [comment]
Merged as 540bdfc. Thanks!

**Comment by lordlycastle** [comment]
@floam Thanks for all that info. To answer your question why I had a `base` branch, it was supposed to point the `fish-shell/master`, so I could just switch from my `master` when I wanted to build it up-to-date. I read somewhere this was the proper way to do it. I think, by mistake I committed to `base` rather than my `master` and hell broke lose....

You said to not touch the `lordlycastle/master` and make changes in its branches only, merge them when they're complete. That's probably a better plan. However, I used a separate branch that points to `fish-shell/master` because I would have to manually fetch/pull `fish-shell/master` into `lordlycastle/master` to get up-to-date commits. Doing that has led me into a similar situation. 

Another problem with your suggestion, I think, is that if I merge a branch that isn't merged with the `fish-shell/master` to my `lordlycastle/master` then when I pull in the future from `fish-shell/master` to mine `lordlycastler/master` wouldn't it raise an issue? Maybe I'm just over thinking it.  

@faho Thanks for the fixes but the first one led to 42 UP and 47 DOWN commits. I know from experience that's not a place you wanna be in. As for the second fix well that did things I though were not possible. 

Regardless, thanks for the help, it's probably best for me to trash my repo and re-fork it again. Git may not be for everybody. :disappointed:

**Pull request closed without merging**
