### PR TITLE
treewide: replace deprecated C headers

### PR DESCRIPTION
**Pull request by neheb**
Found with clang-tidy's modernize-deprecated-headers.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by floam** [comment]
We ought to be using the std:: namespace if using the `cfoo` headers.

**Comment by floam** [comment]
e.g. what I did in https://github.com/fish-shell/fish-shell/commit/aaacdb89b628eb37bb2e7c461662a677baf9b23e#diff-eebc687857eb591b1beb2a6c87379378

**Comment by zanchey** [comment]
And there's symbols on some platforms that aren't in `std::`; given the probable fallout is there significant benefit to this kind of cleanup?

**Comment by floam** [comment]
> And there's symbols on some platforms that aren't in std::
Still the case since the C++11 switch? Since that change we require a newer Clang/GCC than we had in the past. I'm surprised a libc++ or libstdc++ with C++11 officially implemented would still have that happen.

**Comment by zanchey** [comment]
3b0f642de9fef3bac3ef98d8bcecdbdfb81e945b and 1293cd8b6a are the commits that spring to mind; I don't mind testing this on RHEL 6 at some stage as that's probably the oldest platform we support, but I'm not clear on what the actual benefit is.

**Comment by krobelus** [comment]
Regarding a switch to `std::`: if this would affect many lines I would only do it given a good reason as to not unnecessarily clutter `git blame` output.

**Comment by neheb** [comment]
@zanchey the former (which I authored) deals with the libc not supporting _GLIBCXX_USE_C99_MATH_TR1. Fish doesn't actually compile with that libc because of missing locale_t.

In any case, using namespace std; is found nowhere in the codebase. As the C++ headers include the C headers, which is a relatively moot point.

**Comment by zanchey** [comment]
Works fine on RHEL 6; @Mno-hime, are you able to test on OpenIndiana?

**Comment by Mno-hime** [comment]
@zanchey Works me with GCC 6 & 8.

**Comment by zanchey** [comment]
OK, that's useful to know.

I'm still ambivalent about merging; I realise that this is unhelpful "stop energy" but I don't understand what the benefit is. Am I missing something, or is it more than cleanup of technically-deprecated but unlikely to ever stop working headers?

**Comment by ridiculousfish** [comment]
Let's not do this, it does not appear to provide any practical benefit. It's not clear to me which functions would get put in `std` with this change anyways - I think it's C functions but not Unix ones? 

(Incidentally `using namespace std;` would be a grave mistake).

Thank you for opening this anyways - hygiene is important!

**Pull request closed without merging**
