### PR TITLE
Add completions for pass

### PR DESCRIPTION
**Pull request by rstacruz**
Pass: http://www.passwordstore.org/

### CODE REVIEW

**Comment by zanchey** [comment]
I'd like to back this out for the reasons in #1843.

**Comment by rstacruz** [comment]
:+1: sorry about that, had no idea — it seems Homebrew doesn't install that.

**Comment by rstacruz** [comment]
(...fwiw, the implementation i did works much faster: it calls `sed` just once instead of once for every password entry you have.)

**Comment by zanchey** [comment]
You might like to submit the change to the pass project - although I'd be careful with `pushd` as many people hook on the directory change.

**Pull request merged**
