### PR TITLE
Restore lexicon_filter and doc syntax with tags

### LINKED ISSUE #3197: Doxygen XML tags should be restored
- [x] Did you do [a quick search?](/issues?utf8=✓&q=is:issue+user:fish-shell)
- [x] Try [with the latest](/fish-shell/fish-shell/releases/tag/2.3.1) fish version?

In April a number of our custom tags were replaced with a backslashed form:

https://github.com/fish-shell/fish-shell/commit/dcef1a55932db5ad4394eb6fbcb76d63d8ab520d
https://github.com/fish-shell/fish-shell/commit/5df8fab4637865cc895bc698410efedc765dfd8c

This is rather unpleasant and the commit messages seem to indicate it was only done to silence warnings that we don't understand but seemed to not be HTML tags or XML conforming to Doxygen's XML DTD

Curiously, on my system I am actually getting less warnings printed if I revert these, and it improves the readability of the code a lot.

### PR DESCRIPTION
**Pull request by floam**
Fixes #3197

Reverts the two responsible commits, making the docs every-so-slighly less arcane. Also refreshed the Doxyfiles with doxygen -u.

This does not introduce warnings here, contrary to what the commits had me expecting. 

these warnings and one about "args" is gone:
`/Users/floam/src/githubfish/doc.h:5633: warning: found </pre> tag without matching <pre>
/Users/floam/src/githubfish/doc.h:5633: warning: unexpected command endhtmlonly`

---

- [ ] FORMATTING.md needs (un-)updating.
- [ ] Verify it's producing good manpages and HTML elsewhere

### CODE REVIEW

**Comment by krader1961** [comment]
This is a huge change. The majority of it seems to be trivial reformatting. I can't easily tell which portion of the change requires review. Please separate the style reformatting changes from the substantive changes.

**Comment by floam** [comment]
@krader1961 This only reverts two of your commits - I didn't change anything.

**Comment by krader1961** [comment]
> This only reverts two of your commits - I didn't change anything.

Are you serious? Reverting prior changes is itself a change. I'm willing to agree my change that you're reverting was wrong. Yet you have not made the case that this change is itself correct or an improvement.

**Comment by floam** [comment]
> Are you serious? 

Yeah - I feel like the standard is a little bit different when we realize a mistake was made. 

> Yet you have not made the case that this change is itself correct or an improvement.

Like you say it's a big change that this reverts. Both to the lexicon_parser and all the stuff throughout `doc_src`... playing Hardy Boys on problems experienced today and reviewing code back to the April commits to figure out what has been done isn't particularly fun... Given that I can't find a PR where that code was reviewed in the first place, I sort of felt like what I want to do is reject those changes and let us go back to the drawing board on whatever they were accomplishing for fish.

**Comment by floam** [comment]
@MarkGriffiths got tired of waiting for me and did it for us on #3247. Thanks!

**Pull request closed without merging**
