### PR TITLE
Set runtime dir to /tmp/user.$USER if user cannot access $XDG_RUNTIME_DIR

### PR DESCRIPTION
**Pull request by tannerb**
Add simple access checking to see if user has RWX access to XDG_RUNTIME_DIR

### CODE REVIEW

**Comment by zanchey** [comment]
I can't see any adverse effects. This should fix #2222 and possibly other problems as well.

**Comment by zanchey** [comment]
Is it worth using `check_runtime_dir()` as well as `access()`? I guess the case where that would fail is using `sudo` or `su`. I'm not sure that succeeding in those cases is a problem - it ostensibly creates a way to run arbitrary code as another use but luckily fish already lets you do that under those circumstances.

**Comment by tannerb** [comment]
@zanchey I will admit I did not look closely in to check_runtime_dir. Looking now, I believe there may be a slight issue with check_runtime_path at line 139: `|| statpath.st_uid != uid`: what if the user has full access through group permission but is not the owner of the path under test?

**Comment by zanchey** [comment]
I think that is best avoided - there are likely to be assumptions in the universal variable notifiers that expect all processes to be in the same user context.

**Comment by zanchey** [comment]
Merged with rebase and some edits as b4b5c21 - thanks!

**Pull request closed without merging**
