### PR TITLE
escape square brackets in an argument before completing it

### LINKED ISSUE #5831: Incorrect tab-completion escaping with certain characters
```
$ fish --version
fish, version 3.0.2-948-g4ddfd730
```

Repro:

```
$ touch foo foo[bar]
$ ls foo[<TAB>
$ ls foo[bar\]
```

This should have completed to either `foo[bar]` or `foo\[bar\]`, but not `foo[bar\]`:

image

### PR DESCRIPTION
**Pull request by krobelus**
fixes #5831

----

## Description

I believe this solves the issue, which seems to only appear when a non-fuzzy completion of tokens
with unmatched opening brackets is done. I think that's why it does not happen for umatched closing
brackets (because the completion would be fuzzy). Other special characters should not be affected.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by ridiculousfish** [comment]
I think this may just be a tokenizer bug - it's not obvious to me why `foo[bar\]` should fail to tokenize.

**Comment by ridiculousfish** [comment]
It's probably incorrect to ever suggest unescaped `[` or `]` as part of a completion

**Comment by krobelus** [comment]
> it's obvious why it should not tokenize.

Why shouldn't it? I'd guess to be able to report a user error (which is arguably more common than the referenced issue).

> It's probably incorrect to ever suggest unescaped `[` or `]` as part of a completion

Yeah, it sort of already does that - in the example the completion is appended with escaped brackets is but existing unescaped brackets stay.

I realized the patch causes other unexpected behavior :( 
```
echo 1 > 'foo'
echo $PATH[(cat f<TAB>
```
Makes it escape the `[`. So escaping everything in the current token is too much, I'll try to figure that out.

The root of the problem is that unescaped `[` and `]` have a special meaning only in some cases, and it's not that trivial to tell.

**Comment by krobelus** [comment]
> I realized the patch causes other unexpected behavior :(

I have implemented a different approach now, this should work fine now for all cases.

**Comment by ridiculousfish** [comment]
I like the new approach better too! Merged as bc3dde997decd8db318bed322c8d31d0528f4879 with some fixes in b2fe2f9ff31cc8ec105d4340fcb9362ee7e566fd . Thank you, awesome contribution!!

**Pull request closed without merging**
