### PR TITLE
kill all jobs when exiting an interactive shell

### LINKED ISSUE #3497: warn if exiting fish when background jobs exist
If there are any running jobs in the shell, we should not be closing without a warning that the jobs are lost into the greater process list hierarchy. I don't think it should matter if the jobs running are background or foreground, but tell me why I'm wrong.

### PR DESCRIPTION
**Pull request by krader1961**
Fish is not consistent with other shells like bash and zsh when exiting
an interactive shell with background jobs. While it is true that fish
explicitly claims no compatibility with POSIX 1003.1 this is an area
where deviation from the established practice adds negative value.

The reason for the current behavior seems to be due to two users who did
not understand why interactive shells managed background jobs as they
did and were not aware of tools like `nohup` or `disown`.

There is also a fairly significant bug present due to a misunderstanding of
what a true value from `reader_exit_forced()` means. This change corrects
that misunderstanding.

Fixes #3497

### CODE REVIEW

**Comment by floam** [comment]
Makes sense to me, LGTM.

**Comment by ridiculousfish** [comment]
This looks like it does the wrong thing for `breakpoint`. When `breakpoint` is invoked it starts an interactive session (i.e. called `read_i()`). When that session terminates, now we kill all jobs. Example:

    sleep 100 &
    breakpoint
    sleep 1
    jobs
    
Hit control-D to resume when the breakpoint is hit. Before this change, the `sleep 100` will appears in the `jobs` list; after the change it's missing.

**Comment by krader1961** [comment]
Yep, I wasn't even aware of that feature despite using fish for more than a year. Thanks for catching that botch. Should be a trivial fix. I'll also see how difficult it might be to add a unit test.

**Comment by krader1961** [comment]
I've fixed the botch when exiting the `breakpoint` context with commit 9870cf838. I did not add unit tests because doing so is going to be hard and @zanchey is leaning towards reverting this change.

**Comment by zanchey** [comment]
Yes, around Festivus I was thinking "I gotta lotta problems with this patch, and now you're gonna hear about them!"

On reflection, though, I think this is the right behaviour (i.e. warn first, then kill all the jobs). In defence of my original changes, the default behaviour of POSIX shells in unconditionally sending SIGHUP has surprised many people, even if it eventually makes sense once you understand the process model. I am certainly not about to back out this patch but it will need noting in the release notes.

I do have a concern about the warning message, though. "stopped or running jobs" is an unhelpful description; are there any jobs that will no longer get SIGHUP? My reading is no - in that case the warning should just be "There are still jobs active (use the jobs command to see them). A second attempt to exit will terminate them."

**Comment by krader1961** [comment]
> I do have a concern about the warning message, though....

I like your proposed wording so I'll gin up a change in a moment.

**Pull request closed without merging**
