### PR TITLE
 remove unnecessary heap allocation

### PR DESCRIPTION
**Pull request by thechampagne**
## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by Xiretza** [comment]
Ignoring the fact that this doesn't even build, having to explicitly specify the NUL byte is a footgun.

Most of these allocations either happen *at most once* per fish invocation, or only happen in conjunction with some job control syscalls/signals, which are *way more* overhead than a single small allocation. This kind of reduction in readability and safety would need some seriously convincing benchmark results.

**Comment by faho** [comment]
Yeah, I'm rejecting this as not worth it. It's an irrelevant performance optimization and usage pessimization.

Sorry!

**Comment by thechampagne** [comment]
> Ignoring that this doesn't build, having to explicitly specify the NUL byte is a footgun.

@Xiretza why specifying the NULL byte is a footgun ?

**Comment by faho** [comment]
>why specifying the NULL byte is a footgun ?

@thechampagne it's a footgun (i.e. an awkward trap to stumble over) because it is easy to forget. Few things require you to spell out the NUL for typical strings - rust doesn't, C++ doesn't.

And if you do forget it it would break in interesting ways.

That's why we're going for the more idiomatic, easier to read version that we already have, especially because the difference is not going to be measurable.

Performance improvements should come with benchmarks so we can see what impact they have, and if the impact was large enough we would also take a bit of a hit in readability - but that's not the case here.

**Comment by thechampagne** [comment]
I would force myself to remember it instead of using useless runtime code.

**Comment by faho** [comment]
And that is a trade-off we won't make.

We'll lean towards maintainability in favor of an increase in performance that's so small that it's lost in the statistical noise.

Anyway: I do believe this has run its course. Thank you for your interest in fish, I am sorry that I did not accept your pull request. If you do want to work on performance, which is certainly a worthwhile task and something that could much improve fish, please do add a benchmark.

**Pull request closed without merging**
