### PR TITLE
Ignore comments when creating man page completion

### PR DESCRIPTION
**Pull request by mohd-akram**
Comments aren't shown in man pages and shouldn't be parsed.

### CODE REVIEW

**Comment by floam** [comment]
What exactly did this fix?

Not necessarily a ding against this, but just something I'll note: I have seen in some of Apple's manages before that there have been "undocumented" options which are commented out. This would have an effect of causing such options not being picked up.

**Comment by krader1961** [comment]
Liike @floam I am wondering what this fixes. This is a good example of a change the should be tied to an open issue so we have sufficient context to decide if this is a good fix for the issue.

**Comment by mohd-akram** [comment]
Well I noticed this for a [man page](https://github.com/mohd-akram/todo/blob/master/man/todo.1) I wrote; it was picking up the comment on the next line. The [original issue](https://github.com/fish-shell/fish-shell/issues/98) which simply removed the escape is not reintroduced with this change.

@floam Apple has never been a fan of people looking into undocumented features though :D

**Comment by krader1961** [comment]
Okay, seems like a reasonable change to me. Merged as commit d2d707a6fa.

**Pull request closed without merging**
