### PR TITLE
Fixes the end of line bindings in vi-mode.

### PR DESCRIPTION
**Pull request by andgra2**
Solves issue #3005

### CODE REVIEW

**Comment by andgra2** [comment]
I did a quick fix similar to the way the w binding was fixed earlier, but ideally end-of-line should be fixed. Some other bindings depends on its current behaviour. For example A, but that could be handled.

Similarly forward-word could be fixed, so that we don't need the forward-char correction in the w binding. However this is another thing.

Similarly other things could be fixed in a better way.

**Comment by krader1961** [comment]
I"m not convinced this is the correct fix. The `end-of-line` function is doing the right thing in as much as the line contains a trailing space. The problem is that pressing [esc] to switch to normal/command mode doesn't remove the trailing space after moving the cursor to the last typed character. Whether that should be done in the `cancel` command or the \e binding is TBD.

**Comment by andgra2** [comment]
@krader1961: I agree and I think it should be done in the cancel command because there is the root cause of the problem.

Solving it the way you suggested also fixes `forward-char` so that it in normal mode can't move the cursor past the last character that we have typed in.

I revered my earlier quick fix and i'll try to solve it in this better way instead.

**Comment by andgra2** [comment]
@krader1961: Maybe an even better solution would be to not add that extra space in the first place, and instead just have an extra position (with no character in it) after the last character while in insert mode, but not have that extra position while in other modes. Having a space there seems like an ugly hack.

I think this is how it works in vim, there is an extra position after the last character and at that position there is no character, it's not part of the text.

**Comment by e-beach** [comment]
@krader1961 Implementing a buffer ending with character with a position with no character does sound more correct, but it would also be difficult to implement, especially for someone like, for example, me. Would you be opposed to a PR that  modified the behavior of the `cancel` commmand?

**Pull request closed without merging**
