### PR TITLE
Add basic ezjail-admin completion

### PR DESCRIPTION
**Pull request by herrbischoff**
## Description

Add basic completion for ezjail-admin utility on FreeBSD.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

**Comment by zanchey** [comment]
I was going to suggest using `string` instead of `awk`, but I had a look at the zsh completions shipped with ezjail.

Those completions actually read the jail state files directly, so instead of screenscraping the output, you could do something like:

```fish
function __fish_complete_jails
   set -l jails /usr/local/etc/ezjail/*
   echo $jails
end

function __fish_complete_running_jails
    for j in (__fish_complete_jails)
        if test -f /var/run/jail_{$j}.id
             echo $j
        end
    end
end
```

etc.

**Comment by faho** [comment]
>     set -l jails /usr/local/etc/ezjail/*
>     echo $jails

These files need to be separated with a newline, not a space. Otherwise splitting won't be performed.

So either `printf '%s\n' $jails`, or `for j in /usr/local/etc/ezjail/*; echo $j; end`.

**Comment by herrbischoff** [comment]
These look like good suggestions. However, how about filtering for stopped jails? Also, isn't it true that a loop executes slightly slower than the screen scraping approach, especially when chaining two loops like with `__fish_complete_running_jails`?

**Comment by faho** [comment]
> Also, isn't it true that a loop executes slightly slower than the screen scraping approach, especially when chaining two loops like with __fish_complete_running_jails?

The screen scraping approach requires starting an external tool. The overhead of fork/exec is typically larger than a tiny loop. Also note that I also suggested an approach without a loop (the `printf` one).

I'd suggest testing if you are in doubt. My money is on the builtin-approach being faster, which is presumably also why the zsh completions do that.

Rule 1 of optimizing shell scripts: Use external tools as little as possible.

>However, how about filtering for stopped jails?

I would assume there's a way without screen scraping there. Possibly by reading the files. Check the zsh completions.

**Comment by herrbischoff** [comment]
Additionally, @zanchey's suggested approach will output the full path of the jail instead of just the jail name. This leads to cluttered output. If this is what the Zsh completions do, I believe my approach is the cleaner one, as it also has the benefit of not requiring the jail configurations to be present in `/usr/local/etc/ezjail`, which could change in the future when full `jail.conf` compatibility is done.

All used tools (grep, awk) are included in FreeBSD.

I'm open to any kind of improvement.

**Comment by faho** [comment]
>which could change in the future when full jail.conf compatibility is done.

In that case, yeah, we want the command.

**Comment by zanchey** [comment]
Sorry, I left the stopped jails function out. I figured just inverting the test was a trivial addition.

This approach came from the completions for zsh shipped with ezjail, so it might be worth checking with them to see whether it is a stable approach.

**Comment by faho** [comment]
You know what? Let's just merge this for now. Any improvements can be made later.

Thanks @herrbischoff, and sorry for the delay!

**Pull request merged**
